### ISSUE TITLE
No module named '_catboost' 

### ISSUE THREAD

**Issue by crazyelf1971** [catboost/catboost#10]
Anaconda Windows x64, Python 3.5, install was ok:

`pip install catboost`

Jupiter Notebook code:

`import numpy as np`
`from catboost import CatBoostClassifier`

I got this:

`ImportError: No module named '_catboost'`

and this:

`ImportError: DLL load failed: Не найден указанный модуль.`

**Comment by tyz910** [comment]
I have similar error on Anaconda Windows x64, Python 3.5:

```ImportError                               Traceback (most recent call last)
\lib\site-packages\catboost\core.py in <module>()
     17 try:
---> 18     from _catboost import _PoolBase, _CatBoostBase, CatboostError, _cv, _set_logger, _reset_logger
     19 except ImportError:

ImportError: No module named '_catboost'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-ac38b68a6004> in <module>()
      1 import numpy
----> 2 from catboost import CatBoostRegressor
      3 
      4 dataset = numpy.array([[1,4,5,6],[4,5,6,7],[30,40,50,60],[20,15,85,60]])
      5 train_labels = [1.2,3.4,9.5,24.5]

\lib\site-packages\catboost\__init__.py in <module>()
----> 1 from .core import Pool, CatBoost, CatBoostClassifier, CatBoostRegressor, CatboostError, cv  # noqa
      2 try:
      3     from .widget import CatboostIpythonWidget  # noqa
      4 except:
      5     pass

\lib\site-packages\catboost\core.py in <module>()
     18     from _catboost import _PoolBase, _CatBoostBase, CatboostError, _cv, _set_logger, _reset_logger
     19 except ImportError:
---> 20     from ._catboost import _PoolBase, _CatBoostBase, CatboostError, _cv, _set_logger, _reset_logger
     21 
     22 from contextlib import contextmanager

ImportError: Module use of python36.dll conflicts with this version of Python.

**Comment by mstrfx** [comment]
got similar issue, Windows 10 x64, clean python 3.5, installed catboost through pip

**Comment by Donskov7** [comment]
This is because python 3.5 is specific, we load new version for python3.5 in pypi, try reinstall catboost:
pip install catboost --no-cache-dir

*if it doesn't help try to build from source:
https://tech.yandex.com/catboost/doc/dg/concepts/python-installation-docpage/

1. Clone the repository:
`git clone https://github.com/catboost/catboost.git`
2. go to `catboost/catboost/python-package`
3. run `python mk_wheel.py`
Here at the result you get some `.whl` file
4. run `pip install catboost-...whl`

**Comment by tyz910** [comment]
After reinstall got this error "TypeError: the JSON object must be str, not 'bytes'"
same as #2

**Comment by crazyelf1971** [comment]
> This is because python 3.5 is specific, we load new version for python3.5 in pypi, try reinstall catboost:
pip install catboost --no-cache-dir

This helped, errors gone

**Comment by Donskov7** [comment]
New version has been uploaded to PyPi and to GitHub. Please try to reinstall CatBoost and check again.

**Comment by shivamsaboo17** [comment]
I tried building from source on python 3.6.0 and also tried pip3 install catboost but I am getting same error:
```
Python 3.6.0 (default, May 19 2018, 03:17:36)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import catboost
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/shiva/Desktop/AV/catboost/catboost/python-package/catboost/__init__.py", line 1, in <module>
    from .core import FeaturesData, EFstrType, Pool, CatBoost, CatBoostClassifier, CatBoostRegressor, CatboostError, cv, train  # noqa
  File "/mnt/c/Users/shiva/Desktop/AV/catboost/catboost/python-package/catboost/core.py", line 52, in <module>
    _catboost = get_catboost_bin_module()
  File "/mnt/c/Users/shiva/Desktop/AV/catboost/catboost/python-package/catboost/core.py", line 48, in get_catboost_bin_module
    import _catboost
ModuleNotFoundError: No module named '_catboost'
>>> from catboost import CatBoostClassifier
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/shiva/Desktop/AV/catboost/catboost/python-package/catboost/__init__.py", line 1, in <module>
    from .core import FeaturesData, EFstrType, Pool, CatBoost, CatBoostClassifier, CatBoostRegressor, CatboostError, cv, train  # noqa
  File "/mnt/c/Users/shiva/Desktop/AV/catboost/catboost/python-package/catboost/core.py", line 52, in <module>
    _catboost = get_catboost_bin_module()
  File "/mnt/c/Users/shiva/Desktop/AV/catboost/catboost/python-package/catboost/core.py", line 48, in get_catboost_bin_module
    import _catboost
ModuleNotFoundError: No module named '_catboost'
```

**Comment by IrinaMax** [comment]
Error Python 3 after installation  catboost

```
from catboost import Pool, CatBoostClassifier
---> 11 from catboost import Pool, CatBoostClassifier
     12 
     13 from scipy.stats import pearsonr, chi2_contingency

~/anaconda3/envs/dlaiwtpip/lib/python3.6/site-packages/catboost/__init__.py in <module>
----> 1 from .core import FeaturesData, EFstrType, Pool, CatBoost, CatBoostClassifier, CatBoostRegressor, CatBoostError, cv, train, sum_models  # noqa
      2 from .version import VERSION as __version__  # noqa
      3 __all__ = ['FeaturesData', 'EFstrType', 'Pool', 'CatBoost', 'CatBoostClassifier', 'CatBoostRegressor', 'CatBoostError', 'CatboostError', 'cv', 'train', 'sum_models']
      4 
      5 # API compatibility alias.

~/anaconda3/envs/dlaiwtpip/lib/python3.6/site-packages/catboost/core.py in <module>
     58 
     59 
---> 60 _catboost = get_catboost_bin_module()
     61 _PoolBase = _catboost._PoolBase
     62 _CatBoost = _catboost._CatBoost

~/anaconda3/envs/dlaiwtpip/lib/python3.6/site-packages/catboost/core.py in get_catboost_bin_module()
     49     for so_path in so_paths:
     50         try:
---> 51             loaded_catboost = imp.load_dynamic('_catboost', so_path)
     52             sys.modules['catboost._catboost'] = loaded_catboost
     53             return loaded_catboost

~/anaconda3/envs/dlaiwtpip/lib/python3.6/imp.py in load_dynamic(name, path, file)
    340         spec = importlib.machinery.ModuleSpec(
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 
    344 else:

_catboost.pyx in init _catboost()

AttributeError: type object '_catboost._FloatArrayWrapper' has no attribute '__reduce_cython__'


```

**Comment by bikun92** [comment]
Anaconda Linux, Python 3.7, install was ok:

pip install catboost

Jupiter Notebook code:

import numpy as np
import catboost

I got this:

ImportError: No module named '_catboost'

**Comment by NhutTien0905** [comment]
> 
try this:
import sys
!{sys.executable} -m pip install optuna

**Comment by vijaybirju** [comment]
still i got same error
