### ISSUE TITLE
cat_features at cb.CatBoostClassifier has broken since 0.17

### ISSUE THREAD

**Issue by algorc** [catboost/catboost#1004]
Problem:
Hello, cb team!

It seems that something goes wrong at 0.17 version.
I've created a data from pandas and tell cb.CatBoostClassifier.fit to treat one of my features as categorical:

`(python)
clf_1_c7 = cb.CatBoostClassifier(
    random_seed=42,
    task_type="GPU",
)

clf_1_c7.fit(
    X=X_est_1,
    y=y_est_1,
    cat_features = [columns.index("C7")],
      eval_set=(X_vld_1, y_vld_1),
)
`
At 0.16.5 this code just train the model, but at 0.17.2 and 0.17.1 it crash with following messages:

_catboost.pyx in _catboost._PoolBase._init_pool()
_catboost.pyx in _catboost._PoolBase._init_pool()
_catboost.pyx in _catboost._PoolBase._init_features_order_layout_pool()
CatBoostError: catboost/libs/data_new/objects.cpp:537: Internal CatBoost Error (contact developers for assistance): ObjectDataProvider's Categorical feature #0 is null despite being available in featuresLayout

catboost version:
0.17
0.17.1
0.17.2
Operating System: Ubuntu 18.04

CPU:
GPU:

**Comment by dmitrySorokin** [comment]
the same problem

**Comment by andrey-khropov** [comment]
Can you give a minimal broken example?

This minimal example works for me:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

$ cat ./cat_features_in_0.17.py 
#!/usr/bin/env python3

import sys

import pandas as pd

import catboost as cb


print ('python version="%s"' %  sys.version)
print ('CatBoost version=%s' % cb.__version__)


X_est_1 = pd.DataFrame(
    {
        'n0': [0, 1, 2, 3, 4],
        'c0': ['a', 'b', 'c', 'd', 'e'],
        #'c1': ['f', 'g', 'h', 'i', 'j'],
        'n1': [5, 6, 7, 8, 9]
    }
)

y_est_1 = [0, 1, 1, 0, 0]

X_vld_1 = X_est_1
y_vld_1 = y_est_1


clf_1_c7 = cb.CatBoostClassifier(
    random_seed=42,
    task_type="GPU",
    devices='0',
    iterations=2
)

clf_1_c7.fit(
    X=X_est_1,
    y=y_est_1,
    cat_features = [list(X_est_1.columns).index("c0")],
    eval_set=(X_vld_1, y_vld_1),
)

$  ./cat_features_in_0.17.py 
python version="3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0]"
CatBoost version=0.17.2
Learning rate set to 0.5
Warning: less than 75% gpu memory available for training. Free: 119.9375 Total: 119.9375
0:	learn: 0.6304989	test: 0.6304989	best: 0.6304989 (0)	total: 150ms	remaining: 150ms
1:	learn: 0.5867156	test: 0.6105020	best: 0.6105020 (1)	total: 323ms	remaining: 0us
bestTest = 0.6105019569
bestIteration = 1
Shrink model to first 2 iterations.
```
If I change python2 -> python3 it works as well:

```
$  ./cat_features_in_0.17.py 
python version="2.7.15+ (default, Jul  9 2019, 16:51:35) 
[GCC 7.4.0]"
CatBoost version=0.17.2
Learning rate set to 0.5
Warning: less than 75% gpu memory available for training. Free: 119.9375 Total: 119.9375
0:	learn: 0.6304989	test: 0.6304989	best: 0.6304989 (0)	total: 181ms	remaining: 181ms
1:	learn: 0.5759495	test: 0.5759495	best: 0.5759495 (1)	total: 355ms	remaining: 0us
bestTest = 0.5759494781
bestIteration = 1
Shrink model to first 2 iterations.
```
Results differ because of non-deterministic nature of GPU calculations.

**Comment by algorc** [comment]
import catboost as cb

assert(cb.version.VERSION =='0.17.3')

X_est = np.array([[1221646265, 3940311489,       4007,       1505,         30,
              1322,          0],
       [2220759529, 3618116677,       5338,      11958,         41,
              2682,          2]], dtype=np.int64)
y_est_1 = np.array([0, 1], dtype=np.uint8)

clf_1_c5c7 = cb.CatBoostClassifier(
    random_seed=42,
)

clf_1_c5c7.fit(
    X=X_est,
    y=y_est_1,
    cat_features = [4, 6],
  
    eval_set=(X_vld_1, y_vld_1),
)
-----

Leads to

---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
<ipython-input-93-12eec2510428> in <module>
      8     cat_features = [4, 6],
      9 
---> 10     eval_set=(X_vld_1[:2353028,:7], y_vld_1[:2353028]),
     11 )

/usr/local/lib/python3.6/dist-packages/catboost/core.py in fit(self, X, y, cat_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   3676         self._fit(X, y, cat_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
   3677                   eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period,
-> 3678                   silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   3679         return self
   3680 

/usr/local/lib/python3.6/dist-packages/catboost/core.py in _fit(self, X, y, cat_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   1597             use_best_model, eval_set, verbose, logging_level, plot,
   1598             column_description, verbose_eval, metric_period, silent, early_stopping_rounds,
-> 1599             save_snapshot, snapshot_file, snapshot_interval, init_model
   1600         )
   1601         params = train_params["params"]

/usr/local/lib/python3.6/dist-packages/catboost/core.py in _prepare_train_params(self, X, y, cat_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   1553                 if eval_set[0] is None or eval_set[1] is None:
   1554                     raise CatBoostError("'eval_set' tuple contains at least one None value")
-> 1555                 eval_sets.append(Pool(eval_set[0], eval_set[1], cat_features=train_pool.get_cat_feature_indices()))
   1556 
   1557                 eval_total_row_count += eval_sets[-1].num_row()

/usr/local/lib/python3.6/dist-packages/catboost/core.py in __init__(self, data, label, cat_features, column_description, pairs, delimiter, has_header, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names, thread_count)
    329                         )
    330 
--> 331                 self._init(data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names)
    332         super(Pool, self).__init__()
    333 

/usr/local/lib/python3.6/dist-packages/catboost/core.py in _init(self, data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names)
    886             baseline = np.reshape(baseline, (samples_count, -1))
    887             self._check_baseline_shape(baseline, samples_count)
--> 888         self._init_pool(data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names)
    889 
    890 

_catboost.pyx in _catboost._PoolBase._init_pool()

_catboost.pyx in _catboost._PoolBase._init_pool()

_catboost.pyx in _catboost._PoolBase._init_features_order_layout_pool()

CatBoostError: catboost/libs/data_new/objects.cpp:537: Internal CatBoost Error (contact developers for assistance): ObjectDataProvider's Categorical feature #0 is null despite being available in featuresLayout



-----
where X_vld_1.shape is (2353028, 7) and y_vld_1.shape is (2353028,)

At this moment a cannot reduce X_vld_1 to some reasonable shape.

Was this helpful?

**Comment by algorc** [comment]
Please, try to search bugs, because i've catch kernel death during the modeling another dataset with catboost with cat_features option enabled.
Downgrade to 0.16.5 solves the problem.

**Comment by annaveronika** [comment]
@dmitrySorokin Maybe you have a reproducing exampe?

**Comment by dmitrySorokin** [comment]
I have been also fitting data with millions of entries. I will try ro extract minimal example from it tomorrow

**Comment by dmitrySorokin** [comment]
#!/usr/bin/env python3

import sys
import numpy as np
import catboost as cb

print('python version="%s"' % sys.version)
print('CatBoost version=%s' % cb.__version__)

cat_features = [2]

clf = cb.CatBoostClassifier(
        cat_features=cat_features,
        class_weights=[1,  29989752 / 76302],
        loss_function='Logloss'
)

features = np.asarray([[0.27290749, 0.63002519, 0., 0.38624339, 0.]])
labels = np.asarray([0])

pool = cb.Pool(features, labels, cat_features)

model = clf.fit(
    pool
)



Output:
python version="3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0]"
CatBoost version=0.17.4
Traceback (most recent call last):
  File "min_catboost_classifier.py", line 21, in <module>
    pool = cb.Pool(features, labels, cat_features)
  File "/home/dmitry/.local/lib/python3.6/site-packages/catboost/core.py", line 332, in __init__
    self._init(data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names)
  File "/home/dmitry/.local/lib/python3.6/site-packages/catboost/core.py", line 889, in _init
    self._init_pool(data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names)
  File "_catboost.pyx", line 3130, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 3163, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 3068, in _catboost._PoolBase._init_features_order_layout_pool
_catboost.CatBoostError: catboost/libs/data_new/objects.cpp:537: Internal CatBoost Error (contact developers for assistance): ObjectDataProvider's Categorical feature #0 is null despite being available in featuresLayout

**Comment by andrey-khropov** [comment]
> ```python
> #!/usr/bin/env python3
> 
> import sys
> import numpy as np
> import catboost as cb
> 
> print('python version="%s"' % sys.version)
> print('CatBoost version=%s' % cb.__version__)
> 
> cat_features = [2]
> 
> clf = cb.CatBoostClassifier(
>         cat_features=cat_features,
>         class_weights=[1,  29989752 / 76302],
>         loss_function='Logloss'
> )
> 
> features = np.asarray([[0.27290749, 0.63002519, 0., 0.38624339, 0.]])
> labels = np.asarray([0])
> 
> pool = cb.Pool(features, labels, cat_features)
> 
> model = clf.fit(
>     pool
> )
> ```
> 
> Output:
> 
> ```shell
> python version="3.6.8 (default, Aug 20 2019, 17:12:48) 
> [GCC 8.3.0]"
> CatBoost version=0.17.4
> Traceback (most recent call last):
>   File "min_catboost_classifier.py", line 21, in <module>
>     pool = cb.Pool(features, labels, cat_features)
>   File "/home/dmitry/.local/lib/python3.6/site-packages/catboost/core.py", line 332, in __init__
>     self._init(data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names)
>   File "/home/dmitry/.local/lib/python3.6/site-packages/catboost/core.py", line 889, in _init
>     self._init_pool(data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names)
>   File "_catboost.pyx", line 3130, in _catboost._PoolBase._init_pool
>   File "_catboost.pyx", line 3163, in _catboost._PoolBase._init_pool
>   File "_catboost.pyx", line 3068, in _catboost._PoolBase._init_features_order_layout_pool
> _catboost.CatBoostError: catboost/libs/data_new/objects.cpp:537: Internal CatBoost Error (contact developers for assistance): ObjectDataProvider's Categorical feature #0 is null despite being available in featuresLayout
> ```
> 
> Hope this would help

Release 0.17.5 makes this example work as expected - categorical features should not be represented by floating-point values (See [Explanation why in FAQ](https://catboost.ai/docs/concepts/faq.html#specify-weights-or-baseline-for-eval-set)).
