### ISSUE TITLE
Error: can't proceed some features

### ISSUE THREAD

**Issue by pseudotensor** [catboost/catboost#1024]
```
  File "/home/jon/h2oai.clean/tmp/contrib/env/lib/python3.6/site-packages/catboost/core.py", line 3689, in fit
    silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
  File "/home/jon/h2oai.clean/tmp/contrib/env/lib/python3.6/site-packages/catboost/core.py", line 1612, in _fit
    train_params["init_model"]
  File "/home/jon/h2oai.clean/tmp/contrib/env/lib/python3.6/site-packages/catboost/core.py", line 1171, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 3573, in _catboost._CatBoost._train
  File "_catboost.pyx", line 3619, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/cuda/gpu_data/compressed_index_builder.h:116: Error: can't proceed some features
].
```

catboost 0.17.4

There is no explanation of why this happens, but I presume it's because I'm on the GPU.  It doesn't always happen with this daata.

**Comment by pseudotensor** [comment]
Here are the parameters:

```
OrderedDict([('bootstrap_type', 'Bayesian'), ('n_estimators', 4000), ('learning_rate', 0.25), ('early_stopping_rounds', 20), ('max_depth', 8), ('one_hot_max_size', 255), ('task_type', 'GPU'), ('eval_metric', 'AUC'), ('objective', 'Logloss'), ('cat_features', [901, 903, 904, 905, 906, 907, 909, 910, 917, 918, 921, 922, 923, 924, 926, 928, 933, 934, 935, 939, 942, 943, 944, 945, 946, 948, 949, 950, 954, 955, 956, 957, 959, 961, 962, 964, 965, 968, 969, 970, 972, 973, 974, 978, 980, 981, 982, 985, 986, 999, 1000, 1002, 1003, 1006, 1009, 1010, 1011, 1013, 1014, 1015, 1018, 1020, 1022, 1024, 1025, 1026, 1028, 1029, 1036, 1037, 1040, 1041, 1042, 1044, 1045, 1046, 1049, 1050, 1052, 1053, 1057, 1059, 1062, 1063, 1064, 1065, 1066, 1067, 1069, 1070, 1071, 1072, 1079, 1082, 1083, 1085, 1088, 1090, 1091, 1100, 1101, 1104, 1107, 1108, 1109, 1110, 1111, 1113, 1114, 1115, 1116, 1119, 1120, 1123, 1124, 1126, 1127, 1128, 1129, 1131, 1134, 1139, 1141, 1142, 1143, 1147, 1148, 1149, 1153, 1155, 1157, 1158, 1161, 1162, 1163, 1167, 1169, 1170, 1172, 1174, 1175, 1176, 1178, 1180, 1181, 1182, 1183, 1188, 1189, 1190, 1191, 1192, 1194, 1195, 1197, 1202, 1205, 1206, 1209, 1210, 1211, 1213, 1214, 1215, 1217, 1218, 1220, 1222, 1223, 1226, 1228, 1229, 1234, 1235, 1240, 1241, 1242, 1245, 1247, 1248, 1249, 1251, 1252, 1253, 1255, 1256, 1257, 1259, 1260, 1262, 1263, 1266, 1268, 1269, 1272, 1274, 1276, 1277, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1289, 1290, 1291, 1293, 1294, 1295, 1296, 1298, 1299, 1301, 1306, 1308, 1309, 1310, 1311, 1316, 1319, 1320, 1321, 1326, 1330, 1331, 1332, 1334, 1336, 1338, 1339, 1340, 1342, 1343, 1345, 1351, 1353, 1354, 1357, 1359, 1360, 1362, 1363, 1364, 1365, 1366, 1368, 1369, 1374, 1377, 1378, 1380, 1382, 1385, 1386, 1388, 1389, 1390, 1391, 1392, 1393, 1394, 1395, 1396, 1403, 1404, 1406, 1407, 1408, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1419, 1421, 1423, 1426, 1429, 1430, 1431, 1432, 1434, 1436, 1440, 1441, 1442, 1443, 1446, 1447, 1448, 1451, 1455, 1457, 1458, 1459, 1460, 1462, 1463, 1466, 1467, 1468, 1470, 1471, 1473, 1476, 1481, 1485, 1487, 1495, 1496, 1499, 1500, 1504, 1506, 1508, 1509, 1511, 1514, 1515, 1518, 1519, 1523, 1525, 1527, 1528, 1533, 1535, 1539, 1542, 1544, 1545, 1546, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1557, 1559, 1560, 1562, 1564, 1565, 1566, 1567, 1569, 1574, 1577, 1578, 1579, 1581, 1583, 1584, 1586, 1587, 1589, 1590, 1592, 1594, 1596, 1597, 1599, 1600, 1610, 1613, 1615, 1617, 1618, 1621, 1623, 1625, 1627, 1630, 1631, 1633, 1634, 1635, 1636, 1639, 1642, 1643, 1649, 1651, 1652, 1655, 1656, 1659, 1660, 1667, 1668, 1670, 1671, 1675, 1677, 1680, 1681, 1684, 1687, 1689, 1690, 1693, 1694, 1698, 1702, 1703, 1704, 1706, 1708, 1709, 1711, 1713, 1714, 1715, 1717, 1718, 1719, 1721, 1724, 1725, 1727, 1728, 1730, 1733, 1738, 1740, 1745, 1747, 1754, 1755, 1757, 1758, 1759, 1760, 1761, 1762, 1765, 1767, 1768, 1769, 1772, 1775, 1776, 1777, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823, 1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1858, 1859, 1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046, 2047, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2056, 2057, 2058, 2059, 2060, 2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2072, 2073, 2074, 2075, 2076, 2077, 2078, 2079, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2088, 2089, 2090, 2091, 2092, 2093, 2094, 2095, 2096, 2097, 2098, 2099, 2100, 2101, 2102, 2103, 2104, 2105, 2106, 2107, 2108, 2109, 2110, 2111, 2112, 2113, 2114, 2115, 2116, 2117, 2118, 2119, 2120, 2121, 2122, 2123, 2124, 2125, 2126, 2127, 2128, 2129, 2130, 2131, 2132, 2133, 2134, 2135, 2136, 2137, 2138, 2139, 2140, 2141, 2142, 2143, 2144, 2145, 2146, 2147, 2148, 2149, 2150, 2151, 2152, 2153, 2154, 2155, 2156, 2157, 2158, 2159, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167, 2168, 2169, 2170, 2171, 2172, 2173, 2174, 2175, 2176, 2177, 2178, 2179, 2180, 2181, 2182, 2183, 2184, 2185, 2186, 2187, 2188, 2189, 2190, 2191, 2192, 2193, 2194, 2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203, 2204, 2205, 2206, 2207, 2208, 2209, 2210, 2211, 2212, 2213, 2214, 2215, 2216, 2217, 2218, 2219, 2220, 2221, 2222, 2223, 2224, 2225, 2226, 2227, 2228, 2229, 2230, 2231, 2232, 2233, 2234, 2235, 2236, 2237, 2238, 2239, 2240, 2241, 2242, 2243, 2244, 2245, 2246, 2247, 2248, 2249, 2250, 2251, 2252, 2253, 2254, 2255, 2256, 2257, 2258, 2259, 2260, 2261, 2262, 2263, 2264, 2265, 2266, 2267, 2268, 2269, 2270, 2271, 2272, 2273, 2274, 2275, 2276, 2277, 2278, 2279, 2280, 2281, 2282, 2283, 2284, 2285, 2286, 2287, 2288, 2289, 2290, 2291, 2292, 2293, 2294, 2295, 2296, 2297, 2298, 2299, 2300, 2301, 2302, 2303, 2304, 2305, 2306, 2307, 2308, 2309, 2310, 2311, 2312, 2313, 2314, 2315, 2316, 2317, 2318, 2319, 2320, 2321, 2322, 2323, 2324, 2325, 2326, 2327, 2328, 2329, 2330, 2331, 2332, 2333, 2334, 2335, 2336, 2337, 2338, 2339, 2340, 2341, 2342, 2343, 2344, 2345, 2346, 2347, 2348, 2349, 2350, 2351, 2352, 2353, 2354, 2355, 2356, 2357, 2358, 2359, 2360, 2361, 2362, 2363, 2364, 2365, 2366, 2367, 2368, 2369, 2370, 2371, 2372, 2373, 2374, 2375, 2376, 2377, 2378, 2379, 2380, 2381, 2382, 2383, 2384, 2385, 2386, 2387, 2388, 2389, 2390, 2391, 2392, 2393, 2394, 2395, 2396, 2397, 2398, 2399, 2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414, 2415, 2416, 2417, 2418, 2419, 2420, 2421, 2422, 2423, 2424, 2425, 2426, 2427, 2428, 2429, 2430, 2431, 2432, 2433, 2434, 2435, 2436, 2437, 2438, 2439, 2440, 2441, 2442, 2443, 2444, 2445, 2446, 2447, 2448, 2449, 2450, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2461, 2462, 2463, 2464, 2465, 2466, 2467, 2468, 2469, 2470, 2471, 2472, 2473, 2474, 2475, 2476, 2477, 2478, 2479, 2480, 2481, 2482, 2483, 2484, 2485, 2486, 2487, 2488, 2489, 2490, 2491, 2492, 2493, 2494, 2495, 2496, 2497, 2498, 2499, 2500, 2501, 2502, 2503, 2504, 2505, 2506, 2507, 2508, 2509, 2510, 2511, 2512, 2513, 2514, 2515, 2516, 2517, 2518, 2519, 2520, 2521, 2522, 2523, 2524, 2525, 2526, 2527, 2528, 2529, 2530, 2531, 2532, 2533, 2534, 2535, 2536, 2537, 2538, 2539, 2540, 2541, 2542, 2543, 2544, 2545, 2546, 2547, 2548, 2549, 2550, 2551, 2552, 2553, 2554, 2555, 2556, 2557, 2558, 2559, 2560, 2561, 2562, 2563, 2564, 2565, 2566, 2567, 2568, 2569, 2570, 2571, 2572, 2573, 2574, 2575, 2576, 2577, 2578, 2579, 2580, 2581, 2582, 2583, 2584, 2585, 2586, 2587, 2588, 2589, 2590, 2591, 2592]), ('grow_policy', 'SymmetricTree'), ('thread_count', 8), ('max_bin', 127), ('devices', '0-0'), ('gpu_ram_part', 0.9), ('silent', False), ('random_state', 1404136001)])
```

**Comment by annaveronika** [comment]
Could you please provide a minimal reproducing example? Which is the full code that you are running and a sample of data?

**Comment by pseudotensor** [comment]
Please provide some context for this failure so I have some way to know *how* to repro.  Thanks!

**Comment by annaveronika** [comment]
The error occurs in the start of the training when internal representation of the dataset is built. This check happens only in GPU training.

**Comment by pseudotensor** [comment]
right, but why can it happen?  Hard to generate repro if i have nothing except it happens for gpu training.

**Comment by annaveronika** [comment]
This is a check that ensures that everything has worked correctly during building internal dataset representation. I don't know what were the conditions when it has failed, that's why I'm asking for a reproducing example. Is it possible to provide the dataset which triggers the error? It would really help.

**Comment by annaveronika** [comment]
Is it possible to share the big data? You could put it out to some cloud and send us the link in the email, if you don't wish to write it here. And also could you please tell which GPU you are using?

**Comment by pseudotensor** [comment]
I didn't create a re-usable artifact when it happened, must have been like 1/100 chance.  I haven't hit lately, so not sure how to reproduce.  The other issues I mentioned have same data involved but don't hit this particular problem.

**Comment by arnocandel** [comment]
This reproduces the issue:
```
import pickle
m, kw = pickle.load(open("catboost9b6f04.pickle", "rb"))
m.fit(**kw)
```
https://slack-files.com/T0329MHH6-FRJ27T8CT-5f8e41328b (link to `catboost9b6f04.pickle.gz`)
```
Traceback (most recent call last):
  File "debug.py", line 3, in <module>
    m.fit(**kw)
  File "/home/arno/h2oai/tmp/contrib/env/lib/python3.6/site-packages/catboost/core.py", line 3793, in fit
    silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
  File "/home/arno/h2oai/tmp/contrib/env/lib/python3.6/site-packages/catboost/core.py", line 1690, in _fit
    train_params["init_model"]
  File "/home/arno/h2oai/tmp/contrib/env/lib/python3.6/site-packages/catboost/core.py", line 1225, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 3865, in _catboost._CatBoost._train
  File "_catboost.pyx", line 3911, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/cuda/gpu_data/compressed_index_builder.h:116: Error: can't proceed some features
```

**Comment by annaveronika** [comment]
Thanks for the example, we'll look into this!

**Comment by ashumilov** [comment]
I've got the same error on big dataset. I've removed `one_hot_max_size` paramater and error disappeared.

**Comment by pseudotensor** [comment]
This still happens.

**Comment by andrey-khropov** [comment]
Fixed in https://github.com/catboost/catboost/commit/d9d712aa6dfc6cb2fb214d8ab079ef242c3f1dc5
