### ISSUE TITLE
sandbox.yandex-team.ru is blocking requests

### ISSUE THREAD

**Issue by MKisilyov** [catboost/catboost#1027]
Problem: Cannot build from sources because sandbox.yandex-team.ru is blocking requests.
catboost version: v0.17.4
Operating System: Ubuntu 18.04
CPU: AMD Ryzen 7 1700
GPU: Nvidia GeForce GTX 1080 Ti

Build fails when build script is trying to fetch cublas.a from sandbox.yandex-team.ru:
```
$ ../../../ya make -r -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -DPYTHON_CONFIG=python3-config -DCUDA_ROOT=/usr/local/cuda
------- [SB] {FAILED} $(B)/build/platform/cuda/cublas.a
command /home/maksym/.ya/tools/v3/1027728048/python /home/maksym/opt/catboost/build/scripts/fetch_from_sandbox.py --resource-id 1006791015 --untar-to . -- cublas.a failed with exit code 12
ERROR:root:<urlopen error timed out>
ERROR:root:<urlopen error timed out>
ERROR:root:<urlopen error timed out>
ERROR:root:<urlopen error timed out>
ERROR:root:<urlopen error timed out>
ERROR:root:<urlopen error timed out>
ERROR:root:<urlopen error timed out>
ERROR:root:<urlopen error timed out>
ERROR:root:<urlopen error timed out>
ERROR:root:<urlopen error timed out>
ERROR:root:<urlopen error timed out>
Traceback (most recent call last):
  File "/home/maksym/opt/catboost/build/scripts/fetch_from_sandbox.py", line 222, in <module>
    main(args)
  File "/home/maksym/opt/catboost/build/scripts/fetch_from_sandbox.py", line 212, in main
    fetched_file, file_name = fetch(args.resource_id, custom_fetcher)
  File "/home/maksym/opt/catboost/build/scripts/fetch_from_sandbox.py", line 137, in fetch
    raise ResourceInfoError(str(e))
ResourceInfoError: <urlopen error timed out>
Failed
```

The host is blocking all requests to 80 and 443 ports:
```
$ sudo nmap -sS -p80,443 sandbox.yandex-team.ru

Starting Nmap 7.60 ( https://nmap.org ) at 2019-10-08 07:23 PDT
Nmap scan report for sandbox.yandex-team.ru (141.8.146.10)
Host is up (0.33s latency).
Other addresses for sandbox.yandex-team.ru (not scanned): 2a02:6b8:0:3400::1:10

PORT    STATE    SERVICE
80/tcp  filtered http
443/tcp filtered https

Nmap done: 1 IP address (1 host up) scanned in 5.23 seconds
```

I'm located in San Francisco, CA, United States:
```
$ tracepath sandbox.yandex-team.ru
 1?: [LOCALHOST]                        0.009ms pmtu 1500
 1:  2601:645:8301:4eff:723a:cbff:fe11:7b5e                3.829ms 
 1:  2601:645:8301:4eff:723a:cbff:fe11:7b5e                4.601ms 
 2:  2001:558:4000:4c::1                                  12.016ms 
 3:  po-301-1221-rur01.sffolsom.ca.sfba.comcast.net       12.577ms 
 4:  be-209-rar01.santaclara.ca.sfba.comcast.net          22.249ms 
 5:  hu-0-2-0-3-ar01.santaclara.ca.sfba.comcast.net       14.289ms 
 6:  2001:1900:4:3::439                                   13.991ms 
 7:  lo-0-v6.ear2.Stockholm2.Level3.net                  229.878ms 
 8:  YANDEX-EURO.ear2.Stockholm2.Level3.net              204.043ms asymm 16 
 9:  myt-c1.yndx.net                                     408.764ms asymm 17 
10:  sandbox.yandex-team.ru                              205.616ms reached
     Resume: pmtu 1500 hops 10 back 19
```

**Comment by annaveronika** [comment]
Sorry for this inconvenience, our devtools team is looking into the problem!

**Comment by annaveronika** [comment]
This is fixed now, sorry for inconvenience!

**Comment by MKisilyov** [comment]
@annaveronika It works on v0.18. Thank you!
