### ISSUE TITLE
sum_models fails

### ISSUE THREAD

**Issue by Garfield2013** [catboost/catboost#1097]
I'm following the DOCS: [https://catboost.ai/docs/concepts/python-reference_sum_models.html](https://catboost.ai/docs/concepts/python-reference_sum_models.html)

But I end up with this error below: runtime data should be initialized

```
Traceback (most recent call last):
  File "/home/tb/Desktop/catboost/test_single.py", line 34, in <module>
    models_avg = sum_models(models, weights=[1.0/len(models)] * len(models))
  File "/home/tb/.local/lib/python3.6/site-packages/catboost/core.py", line 4701, in sum_models
    result._sum_models(models, weights, ctr_merge_policy)
  File "/home/tb/.local/lib/python3.6/site-packages/catboost/core.py", line 1321, in _sum_models
    self._object._sum_models(models_inner, weights, ctr_merge_policy)
  File "_catboost.pyx", line 4085, in _catboost._CatBoost._sum_models
  File "_catboost.pyx", line 4095, in _catboost._CatBoost._sum_models
_catboost.CatBoostError: catboost/libs/model/model.h:395: runtime data should be initialized
```

My code looks like:

```
import pandas as pd
from catboost import CatBoostClassifier, Pool, sum_models
from sklearn.model_selection import GridSearchCV

eval_dataset = Pool(val_data, val_labels)
```

```
models = []
model = CatBoostClassifier(task_type="CPU", eval_metric='Accuracy', boosting_type="Ordered", use_best_model=True, # 'Accuracy'
iterations=10, depth=9, max_bin=100, l2_leaf_reg=20, bagging_temperature=0, random_strength=None)#, class_weights=[0.4, 1])#, fold_len_multiplier=1.01, approx_on_full_history=True)
result = model.fit(train_data, y=label_data, eval_set=eval_dataset, verbose=1, plot=True)
models.append(model)
```

```
model1 = CatBoostClassifier(task_type="CPU", eval_metric='Accuracy', boosting_type="Ordered", use_best_model=True, # 'Accuracy'
iterations=10, depth=9, max_bin=100, l2_leaf_reg=20, bagging_temperature=0, random_strength=None)#, class_weights=[0.4, 1])#, fold_len_multiplier=1.01, approx_on_full_history=True)
result1 = model.fit(train_data, y=label_data, eval_set=eval_dataset, verbose=1, plot=True)
models.append(model1)
```

```
#THIS LINE FAILS
models_avg = sum_models(models, weights=[1.0/len(models)] * len(models))
```

**Comment by dbakshee** [comment]
Hi @Garfield2013 
It is a typo in your code. You did not fit `model1`. Instead you fit `model` twice.

**Comment by Garfield2013** [comment]
Ooh! So sorry! But thank you so much! :-) I really couldn't understand the error message and nothing popped up when I googled the error message.
