### ISSUE TITLE
Did any one succeeded in installing catboost in R? I am getting below error

### ISSUE THREAD

**Issue by mosrihari** [catboost/catboost#122]
> install_github('catboost/catboost',subdir='catboost/R-package')
Downloading GitHub repo catboost/catboost@master
from URL https://api.github.com/repos/catboost/catboost/zipball/master
Installing catboost
"F:/R-3.4.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL  \
  "C:/Users/srihari/AppData/Local/Temp/RtmpyyobGm/devtools458b6b1cd9/catboost-catboost-8e4283c/catboost/R-package"  \
  --library="F:/R-3.4.1/library" --install-tests 
* installing *source* package 'catboost' ...
** libs
  running 'src/Makefile.win' ...
/cygdrive/c/Users/srihari/AppData/Local/Temp/RtmpyyobGm/devtools458b6b1cd9/catboost-catboost-8e4283c/catboost/R-package/src/../../../ya.bat make -r -o ../../..
Traceback (most recent call last):
  File "devtools/ya/entry/entry.py", line 157, in exit_interceptor
    func()
  File "devtools/ya/entry/entry.py", line 56, in <lambda>
    return lambda: wrapper(f)
  File "devtools/ya/entry/entry.py", line 121, in f
    res = func()
  File "devtools/ya/entry/entry.py", line 250, in <lambda>
    run_main = lambda: do_main(args)
  File "devtools/ya/entry/entry.py", line 49, in do_main
    res = handler.handle(handler, args, prefix=['ya'])
  File "devtools/ya/core/handler.py", line 157, in handle
    return handler.handle(self, args[1:], prefix + [name])
  File "devtools/ya/core/dispatch.py", line 37, in handle
    return self.command().handle(root_handler, args, prefix)
  File "devtools/ya/core/handler.py", line 337, in handle
    return self._action(params)
  File "devtools/ya/app.py", line 66, in helper
    return action(ctx.params)
  File "devtools/ya/build/build_handler.py", line 11, in do_ya_make
    return YaMake(params, app_ctx).go()
  File "devtools/ya/build/ya_make.py", line 523, in __init__
    self.ctx = Context(self.opts, app_ctx=app_ctx, graph=graph, tests=tests, configure_errors=configure_errors, make_files=make_files)
  File "devtools/ya/build/ya_make.py", line 352, in __init__
    self.graph, self.tests, self.configure_errors, self.make_files = _build_graph_and_tests(self.opts, app_ctx)
  File "devtools/ya/build/ya_make.py", line 244, in _build_graph_and_tests
    graph, tests, gh, make_files = lg.build_graph_and_tests(opts, check=True, ev_listener=ev_listener)
  File "devtools/ya/build/graph.py", line 1343, in build_graph_and_tests
    host_tc = bg.gen_tc(host)
  File "devtools/ya/build/genconf.py", line 103, in gen_tc
    return _resolve_cxx(platform_name, platform_name)
  File "devtools/ya/build/genconf.py", line 73, in _resolve_cxx
    return resolve_system_cxx("cl.exe", host, target)
  File "devtools/ya/exts/func.py", line 60, in wrapper
    return get(args)
  File "devtools/ya/exts/func.py", line 54, in get
    memory[args] = func(*args)
TypeError: resolve_system_cxx() takes exactly 4 arguments (3 given)
make: *** [all] Error 1
Warning: running command 'make --no-print-directory -f "Makefile.win"' had status 2
ERROR: compilation failed for package 'catboost'
* removing 'F:/R-3.4.1/library/catboost'
Installation failed: Command failed (1)

**Comment by annaveronika** [comment]
this is fixed now
