### ISSUE TITLE
Custom loss function doesn't work

### ISSUE THREAD

**Issue by Udimus** [catboost/catboost#1283]
Problem: Can't implement custom loss function
catboost version: 0.23
Operating System: Ubuntu 18.04.4 LTS
CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

I try to add custom objective as in https://catboost.ai/docs/concepts/python-usages-examples.html#user-defined-loss-function

Loss function, like at docs, only add default weights value:
```
class RmseObjective(object):
    def calc_ders_range(self, approxes, targets, weights=None):
        assert len(approxes) == len(targets)
        if weights is not None:
            assert len(weights) == len(approxes)
        result = []
        for index in range(len(targets)):
            der1 = targets[index] - approxes[index]
            der2 = -1
            if weights is not None:
                der1 *= weights[index]
                der2 *= weights[index]
            result.append((der1, der2))
        return result
```

Then I describe sample dataframe:
```
df = pd.DataFrame({
    'target': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'num_feat': [0, 0, 1, 1, 1, 0, 0, 1, 1, 1],
})
```

If I run the code below, everything is fine:
```
model = CatBoostRegressor()
model.fit(X=df[['num_feat'], y = df['target'])
```

But when I try to fit regressor with this new loss, I get error:

```
model = CatBoostRegressor(loss_function=RmseObjective, eval_metric='RMSE')
model.fit(X=df[['num_feat'], y = df['target'])
```

Full error message:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
_catboost.pyx in _catboost._ObjectiveCalcDersRange()

<ipython-input-9-33c6e5bff051> in calc_ders_range(self, approxes, targets, weights)
      2     def calc_ders_range(self, approxes, targets, weights=None):
----> 3         assert len(approxes) == len(targets)
      4         if weights is not None:

TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

CatBoostError                             Traceback (most recent call last)
<ipython-input-21-115586d1d2f3> in <module>
----> 1 model.fit(X=df[['num_feat']], y=df['target'])

~/env/sber-task/lib/python3.6/site-packages/catboost/core.py in fit(self, X, y, cat_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   4503                          use_best_model, eval_set, verbose, logging_level, plot, column_description,
   4504                          verbose_eval, metric_period, silent, early_stopping_rounds,
-> 4505                          save_snapshot, snapshot_file, snapshot_interval, init_model)
   4506 
   4507     def predict(self, data, prediction_type=None, ntree_start=0, ntree_end=0, thread_count=-1, verbose=None):

~/env/sber-task/lib/python3.6/site-packages/catboost/core.py in _fit(self, X, y, cat_features, text_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
   1711                 params,
   1712                 allow_clear_pool,
-> 1713                 train_params["init_model"]
   1714             )
   1715 

~/env/sber-task/lib/python3.6/site-packages/catboost/core.py in _train(self, train_pool, test_pool, params, allow_clear_pool, init_model)
   1227 
   1228     def _train(self, train_pool, test_pool, params, allow_clear_pool, init_model):
-> 1229         self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
   1230         self._set_trained_model_attributes()
   1231 

_catboost.pyx in _catboost._CatBoost._train()

_catboost.pyx in _catboost._CatBoost._train()

CatBoostError: catboost/python-package/catboost/helpers.cpp:41: Traceback (most recent call last):
  File "_catboost.pyx", line 1803, in _catboost._ObjectiveCalcDersRange
  File "<ipython-input-9-33c6e5bff051>", line 3, in calc_ders_range
    assert len(approxes) == len(targets)
TypeError: object of type 'NoneType' has no len()
```

**Comment by LyzhinIvan** [comment]
Hi, @Udimus ! You should pass to loss_function object of your custom loss, not class.

**Comment by Udimus** [comment]
Thank you, sorry for carelessness!

**Comment by Udimus** [comment]
No model fit correct. But I have new problem.


```
model = CatBoostRegressor(loss_function=RmseObjective(), eval_metric='RMSE')
df = pd.DataFrame({
    'target': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'num_feat': [0, 0, 1, 1, 1, 0, 0, 1, 1, 1],
})
model.fit(X=df[['num_feat']], y=df['target'], verbose=False)
model.predict(df[['num_feat']])
```

And I get this error message:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-521d108aef97> in <module>
----> 1 model.predict(df[['num_feat']])

~/env/sber-task/lib/python3.6/site-packages/catboost/core.py in predict(self, data, prediction_type, ntree_start, ntree_end, thread_count, verbose)
   4549             _process_synonyms(params)
   4550             if 'loss_function' in params:
-> 4551                 if 'Poisson' in params['loss_function'] or 'Tweedie' in params['loss_function']:
   4552                     prediction_type = 'Exponent'
   4553         return self._predict(data, prediction_type, ntree_start, ntree_end, thread_count, verbose, 'predict')

TypeError: argument of type 'RmseObjective' is not iterable
```

**Comment by LyzhinIvan** [comment]
Yes, it's a bug. Thanks for reporting! Fix will be on Github soon.
