### ISSUE TITLE
Error: change of option monotone_constraints is unimplemented for task type GPU and was not default in previous run

### ISSUE THREAD

**Issue by yangqingqinghealsci** [catboost/catboost#1351]
Problem:Error: change of option monotone_constraints is unimplemented for task type GPU and was not default in previous run
catboost version:0.23.2
Operating System:
CPU:
# GPU:

**Comment by yangqingqinghealsci** [comment]
here is my param set：

model = CatBoostClassifier(loss_function='Logloss', task_type="GPU", monotone_constraints={‘BE_LAB_HB’:-1})
 model.fit(
            X=train_dataset,
            eval_set=eval_data, 
            early_stopping_rounds = 50,
            verbose=50,
            plot=is_plot
            )

**Comment by yangqingqinghealsci** [comment]
Traceback (most recent call last):
  File "/miniconda/envs/py36/lib/python3.6/site-packages/luigi/worker.py", line 194, in run
    new_deps = self._run_get_new_deps()
  File "/miniconda/envs/py36/lib/python3.6/site-packages/luigi/worker.py", line 131, in _run_get_new_deps
    task_gen = self.task.run()
  File "/aa/code/online_training/online_training.py", line 468, in run
    train_dump, test_dump, model_vecs, pred_info = trn.loss_models_train_xgb(loss_predictors, train, test)
  File "/aa/code/online_training/train.py", line 747, in loss_models_train_xgb
    is_plot=True, cv_num=cv_num, monotone_constraints=config.LOSS_MNT_CNTS)
  File "tools/do_model.py", line 666, in kfold_train_regression_cat
    plot=is_plot
  File "/miniconda/envs/py36/lib/python3.6/site-packages/catboost/core.py", line 4662, in fit
    save_snapshot, snapshot_file, snapshot_interval, init_model)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/catboost/core.py", line 1743, in _fit
    train_params["init_model"]
  File "/miniconda/envs/py36/lib/python3.6/site-packages/catboost/core.py", line 1230, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4345, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4391, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/private/libs/options/json_helper.h:270: Error: change of option monotone_constraints is unimplemented for task type GPU and was not default in previous run

**Comment by LyzhinIvan** [comment]
Monotone constraints are supported for CPU only.
