### ISSUE TITLE
_catboost.CatBoostError: catboost/private/libs/options/bootstrap_options.cpp:5: Taken fraction should in in (0,1]

### ISSUE THREAD

**Issue by Huagela** [catboost/catboost#1361]
**Problem:**_catboost.CatBoostError: catboost/private/libs/options/bootstrap_options.cpp:5: Taken fraction should in in (0,1]
**catboost version:** 0.23
**Operating System:** ubuntu 18.04
**CPU:** 16  Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz

when use BayesianOptimization ,pbounds as follows:
```
Bounded region of parameter space
pbounds = {
            'l2_leaf_reg': (2,30),
            'random_strength': (0,10), 
            'model_size_reg': (0,1), 
            'subsample': (0,1), 
            'depth': (1,10),
            'border_count': (1,512),
            'min_data_in_leaf': (1,5),
            'learning_rate': (0.01, 0.5), # default:0.15237300097942352
            'leaf_estimation_iterations': (1,20)}
```
it can  run about 20+ catboost model successfully in  hyper parameter searching ,but a few minuters later, it shows error:
```Shrink model to first 210 iterations.
{'nan_mode': 'Min', 'eval_metric': 'AUC', 'iterations': 10000, 'sampling_frequency': 'PerTree', 'leaf_estimation_method': 'Newton', 'od_pval': 0, 'grow_policy': 'SymmetricTree', 'penalties_coefficient': 1, 'boosting_type': 'Plain', 'model_shrink_mode': 'Constant', 'feature_border_type': 'GreedyLogSum', 'bayesian_matrix_reg': 0.10000000149011612, 'l2_leaf_reg': 16, 'random_strength': 4.745438575744629, 'od_type': 'Iter', 'rsm': 1, 'boost_from_average': False, 'model_size_reg': 0.188485324382782, 'subsample': 0.8982927799224854, 'use_best_model': True, 'od_wait': 50, 'class_names': [0, 1], 'random_seed': 0, 'depth': 1, 'border_count': 252, 'classes_count': 0, 'auto_class_weights': 'None', 'sparse_features_conflict_fraction': 0, 'leaf_estimation_backtracking': 'AnyImprovement', 'best_model_min_trees': 1, 'model_shrink_rate': 0, 'min_data_in_leaf': 4.822692740671863, 'loss_function': 'Logloss', 'learning_rate': 0.7676105499267578, 'score_function': 'Cosine', 'task_type': 'CPU', 'leaf_estimation_iterations': 5, 'bootstrap_type': 'MVS', 'max_leaves': 2}
AUC:0.6837
fold: 1
backend:cpu
Traceback (most recent call last):
  File "/home/spark/.local/lib/python3.6/site-packages/bayes_opt/target_space.py", line 191, in probe
    target = self._cache[_hashable(x)]
KeyError: (36.15376560053348, 1.0, 30.0, 20.0, 0.01, 1.0, 0.0, 10.0, 0.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "search_params_catboost.py", line 127, in <module>
    n_iter=100,
  File "/home/xxx/.local/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py", line 185, in maximize
    self.probe(x_probe, lazy=False)
  File "/home/xxx/.local/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py", line 116, in probe
    self._space.probe(params)
  File "/home/xxx/.local/lib/python3.6/site-packages/bayes_opt/target_space.py", line 194, in probe
    target = self.target_func(**params)
  File "search_params_catboost.py", line 70, in train_my_model
    model.fit(X_trn, y_trn,eval_set=[(X_val, y_val)],verbose=100, early_stopping_rounds=50)
  File "/home/xxx/.local/lib/python3.6/site-packages/catboost/core.py", line 4115, in fit
    silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
  File "/home/xxx/.local/lib/python3.6/site-packages/catboost/core.py", line 1731, in _fit
    save_snapshot, snapshot_file, snapshot_interval, init_model
  File "/home/xxx/.local/lib/python3.6/site-packages/catboost/core.py", line 1659, in _prepare_train_params
    _check_train_params(params)
  File "_catboost.pyx", line 5624, in _catboost._check_train_params
  File "_catboost.pyx", line 5643, in _catboost._check_train_params
_catboost.CatBoostError: catboost/private/libs/options/bootstrap_options.cpp:5: Taken fraction should in in (0,1]
```

 I need more info to debug, thx~

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Boostrap option "taken fraction" corresponds to subsample in CatBoost Pyhton module.
Most likely, subsample = 0 is passed to CatBoost.
Could you please try increasing the lower bound for subsample.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Should you have further questions, please feel free to reopen this issue.
