### ISSUE TITLE
NameError: name 'basestring' is not defined when using Makefile

### ISSUE THREAD

**Issue by rahul-iyer** [catboost/catboost#1365]
### CPU: Intel

```
'/usr/bin/python' '/local/home/iyerrahu/workspace/Catboost/src/build/scripts/vcs_info.py' '/vcs.json' '/local/home/iyerrahu/workspace/Catboost/src/contrib/tools/ragel6/__vcs_version__.c' '/local/home/iyerrahu/workspace/Catboost/src/build/scripts/c_templates/svn_interface.c'
Traceback (most recent call last):
  File "/local/home/iyerrahu/workspace/Catboost/src/build/scripts/vcs_info.py", line 266, in <module>
    print_c(json_file, sys.argv[2], sys.argv[3:])
  File "/local/home/iyerrahu/workspace/Catboost/src/build/scripts/vcs_info.py", line 102, in print_c
    f.write('\n'.join(gen_header(json_file)).encode('utf-8') + '\n' + c_file)
  File "/local/home/iyerrahu/workspace/Catboost/src/build/scripts/vcs_info.py", line 94, in gen_header
    lines.append(_Formatting.escaped_define(k, v))
  File "/local/home/iyerrahu/workspace/Catboost/src/build/scripts/vcs_info.py", line 33, in escaped_define
    if isinstance(val, basestring):
NameError: name 'basestring' is not defined
```

`basestring` is deprecated in python3. Python2 is not supported in my env. How should I go about solving this?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Many thanks for reporting the issue! We have passed it to the responsible team.
Meanwhile, you may use conda to setup Python 2.7 environment https://docs.anaconda.com/anaconda/user-guide/tasks/switch-environment/.
