### ISSUE TITLE
Test executing failed on Windows 10 64bit

### ISSUE THREAD

**Issue by feeeper** [catboost/catboost#1439]
Problem:
 `python ../../ya make -t` failed in the `catboost/pytest`

```
D:\Projects\catboost\catboost\pytest>python ../../ya make -t
------- [CC] {default-win-x86_64, debug, FAILED} $(S)/catboost/private/libs/data_util/exists_checker.cpp
command C:\Users\andre\.ya\tools\v3\1643218667/python D:\Projects\catboost/build/scripts/fix_msvc_output.py cl c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /FoC:\Users\andre\.ya\build\build_root\5wzz\000006/catboost/private/libs/data_util/exists_checker.cpp.obj D:\Projects\catboost/catboost/private/libs/data_util/exists_checker.cpp /I C:\Users\andre\.ya\build\build_root\5wzz\000006 /I D:\Projects\catboost /I D:\Projects\catboost/contrib/libs/cxxsupp/libcxx/include /I D:\Projects\catboost/contrib/libs/zlib/include /I D:\Projects\catboost/contrib/libs/double-conversion/include /I D:\Projects\catboost/contrib/libs/libc_compat/include/windows /nologo /Zm500 /GR /bigobj /FC /EHs /errorReport:prompt /Zc:inline /utf-8 /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt /I c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include /Ob0 /Od /D_DEBUG /MTd /Z7 /we4013 /w14018 /w14265 /w14296 /w14431 /wd4127 /wd4200 /wd4201 /wd4351 /wd4355 /wd4503 /wd4510 /wd4511 /wd4512 /wd4554 /wd4610 /wd4706 /wd4800 /wd4996 /wd4714 /wd4197 /wd4245 /wd4324 /wd5033 /DFAKEID=5020880 /DWIN32 /D_WIN32 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_WARNINGS /D_USE_MATH_DEFINES /D__STDC_CONSTANT_MACROS /D__STDC_FORMAT_MACROS /D_USING_V110_SDK71_ /D_LIBCPP_ENABLE_CXX17_REMOVED_FEATURES /D_WIN64 /DWIN64 /D_WIN32_WINNT=0x0601 /D_MBCS /DSSE_ENABLED=1 /DSSE3_ENABLED=1 /DSSSE3_ENABLED=1 /DSSE41_ENABLED=1 /DSSE42_ENABLED=1 /DPOPCNT_ENABLED=1 /DCX16_ENABLED=1 -DCATBOOST_OPENSOURCE=yes -D_LIBCPP_VASPRINTF_DEFINED -D_WCHAR_H_CPLUSPLUS_98_CONFORMANCE_ /DY_UCRT_INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt /DY_MSVC_INCLUDE=c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include /DSTRICT /DNOGDI /DNOMINMAX /DWIN32_LEAN_AND_MEAN /D__SSE2__=1 /D__SSE3__=1 /D__SSSE3__=1 /D__SSE4_1__=1 /D__SSE4_2__=1 /D__POPCNT__=1 /std:c++17 -DCATBOOST_OPENSOURCE=yes failed with exit code 1 in C:\Users\andre\.ya\build\build_root\5wzz\000006
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "library/python/runtime/importer.pxi", line 266, in __res.ResourceImporter.run_main
    self.load_module(entry_point, fix_name='__main__')
  File "library/python/runtime/importer.pxi", line 237, in __res.ResourceImporter.load_module
    exec code in mod.__dict__
  File "devtools/huge_python/__main__.py", line 69, in <module>
    runpy.run_path(script, run_name='__main__')
  File "contrib/tools/python/src/Lib/runpy.py", line 252, in run_path
  File "contrib/tools/python/src/Lib/runpy.py", line 82, in _run_module_code
  File "contrib/tools/python/src/Lib/runpy.py", line 72, in _run_code
  File "D:\Projects\catboost/build/scripts/fix_msvc_output.py", line 30, in <module>
    sys.exit(run(cmd))
  File "D:\Projects\catboost/build/scripts/fix_msvc_output.py", line 10, in out2err_cut_first_line
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "contrib/tools/python/src/Lib/subprocess.py", line 394, in __init__
  File "contrib/tools/python/src/Lib/subprocess.py", line 644, in _execute_child
WindowsError: [Error 193] %1 is not a valid Win32 application
------- [CC] {default-win-x86_64, debug, FAILED} $(S)/catboost/private/libs/init/init_reg.cpp
command C:\Users\andre\.ya\tools\v3\1643218667/python D:\Projects\catboost/build/scripts/fix_msvc_output.py cl c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /FoC:\Users\andre\.ya\build\build_root\5wzz\000008/catboost/private/libs/init/init_reg.cpp.obj D:\Projects\catboost/catboost/private/libs/init/init_reg.cpp /I C:\Users\andre\.ya\build\build_root\5wzz\000008 /I D:\Projects\catboost /I D:\Projects\catboost/contrib/libs/cxxsupp/libcxx/include /I D:\Projects\catboost/contrib/libs/zlib/include /I D:\Projects\catboost/contrib/libs/double-conversion/include /I D:\Projects\catboost/contrib/libs/libc_compat/include/windows /nologo /Zm500 /GR /bigobj /FC /EHs /errorReport:prompt /Zc:inline /utf-8 /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt /I c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include /Ob0 /Od /D_DEBUG /MTd /Z7 /we4013 /w14018 /w14265 /w14296 /w14431 /wd4127 /wd4200 /wd4201 /wd4351 /wd4355 /wd4503 /wd4510 /wd4511 /wd4512 /wd4554 /wd4610 /wd4706 /wd4800 /wd4996 /wd4714 /wd4197 /wd4245 /wd4324 /wd5033 /DFAKEID=5020880 /DWIN32 /D_WIN32 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_WARNINGS /D_USE_MATH_DEFINES /D__STDC_CONSTANT_MACROS /D__STDC_FORMAT_MACROS /D_USING_V110_SDK71_ /D_LIBCPP_ENABLE_CXX17_REMOVED_FEATURES /D_WIN64 /DWIN64 /D_WIN32_WINNT=0x0601 /D_MBCS /DSSE_ENABLED=1 /DSSE3_ENABLED=1 /DSSSE3_ENABLED=1 /DSSE41_ENABLED=1 /DSSE42_ENABLED=1 /DPOPCNT_ENABLED=1 /DCX16_ENABLED=1 -DCATBOOST_OPENSOURCE=yes -D_LIBCPP_VASPRINTF_DEFINED -D_WCHAR_H_CPLUSPLUS_98_CONFORMANCE_ /DY_UCRT_INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt /DY_MSVC_INCLUDE=c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include /DSTRICT /DNOGDI /DNOMINMAX /DWIN32_LEAN_AND_MEAN /D__SSE2__=1 /D__SSE3__=1 /D__SSSE3__=1 /D__SSE4_1__=1 /D__SSE4_2__=1 /D__POPCNT__=1 /std:c++17 -DCATBOOST_OPENSOURCE=yes failed with exit code 1 in C:\Users\andre\.ya\build\build_root\5wzz\000008
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "library/python/runtime/importer.pxi", line 266, in __res.ResourceImporter.run_main
    self.load_module(entry_point, fix_name='__main__')
  File "library/python/runtime/importer.pxi", line 237, in __res.ResourceImporter.load_module
    exec code in mod.__dict__
  File "devtools/huge_python/__main__.py", line 69, in <module>
    runpy.run_path(script, run_name='__main__')
  File "contrib/tools/python/src/Lib/runpy.py", line 252, in run_path
  File "contrib/tools/python/src/Lib/runpy.py", line 82, in _run_module_code
  File "contrib/tools/python/src/Lib/runpy.py", line 72, in _run_code
  File "D:\Projects\catboost/build/scripts/fix_msvc_output.py", line 30, in <module>
    sys.exit(run(cmd))
  File "D:\Projects\catboost/build/scripts/fix_msvc_output.py", line 10, in out2err_cut_first_line
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "contrib/tools/python/src/Lib/subprocess.py", line 394, in __init__
  File "contrib/tools/python/src/Lib/subprocess.py", line 644, in _execute_child
WindowsError: [Error 193] %1 is not a valid Win32 application
------- [CC] {default-win-x86_64, debug, FAILED} $(S)/catboost/private/libs/data_util/line_data_reader.cpp
command C:\Users\andre\.ya\tools\v3\1643218667/python D:\Projects\catboost/build/scripts/fix_msvc_output.py cl c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /FoC:\Users\andre\.ya\build\build_root\5wzz\000007/catboost/private/libs/data_util/line_data_reader.cpp.obj D:\Projects\catboost/catboost/private/libs/data_util/line_data_reader.cpp /I C:\Users\andre\.ya\build\build_root\5wzz\000007 /I D:\Projects\catboost /I D:\Projects\catboost/contrib/libs/cxxsupp/libcxx/include /I D:\Projects\catboost/contrib/libs/zlib/include /I D:\Projects\catboost/contrib/libs/double-conversion/include /I D:\Projects\catboost/contrib/libs/libc_compat/include/windows /nologo /Zm500 /GR /bigobj /FC /EHs /errorReport:prompt /Zc:inline /utf-8 /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt /I c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include /Ob0 /Od /D_DEBUG /MTd /Z7 /we4013 /w14018 /w14265 /w14296 /w14431 /wd4127 /wd4200 /wd4201 /wd4351 /wd4355 /wd4503 /wd4510 /wd4511 /wd4512 /wd4554 /wd4610 /wd4706 /wd4800 /wd4996 /wd4714 /wd4197 /wd4245 /wd4324 /wd5033 /DFAKEID=5020880 /DWIN32 /D_WIN32 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_WARNINGS /D_USE_MATH_DEFINES /D__STDC_CONSTANT_MACROS /D__STDC_FORMAT_MACROS /D_USING_V110_SDK71_ /D_LIBCPP_ENABLE_CXX17_REMOVED_FEATURES /D_WIN64 /DWIN64 /D_WIN32_WINNT=0x0601 /D_MBCS /DSSE_ENABLED=1 /DSSE3_ENABLED=1 /DSSSE3_ENABLED=1 /DSSE41_ENABLED=1 /DSSE42_ENABLED=1 /DPOPCNT_ENABLED=1 /DCX16_ENABLED=1 -DCATBOOST_OPENSOURCE=yes -D_LIBCPP_VASPRINTF_DEFINED -D_WCHAR_H_CPLUSPLUS_98_CONFORMANCE_ /DY_UCRT_INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt /DY_MSVC_INCLUDE=c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include /DSTRICT /DNOGDI /DNOMINMAX /DWIN32_LEAN_AND_MEAN /D__SSE2__=1 /D__SSE3__=1 /D__SSSE3__=1 /D__SSE4_1__=1 /D__SSE4_2__=1 /D__POPCNT__=1 /std:c++17 -DCATBOOST_OPENSOURCE=yes failed with exit code 1 in C:\Users\andre\.ya\build\build_root\5wzz\000007
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "library/python/runtime/importer.pxi", line 266, in __res.ResourceImporter.run_main
    self.load_module(entry_point, fix_name='__main__')
  File "library/python/runtime/importer.pxi", line 237, in __res.ResourceImporter.load_module
    exec code in mod.__dict__
  File "devtools/huge_python/__main__.py", line 69, in <module>
    runpy.run_path(script, run_name='__main__')
  File "contrib/tools/python/src/Lib/runpy.py", line 252, in run_path
  File "contrib/tools/python/src/Lib/runpy.py", line 82, in _run_module_code
  File "contrib/tools/python/src/Lib/runpy.py", line 72, in _run_code
  File "D:\Projects\catboost/build/scripts/fix_msvc_output.py", line 30, in <module>
    sys.exit(run(cmd))
  File "D:\Projects\catboost/build/scripts/fix_msvc_output.py", line 10, in out2err_cut_first_line
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "contrib/tools/python/src/Lib/subprocess.py", line 394, in __init__
  File "contrib/tools/python/src/Lib/subprocess.py", line 644, in _execute_child
WindowsError: [Error 193] %1 is not a valid Win32 application
------- [CC] {default-win-x86_64, debug, FAILED} $(S)/library/cpp/cpuid_check/cpu_id_check.cpp
command C:\Users\andre\.ya\tools\v3\1643218667/python D:\Projects\catboost/build/scripts/fix_msvc_output.py cl c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /FoC:\Users\andre\.ya\build\build_root\5wzz\000005/library/cpp/cpuid_check/cpu_id_check.cpp.obj D:\Projects\catboost/library/cpp/cpuid_check/cpu_id_check.cpp /I C:\Users\andre\.ya\build\build_root\5wzz\000005 /I D:\Projects\catboost /I D:\Projects\catboost/contrib/libs/cxxsupp/libcxx/include /I D:\Projects\catboost/contrib/libs/zlib/include /I D:\Projects\catboost/contrib/libs/double-conversion/include /I D:\Projects\catboost/contrib/libs/libc_compat/include/windows /nologo /Zm500 /GR /bigobj /FC /EHs /errorReport:prompt /Zc:inline /utf-8 /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt /I c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include /Ob0 /Od /D_DEBUG /MTd /Z7 /we4013 /w14018 /w14265 /w14296 /w14431 /wd4127 /wd4200 /wd4201 /wd4351 /wd4355 /wd4503 /wd4510 /wd4511 /wd4512 /wd4554 /wd4610 /wd4706 /wd4800 /wd4996 /wd4714 /wd4197 /wd4245 /wd4324 /wd5033 /DFAKEID=5020880 /DWIN32 /D_WIN32 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_WARNINGS /D_USE_MATH_DEFINES /D__STDC_CONSTANT_MACROS /D__STDC_FORMAT_MACROS /D_USING_V110_SDK71_ /D_LIBCPP_ENABLE_CXX17_REMOVED_FEATURES /D_WIN64 /DWIN64 /D_WIN32_WINNT=0x0601 /D_MBCS /DSSE_ENABLED=1 /DSSE3_ENABLED=1 /DSSSE3_ENABLED=1 /DSSE41_ENABLED=1 /DSSE42_ENABLED=1 /DPOPCNT_ENABLED=1 /DCX16_ENABLED=1 -DCATBOOST_OPENSOURCE=yes -D_LIBCPP_VASPRINTF_DEFINED -D_WCHAR_H_CPLUSPLUS_98_CONFORMANCE_ /DY_UCRT_INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt /DY_MSVC_INCLUDE=c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include /DSTRICT /DNOGDI /DNOMINMAX /DWIN32_LEAN_AND_MEAN /D__SSE2__=1 /D__SSE3__=1 /D__SSSE3__=1 /D__SSE4_1__=1 /D__SSE4_2__=1 /D__POPCNT__=1 /std:c++17 -DCATBOOST_OPENSOURCE=yes failed with exit code 1 in C:\Users\andre\.ya\build\build_root\5wzz\000005
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "library/python/runtime/importer.pxi", line 266, in __res.ResourceImporter.run_main
    self.load_module(entry_point, fix_name='__main__')
  File "library/python/runtime/importer.pxi", line 237, in __res.ResourceImporter.load_module
    exec code in mod.__dict__
  File "devtools/huge_python/__main__.py", line 69, in <module>
    runpy.run_path(script, run_name='__main__')
  File "contrib/tools/python/src/Lib/runpy.py", line 252, in run_path
  File "contrib/tools/python/src/Lib/runpy.py", line 82, in _run_module_code
  File "contrib/tools/python/src/Lib/runpy.py", line 72, in _run_code
  File "D:\Projects\catboost/build/scripts/fix_msvc_output.py", line 30, in <module>
    sys.exit(run(cmd))
  File "D:\Projects\catboost/build/scripts/fix_msvc_output.py", line 10, in out2err_cut_first_line
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "contrib/tools/python/src/Lib/subprocess.py", line 394, in __init__
  File "contrib/tools/python/src/Lib/subprocess.py", line 644, in _execute_child
WindowsError: [Error 193] %1 is not a valid Win32 application
------- [CC] {default-win-x86_64, debug, FAILED} $(S)/library/cpp/blockcodecs/codecs/brotli/brotli.cpp
command C:\Users\andre\.ya\tools\v3\1643218667/python D:\Projects\catboost/build/scripts/fix_msvc_output.py cl c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /FoC:\Users\andre\.ya\build\build_root\5wzz\000009/library/cpp/blockcodecs/codecs/brotli/brotli.cpp.obj D:\Projects\catboost/library/cpp/blockcodecs/codecs/brotli/brotli.cpp /I C:\Users\andre\.ya\build\build_root\5wzz\000009 /I D:\Projects\catboost /I D:\Projects\catboost/contrib/libs/cxxsupp/libcxx/include /I D:\Projects\catboost/contrib/libs/zlib/include /I D:\Projects\catboost/contrib/libs/double-conversion/include /I D:\Projects\catboost/contrib/libs/libc_compat/include/windows /I D:\Projects\catboost/contrib/libs/brotli/include /nologo /Zm500 /GR /bigobj /FC /EHs 
/errorReport:prompt /Zc:inline /utf-8 /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt /I c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include /Ob0 /Od /D_DEBUG /MTd /Z7 /we4013 /w14018 /w14265 /w14296 /w14431 /wd4127 /wd4200 /wd4201 /wd4351 /wd4355 /wd4503 /wd4510 /wd4511 /wd4512 /wd4554 /wd4610 /wd4706 /wd4800 /wd4996 /wd4714 /wd4197 /wd4245 /wd4324 /wd5033 /DFAKEID=5020880 /DWIN32 /D_WIN32 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_WARNINGS /D_USE_MATH_DEFINES /D__STDC_CONSTANT_MACROS /D__STDC_FORMAT_MACROS /D_USING_V110_SDK71_ /D_LIBCPP_ENABLE_CXX17_REMOVED_FEATURES /D_WIN64 /DWIN64 /D_WIN32_WINNT=0x0601 /D_MBCS /DSSE_ENABLED=1 /DSSE3_ENABLED=1 /DSSSE3_ENABLED=1 /DSSE41_ENABLED=1 /DSSE42_ENABLED=1 /DPOPCNT_ENABLED=1 /DCX16_ENABLED=1 -DCATBOOST_OPENSOURCE=yes -D_LIBCPP_VASPRINTF_DEFINED -D_WCHAR_H_CPLUSPLUS_98_CONFORMANCE_ /DY_UCRT_INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt /DY_MSVC_INCLUDE=c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include /DSTRICT /DNOGDI /DNOMINMAX /DWIN32_LEAN_AND_MEAN /D__SSE2__=1 /D__SSE3__=1 /D__SSSE3__=1 /D__SSE4_1__=1 /D__SSE4_2__=1 /D__POPCNT__=1 /std:c++17 -DCATBOOST_OPENSOURCE=yes failed with exit code 1 in C:\Users\andre\.ya\build\build_root\5wzz\000009
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "library/python/runtime/importer.pxi", line 266, in __res.ResourceImporter.run_main
    self.load_module(entry_point, fix_name='__main__')
  File "library/python/runtime/importer.pxi", line 237, in __res.ResourceImporter.load_module
    exec code in mod.__dict__
  File "devtools/huge_python/__main__.py", line 69, in <module>
    runpy.run_path(script, run_name='__main__')
  File "contrib/tools/python/src/Lib/runpy.py", line 252, in run_path
  File "contrib/tools/python/src/Lib/runpy.py", line 82, in _run_module_code
  File "contrib/tools/python/src/Lib/runpy.py", line 72, in _run_code
  File "D:\Projects\catboost/build/scripts/fix_msvc_output.py", line 30, in <module>
    sys.exit(run(cmd))
  File "D:\Projects\catboost/build/scripts/fix_msvc_output.py", line 10, in out2err_cut_first_line
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "contrib/tools/python/src/Lib/subprocess.py", line 394, in __init__
  File "contrib/tools/python/src/Lib/subprocess.py", line 644, in _execute_child
WindowsError: [Error 193] %1 is not a valid Win32 application
------- [CC] {default-win-x86_64, debug, FAILED} $(S)/library/cpp/blockcodecs/codecs/bzip/bzip.cpp
command C:\Users\andre\.ya\tools\v3\1643218667/python D:\Projects\catboost/build/scripts/fix_msvc_output.py cl c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe /c /FoC:\Users\andre\.ya\build\build_root\5wzz\00000a/library/cpp/blockcodecs/codecs/bzip/bzip.cpp.obj D:\Projects\catboost/library/cpp/blockcodecs/codecs/bzip/bzip.cpp /I C:\Users\andre\.ya\build\build_root\5wzz\00000a /I D:\Projects\catboost /I D:\Projects\catboost/contrib/libs/cxxsupp/libcxx/include /I D:\Projects\catboost/contrib/libs/zlib/include /I D:\Projects\catboost/contrib/libs/double-conversion/include /I D:\Projects\catboost/contrib/libs/libc_compat/include/windows /nologo /Zm500 /GR /bigobj /FC /EHs /errorReport:prompt /Zc:inline /utf-8 /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um /I C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt /I c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include /Ob0 /Od /D_DEBUG /MTd /Z7 /we4013 /w14018 /w14265 /w14296 /w14431 /wd4127 /wd4200 /wd4201 /wd4351 /wd4355 /wd4503 /wd4510 /wd4511 /wd4512 /wd4554 /wd4610 /wd4706 /wd4800 /wd4996 /wd4714 /wd4197 /wd4245 /wd4324 /wd5033 /DFAKEID=5020880 /DWIN32 /D_WIN32 /D_WINDOWS /D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_WARNINGS /D_USE_MATH_DEFINES /D__STDC_CONSTANT_MACROS /D__STDC_FORMAT_MACROS /D_USING_V110_SDK71_ /D_LIBCPP_ENABLE_CXX17_REMOVED_FEATURES /D_WIN64 /DWIN64 /D_WIN32_WINNT=0x0601 /D_MBCS /DSSE_ENABLED=1 /DSSE3_ENABLED=1 /DSSSE3_ENABLED=1 /DSSE41_ENABLED=1 /DSSE42_ENABLED=1 /DPOPCNT_ENABLED=1 /DCX16_ENABLED=1 -DCATBOOST_OPENSOURCE=yes -D_LIBCPP_VASPRINTF_DEFINED -D_WCHAR_H_CPLUSPLUS_98_CONFORMANCE_ /DY_UCRT_INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt /DY_MSVC_INCLUDE=c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include /DSTRICT /DNOGDI /DNOMINMAX /DWIN32_LEAN_AND_MEAN /D__SSE2__=1 /D__SSE3__=1 /D__SSSE3__=1 /D__SSE4_1__=1 /D__SSE4_2__=1 /D__POPCNT__=1 /std:c++17 -DCATBOOST_OPENSOURCE=yes failed with exit code 1 in C:\Users\andre\.ya\build\build_root\5wzz\00000a
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "library/python/runtime/importer.pxi", line 266, in __res.ResourceImporter.run_main
    self.load_module(entry_point, fix_name='__main__')
  File "library/python/runtime/importer.pxi", line 237, in __res.ResourceImporter.load_module
    exec code in mod.__dict__
  File "devtools/huge_python/__main__.py", line 69, in <module>
    runpy.run_path(script, run_name='__main__')
  File "contrib/tools/python/src/Lib/runpy.py", line 252, in run_path
  File "contrib/tools/python/src/Lib/runpy.py", line 82, in _run_module_code
  File "contrib/tools/python/src/Lib/runpy.py", line 72, in _run_code
  File "D:\Projects\catboost/build/scripts/fix_msvc_output.py", line 30, in <module>
    sys.exit(run(cmd))
  File "D:\Projects\catboost/build/scripts/fix_msvc_output.py", line 10, in out2err_cut_first_line
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "contrib/tools/python/src/Lib/subprocess.py", line 394, in __init__
  File "contrib/tools/python/src/Lib/subprocess.py", line 644, in _execute_child
WindowsError: [Error 193] %1 is not a valid Win32 application
Failed
```

catboost version: latest (master branch)
Operating System: Windows 10 (x64)
CPU: Intel Core i7-7700HQ
GPU: gtx1070

1. Tried different python (x32, x64). 
2. Ran `c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat` before `ya make -t`

**Comment by andrey-khropov** [comment]
I cannot reproduce it, tried for multiple revisions from 2020-10-02.
