### ISSUE TITLE
Support `pathlib.Path` as an argument for `save_model`

### ISSUE THREAD

**Issue by Yura52** [catboost/catboost#1520]
Problem: [`pathlib.Path`](https://docs.python.org/3/library/pathlib.html) is one of the mainstream ways to deal with paths. However, the method `save_model` seems to support only strings:
```
# the variable `output` is an instance of pathlib.Path

...
Shrink model to first 160 iterations.
...
Traceback (most recent call last):
  File "catboost_.py", line 81, in <module>
    model.save_model(output / 'catboost.cbm')
  File ".../lib/python3.8/site-packages/catboost/core.py", line 2725, in save_model
    raise CatBoostError("Invalid fname type={}: must be str().".format(type(fname)))
_catboost.CatBoostError: Invalid fname type=<class 'pathlib.PosixPath'>: must be str().
```

catboost version: 0.24.3

**Comment by kizill** [comment]
Rolled out as part of 0.25 release!
