### ISSUE TITLE
Compile from source on Ubuntu 20.04 with CUDA 11.2

### ISSUE THREAD

**Issue by JohnStott** [catboost/catboost#1559]
Compile from source on Ubuntu 20.04 with CUDA 11.2:

../../../ya make -r -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -DPYTHON_CONFIG=python3-config -DCUDA_ROOT=/usr/local/cuda-11.2

looks like it is trying to download some file to my system as get this error (have tried with firewall switched off but makes no difference):

Traceback (most recent call last):
  File "devtools/ya/app.py", line 418, in configure_exit_interceptor
    yield
  File "devtools/ya/app.py", line 65, in helper
    return action(args)
  File "devtools/ya/entry/entry.py", line 55, in do_main
    res = handler.handle(handler, args, prefix=['ya'])
  File "devtools/ya/core/handler.py", line 159, in handle
    return handler.handle(self, args[1:], prefix + [name])
  File "devtools/ya/core/dispatch.py", line 37, in handle
    return self.command().handle(root_handler, args, prefix)
  File "devtools/ya/core/handler.py", line 341, in handle
    return self._action(params)
  File "devtools/ya/app.py", line 92, in helper
    return action(ctx.params)
  File "devtools/ya/build/build_handler.py", line 85, in do_ya_make
    builder = ya_make.YaMake(params, app_ctx)
  File "devtools/ya/build/ya_make.py", line 895, in __init__
    self.ctx = Context(self.opts, app_ctx=app_ctx, graph=graph, tests=tests, stripped_tests=stripped_tests, configure_errors=configure_errors, make_files=make_files, lite_graph=lite_graph)
  File "devtools/ya/build/ya_make.py", line 574, in __init__
    self.graph, self.tests, self.stripped_tests, self.configure_errors, self.make_files = _build_graph_and_tests(self.opts, app_ctx)
  File "devtools/ya/build/ya_make.py", line 258, in _build_graph_and_tests
    graph, tests, stripped_tests, gh, make_files = lg.build_graph_and_tests(opts, check=True, ev_listener=ev_listener, display=display)
  File "devtools/ya/build/graph.py", line 1688, in build_graph_and_tests
    return _build_graph_and_tests(opts, check, ev_listener, exit_stack, display)
  File "devtools/ya/build/graph.py", line 1992, in _build_graph_and_tests
    real_ymake_bin = tools.tool('ymake')
  File "devtools/ya/yalibrary/tools/__init__.py", line 220, in tool
    return toolchain.find(name, with_params, for_platform, cache=cache)
  File "devtools/ya/yalibrary/tools/__init__.py", line 158, in find
    executable = cur_bottle[executable_name]  # if executable_name is None it's Ok
  File "devtools/ya/yalibrary/tools/__init__.py", line 64, in __getitem__
    path = self.resolve()
  File "devtools/ya/yalibrary/tools/__init__.py", line 46, in resolve
    return self.__fetcher.fetch_if_need(self.__formula["match"], tared, binname, cache=cache).where
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 385, in fetch_if_need
    self.__c[key] = self._fetch_if_need(*args, **kwargs)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 452, in _fetch_if_need
    if self._fetch(name, tared, lambda x: name.lower() in x.lower(), binname):
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 368, in _fetch
    _install(res_path, do_install)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 104, in _install
    fs_handler(install_guard)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 95, in fs_handler
    func(install_guard)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 346, in do_install
    resource_info = self._download(name, res, download_to)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 524, in _download
    http_client.download_file(url=config.mapping()["resources"][resource["id"]], path=download_to)
  File "devtools/ya/exts/retry.py", line 20, in wrapper
    return retry(proxy_func, **retry_kwargs)
  File "devtools/ya/exts/retry.py", line 12, in retry
    return lpr.retry_call(func, conf=_conf(func, *args, **kwargs))
  File "library/python/retry/__init__.py", line 183, in retry_call
    return _retry(conf, functools.partial(f, *f_args, **f_kwargs))
  File "library/python/retry/__init__.py", line 221, in _retry
    return f()
  File "devtools/ya/exts/retry.py", line 19, in <lambda>
    proxy_func = lambda: func(*args, **kwargs)
  File "devtools/ya/exts/http_client.py", line 67, in download_file
    raise e
URLError: <urlopen error [Errno -3] Try again>

What is "ya" trying to download and how can I fix this?

**Comment by kizill** [comment]
Ya make is downloading CLANG toolkit archive, so it's important to have network access to https://storage.mds.yandex.net/
