### ISSUE TITLE
[catboost4j-spark] java.lang.IndexOutOfBoundsException error with real-world datasets

### ISSUE THREAD

**Issue by candalfigomoro** [catboost/catboost#1563]
Problem:
I'm able to run the code examples (with 4-row datasets) of the README file in https://github.com/catboost/catboost/tree/master/catboost/spark/catboost4j-spark

However, when I try to replace the toy dataset with real-world Spark dataframes (e.g. 50 vector-assembled columns with real values, 130000 rows), I keep getting the following error:

```
py4j.protocol.Py4JJavaError: An error occurred while calling o285.fit.
: java.lang.RuntimeException: Error while executing workers
	at ai.catboost.spark.impl.Helpers$.checkOneFutureAndWaitForOther(Helpers.scala:30)
	at ai.catboost.spark.CatBoostPredictorTrait.fit(CatBoostPredictor.scala:201)
	at ai.catboost.spark.CatBoostPredictorTrait.fit$(CatBoostPredictor.scala:108)
	at ai.catboost.spark.CatBoostClassifier.fit(CatBoostClassifier.scala:362)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	...
Caused by: java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at ai.catboost.spark.impl.Helpers$.checkOneFutureAndWaitForOther(Helpers.scala:26)
	... 22 more
Caused by: java.lang.IndexOutOfBoundsException
	at java.base/java.nio.Buffer.checkIndex(Buffer.java:686)
	at java.base/java.nio.DirectByteBuffer.put(DirectByteBuffer.java:344)
	at ai.catboost.spark.FeaturesColumnStorage.$anonfun$addRowFeatures$1(DataHelpers.scala:188)
	at ai.catboost.spark.FeaturesColumnStorage.$anonfun$addRowFeatures$1$adapted(DataHelpers.scala:187)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at ai.catboost.spark.FeaturesColumnStorage.addRowFeatures(DataHelpers.scala:187)
	at ai.catboost.spark.DataHelpers$.$anonfun$getMainDataProcessingCallbacks$1(DataHelpers.scala:576)
	at ai.catboost.spark.DataHelpers$.$anonfun$getMainDataProcessingCallbacks$1$adapted(DataHelpers.scala:575)
	at ai.catboost.spark.DataHelpers$.$anonfun$loadQuantizedDatasets$2(DataHelpers.scala:782)
	at ai.catboost.spark.DataHelpers$.$anonfun$loadQuantizedDatasets$2$adapted(DataHelpers.scala:782)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ai.catboost.spark.DataHelpers$.$anonfun$loadQuantizedDatasets$1(DataHelpers.scala:782)
	at ai.catboost.spark.DataHelpers$.$anonfun$loadQuantizedDatasets$1$adapted(DataHelpers.scala:781)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at ai.catboost.spark.DataHelpers$.loadQuantizedDatasets(DataHelpers.scala:781)
	at ai.catboost.spark.DataHelpers$.downloadQuantizedPoolToTempFiles(DataHelpers.scala:1021)
	at ai.catboost.spark.impl.Master$.$anonfun$apply$2(Master.scala:46)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:273)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at ai.catboost.spark.impl.Master$.$anonfun$apply$1(Master.scala:45)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

Traceback (most recent call last):
  ...
  File "/tmp/conda-1e956606-c81e-46ea-a9bf-6a5b910666aa/real/envs/conda-env/lib/python3.6/site-packages/myproject/datasets/examples.py", line 19, in my_compute_function
    model = classifier.fit(trainPool, [evalPool])
  File "/tmp/conda-1e956606-c81e-46ea-a9bf-6a5b910666aa/real/envs/conda-env/lib/python3.6/site-packages/catboost_spark/core.py", line 4749, in fit
    java_model = self._java_obj.fit(_py2java(sc, trainDataset), evalDatasetsAsJavaObject)
  File "/tmp/conda-1e956606-c81e-46ea-a9bf-6a5b910666aa/real/envs/conda-env/lib/python3.6/site-packages/py4j/java_gateway.py", line 1286, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/tmp/conda-1e956606-c81e-46ea-a9bf-6a5b910666aa/real/envs/conda-env/lib/python3.6/site-packages/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/tmp/conda-1e956606-c81e-46ea-a9bf-6a5b910666aa/real/envs/conda-env/lib/python3.6/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o285.fit.
: java.lang.RuntimeException: Error while executing workers
	at ai.catboost.spark.impl.Helpers$.checkOneFutureAndWaitForOther(Helpers.scala:30)
	at ai.catboost.spark.CatBoostPredictorTrait.fit(CatBoostPredictor.scala:201)
	at ai.catboost.spark.CatBoostPredictorTrait.fit$(CatBoostPredictor.scala:108)
	at ai.catboost.spark.CatBoostClassifier.fit(CatBoostClassifier.scala:362)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	...
Caused by: java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at ai.catboost.spark.impl.Helpers$.checkOneFutureAndWaitForOther(Helpers.scala:26)
	... 22 more
Caused by: java.lang.IndexOutOfBoundsException
	at java.base/java.nio.Buffer.checkIndex(Buffer.java:686)
	at java.base/java.nio.DirectByteBuffer.put(DirectByteBuffer.java:344)
	at ai.catboost.spark.FeaturesColumnStorage.$anonfun$addRowFeatures$1(DataHelpers.scala:188)
	at ai.catboost.spark.FeaturesColumnStorage.$anonfun$addRowFeatures$1$adapted(DataHelpers.scala:187)
	at scala.collection.immutable.Range.foreach(Range.scala:158)
	at ai.catboost.spark.FeaturesColumnStorage.addRowFeatures(DataHelpers.scala:187)
	at ai.catboost.spark.DataHelpers$.$anonfun$getMainDataProcessingCallbacks$1(DataHelpers.scala:576)
	at ai.catboost.spark.DataHelpers$.$anonfun$getMainDataProcessingCallbacks$1$adapted(DataHelpers.scala:575)
	at ai.catboost.spark.DataHelpers$.$anonfun$loadQuantizedDatasets$2(DataHelpers.scala:782)
	at ai.catboost.spark.DataHelpers$.$anonfun$loadQuantizedDatasets$2$adapted(DataHelpers.scala:782)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at ai.catboost.spark.DataHelpers$.$anonfun$loadQuantizedDatasets$1(DataHelpers.scala:782)
	at ai.catboost.spark.DataHelpers$.$anonfun$loadQuantizedDatasets$1$adapted(DataHelpers.scala:781)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at ai.catboost.spark.DataHelpers$.loadQuantizedDatasets(DataHelpers.scala:781)
	at ai.catboost.spark.DataHelpers$.downloadQuantizedPoolToTempFiles(DataHelpers.scala:1021)
	at ai.catboost.spark.impl.Master$.$anonfun$apply$2(Master.scala:46)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:273)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at ai.catboost.spark.impl.Master$.$anonfun$apply$1(Master.scala:45)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```
catboost version: catboost-spark_2.12-0.25-rc3 (PySpark)
Operating System: Linux
CPU: Intel

@andrey-khropov

**Comment by andrey-khropov** [comment]
Release 0.25 includes the fix.
