### ISSUE TITLE
[catboost4j-spark] SparkException error when spark.executor.cores > 1

### ISSUE THREAD

**Issue by candalfigomoro** [catboost/catboost#1622]
Problem:
With real-world Spark dataframes (e.g. 50 vector-assembled columns with real values, 130000 rows), I get this "An active CatBoost worker is already present in the current process" error when `spark.executor.cores` is greater than `1`:
```
py4j.protocol.Py4JJavaError: An error occurred while calling o289.fit.
: java.lang.RuntimeException: Error while executing workers
	at ai.catboost.spark.impl.Helpers$.checkOneFutureAndWaitForOther(Helpers.scala:30)
	at ai.catboost.spark.CatBoostPredictorTrait.fit(CatBoostPredictor.scala:206)
	at ai.catboost.spark.CatBoostPredictorTrait.fit$(CatBoostPredictor.scala:109)
	at ai.catboost.spark.CatBoostClassifier.fit(CatBoostClassifier.scala:362)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
Caused by: java.util.concurrent.ExecutionException: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 97.0 failed 4 times, most recent failure: Lost task 2.3 in stage 97.0 (TID 265, executor 2): ai.catboost.CatBoostError: An active CatBoost worker is already present in the current process
	at ai.catboost.spark.impl.CatBoostWorker.processPartition(Workers.scala:46)
	at ai.catboost.spark.impl.CatBoostWorkers.$anonfun$run$5(Workers.scala:241)
	at ai.catboost.spark.impl.CatBoostWorkers.$anonfun$run$5$adapted(Workers.scala:234)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:951)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:951)
	at org.apache.spark.SparkContext.$anonfun$runJob$3(SparkContext.scala:2102)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:128)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$1(Executor.scala:440)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1318)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:443)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Driver stacktrace:
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at ai.catboost.spark.impl.Helpers$.checkOneFutureAndWaitForOther(Helpers.scala:26)
	... 22 more
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 97.0 failed 4 times, most recent failure: Lost task 2.3 in stage 97.0 (TID 265, executor 2): ai.catboost.CatBoostError: An active CatBoost worker is already present in the current process
	at ai.catboost.spark.impl.CatBoostWorker.processPartition(Workers.scala:46)
	at ai.catboost.spark.impl.CatBoostWorkers.$anonfun$run$5(Workers.scala:241)
	at ai.catboost.spark.impl.CatBoostWorkers.$anonfun$run$5$adapted(Workers.scala:234)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:951)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:951)
	at org.apache.spark.SparkContext.$anonfun$runJob$3(SparkContext.scala:2102)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:128)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$1(Executor.scala:440)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1318)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:443)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:1990)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:1978)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:1977)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1977)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:953)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:953)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:953)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2207)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2156)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2145)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:764)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2062)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2083)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2102)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2127)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:951)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:153)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:114)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:366)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:949)
	at org.apache.spark.sql.Dataset.$anonfun$foreachPartition$1(Dataset.scala:2663)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.Dataset.$anonfun$withNewRDDExecutionId$1(Dataset.scala:3333)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:87)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:147)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:74)
	at org.apache.spark.sql.Dataset.withNewRDDExecutionId(Dataset.scala:3329)
	at org.apache.spark.sql.Dataset.foreachPartition(Dataset.scala:2663)
	at ai.catboost.spark.impl.CatBoostWorkers.run(Workers.scala:234)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
Caused by: ai.catboost.CatBoostError: An active CatBoost worker is already present in the current process
	at ai.catboost.spark.impl.CatBoostWorker.processPartition(Workers.scala:46)
	at ai.catboost.spark.impl.CatBoostWorkers.$anonfun$run$5(Workers.scala:241)
	at ai.catboost.spark.impl.CatBoostWorkers.$anonfun$run$5$adapted(Workers.scala:234)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:951)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:951)
	at org.apache.spark.SparkContext.$anonfun$runJob$3(SparkContext.scala:2102)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:128)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$1(Executor.scala:440)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1318)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:443)
	... 3 more

Traceback (most recent call last):
  File "/tmp/conda-9a36ea6e-22fc-431c-9ace-3dc8c8f0a2bd/real/envs/conda-env/lib/python3.6/site-packages/transforms_spark_module/delegate.py", line 84, in _execute_job
    outputs = job.run(input_specs, output_specs, branch, compute_function=compute_function, parameters=parameters)
  File "/tmp/conda-9a36ea6e-22fc-431c-9ace-3dc8c8f0a2bd/real/envs/conda-env/lib/python3.6/site-packages/transforms/_build.py", line 211, in run
    self._transform.compute(ctx=transform_context, **parameters)
  File "/tmp/conda-9a36ea6e-22fc-431c-9ace-3dc8c8f0a2bd/real/envs/conda-env/lib/python3.6/site-packages/transforms/api/_transform.py", line 251, in compute
    output_df = self(**kwargs)
  File "/tmp/conda-9a36ea6e-22fc-431c-9ace-3dc8c8f0a2bd/real/envs/conda-env/lib/python3.6/site-packages/transforms/api/_transform.py", line 120, in __call__
    return self._compute_func(*args, **kwargs)
  File "/tmp/conda-9a36ea6e-22fc-431c-9ace-3dc8c8f0a2bd/real/envs/conda-env/lib/python3.6/site-packages/myproject/datasets/examples.py", line 19, in my_compute_function
    model = classifier.fit(trainPool, [evalPool])
  File "/tmp/conda-9a36ea6e-22fc-431c-9ace-3dc8c8f0a2bd/real/envs/conda-env/lib/python3.6/site-packages/catboost_spark/core.py", line 4978, in fit
    java_model = self._java_obj.fit(_py2java(sc, trainDataset), evalDatasetsAsJavaObject)
  File "/tmp/conda-9a36ea6e-22fc-431c-9ace-3dc8c8f0a2bd/real/envs/conda-env/lib/python3.6/site-packages/py4j/java_gateway.py", line 1286, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/tmp/conda-9a36ea6e-22fc-431c-9ace-3dc8c8f0a2bd/real/envs/conda-env/lib/python3.6/site-packages/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/tmp/conda-9a36ea6e-22fc-431c-9ace-3dc8c8f0a2bd/real/envs/conda-env/lib/python3.6/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o289.fit.
: java.lang.RuntimeException: Error while executing workers
	at ai.catboost.spark.impl.Helpers$.checkOneFutureAndWaitForOther(Helpers.scala:30)
	at ai.catboost.spark.CatBoostPredictorTrait.fit(CatBoostPredictor.scala:206)
	at ai.catboost.spark.CatBoostPredictorTrait.fit$(CatBoostPredictor.scala:109)
	at ai.catboost.spark.CatBoostClassifier.fit(CatBoostClassifier.scala:362)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
Caused by: java.util.concurrent.ExecutionException: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 97.0 failed 4 times, most recent failure: Lost task 2.3 in stage 97.0 (TID 265, executor 2): ai.catboost.CatBoostError: An active CatBoost worker is already present in the current process
	at ai.catboost.spark.impl.CatBoostWorker.processPartition(Workers.scala:46)
	at ai.catboost.spark.impl.CatBoostWorkers.$anonfun$run$5(Workers.scala:241)
	at ai.catboost.spark.impl.CatBoostWorkers.$anonfun$run$5$adapted(Workers.scala:234)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:951)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:951)
	at org.apache.spark.SparkContext.$anonfun$runJob$3(SparkContext.scala:2102)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:128)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$1(Executor.scala:440)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1318)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:443)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Driver stacktrace:
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at ai.catboost.spark.impl.Helpers$.checkOneFutureAndWaitForOther(Helpers.scala:26)
	... 22 more
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 97.0 failed 4 times, most recent failure: Lost task 2.3 in stage 97.0 (TID 265, executor 2): ai.catboost.CatBoostError: An active CatBoost worker is already present in the current process
	at ai.catboost.spark.impl.CatBoostWorker.processPartition(Workers.scala:46)
	at ai.catboost.spark.impl.CatBoostWorkers.$anonfun$run$5(Workers.scala:241)
	at ai.catboost.spark.impl.CatBoostWorkers.$anonfun$run$5$adapted(Workers.scala:234)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:951)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:951)
	at org.apache.spark.SparkContext.$anonfun$runJob$3(SparkContext.scala:2102)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:128)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$1(Executor.scala:440)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1318)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:443)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:1990)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:1978)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:1977)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1977)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:953)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:953)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:953)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2207)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2156)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2145)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:764)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2062)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2083)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2102)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2127)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:951)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:153)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:114)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:366)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:949)
	at org.apache.spark.sql.Dataset.$anonfun$foreachPartition$1(Dataset.scala:2663)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.Dataset.$anonfun$withNewRDDExecutionId$1(Dataset.scala:3333)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:87)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:147)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:74)
	at org.apache.spark.sql.Dataset.withNewRDDExecutionId(Dataset.scala:3329)
	at org.apache.spark.sql.Dataset.foreachPartition(Dataset.scala:2663)
	at ai.catboost.spark.impl.CatBoostWorkers.run(Workers.scala:234)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
Caused by: ai.catboost.CatBoostError: An active CatBoost worker is already present in the current process
	at ai.catboost.spark.impl.CatBoostWorker.processPartition(Workers.scala:46)
	at ai.catboost.spark.impl.CatBoostWorkers.$anonfun$run$5(Workers.scala:241)
	at ai.catboost.spark.impl.CatBoostWorkers.$anonfun$run$5$adapted(Workers.scala:234)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:951)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:951)
	at org.apache.spark.SparkContext.$anonfun$runJob$3(SparkContext.scala:2102)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:128)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$1(Executor.scala:440)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1318)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:443)
	... 3 more
```

catboost version: catboost-spark_2.4_2.12-0.25 (PySpark)

@andrey-khropov

**Comment by andrey-khropov** [comment]
I'll update the docs about that, CatBoost workers used in training cannot coexist in one process for now. You should set `spark.task.cpus` parameter to be equal to the number of cores in executors (`spark.executor.cores`).

**Comment by sidharth-iitkgp** [comment]
Is this still required while model training? If yes, then where/how should I set it?

**Comment by summer5e55** [comment]
> I'll update the docs about that, CatBoost workers used in training cannot coexist in one process for now. You should set `spark.task.cpus` parameter to be equal to the number of cores in executors (`spark.executor.cores`).

I have set spark.task.cpus to spark.executor.cores in my spark context, but for some reason, still getting this error. Any suggestion on this?  Am I set the parameter correctly as follows:
spark.conf.set("spark.tasks.cpus","spark.executor.cores")
