### ISSUE TITLE
Model loading error

### ISSUE THREAD

**Issue by dvigal** [catboost/catboost#164]
Hi, 
I have got an error while loading dump model
`>>> joblib.load('model.pkl')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 575, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/opt/anaconda3/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 507, in _unpickle
    obj = unpickler.load()
  File "/opt/anaconda3/lib/python3.5/pickle.py", line 1039, in load
    dispatch[key[0]](self)
  File "/opt/anaconda3/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 327, in load_build
    Unpickler.load_build(self)
  File "/opt/anaconda3/lib/python3.5/pickle.py", line 1510, in load_build
    setstate(state)
  File "_catboost.pyx", line 744, in _catboost._CatBoostBase.__setstate__ (/home/donskov/.ya/build/build_root/kd7z/00034f/catboost/python-package/catboost/_catboost.pyx.cpp:13770)
  File "_catboost.pyx", line 812, in _catboost._CatBoostBase._deserialize_model (/home/donskov/.ya/build/build_root/kd7z/00034f/catboost/python-package/catboost/_catboost.pyx.cpp:16290)
  File "_catboost.pyx", line 700, in _catboost._CatBoost._deserialize_model (/home/donskov/.ya/build/build_root/kd7z/00034f/catboost/python-package/catboost/_catboost.pyx.cpp:12602)
  File "_catboost.pyx", line 702, in _catboost._CatBoost._deserialize_model (/home/donskov/.ya/build/build_root/kd7z/00034f/catboost/python-package/catboost/_catboost.pyx.cpp:12529)
_catboost.CatboostError: util/ysaveload.h:55: can not load pod type(4, 0 bytes)`

The dump of the model was obtained as follows 
`catboost_model = CatBoostClassifier(custom_loss=['Logloss'], eval_metric='AUC',
                                        random_seed=99, iterations=500)
    categorical_features_indices = np.where(train.dtypes != np.float)[0]
    catboost_model.fit(train, train_offline_target, cat_features=categorical_features_indices,
                       eval_set=(test, test_offline_target), plot=True)
    joblib.dump(catboost_model, 'model.pkl')`

**Comment by annaveronika** [comment]
this is probably because the model format has changed. Please try using the same version of catboost for training and applyling the model.

Actually we are switching to flat buffer models this week, after that there will be no breaking changes to the model.

**Comment by annaveronika** [comment]
Please follow this issue:
https://github.com/catboost/catboost/issues/124
