### ISSUE TITLE
[catboost4j-spark] Error when using the autoClassWeights parameter

### ISSUE THREAD

**Issue by candalfigomoro** [catboost/catboost#1650]
Problem:
When using the autoClassWeights parameter (i.e. `autoClassWeights=catboost_spark.EAutoClassWeightsType.Balanced`), I get the following error

```
py4j.protocol.Py4JJavaError: An error occurred while calling o308.fit.
: java.lang.RuntimeException: Error while executing master
	at ai.catboost.spark.impl.Helpers$.checkOneFutureAndWaitForOther(Helpers.scala:30)
	at ai.catboost.spark.CatBoostPredictorTrait.fit(CatBoostPredictor.scala:208)
	at ai.catboost.spark.CatBoostPredictorTrait.fit$(CatBoostPredictor.scala:109)
	at ai.catboost.spark.CatBoostClassifier.fit(CatBoostClassifier.scala:362)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
Caused by: java.util.concurrent.ExecutionException: ai.catboost.CatBoostError: CatBoost master won't be restarted - no relaunched workers after timeout 00sec expired
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at ai.catboost.spark.impl.Helpers$.checkOneFutureAndWaitForOther(Helpers.scala:26)
	... 22 more
Caused by: ai.catboost.CatBoostError: CatBoost master won't be restarted - no relaunched workers after timeout 00sec expired
	at ai.catboost.spark.TrainingDriver.run(TrainingDriver.scala:208)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more

Traceback (most recent call last):
  File "/tmp/conda-54093610-f0cf-408d-b163-a721802640b1/real/envs/conda-env/lib/python3.6/site-packages/myproject/datasets/predictions.py", line 29, in my_compute_function
    model = classifier.fit(trainPool, [validationPool])
  File "/tmp/conda-54093610-f0cf-408d-b163-a721802640b1/real/envs/conda-env/lib/python3.6/site-packages/catboost_spark/core.py", line 4978, in fit
    java_model = self._java_obj.fit(_py2java(sc, trainDataset), evalDatasetsAsJavaObject)
  File "/tmp/conda-54093610-f0cf-408d-b163-a721802640b1/real/envs/conda-env/lib/python3.6/site-packages/py4j/java_gateway.py", line 1286, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/tmp/conda-54093610-f0cf-408d-b163-a721802640b1/real/envs/conda-env/lib/python3.6/site-packages/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/tmp/conda-54093610-f0cf-408d-b163-a721802640b1/real/envs/conda-env/lib/python3.6/site-packages/py4j/protocol.py", line 328, in get_return_value
    format(target_id, ".", name), value)
py4j.protocol.Py4JJavaError: An error occurred while calling o308.fit.
: java.lang.RuntimeException: Error while executing master
	at ai.catboost.spark.impl.Helpers$.checkOneFutureAndWaitForOther(Helpers.scala:30)
	at ai.catboost.spark.CatBoostPredictorTrait.fit(CatBoostPredictor.scala:208)
	at ai.catboost.spark.CatBoostPredictorTrait.fit$(CatBoostPredictor.scala:109)
	at ai.catboost.spark.CatBoostClassifier.fit(CatBoostClassifier.scala:362)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
Caused by: java.util.concurrent.ExecutionException: ai.catboost.CatBoostError: CatBoost master won't be restarted - no relaunched workers after timeout 00sec expired
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at ai.catboost.spark.impl.Helpers$.checkOneFutureAndWaitForOther(Helpers.scala:26)
	... 22 more
Caused by: ai.catboost.CatBoostError: CatBoost master won't be restarted - no relaunched workers after timeout 00sec expired
	at ai.catboost.spark.TrainingDriver.run(TrainingDriver.scala:208)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more
```

I have to use something like this https://danvatterott.com/blog/2019/11/18/balancing-model-weights-in-pyspark/ and calculate the weights in advance.

catboost version: catboost-spark_2.4_2.12-0.25

@andrey-khropov

**Comment by andrey-khropov** [comment]
Released in 0.26.
