### ISSUE TITLE
Predicting after ranking fails / is poorly documented

### ISSUE THREAD

**Issue by ben-watt-es** [catboost/catboost#1661]
Problem: Predicting after ranking fails / is poorly documented
catboost version: 0.24.4 (Python 3.8.5)
Operating System: Ubuntu 20.04
CPU: Intel i9 i9-9900K

I have set up a pool `train` and a pool `test` like so:
```
train = Pool(X_train.values, y_train.values, group_id=g_train)
```
Where `X_train` contains my features, `y_train` contains my scores, and `g_train` contains all the groups. Everything is sorted to match the group order.

I create the model and fit it like so:
```
model = CatBoost({"loss_function":"YetiRank"})
model.fit(train, eval_set=(test), use_best_model=True, early_stopping_rounds=100)
```
Then when I try to predict:
```
model.predict(test, prediction_type="Class")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sakuya/.local/lib/python3.8/site-packages/catboost/core.py", line 2033, in predict
    return self._predict(data, prediction_type, ntree_start, ntree_end, thread_count, verbose, 'predict')
  File "/home/sakuya/.local/lib/python3.8/site-packages/catboost/core.py", line 1981, in _predict
    predictions = self._base_predict(data, prediction_type, ntree_start, ntree_end, thread_count, verbose)
  File "/home/sakuya/.local/lib/python3.8/site-packages/catboost/core.py", line 1310, in _base_predict
    return self._object._base_predict(pool, prediction_type, ntree_start, ntree_end, thread_count, verbose)
  File "_catboost.pyx", line 4308, in _catboost._CatBoost._base_predict
  File "_catboost.pyx", line 4323, in _catboost._CatBoost._base_predict
  File "_catboost.pyx", line 1456, in _catboost.transform_predictions
  File "_catboost.pyx", line 5086, in _catboost._convert_to_visible_labels
IndexError: index 0 is out of bounds for axis 0 with size 0
```
My groups are strings, and there are 5 groups in total. Which makes predicting probability even more confusing, because I only get 2 outputs per row instead of the 5 I was expecting:
```
model.predict(test, prediction_type="Probability")
array([[0.53883141, 0.46116859],
       [0.52118767, 0.47881233],
       [0.53749065, 0.46250935],
       ...,
       [0.54306105, 0.45693895],
       [0.52692491, 0.47307509],
       [0.52297527, 0.47702473]])
```
I expected to see predicted classes per row, and predicted probabilities for each class per row. But I don't get either of those.

Where is this documented? The msrank guide only covers training a model for ranking, and nowhere does it even mention how to use the model afterwards.

**Comment by andrey-khropov** [comment]
You're right. 

1) Documentation and tutorials do not make it clear how to predict for ranking problems.
In fact a model trained for ranking will just predict one real value for a sample (corresponding to prediction type `RawFormulaVal`) and you should rank samples according to the predicted value (i.e. `predict` function does not return rank, only value that you can use to rank samples).

Something like that (for a single group):

```py
from operator import itemgetter
...
predictions = model.predict(X_group)
...
# print group samples with predictions, ranked by predictions
print (sorted(zip(predictions, X_group), key=itemgetter(0)))

```

Prediction does not use group or label data, only features, so it is enough to have only features data as an argument to `predict` but full `Pool` data is also accepted (but only features data from it is used for prediction).

You can predict for all groups in the dataset in one call to `predict` but additional postprocessing (in your - user - code) to sort all samples in each group according to the predicted value to get ranked samples is required.

2) prediction types `Class` and `Probability` make sense only for Classification problems. In case of non-Classification problems error message should clearly state that. We'll fix this inconsistency.
