### ISSUE TITLE
Ubuntu 14.04 R installation failed during make

### ISSUE THREAD

**Issue by wescleveland** [catboost/catboost#167]
Hi all,

I am trying to install the R package from master on github, ubuntu 14.04.5 LTS, system python is 2.7.6.  Have tried installing as root and a user.

Install log:

```> devtools::install_github('catboost/catboost', subdir = 'catboost/R-package')
Downloading GitHub repo catboost/catboost@master
from URL https://api.github.com/repos/catboost/catboost/zipball/master
Installing catboost
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL  \
  '/tmp/RtmpxwYECr/devtools8ae1308381de/catboost-catboost-f28154d/catboost/R-package'  \
  --library='/usr/local/lib/R/site-library' --install-tests

* installing *source* package ‘catboost’ ...
** libs
** arch -
chmod +rx /tmp/RtmpxwYECr/devtools8ae1308381de/catboost-catboost-f28154d/catboost/R-package/src//../../../ya
/tmp/RtmpxwYECr/devtools8ae1308381de/catboost-catboost-f28154d/catboost/R-package/src//../../../ya make -r
Downloading https://storage.mds.yandex.net/get-devtools-opensource/250854/dcfe6db46a15b7bbadeaf6e48700cbfe [..] OK
Downloading https://storage.mds.yandex.net/get-devtools-opensource/233854/387642396 [..........................] OK
make: *** [all] Aborted (core dumped)
ERROR: compilation failed for package ‘catboost’
* removing ‘/usr/local/lib/R/site-library/catboost’
Installation failed: Command failed (1)```

> version
               _
platform       x86_64-pc-linux-gnu
arch           x86_64
os             linux-gnu
system         x86_64, linux-gnu
status
major          3
minor          4.2
year           2017
month          09
day            28
svn rev        73368
language       R
version.string R version 3.4.2 (2017-09-28)
nickname       Short Summer
```

For what it's worth, I have the python catboost package installed with python 3.6.1 in a virtual environment and it works without any issues.

Anything I should try to get the R package to install?

Thanks!

**Comment by exprmntr** [comment]
Hi @wescleveland 

`Aborted (core dumped)` message means that coredump file was generated, can you show it?

**Comment by wescleveland** [comment]
Does this help?  I can send the actual core file if that would be easier.

```
root@ns3043613:~# gdb /root/.ya/tools/d00ec1d37c_d/ya-bin core.ya-bin.2359.1510681078
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.3) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /root/.ya/tools/d00ec1d37c_d/ya-bin...done.
[New LWP 2359]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/root/.ya/tools/d00ec1d37c_d/ya-bin make -r'.
Program terminated with signal SIGABRT, Aborted.
#0  0x000035b5dce6dc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

**Comment by wescleveland** [comment]
Here is the response for "bt":

```(gdb) bt
#0  0x000035b5dce6dc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x000035b5dce71028 in __GI_abort () at abort.c:89
#2  0x00000000004205ad in NMalloc::AbortFromCorruptedAllocator () at /place/db-0/key_0/user-0/svnc2/1/root/4ac544466abf4ec69ea4c9b47272fff3/rev_3224207_0x2873/library/malloc/api/malloc.cpp:32
#3  0x00000000002c1c92 in AllocWithMMapLinuxImpl (mode=<optimised out>, sz=<optimised out>) at /place/db-0/key_0/user-0/svnc2/1/root/4ac544466abf4ec69ea4c9b47272fff3/rev_3224207_0xA81A/library/lfalloc/lf_allocX64.cpp:327
#4  AllocWithMMap (sz=<optimised out>, mode=<optimised out>) at /place/db-0/key_0/user-0/svnc2/1/root/4ac544466abf4ec69ea4c9b47272fff3/rev_3224207_0xA81A/library/lfalloc/lf_allocX64.cpp:369
#5  0x00000000002c1db2 in LargeBlockAlloc (_nSize=<optimised out>, counter=CT_USER_ALLOC) at /place/db-0/key_0/user-0/svnc2/1/root/4ac544466abf4ec69ea4c9b47272fff3/rev_3224207_0xA81A/library/lfalloc/lf_allocX64.cpp:444
#6  0x00000000002c208c in SystemAlloc (_nSize=51624) at /place/db-0/key_0/user-0/svnc2/1/root/4ac544466abf4ec69ea4c9b47272fff3/rev_3224207_0xA81A/library/lfalloc/lf_allocX64.cpp:501
#7  AllocThreadInfo () at /place/db-0/key_0/user-0/svnc2/1/root/4ac544466abf4ec69ea4c9b47272fff3/rev_3224207_0xA81A/library/lfalloc/lf_allocX64.cpp:1203
#8  0x00000000002bba9e in LFAlloc (_nSize=<optimised out>) at /place/db-0/key_0/user-0/svnc2/1/root/4ac544466abf4ec69ea4c9b47272fff3/rev_3224207_0xA81A/library/lfalloc/lf_allocX64.cpp:1449
#9  operator new (size=<optimised out>) at /place/db-0/key_0/user-0/svnc2/1/root/4ac544466abf4ec69ea4c9b47272fff3/rev_3224207_0xA81A/library/lfalloc/lf_allocX64.cpp:1845
#10 0x0000000000269929 in __libcpp_allocate (__size=2359) at /place/db-0/key_0/user-0/svnc2/1/root/4ac544466abf4ec69ea4c9b47272fff3/rev_3224207_0x6C75/contrib/libs/cxxsupp/libcxx-next/include/new:226
#11 allocate (this=<optimised out>, __n=<optimised out>) at /place/db-0/key_0/user-0/svnc2/1/root/4ac544466abf4ec69ea4c9b47272fff3/rev_3224207_0x6C75/contrib/libs/cxxsupp/libcxx-next/include/memory:1752
#12 allocate (__a=..., __n=<optimised out>) at /place/db-0/key_0/user-0/svnc2/1/root/4ac544466abf4ec69ea4c9b47272fff3/rev_3224207_0x6C75/contrib/libs/cxxsupp/libcxx-next/include/memory:1506
#13 __split_buffer (__cap=1, __start=18446744073709551615, this=<optimised out>, __a=...) at /place/db-0/key_0/user-0/svnc2/1/root/4ac544466abf4ec69ea4c9b47272fff3/rev_3224207_0x6C75/contrib/libs/cxxsupp/libcxx-next/include/__split_buffer:319
#14 __add_back_capacity (this=<optimised out>) at /place/db-0/key_0/user-0/svnc2/1/root/4ac544466abf4ec69ea4c9b47272fff3/rev_3224207_0x6C75/contrib/libs/cxxsupp/libcxx-next/include/deque:2440
#15 push_back (this=<optimised out>, __v=<optimised out>) at /place/db-0/key_0/user-0/svnc2/1/root/4ac544466abf4ec69ea4c9b47272fff3/rev_3224207_0x6C75/contrib/libs/cxxsupp/libcxx-next/include/deque:1827
#16 Register (this=<optimised out>, func=<optimised out>, ctx=<optimised out>, priority=<optimised out>) at /place/db-0/key_0/user-0/svnc2/1/root/4ac544466abf4ec69ea4c9b47272fff3/rev_3224207_0x6C75/util/system/atexit.cpp:63
#17 AtExit (func=<optimised out>, ctx=<optimised out>, priority=<optimised out>) at /place/db-0/key_0/user-0/svnc2/1/root/4ac544466abf4ec69ea4c9b47272fff3/rev_3224207_0x6C75/util/system/atexit.cpp:113
#18 0x000000000024ed33 in NPrivate::SingletonBase<(anonymous namespace)::TStore, 0ul> (ptr=<optimised out>) at /place/db-0/key_0/user-0/svnc2/1/temp/4ac544466abf4ec69ea4c9b47272fff3/tmpDmXKFN/.mount/util/generic/singleton.h:39
#19 0x000000000020044f in _GLOBAL__sub_I_nxq3gm2xqggxabhypl3hqnl3wi.cpp () at /place/db-0/key_0/user-0/svnc2/1/root/4ac544466abf4ec69ea4c9b47272fff3/rev_3224207_0x637D/library/resource/registry.h:32
#20 0x00000000009c52dd in __libc_csu_init ()
#21 0x000035b5dce58ed5 in __libc_start_main (main=0x24e1b0 <main>, argc=3, argv=0x7ec7ee5794e8, init=0x9c5280 <__libc_csu_init>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7ec7ee5794d8) at libc-start.c:246
#22 0x0000000000200329 in _start ()```

**Comment by exprmntr** [comment]
Thank you, I will try to fix it soon

**Comment by exprmntr** [comment]
Should be fixed in new version. Please reopen, if problem still exists.
