### ISSUE TITLE
Get Object Importance Fails with MultiRmse

### ISSUE THREAD

**Issue by ThomasWolf0701** [catboost/catboost#1693]
Problem: Get Object Importance Fails with MultiRmse

poolTrain =catboost.Pool(featureMatrix.iloc[:,0:2214],values.iloc[:,1:2])
poolTest = catboost.Pool(featureMatrix.iloc[:,0:2214],values.iloc[:,1:2])

bestModel["m"].get_object_importance(poolTest,
                      poolTrain)
Traceback (most recent call last):

  File "<ipython-input-177-82bde7dd29c8>", line 1, in <module>
    bestModel["m"].get_object_importance(poolTest,

  File "C:\Users\Thomas Wolf\anaconda3\envs\ChemPipeline\lib\site-packages\catboost\core.py", line 2787, in get_object_importance
    result = self._calc_ostr(train_pool, pool, top_size, type, update_method, importance_values_sign, thread_count, verbose)

  File "C:\Users\Thomas Wolf\anaconda3\envs\ChemPipeline\lib\site-packages\catboost\core.py", line 1440, in _calc_ostr
    return self._object._calc_ostr(train_pool, test_pool, top_size, ostr_type, update_method, importance_values_sign, thread_count, verbose)

  File "_catboost.pyx", line 4478, in _catboost._CatBoost._calc_ostr

  File "_catboost.pyx", line 4480, in _catboost._CatBoost._calc_ostr

CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/private/libs/documents_importance/ders_helpers.cpp:95: Error function MultiRMSE is not supported yet in ostr mode

Or if do nor slice the values object:

import catboost
#get the most influential sample for each sample
poolTrain =catboost.Pool(featureMatrix.iloc[:,0:2214],values)
poolTest = catboost.Pool(featureMatrix.iloc[:,0:2214],values)

bestModel["m"].get_object_importance(poolTest,
                      poolTrain)

import catboost
#get the most influential sample for each sample
poolTrain =catboost.Pool(featureMatrix.iloc[:,0:2214],values)
poolTest = catboost.Pool(featureMatrix.iloc[:,0:2214],values)

bestModel["m"].get_object_importance(poolTest,
                      poolTrain)
Traceback (most recent call last):

  File "<ipython-input-178-231b30e9e7bb>", line 6, in <module>
    bestModel["m"].get_object_importance(poolTest,

  File "C:\Users\Thomas Wolf\anaconda3\envs\ChemPipeline\lib\site-packages\catboost\core.py", line 2787, in get_object_importance
    result = self._calc_ostr(train_pool, pool, top_size, type, update_method, importance_values_sign, thread_count, verbose)

  File "C:\Users\Thomas Wolf\anaconda3\envs\ChemPipeline\lib\site-packages\catboost\core.py", line 1440, in _calc_ostr
    return self._object._calc_ostr(train_pool, test_pool, top_size, ostr_type, update_method, importance_values_sign, thread_count, verbose)

  File "_catboost.pyx", line 4478, in _catboost._CatBoost._calc_ostr

  File "_catboost.pyx", line 4480, in _catboost._CatBoost._calc_ostr

CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/libs/data/target.h:308: Attempt to use multidimintional target as one-dimensional

catboost version: 0.25.1
Operating System: Windows
CPU: Intel Core I7
# GPU:

**Comment by ek-ak** [comment]
Hello! Thanks for your question! Object importance method is incompatible with multi-dimensional target like in MultiRmse case.

**Comment by ThomasWolf0701** [comment]
Thanks for the information. Does this mean that it´s not possible or that it´s just not implemented ? And are there any plans to implement this ?
