### ISSUE TITLE
Compiling on machine without internet connection

### ISSUE THREAD

**Issue by marcelned** [catboost/catboost#1706]
I am compiling on a PowerPC machine behind a corporate proxy with no internet.

I have managed to manually move the needed files needed for ppc64le (https://storage.mds.yandex.net/get-devtools-opensource/250854/5b2d4493900f309ca047981edd693a8e) to /root/.ya/tools/.

However it seems there are still missing artefacts that the process needs to compile.
Which files do I still need to manually source and where should I put them?

```console
[root@wslcomp4 catboost]# ../../../ya make -r -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -DPYTHON_CONFIG=python3-config -DHAVE_CUDA=no
Info: Attention! CC and CXX env.vars are ignored: use --c(xx)-compiler/--target-platform-c(xx)-compiler options to specify user-defined compiler.
Traceback (most recent call last):
  File "devtools/ya/app.py", line 499, in configure_exit_interceptor
    yield
  File "devtools/ya/app.py", line 66, in helper
    return action(args)
  File "devtools/ya/entry/entry.py", line 55, in do_main
    res = handler.handle(handler, args, prefix=['ya'])
  File "devtools/ya/core/handler.py", line 161, in handle
    return handler.handle(self, args[1:], prefix + [name])
  File "devtools/ya/core/dispatch.py", line 37, in handle
    return self.command().handle(root_handler, args, prefix)
  File "devtools/ya/core/handler.py", line 343, in handle
    return self._action(params)
  File "devtools/ya/app.py", line 94, in helper
    return action(ctx.params)
  File "devtools/ya/build/build_handler.py", line 87, in do_ya_make
    builder = ya_make.YaMake(params, app_ctx)
  File "devtools/ya/build/ya_make.py", line 896, in __init__
    self.ctx = Context(self.opts, app_ctx=app_ctx, graph=graph, tests=tests, stripped_tests=stripped_tests, configure_errors=configure_errors, make_files=make_files, lite_graph=lite_graph)
  File "devtools/ya/build/ya_make.py", line 573, in __init__
    self.graph, self.tests, self.stripped_tests, self.configure_errors, self.make_files = _build_graph_and_tests(self.opts, app_ctx)
  File "devtools/ya/build/ya_make.py", line 255, in _build_graph_and_tests
    graph, tests, stripped_tests, gh, make_files = lg.build_graph_and_tests(opts, check=True, ev_listener=ev_listener, display=display)
  File "devtools/ya/build/graph.py", line 1633, in build_graph_and_tests
    return _build_graph_and_tests(opts, check, ev_listener, exit_stack, display)
  File "devtools/ya/build/graph.py", line 1937, in _build_graph_and_tests
    real_ymake_bin = tools.tool('ymake')
  File "devtools/ya/yalibrary/tools/__init__.py", line 220, in tool
    return toolchain.find(name, with_params, for_platform, cache=cache)
  File "devtools/ya/yalibrary/tools/__init__.py", line 158, in find
    executable = cur_bottle[executable_name]  # if executable_name is None it's Ok
  File "devtools/ya/yalibrary/tools/__init__.py", line 64, in __getitem__
    path = self.resolve()
  File "devtools/ya/yalibrary/tools/__init__.py", line 46, in resolve
    return self.__fetcher.fetch_if_need(self.__formula["match"], tared, binname, cache=cache).where
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 385, in fetch_if_need
    self.__c[key] = self._fetch_if_need(*args, **kwargs)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 452, in _fetch_if_need
    if self._fetch(name, tared, lambda x: name.lower() in x.lower(), binname):
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 368, in _fetch
    _install(res_path, do_install)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 104, in _install
    fs_handler(install_guard)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 95, in fs_handler
    func(install_guard)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 346, in do_install
    resource_info = self._download(name, res, download_to)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 524, in _download
    http_client.download_file(url=config.mapping()["resources"][resource["id"]], path=download_to)
  File "devtools/ya/exts/retry.py", line 20, in wrapper
    return retry(proxy_func, **retry_kwargs)
  File "devtools/ya/exts/retry.py", line 12, in retry
    return lpr.retry_call(func, conf=_conf(func, *args, **kwargs))
  File "library/python/retry/__init__.py", line 183, in retry_call
    return _retry(conf, functools.partial(f, *f_args, **f_kwargs))
  File "library/python/retry/__init__.py", line 221, in _retry
    return f()
  File "devtools/ya/exts/retry.py", line 19, in <lambda>
    proxy_func = lambda: func(*args, **kwargs)
  File "devtools/ya/exts/http_client.py", line 67, in download_file
    raise e
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>
```

Thank you for the help

**Comment by ek-ak** [comment]
Hello!
Probably you could find the solution here https://github.com/catboost/catboost/issues/973#issuecomment-535225020

**Comment by hombit** [comment]
I cannot do it on PowerPC even with the internet connection, looks like building requires Yandex homemade build tool which is not available for PowerPC. I think the same problem exists for other platforms, it would be good if a list of supported platforms was in the readme.

**Comment by kizill** [comment]
We've switched to CMake + Conan so I guess now this could be finally done. Closing as fixed and sorry for such a long wait.
