### ISSUE TITLE
Building wheel from source fails with `could not resolve include file`

### ISSUE THREAD

**Issue by harupy** [catboost/catboost#1743]
In our repository (https://github.com/mlflow/mlflow), we have a test suite that runs our unit tests against the dev version of catboost built from the source using the following command:

```bash
pip install wheel
git clone https://github.com/catboost/catboost.git
cd catboost/catboost/python-package
git checkout $BRANCH_OR_COMMIT
python setup.py bdist_wheel

# test commands
```

Last week, this test suite started failing with the following error:

```diff
Collecting wheel
  Downloading wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel
Successfully installed wheel-0.36.2
Cloning into 'catboost'...
Updating files:  18% (5504/29293)
...
Updating files:  99% (29001/29293)
Updating files: 100% (29293/29293)
Updating files: 100% (29293/29293), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
running bdist_wheel
running build
running build_py
06:20:45 I Generating grammar tables from %s
06:20:45 I Writing grammar tables to %s
06:20:45 I Generating grammar tables from %s
06:20:45 I Writing grammar tables to %s
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/catboost
copying catboost/plot_helpers.py -> build/lib.linux-x86_64-3.6/catboost
copying catboost/__init__.py -> build/lib.linux-x86_64-3.6/catboost
copying catboost/text_processing.py -> build/lib.linux-x86_64-3.6/catboost
copying catboost/utils.py -> build/lib.linux-x86_64-3.6/catboost
copying catboost/dev_utils.py -> build/lib.linux-x86_64-3.6/catboost
copying catboost/metrics.py -> build/lib.linux-x86_64-3.6/catboost
copying catboost/monoforest.py -> build/lib.linux-x86_64-3.6/catboost
copying catboost/version.py -> build/lib.linux-x86_64-3.6/catboost
copying catboost/core.py -> build/lib.linux-x86_64-3.6/catboost
copying catboost/datasets.py -> build/lib.linux-x86_64-3.6/catboost
creating build/lib.linux-x86_64-3.6/catboost/eval
copying catboost/eval/evaluation_result.py -> build/lib.linux-x86_64-3.6/catboost/eval
copying catboost/eval/_fold_storage.py -> build/lib.linux-x86_64-3.6/catboost/eval
copying catboost/eval/_splitter.py -> build/lib.linux-x86_64-3.6/catboost/eval
copying catboost/eval/__init__.py -> build/lib.linux-x86_64-3.6/catboost/eval
copying catboost/eval/_readers.py -> build/lib.linux-x86_64-3.6/catboost/eval
copying catboost/eval/utils.py -> build/lib.linux-x86_64-3.6/catboost/eval
copying catboost/eval/log_config.py -> build/lib.linux-x86_64-3.6/catboost/eval
copying catboost/eval/catboost_evaluation.py -> build/lib.linux-x86_64-3.6/catboost/eval
copying catboost/eval/execution_case.py -> build/lib.linux-x86_64-3.6/catboost/eval
copying catboost/eval/_fold_models_handler.py -> build/lib.linux-x86_64-3.6/catboost/eval
copying catboost/eval/_fold_model.py -> build/lib.linux-x86_64-3.6/catboost/eval
copying catboost/eval/factor_utils.py -> build/lib.linux-x86_64-3.6/catboost/eval
creating build/lib.linux-x86_64-3.6/catboost/widget
copying catboost/widget/__init__.py -> build/lib.linux-x86_64-3.6/catboost/widget
copying catboost/widget/ipythonwidget.py -> build/lib.linux-x86_64-3.6/catboost/widget
creating build/lib.linux-x86_64-3.6/catboost/widget/ipython
copying catboost/widget/ipython/catboost-ipython-debug.ipynb -> build/lib.linux-x86_64-3.6/catboost/widget/ipython
creating build/lib.linux-x86_64-3.6/catboost/widget/ipython/new_cv_1
copying catboost/widget/ipython/new_cv_1/catboost_training.json -> build/lib.linux-x86_64-3.6/catboost/widget/ipython/new_cv_1
creating build/lib.linux-x86_64-3.6/catboost/widget/ipython/new_eval
copying catboost/widget/ipython/new_eval/catboost_training.json -> build/lib.linux-x86_64-3.6/catboost/widget/ipython/new_eval
creating build/lib.linux-x86_64-3.6/catboost/widget/ipython/new_train
copying catboost/widget/ipython/new_train/catboost_training.json -> build/lib.linux-x86_64-3.6/catboost/widget/ipython/new_train
creating build/lib.linux-x86_64-3.6/catboost/widget/ipython/new_cv_3
copying catboost/widget/ipython/new_cv_3/catboost_training.json -> build/lib.linux-x86_64-3.6/catboost/widget/ipython/new_cv_3
creating build/lib.linux-x86_64-3.6/catboost/widget/ipython/new_cv_2
copying catboost/widget/ipython/new_cv_2/catboost_training.json -> build/lib.linux-x86_64-3.6/catboost/widget/ipython/new_cv_2
creating build/lib.linux-x86_64-3.6/catboost/widget/ipython/new_train_with_nan
copying catboost/widget/ipython/new_train_with_nan/catboost_training.json -> build/lib.linux-x86_64-3.6/catboost/widget/ipython/new_train_with_nan
creating build/lib.linux-x86_64-3.6/catboost/widget/ipython/new_train_best
copying catboost/widget/ipython/new_train_best/catboost_training.json -> build/lib.linux-x86_64-3.6/catboost/widget/ipython/new_train_best
creating build/lib.linux-x86_64-3.6/catboost/widget/ipython/accuracy
copying catboost/widget/ipython/accuracy/catboost_training.json -> build/lib.linux-x86_64-3.6/catboost/widget/ipython/accuracy
creating build/lib.linux-x86_64-3.6/catboost/widget/ipython/subdirs
creating build/lib.linux-x86_64-3.6/catboost/widget/ipython/subdirs/new_train
copying catboost/widget/ipython/subdirs/new_train/catboost_training.json -> build/lib.linux-x86_64-3.6/catboost/widget/ipython/subdirs/new_train
creating build/lib.linux-x86_64-3.6/catboost/widget/ipython/subdirs/new_train_multi
copying catboost/widget/ipython/subdirs/new_train_multi/catboost_training.json -> build/lib.linux-x86_64-3.6/catboost/widget/ipython/subdirs/new_train_multi
creating build/lib.linux-x86_64-3.6/catboost/widget/ipython/new_cv_subdirs
creating build/lib.linux-x86_64-3.6/catboost/widget/ipython/new_cv_subdirs/second
copying catboost/widget/ipython/new_cv_subdirs/second/catboost_training.json -> build/lib.linux-x86_64-3.6/catboost/widget/ipython/new_cv_subdirs/second
creating build/lib.linux-x86_64-3.6/catboost/widget/ipython/new_cv_subdirs/first
copying catboost/widget/ipython/new_cv_subdirs/first/catboost_training.json -> build/lib.linux-x86_64-3.6/catboost/widget/ipython/new_cv_subdirs/first
06:20:45 I Buildling _catboost.so with ymake
running build_ext
06:20:45 I EXECUTE: /opt/hostedtoolcache/Python/3.6.13/x64/bin/python /home/runner/work/install-catboost-from-github/install-catboost-from-github/catboost/ya make /home/runner/work/install-catboost-from-github/install-catboost-from-github/catboost/catboost/python-package/../../catboost/python-package/catboost --no-src-links --output /home/runner/work/install-catboost-from-github/install-catboost-from-github/catboost/catboost/python-package/build/temp.linux-x86_64-3.6 -DPYTHON_CONFIG=python3-config -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -r -DNO_DEBUGINFO -DHAVE_CUDA=no
Output root is subdirectory of Arcadia root, this may cause non-idempotent build
+ Error[-WBadIncl]: in $B/library/cpp/netliba/v6/libcpp-netliba-v6.a: could not resolve include file: contrib/libs/ibdrv/include/infiniband/verbs.h included from here: $S/library/cpp/netliba/v6/ib_low.h
+ Error[-WBadIncl]: in $B/library/cpp/netliba/v6/libcpp-netliba-v6.a: could not resolve include file: contrib/libs/ibdrv/include/rdma/rdma_cma.h included from here: $S/library/cpp/netliba/v6/ib_low.h
+ Error[-WBadIncl]: in $B/library/cpp/netliba/v12/libcpp-netliba-v12.a: could not resolve include file: contrib/libs/ibdrv/include/infiniband/verbs.h included from here: $S/library/cpp/netliba/v12/ib_low.h
+ Error[-WBadIncl]: in $B/library/cpp/netliba/v12/libcpp-netliba-v12.a: could not resolve include file: contrib/libs/ibdrv/include/rdma/rdma_cma.h included from here: $S/library/cpp/netliba/v12/ib_low.h
Configure error (use -k to proceed)
Traceback (most recent call last):
  File "setup.py", line 311, in <module>
    setup_requires=['wheel'],
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/setuptools/__init__.py", line 143, in setup
    return distutils.core.setup(**attrs)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 151, in run
    _bdist_wheel.run(self)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 117, in run
    _build.run(self)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 186, in run
    self.build_with_ymake(topsrc_dir, build_dir, catboost_ext, put_dir, verbose, dry_run)
  File "setup.py", line 219, in build_with_ymake
    logging_execute(ymake_cmd + ['-DHAVE_CUDA=no'], verbose, dry_run)
  File "setup.py", line 62, in logging_execute
    subprocess.check_call(cmd, universal_newlines=True)
  File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.6.13/x64/bin/python', '/home/runner/work/install-catboost-from-github/install-catboost-from-github/catboost/ya', 'make', '/home/runner/work/install-catboost-from-github/install-catboost-from-github/catboost/catboost/python-package/../../catboost/python-package/catboost', '--no-src-links', '--output', '/home/runner/work/install-catboost-from-github/install-catboost-from-github/catboost/catboost/python-package/build/temp.linux-x86_64-3.6', '-DPYTHON_CONFIG=python3-config', '-DUSE_ARCADIA_PYTHON=no', '-DOS_SDK=local', '-r', '-DNO_DEBUGINFO', '-DHAVE_CUDA=no']' returned non-zero exit status 1.
```

**Comment by harupy** [comment]
Here's a PR to reproduce the issue:

https://github.com/harupy/install-catboost-from-github/pull/1

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Many thanks for reporting! A fix is on its way.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Fixed by https://github.com/catboost/catboost/commit/9b45e25c97fae1b211ec6b64d0e777a40f9b5afb

**Comment by harupy** [comment]
@Evgueni-Petrov-aka-espetrov Confirmed the issue has been fixed, thanks!
