### ISSUE TITLE
[catboost4j-spark] Random failure on foreachPartition at Workers.scala

### ISSUE THREAD

**Issue by candalfigomoro** [catboost/catboost#1765]
Problem:
The same code, with the same data and the same Spark config, fails 80% of the time, but succeeds 20% of the time.

```
    trainPool = catboost_spark.Pool(train)
    validationPool = catboost_spark.Pool(validation)
    testPool = catboost_spark.Pool(test)

    classifier = catboost_spark.CatBoostClassifier(
        sparkPartitionCount=8,
        threadCount=1,
        iterations=20,
    )

    model = classifier.fit(trainPool, [validationPool])

    predictions = model.transform(testPool.data)
```

At the `foreachPartition at Workers.scala` stage, tasks often (but not always!) start failing with errors like:
```
Job aborted due to stage failure: Task 7 in stage 72.0 failed 4 times, most recent failure: Lost task 7.3 in stage 72.0 (TID 153, executor 17): ExecutorLostFailure (executor 17 exited caused by one of the running tasks) Reason: Container from a bad node: container_e126_1625557188504_13505_01_000057. Exit status: 134. Diagnostics: logs/application_1625557188504_13505/container_e126_1625557188504_13505_01_000057/stderr
Last 4096 bytes of stderr :
re.config.DefaultConfiguration@5495333e OK
TRACE StatusLogger Reregistering MBeans after reconfigure. Selector=org.apache.logging.log4j.core.selector.ClassLoaderContextSelector@1a1d3c1a
TRACE StatusLogger Reregistering context (1/1): '5ef04b5' org.apache.logging.log4j.core.LoggerContext@28e8dde3
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=5ef04b5'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=5ef04b5,component=StatusLogger'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=5ef04b5,component=ContextSelector'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=5ef04b5,component=Loggers,name=*'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=5ef04b5,component=Appenders,name=*'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=5ef04b5,component=AsyncAppenders,name=*'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=5ef04b5,component=AsyncLoggerRingBuffer'
TRACE StatusLogger Unregistering but no MBeans found matching 'org.apache.logging.log4j2:type=5ef04b5,component=Loggers,name=*,subtype=RingBuffer'
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=5ef04b5
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=5ef04b5,component=StatusLogger
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=5ef04b5,component=ContextSelector
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=5ef04b5,component=Loggers,name=
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=5ef04b5,component=Loggers,name=org.apache.spark.api.conda
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=5ef04b5,component=Loggers,name=py4j
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=5ef04b5,component=Loggers,name=org.apache.hadoop.yarn.util.RackResolver
DEBUG StatusLogger Registering MBean org.apache.logging.log4j2:type=5ef04b5,component=Appenders,name=Console
TRACE StatusLogger Using default SystemClock for timestamps.
DEBUG StatusLogger org.apache.logging.log4j.core.util.SystemClock supports precise timestamps.
TRACE StatusLogger Using DummyNanoClock for nanosecond timestamps.
DEBUG StatusLogger Shutdown hook enabled. Registering a new one.
DEBUG StatusLogger LoggerContext[name=5ef04b5, org.apache.logging.log4j.core.LoggerContext@28e8dde3] started OK.
DEBUG StatusLogger AsyncLogger.ThreadNameStrategy=UNCACHED (user specified null, default is UNCACHED)
TRACE StatusLogger Using default SystemClock for timestamps.
DEBUG StatusLogger org.apache.logging.log4j.core.util.SystemClock supports precise timestamps.
uncaught exception:
    address -> 0x10720b810
    what() -> "(Bad file descriptor) util/network/socket.h:76: setsockopt() failed for reuse addr"
    type -> TSystemError
```

In general, I don't have any "bad node" issue with other code.

This error then propagates to errors like:
```
py4j.protocol.Py4JJavaError: An error occurred while calling o319.fit.
: java.lang.RuntimeException: Error while executing workers
	at ai.catboost.spark.impl.Helpers$.checkOneFutureAndWaitForOther(Helpers.scala:30)
	at ai.catboost.spark.CatBoostPredictorTrait.fit(CatBoostPredictor.scala:206)
	at ai.catboost.spark.CatBoostPredictorTrait.fit$(CatBoostPredictor.scala:109)
	at ai.catboost.spark.CatBoostClassifier.fit(CatBoostClassifier.scala:362)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
```

or

```
py4j.protocol.Py4JJavaError: An error occurred while calling o318.fit.
: java.lang.RuntimeException: Error while executing master
	at ai.catboost.spark.impl.Helpers$.checkOneFutureAndWaitForOther(Helpers.scala:30)
	at ai.catboost.spark.CatBoostPredictorTrait.fit(CatBoostPredictor.scala:208)
	at ai.catboost.spark.CatBoostPredictorTrait.fit$(CatBoostPredictor.scala:109)
	at ai.catboost.spark.CatBoostClassifier.fit(CatBoostClassifier.scala:362)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
```

But the root cause is always the tasks failure on foreachPartition at Workers.scala

catboost version: catboost-spark_2.4_2.12-0.25, catboost-spark_3.0_2.12-0.26

@andrey-khropov

**Comment by guidiandrea** [comment]
I am experiencing the same issue 

spark on Yarn, RHEL 7
catboost version: 2.6

when launching the training I get:

`SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
uncaught exception:
    address -> 0x14710b810
    what() -> "(Bad file descriptor) util/network/socket.h:76: setsockopt() failed for reuse addr"
    type -> TSystemError`

**Comment by candalfigomoro** [comment]
Still an issue with version 0.26.1

**Comment by candalfigomoro** [comment]
Still an issue with version 1.0.2

@andrey-khropov

**Comment by andrey-khropov** [comment]
It is not fixed yet because it is somewhat hard to reproduce. So I need the maximum possible details to reproduce it (the version of Spark, the cluster configuration, the Spark configuration, the dataset (preferably as small as possible or give a description of the dataset size)).

**Comment by candalfigomoro** [comment]
@andrey-khropov 

Spark version: 3.0.2
Spark dynamic allocation: disabled
Num executors: 8
Spark executor cores: 1
Spark executor memory: 13 GB
Spark executor memory overhead: 2 GB
Spark driver cores: 1
Spark driver memory:  6 GB
Spark driver memory overhead: 4 GB
Spark driver max result size: 4 GB

catboost sparkPartitionCount: 8
catboost threadCount: 1

Dataset: https://archive.ics.uci.edu/ml/datasets/MiniBooNE+particle+identification (70% training pool, 10% eval pool, 20% test pool for prediction)

**Comment by candalfigomoro** [comment]
Still an issue with version 1.0.4

**Comment by devmindset** [comment]
Yes it is still an issue with version 1.0.4. Any date when we can get a fix for this....

**Comment by weihuacern** [comment]
Still an issue in 1.0.6.
Logs on executor:
`
OpenJDK 64-Bit Server VM warning: UseCMSCompactAtFullCollection is deprecated and will likely be removed in a future release.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/data6/yarnenv/local/filecache/996418/spark-jars.zip/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/data/gaiaadmin/gaiaenv/tdwgaia/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:ERROR A "org.apache.log4j.ConsoleAppender" object is not assignable to a "tdbank.org.apache.log4j.Appender" variable.
log4j:ERROR The class "tdbank.org.apache.log4j.Appender" was loaded by 
log4j:ERROR [sun.misc.Launcher$AppClassLoader@18b4aac2] whereas object of type 
log4j:ERROR "org.apache.log4j.ConsoleAppender" was loaded by [sun.misc.Launcher$AppClassLoader@18b4aac2].
log4j:ERROR Could not instantiate appender named "stderr".
log4j:ERROR A "org.apache.log4j.RollingFileAppender" object is not assignable to a "tdbank.org.apache.log4j.Appender" variable.
log4j:ERROR The class "tdbank.org.apache.log4j.Appender" was loaded by 
log4j:ERROR [sun.misc.Launcher$AppClassLoader@18b4aac2] whereas object of type 
log4j:ERROR "org.apache.log4j.RollingFileAppender" was loaded by [sun.misc.Launcher$AppClassLoader@18b4aac2].
log4j:ERROR Could not instantiate appender named "spark".
log4j:WARN No appenders could be found for logger (tdbank.kona.com.tencent.tdbank.busapi.config.BusConfigManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
22/09/01 21:38:38 ERROR Executor: Exception in task 2.0 in stage 4462.0 (TID 82724)
ai.catboost.CatBoostError: An active CatBoost worker is already present in the current process
	at ai.catboost.spark.impl.CatBoostWorker.processPartition(Workers.scala:56)
	at ai.catboost.spark.impl.CatBoostWorkers$$anonfun$2$$anonfun$apply$mcVI$sp$2.apply(Workers.scala:324)
	at ai.catboost.spark.impl.CatBoostWorkers$$anonfun$2$$anonfun$apply$mcVI$sp$2.apply(Workers.scala:323)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:980)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$28.apply(RDD.scala:980)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2162)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2162)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:123)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1449)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
VERIFY failed (2022-09-01T21:38:40.135039+0800): emplacing non uniq value
  library/cpp/par/par_locked_hash.h:85
  EmplaceValue(): requirement Storages[binIndex].emplace(key, std::forward<Args>(args)...).second failed
??+0 (0x7FE2AFB82EB9)
??+0 (0x7FE2AFB81008)
??+0 (0x7FE2B07E681B)
??+0 (0x7FE2B07EFF73)
??+0 (0x7FE2AFDD9416)
??+0 (0x7FE2AFDD9707)
??+0 (0x7FE2AFB832F6)
??+0 (0x7FE2F5F04EA5)
clone+109 (0x7FE2F58129FD)
`

**Comment by bakuteyev** [comment]
It is still there for 1.2. Also I found that it happens more frequently with big number of workers in Databricks.

**Comment by chrisdupreez** [comment]
It is still there for 1.2.5 (ai.catboost:catboost-spark_3.4_2.12:1.2.5)
Wasting hours/days trying to figure out how to avoid.

**Comment by chrisdupreez** [comment]
> I don’t see this issue after I increased memory on workers. I am using it in Databricks.
Sounds amazing to me.

Can you share some details like:
spark.executor.memory allocation
count data rows and feature count

**Comment by iptkachev** [comment]
still an issue with 1.2.7

**Comment by shanalyb** [comment]
This crashes whenever socket() fails - deterministically on kernels with ipv6.disable=1, sporadically under fd pressure - there is a missing return in library/cpp/neh/asio/tcp_acceptor_impl.h:

```
if (s == INVALID_SOCKET) {
    ec.Assign(LastSystemError());
    return;  // <-- missing
}
```

Without it CheckedSetSockOpt gets fd=-1 and throws inside a noexcept method - that's the "setsockopt() failed for reuse addr" abort.

Easy repro on a no-IPv6 kernel: catboost run-worker --node-port 9999.
