### ISSUE TITLE
crossed compile catboost python run on armv8 failed

### ISSUE THREAD

**Issue by nmreadelf** [catboost/catboost#1787]
Problem: I was cross compile catboot for armv8 on x86_64 fedora, in armv8 machine, run `from catboost.datasets import titanic`  in python, err msg:
```bash
root@0a178b1ad665:/tmp# PYTHONPATH=/usr/local/lib/python3.7/site-packages python3
Python 3.7.11 (default, Jul 22 2021, 11:25:48)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from catboost.datasets import titanic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/catboost/__init__.py", line 1, in <module>
    from .core import FeaturesData, EFstrType, Pool, CatBoost, CatBoostClassifier, CatBoostRegressor, CatBoostError, cv, train, sum_models, _have_equal_features, to_regressor, to_classifier, MultiRegressionCustomMetric, MultiRegressionCustomObjective  # noqa
  File "/usr/local/lib/python3.7/site-packages/catboost/core.py", line 42, in <module>
    from . import _catboost
ImportError: /usr/local/lib/python3.7/site-packages/catboost/_catboost.so: undefined symbol: PyCObject_Type
>>>
```
catboost version: 0.24.3
Operating System: host os system is `centos7`, container system base on `Debian GNU/Linux 10 (buster)`
CPU: cat /proc/cpuinfo
```
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              24
On-line CPU(s) list: 0-23
Thread(s) per core:  1
Core(s) per socket:  12
Socket(s):           2
NUMA node(s):        2
Vendor ID:           0x48
Model:               0
Stepping:            0x1
CPU max MHz:         2000.0000
CPU min MHz:         2000.0000
BogoMIPS:            200.00
L1d cache:           64K
L1i cache:           64K
L2 cache:            512K
L3 cache:            32768K
NUMA node0 CPU(s):   0-11
NUMA node1 CPU(s):   12-23
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop
```
# GPU:

i was use cmd  `../../../ya make -r -DHAVE_CUDA=no --target-platform default-linux-aarch64`  compile `_catboost.so`
work directory is `catboost/catboost/python-package/catboost`

x86 system gcc and g++ version is  `11.1.1 20210531 (Red Hat 11.1.1-3)`

**Comment by kizill** [comment]
You should select proper version of python like this: 
```
../../../ya make -r -DHAVE_CUDA=no --target-platform default-linux-aarch64 -DUSE_SYSTEM_PYTHON=3.7 -DOS_SDK=local```

**Comment by nmreadelf** [comment]
oops, i got new error
```
command /root/.ya/tools/v3/958916803/bin/clang++ --target=aarch64-linux-gnu -fsigned-char -march=armv8a -B$OS_SDK_ROOT_RESOURCE_GLOBAL/usr/bin -c -o /root/.ya/build/build_root/7bw8/000005/catboost/private/libs/init/init_reg.cpp.pic.o /src/catboost/private/libs/init/init_reg.cpp -I/root/.ya/build/build_root/7bw8/000005 -I/src -I/src/contrib/libs/linux-headers -I/src/contrib/libs/linux-headers/_nf -I/src/contrib/libs/cxxsupp/libcxx/include -I/src/contrib/libs/cxxsupp/libcxxrt -I/src/contrib/libs/zlib/include -I/src/contrib/libs/double-conversion/include -fdebug-prefix-map=/root/.ya/build/build_root/7bw8/000005=/-B -Xclang -fdebug-compilation-dir -Xclang /tmp -pipe -O3 -g -ggnu-pubnames -fexceptions -fuse-init-array -faligned-allocation -W -Wall -Wno-parentheses -Werror -DFAKEID=5020880 -DARCADIA_ROOT=/src -DARCADIA_BUILD_ROOT=/root/.ya/build/build_root/7bw8/000005 -D_THREAD_SAFE -D_PTHREADS -D_REENTRANT -D_LIBCPP_ENABLE_CXX17_REMOVED_FEATURES -D_LARGEFILE_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DNDEBUG -D__LONG_LONG_SUPPORTED -DCATBOOST_OPENSOURCE=yes -D_libunwind_ -nostdinc++ -fPIC -fPIC -std=c++17 -Woverloaded-virtual -Wno-invalid-offsetof -Wno-attributes -Wno-dynamic-exception-spec -Wno-register -Wimport-preprocessor-directive-pedantic -Wno-c++17-extensions -Wno-exceptions -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-return-std-move -DCATBOOST_OPENSOURCE=yes -nostdinc++ failed with exit code 1 in /root/.ya/build/build_root/7bw8/000005
In file included from /src/catboost/private/libs/init/init_reg.cpp:1:
In file included from /src/catboost/private/libs/init/init_reg.h:3:
In file included from /src/util/generic/singleton.h:4:
In file included from /src/util/system/atomic.h:51:
In file included from /src/util/system/atomic_ops.h:3:
In file included from /src/util/generic/typetraits.h:7:
In file included from /src/contrib/libs/cxxsupp/libcxx/include/iterator:421:
In file included from /src/contrib/libs/cxxsupp/libcxx/include/__functional_base:15:
/src/contrib/libs/cxxsupp/libcxx/include/typeinfo:215:14: error: cast from pointer to smaller type 'std::__type_info_implementations::__non_unique_arm_rtti_bit_impl::__type_name_t' (aka 'unsigned int') loses information
      return reinterpret_cast<__type_name_t>(__v);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/src/contrib/libs/cxxsupp/libcxx/include/typeinfo:221:16: error: reinterpret_cast from 'std::__type_info_implementations::__non_unique_arm_rtti_bit_impl::__type_name_t' (aka 'unsigned int') to 'size_t' (aka 'unsigned long') is not allowed
        return reinterpret_cast<size_t>(__v);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /src/catboost/private/libs/init/init_reg.cpp:1:
In file included from /src/catboost/private/libs/init/init_reg.h:3:
In file included from /src/util/generic/singleton.h:4:
In file included from /src/util/system/atomic.h:51:
/src/util/system/atomic_ops.h:131:38: error: cast from pointer to smaller type 'TAtomicBase' (aka 'int') loses information
    AtomicSet(*AsAtomicPtr(&target), reinterpret_cast<TAtomicBase>(value));
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/src/util/generic/singleton.h:47:17: note: in instantiation of function template specialization 'AtomicSet<NCB::TInitBase<> >' requested here
                AtomicSet(ptr, ret);
                ^
/src/util/generic/singleton.h:68:19: note: in instantiation of function template specialization 'NPrivate::SingletonBase<NCB::TInitBase<>, 65536>' requested here
            ret = SingletonBase<T, P>(ptr, std::forward<TArgs>(args)...);
                  ^
/src/util/generic/singleton.h:115:24: note: in instantiation of function template specialization 'NPrivate::SingletonInt<NCB::TInitBase<>, 65536>' requested here
    return ::NPrivate::SingletonInt<T, TSingletonTraits<T>::Priority>(std::forward<TArgs>(args)...);
                       ^
/src/catboost/private/libs/init/init_reg.h:23:30: note: in instantiation of function template specialization 'Singleton<NCB::TInitBase<>>' requested here
            for (auto func : Singleton<TInitBase>()->Funcs) {
                             ^
/src/catboost/private/libs/init/init_reg.cpp:4:24: note: in instantiation of member function 'NCB::TInitBase<>::Do' requested here
    NCB::TLibraryInit::Do();
                       ^
3 errors generated.
Failed

```

**Comment by kizill** [comment]
Sorry, please drop ```-DOS_SDK=local``` from cmd options :) It forces to mix arm clang and local linux headers

**Comment by nmreadelf** [comment]
> Sorry, please drop `-DOS_SDK=local` from cmd options :) It forces to mix arm clang and local linux headers

ok, thanks, i am trying

**Comment by kizill** [comment]
Fixed tbb build under aarch64, will work now.

**Comment by HelloDylan** [comment]
> Problem: I was cross compile catboot for armv8 on x86_64 fedora, in armv8 machine, run `from catboost.datasets import titanic` in python, err msg:
> 
> ```shell
> root@0a178b1ad665:/tmp# PYTHONPATH=/usr/local/lib/python3.7/site-packages python3
> Python 3.7.11 (default, Jul 22 2021, 11:25:48)
> [GCC 8.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from catboost.datasets import titanic
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.7/site-packages/catboost/__init__.py", line 1, in <module>
>     from .core import FeaturesData, EFstrType, Pool, CatBoost, CatBoostClassifier, CatBoostRegressor, CatBoostError, cv, train, sum_models, _have_equal_features, to_regressor, to_classifier, MultiRegressionCustomMetric, MultiRegressionCustomObjective  # noqa
>   File "/usr/local/lib/python3.7/site-packages/catboost/core.py", line 42, in <module>
>     from . import _catboost
> ImportError: /usr/local/lib/python3.7/site-packages/catboost/_catboost.so: undefined symbol: PyCObject_Type
> >>>
> ```
> 
> catboost version: 0.24.3 Operating System: host os system is `centos7`, container system base on `Debian GNU/Linux 10 (buster)` CPU: cat /proc/cpuinfo
> 
> ```
> Architecture:        aarch64
> Byte Order:          Little Endian
> CPU(s):              24
> On-line CPU(s) list: 0-23
> Thread(s) per core:  1
> Core(s) per socket:  12
> Socket(s):           2
> NUMA node(s):        2
> Vendor ID:           0x48
> Model:               0
> Stepping:            0x1
> CPU max MHz:         2000.0000
> CPU min MHz:         2000.0000
> BogoMIPS:            200.00
> L1d cache:           64K
> L1i cache:           64K
> L2 cache:            512K
> L3 cache:            32768K
> NUMA node0 CPU(s):   0-11
> NUMA node1 CPU(s):   12-23
> Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop
> ```
> 
> # GPU:
> i was use cmd `../../../ya make -r -DHAVE_CUDA=no --target-platform default-linux-aarch64` compile `_catboost.so` work directory is `catboost/catboost/python-package/catboost`
> 
> x86 system gcc and g++ version is `11.1.1 20210531 (Red Hat 11.1.1-3)`

could you please tell me how to install catboost on armv8 after compile _catboost.so?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
This looks like a mismatch between Python versions at compile and run time.
Could you please try to specify Python config as in this comment?
https://github.com/catboost/catboost/issues/1857#issuecomment-929576960
