### ISSUE TITLE
'Pool' object has no attribute '_java_obj'

### ISSUE THREAD

**Issue by HankPeng03** [catboost/catboost#1830]
Problem: 'Pool' object has no attribute '_java_obj'
catboost version: 0.25
Operating System: 
CPU:
# GPU:

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Hi @HankPeng03! Could you please share a reproducer?

**Comment by dfufdhf** [comment]
Hi @Evgueni-Petrov-aka-espetrov , I got the same error as @HankPeng03 when trying a catboost demo. Please check this comment, thanks a lot!

1.enviroment
catboost version: catboost-spark_2.4_2.11-0.26.1.jar
Operating System: linux
code language: PySpark
spark-version: 2.4.7
scala-version: 2.11.12

2.My shell scripts for submitting task:
spark-submit \
--master yarn \
--deploy-mode cluster \
--conf spark.yarn.appMasterEnv.yarn.nodemanager.container-executor.class=DockerLinuxContainer \
--conf spark.executorEnv.yarn.nodemanager.container-executor.class=DockerLinuxContainer \
--conf spark.yarn.appMasterEnv.yarn.nodemanager.docker-container-executor.image-name=bdp-docker.jd.com:5000/wise_mart_bag:latest \
--conf spark.executorEnv.yarn.nodemanager.docker-container-executor.image-name=bdp-docker.jd.com:5000/wise_mart_bag:latest \
--driver-cores 4 \
--driver-memory 8G \
--executor-cores 8 \
--executor-memory 16G \
--num-executors 100 \
--conf spark.shuffle.service.enabled=true \
--conf spark.dynamicAllocation.enabled=false \
--conf spark.dynamicAllocation.minExecutors=5 \
--conf spark.dynamicAllocation.maxExecutors=300 \
--conf spark.executor.memoryOverhead=16G \
--conf spark.broadcast.compress=true \
--conf spark.rdd.compress=true \
--conf spark.speculation=false \
--conf spark.sql.orc.filterPushdown=true \
--conf spark.sql.files.openCostInBytes=6291456 \
--conf spark.shuffle.consolidateFiles=true \
--py-files ../resource/configparser-5.0.1-py3-none-any.whl \
--py-files ../resource/ds_casual_inference.zip,../resource/sparkxgb.zip,../resource/catboost-spark_2.4_2.11-0.26.1.jar \
--jars ../resource/xgboost4j-0.80.jar,../resource/xgboost4j-spark-0.80.jar,../resource/catboost-spark_2.4_2.11-0.26.1.jar \
test_catboost.py

3.My PySpark scripts:
spark = (SparkSession
         .builder.appName("ai")
         .enableHiveSupport()
         .config("spark.executor.instances", "50")
         .config("spark.executor.memory", "8g")
         .config("spark.executor.cores", "4")
         .config("spark.driver.memory", "4g")
         .config("spark.driver.maxResultSize", "4g")
         .config("spark.sql.shuffle.partitions", "500")
         .config("hive.exec.dynamic.partition", "True")
         .config("hive.exec.dynamic.partition.mode","nonstrict")
         .config("spark.yarn.appMasterEnv.yarn.nodemanager.container-executor.class", "DockerLinuxContainer")
         .config("spark.executorEnv.yarn.nodemanager.container-executor.class", "DockerLinuxContainer")
         .config("spark.yarn.appMasterEnv.yarn.nodemanager.docker-container-executor.image-name", "bdp-docker.jd.com:5000/wise_mart_bag:latest")
         .config("spark.executorEnv.yarn.nodemanager.docker-container-executor.image-name", "bdp-docker.jd.com:5000/wise_mart_bag:latest")
         .config("spark.jars.packages", "ai.catboost:catboost-spark_2.4_2.11:0.26.1")
         .getOrCreate())
training_set_df = spark.read.format('com.databricks.spark.csv').options(header='true', inferschema='true').load(file_path)
vecAssembler = VectorAssembler(inputCols=feature_list, outputCol='feature_vector')
import catboost_spark
trainDF, testDF = training_set_df.randomSplit([0.8, 0.2], seed=24)
trainPool = catboost_spark.Pool(trainDF)
evalPool = catboost_spark.Pool(testDF)
regressor = catboost_spark.CatBoostRegressor()
model = regressor.fit(trainPool, [evalPool])


4.Problem (from my spark driver log): 
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/data7/yarn1/local/usercache/rank/appcache/application_7681618102802_17658793/container_e168_7681618102802_17658793_01_000001/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1159, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data7/yarn1/local/usercache/rank/appcache/application_7681618102802_17658793/container_e168_7681618102802_17658793_01_000001/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 985, in send_command
    response = connection.send_command(command)
  File "/data7/yarn1/local/usercache/rank/appcache/application_7681618102802_17658793/container_e168_7681618102802_17658793_01_000001/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1164, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
Traceback (most recent call last):
  File "test_catboost.py", line 93, in <module>
    trainPool = catboost_spark.Pool(trainDF)
  File "/data1/yarn1/local/usercache/rank/appcache/application_7681618102802_17658793/spark-791d3461-f1a1-42a9-80e8-d2510c423c66/userFiles-8d9298e3-ff90-49c2-bb11-bf5ac502ca5b/catboost-spark_2.4_2.11-0.26.1.jar/catboost_spark/core.py", line 490, in __init__
  File "/data7/yarn1/local/usercache/rank/appcache/application_7681618102802_17658793/container_e168_7681618102802_17658793_01_000001/pyspark.zip/pyspark/ml/wrapper.py", line 65, in _new_java_obj
  File "/data7/yarn1/local/usercache/rank/appcache/application_7681618102802_17658793/container_e168_7681618102802_17658793_01_000001/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1598, in __getattr__
py4j.protocol.Py4JError: ai.catboost.spark.Pool does not exist in the JVM
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/data7/yarn1/local/usercache/rank/appcache/application_7681618102802_17658793/container_e168_7681618102802_17658793_01_000001/pyspark.zip/pyspark/ml/wrapper.py", line 40, in __del__
AttributeError: 'Pool' object has no attribute '_java_obj'

**Comment by andrey-khropov** [comment]
I can reproduce such an error locally if Scala version in PySpark installation and in CatBoost package differ (for example if I try to use `catboost-spark_2.4_2.11` with pyspark==2.4.2 that uses Scala 2.12).

Do your Spark and PySpark libraries use Scala 2.11 indeed?

**Comment by dfufdhf** [comment]
I double checked my spark version as the screenshot below. And I guessed maybe there are some exceptions in the pyspark_wrapper_generator. 
![image](https://user-images.githubusercontent.com/7621580/140034914-61596187-b69b-41fb-a26a-21cec9781216.png)

**Comment by andrey-khropov** [comment]
> I double checked my spark version as the screenshot below. And I guessed maybe there are some exceptions in the pyspark_wrapper_generator. ![image](https://user-images.githubusercontent.com/7621580/140034914-61596187-b69b-41fb-a26a-21cec9781216.png)

That's the version of Spark, but pyspark is a separate library that can possibly have a different version.
Do you install it [manually](https://spark.apache.org/docs/latest/api/python/getting_started/install.html#manually-downloading) or [using pip](https://spark.apache.org/docs/latest/api/python/getting_started/install.html#using-pypi) ?

If you install pyspark using pip, what's the version displayed when you run `pip show` for `pyspark`

```
python -m pip show pyspark
```

?

**Comment by dfufdhf** [comment]
I checked the PySpark version on our cluster, and it's 2.4.7. Here is my code and screenshot.

import pyspark
os.environ['PYSPARK_PYTHON'] = "/usr/local/anaconda3/bin/python3.6"
print(pyspark.__version__)

![image](https://user-images.githubusercontent.com/7621580/140267096-bd5c93f1-9dec-4281-a641-9471ddc0a840.png)

**Comment by dfufdhf** [comment]
> I checked the PySpark version on our cluster, and it's 2.4.7. Here is my code and screenshot.
> 
> import pyspark os.environ['PYSPARK_PYTHON'] = "/usr/local/anaconda3/bin/python3.6" print(pyspark.**version**)
> 
> ![image](https://user-images.githubusercontent.com/7621580/140267096-bd5c93f1-9dec-4281-a641-9471ddc0a840.png)

By the way,  the python wrapper files are generated while running. I could only got exception traceback from P4J, and I have no idea how to debug the python wrapper code.

**Comment by antonsavostianov** [comment]
Hi! I am trying to use catboost_pyspark on Databricks. 
The error is:
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1207, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1033, in send_command
    response = connection.send_command(command)
  File "/databricks/spark/python/lib/py4j-0.10.9-src.zip/py4j/java_gateway.py", line 1211, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while receiving
Py4JError: ai.catboost.spark.Pool does not exist in the JVM

The cluster configuration is

Databricks Runtime Version: 9.1 LTS (includes Apache Spark 3.1.2, Scala 2.12)
Autoscaling is enabled  
Worker Type: Standard_D8s_v3 
Driver Type: Standard_D8s_v3
pyspark.__version__ is 3.1.2

catboost is installed on the cluster from the jar file:
https://search.maven.org/search?q=g:ai.catboost
catboost-spark_3.1_2.12-1.0.3.jar
################################################
The code is:

spark.conf.set(
  "spark.jars.packages", 
  "ai.catboost:catboost-spark_3.1_2.12:1.0.3"
)

import catboost_spark
classifier = catboost_spark.Classifier()
######################################
