### ISSUE TITLE
Unknown class labels

### ISSUE THREAD

**Issue by sujay003** [catboost/catboost#1939]
I'm beginner using boosting models ,I'm trying to implement catboost . My input data has 6 categorical features and 2 numerical feature . My target variable is numerical data. I'm running on GPU . I'm facing the problem below please help me. Cannot chare data due privacy issue.

Traceback (most recent call last):
  File "/work/ilt/css8222/cat_boost/cat_boost.py", line 127, in <module>
    save_snapshot = True
  File "/fibus/fs2/15/css8222/.local/lib/python3.6/site-packages/catboost/core.py", line 4718, in fit
    silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
  File "/fibus/fs2/15/css8222/.local/lib/python3.6/site-packages/catboost/core.py", line 2042, in _fit
    train_params["init_model"]
  File "/fibus/fs2/15/css8222/.local/lib/python3.6/site-packages/catboost/core.py", line 1464, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4393, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4442, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/private/libs/target/target_converter.cpp:226: Unknown class label: "14289"

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
This exception is thrown if some label exceeds or equals classes_count.
https://catboost.ai/docs/references/training-parameters/multiclassification

**Comment by sujay003** [comment]
I couldn't understand the documentation, is it possible to explain?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@sujay003 could you please post here the training parameters?

**Comment by sujay003** [comment]
params = {'iterations':5000,
        'learning_rate':0.01,
        'cat_features': categories,
        'depth':3,
        'eval_metric':'AUC',
        'verbose':200,
        'od_type':"Iter", # overfit detector
        'od_wait':500, # most recent best iteration to wait before stopping
        'random_seed': SEED
          }

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
and this is catboost.Classifier?

**Comment by sujay003** [comment]
yes

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Could you please do cat_model.get_all_params() after cat_model.fit(...), and post the output?

**Comment by sujay003** [comment]
---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_6748/4251039493.py in <module>
     11 
     12 cat_model = CatBoostClassifier(**params)
---> 13 cat_model.fit(X_train, y_train,
     14 eval_set=(X_test, y_test),
     15 use_best_model=True, # True if we don't want to save trees created after iteration with the best validation score

E:\Conda\lib\site-packages\catboost\core.py in fit(self, X, y, cat_features, text_features, embedding_features, sample_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   4714             CatBoostClassifier._check_is_compatible_loss(params['loss_function'])
   4715 
-> 4716         self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
   4717                   eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period,
   4718                   silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)

E:\Conda\lib\site-packages\catboost\core.py in _fit(self, X, y, cat_features, text_features, embedding_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, use_best_model, eval_set, verbose, logging_level, plot, column_description, verbose_eval, metric_period, silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
   2035         with log_fixup(log_cout, log_cerr), \
   2036             plot_wrapper(plot, [_get_train_dir(self.get_params())]):
-> 2037             self._train(
   2038                 train_pool,
   2039                 train_params["eval_sets"],

E:\Conda\lib\site-packages\catboost\core.py in _train(self, train_pool, test_pool, params, allow_clear_pool, init_model)
   1462 
   1463     def _train(self, train_pool, test_pool, params, allow_clear_pool, init_model):
-> 1464         self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
   1465         self._set_trained_model_attributes()
   1466 

_catboost.pyx in _catboost._CatBoost._train()

_catboost.pyx in _catboost._CatBoost._train()

CatBoostError: C:/Program Files (x86)/Go Agent/pipelines/BuildMaster/catboost.git/catboost/private/libs/target/target_converter.cpp:226: Unknown class label: "4340"

**Comment by sujay003** [comment]
---------------------------------------------------------------------------
CatBoostError                             Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_6748/1199477243.py in <module>
----> 1 cat_model.get_all_params()

E:\Conda\lib\site-packages\catboost\core.py in get_all_params(self)
   3065         """
   3066         if not self.is_fitted():
-> 3067             raise CatBoostError("There is no trained model to use get_all_params(). Use fit() to train model. Then use this method.")
   3068         return self._object._get_plain_params()
   3069 

CatBoostError: There is no trained model to use get_all_params(). Use fit() to train model. Then use this method.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Okay ) And if you remove eval_set everything works fine?

**Comment by sujay003** [comment]
without eval_set it gives CatBoost Error: bad allocation

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
How many different labels are there in y_train, y_test?

**Comment by sujay003** [comment]
y_train has 21635
y_test has 16701

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Hm, this means that you have 20K classes. Is this expected?

**Comment by sujay003** [comment]
Yes it is expected

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Multi-classification with that many classes needs about 5-10GB of free RAM.
This is likely the reason for 'bad allocation'.

As for 'unknown class label', this is likely because train does not contains some labels that are present in eval.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Btw, with that many classes, classification looks almost like regression...

**Comment by sujay003** [comment]
my labels are discrete data not continuous

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Well, you may try to train with leaf_estimation_method='Gradient' to reduce memory consumption.
https://catboost.ai/en/docs/references/training-parameters/common#leaf_estimation_method

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Is it finally working?

**Comment by sujay003** [comment]
no still giving bad allocation

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
max_ctr_complexity=1?

**Comment by sujay003** [comment]
same problem

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Definitely, you have some unusual setup.
I would suggest starting from few classes, categories, samples, and iterations, and scale up gradually.

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
closing as inactive for more than one month. please feel free to reopen :)
