### ISSUE TITLE
catboost_spark 'JavaPackage' object is not callable

### ISSUE THREAD

**Issue by arose13** [catboost/catboost#1997]
Simply put, this is the python code I run and the output below. The docs imply that `CatBoostClassifier` could be callable.
```
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.4.4
      /_/

Using Python version 3.6.8 (default, Oct 14 2019 21:22:53)
SparkSession available as 'spark'.
>>> import catboost_spark
>>> model = catboost_spark.CatBoostClassifier()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/spark/python/pyspark/__init__.py", line 110, in wrapper
    return func(self, **kwargs)
  File "/mnt/tmp/spark-6ea0fd77-dd8a-4350-8222-371c83e7c9fd/userFiles-4e95c169-bd5b-47a9-882e-bdebd9fbbe59/catboost_spark.jar/catboost_spark/core.py", line 3248, in __init__
  File "/usr/lib/spark/python/pyspark/ml/wrapper.py", line 67, in _new_java_obj
    return java_obj(*java_args)
TypeError: 'JavaPackage' object is not callable
```

I'm running on PySpark with spark version 2.4.4 scala 2.11

**Comment by arose13** [comment]
This was solved by specifying the `spark.jars.packages` in the config before spark starts up.

Example
    1. `pyspark --conf spark.jars.packages=ai.catboost:catboost-spark_2.4_2.11:1.0.4`
    2. `spark-submit --conf spark.jars.packages=ai.catboost:catboost-spark_2.4_2.11:1.0.4 <SPARK_SCRIPT.PY>`
