### ISSUE TITLE
Simple 

### ISSUE THREAD

**Issue by arturopineda92** [catboost/catboost#2008]
Problem:
catboost version:
Operating System:
CPU:
GPU:

**Comment by andrey-khropov** [comment]
> CatBoost Master process failed: exited with code 134

code 134 means CatBoost master process (a separate process launched on Spark driver node during training) recieved signal SIGABRT.

There could be some more detailed information from the master in driver logs. Can you look it up?

**Comment by arturopineda92** [comment]
I found these lines in master log
22/02/25 22:20:34 INFO LineBufferedStream: 22/02/25 22:20:34 INFO CatBoostMasterWrapper: Dataset data parts are ready. Start CatBoost Master process.
22/02/25 22:20:38 INFO LineBufferedStream: [CatBoost Master] java.lang.RuntimeException: (Permission denied) util/system/file.cpp:857: can't open "delay_matrix.bin" with mode WrOnly|CreateAlways|Seq (0x00000034)
22/02/25 22:20:38 INFO LineBufferedStream: [CatBoost Master] 	at ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl.native_implJNI.ModeFitImpl(Native Method)
22/02/25 22:20:38 INFO LineBufferedStream: [CatBoost Master] 	at ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl.native_impl.ModeFitImpl(native_impl.java:205)
22/02/25 22:20:38 INFO LineBufferedStream: [CatBoost Master] 	at ai.catboost.spark.impl.MasterApp$$anonfun$main$1.apply$mcI$sp(MasterApps.scala:38)
22/02/25 22:20:38 INFO LineBufferedStream: [CatBoost Master] 	at ai.catboost.spark.impl.AppWrapper$.apply(MasterApps.scala:19)
22/02/25 22:20:38 INFO LineBufferedStream: [CatBoost Master] 	at ai.catboost.spark.impl.MasterApp$.main(MasterApps.scala:38)
22/02/25 22:20:38 INFO LineBufferedStream: [CatBoost Master] 	at ai.catboost.spark.impl.MasterApp.main(MasterApps.scala)
