### ISSUE TITLE
[Spark] Azure Databricks - An active CatBoost worker is already present in the current process

### ISSUE THREAD

**Issue by CorentingData** [catboost/catboost#2088]
Hello everyone,

I working with catboost_spark on a Microsoft Azure Databricks. Catboost is doing great, but if I stop the current execution, I can't re-execute the same chunk of code. I have in this situation the following error message :

` ai.catboost.CatBoostError: An active CatBoost worker is already present in the current process`

I saw that this problem had been solved on a former catboost_spark version  #1795  but I think it is still present on Azure Databricks.

Thanks in advance for your help. Have a nice day !

```python
catboost version: 1.0.5
catboost_spark version: 1.0.4
spark version: 3.1.2
scala version: 2.12
```

**Comment by florent-pajot** [comment]
Hello, I'm encountering the same issue using Catboost on a Spark EMR cluster with similar version: EMR 6.50, Spark 3.1.2 and catboost-spark_3.1 1.0.4.

I also set a Spark configuration like this:
{
    "Classification": "spark",
    "Properties": {
      "spark.task.cpus": "4",
      "spark.executor.cores": "4",
      "spark.executor.memory": "12g"
    }
  }
the issue is the same with:
{
    "Classification": "spark",
    "Properties": {
      "spark.task.cpus": "1",
      "spark.executor.cores": "1",
      "spark.executor.memory": "12g"
    }
  }
Do you know if this bug is related to the Spark configuration? 

The full trace:
`22/05/19 10:17:07 ERROR Instrumentation: java.util.concurrent.ExecutionException: Error while executing workers
	at ai.catboost.spark.impl.Helpers$.checkOneFutureAndWaitForOther(Helpers.scala:33)
	at ai.catboost.spark.impl.Helpers$.waitForTwoFutures(Helpers.scala:61)
	at ai.catboost.spark.CatBoostPredictorTrait.$anonfun$fit$12(CatBoostPredictor.scala:256)
	at scala.util.control.Breaks.breakable(Breaks.scala:42)
	at ai.catboost.spark.CatBoostPredictorTrait.fit(CatBoostPredictor.scala:226)
	at ai.catboost.spark.CatBoostPredictorTrait.fit$(CatBoostPredictor.scala:125)
	at ai.catboost.spark.CatBoostClassifier.fit(CatBoostClassifier.scala:366)
	at ai.catboost.spark.CatBoostPredictorTrait.train(CatBoostPredictor.scala:111)
	at ai.catboost.spark.CatBoostPredictorTrait.train$(CatBoostPredictor.scala:108)
	at ai.catboost.spark.CatBoostClassifier.train(CatBoostClassifier.scala:366)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
	at org.apache.spark.ml.Predictor.fit(Predictor.scala:115)
	at org.apache.spark.ml.Pipeline.$anonfun$fit$5(Pipeline.scala:151)
	at org.apache.spark.ml.MLEvents.withFitEvent(events.scala:130)
	at org.apache.spark.ml.MLEvents.withFitEvent$(events.scala:123)
	at org.apache.spark.ml.util.Instrumentation.withFitEvent(Instrumentation.scala:42)
	at org.apache.spark.ml.Pipeline.$anonfun$fit$4(Pipeline.scala:151)
	at scala.collection.Iterator.foreach(Iterator.scala:941)
	at scala.collection.Iterator.foreach$(Iterator.scala:941)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
	at org.apache.spark.ml.Pipeline.$anonfun$fit$2(Pipeline.scala:147)
	at org.apache.spark.ml.MLEvents.withFitEvent(events.scala:130)
	at org.apache.spark.ml.MLEvents.withFitEvent$(events.scala:123)
	at org.apache.spark.ml.util.Instrumentation.withFitEvent(Instrumentation.scala:42)
	at org.apache.spark.ml.Pipeline.$anonfun$fit$1(Pipeline.scala:133)
	at org.apache.spark.ml.util.Instrumentation$.$anonfun$instrumented$1(Instrumentation.scala:191)
	at scala.util.Try$.apply(Try.scala:213)
	at org.apache.spark.ml.util.Instrumentation$.instrumented(Instrumentation.scala:191)
	at org.apache.spark.ml.Pipeline.fit(Pipeline.scala:133)
	at co.datadome.morpheus.actions.ModelTrainer$.run(ModelTrainer.scala:100)
	at co.datadome.morpheus.main.Main$.main(Main.scala:134)
	at co.datadome.morpheus.main.Main.main(Main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:959)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1047)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1056)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 7 in stage 682.0 failed 4 times, most recent failure: Lost task 7.3 in stage 682.0 (TID 6166) (ip-172-31-28-164.eu-west-3.compute.internal executor 9): ai.catboost.CatBoostError: An active CatBoost worker is already present in the current process
	at ai.catboost.spark.impl.CatBoostWorker.processPartition(Workers.scala:56)
	at ai.catboost.spark.impl.CatBoostWorkers$.$anonfun$apply$10(Workers.scala:333)
	at ai.catboost.spark.impl.CatBoostWorkers$.$anonfun$apply$10$adapted(Workers.scala:323)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2281)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2470)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2419)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2418)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2418)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1125)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1125)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1125)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2684)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2626)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2615)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:914)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2241)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2262)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2281)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2306)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$1(RDD.scala:1020)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:414)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:1018)
	at ai.catboost.spark.impl.CatBoostWorkers$.$anonfun$apply$9(Workers.scala:323)
	at ai.catboost.spark.impl.CatBoostWorkers.run(Workers.scala:177)
	at ai.catboost.spark.CatBoostPredictorTrait$$anon$1.run(CatBoostPredictor.scala:248)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: ai.catboost.CatBoostError: An active CatBoost worker is already present in the current process
	at ai.catboost.spark.impl.CatBoostWorker.processPartition(Workers.scala:56)
	at ai.catboost.spark.impl.CatBoostWorkers$.$anonfun$apply$10(Workers.scala:333)
	at ai.catboost.spark.impl.CatBoostWorkers$.$anonfun$apply$10$adapted(Workers.scala:323)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1020)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1020)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2281)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
	... 3 more
`

**Comment by iBalag** [comment]
Hello,
I have faced with the same issue in `ai.catboost:catboost-spark_2.4_2.11:1.1`. I use cloudera cluster for running Spark.
```
catboost-spark version: 1.1
spark version: 2.4.0
scala version: 2.11
```

**Comment by spencer-wallace** [comment]
Hello, 
Facing this issue as well on Azure Databricks. 

Spark version 3.3.0
Scala version 2.12
Catboost spark version 1.2

**Comment by shay16144** [comment]
Hi, I also have this issue on azure databricks with versions:
Spark version 3.3.0
Scala version 2.12
Catboost spark version 1.2

**Comment by alexyalunin** [comment]
any updates?

**Comment by Attol8** [comment]
I am facing the same issue on databricks on aws

**Comment by minhdang241** [comment]
Any updates on this issues?

**Comment by Jerome3590** [comment]
Using Apache Spark EMR I got past this issue with below Jupyter notebook settings and ensuring pipeline starts from a fresh cluster start

m5.8xlarge
%%configure -f
{
    "conf": {
        "spark.jars.packages": "ai.catboost:catboost-spark_3.5_2.12:1.2.7",
        "spark.executor.memory": "24g",
        "spark.executor.cores": "32",       
        "spark.driver.memory": "32g",      
        "spark.yarn.am.memory": "8g",     
        "spark.dynamicAllocation.enabled": "true", 
        "spark.task.cpus": "32",          
        "spark.jars.packages.resolve.transitive": "true",
        "spark.executor.extraJavaOptions": "--add-exports java.base/sun.net.util=ALL-UNNAMED",
        "spark.driver.extraJavaOptions": "--add-exports java.base/sun.net.util=ALL-UNNAMED",
        "spark.network.timeout": "1200s",  
        "spark.rpc.askTimeout": "1200s", 
        "spark.executor.memoryOverhead": "4g"
    }
}


# JARs preloaded via bash script
JAR_URLS=(
  "https://repo1.maven.org/maven2/ai/catboost/catboost-spark_3.5_2.12/1.2.7/catboost-spark_3.5_2.12-1.2.7.jar"
  "https://repo1.maven.org/maven2/ai/catboost/catboost-prediction/1.2.7/catboost-prediction-1.2.7.jar"
  "https://repo1.maven.org/maven2/ai/catboost/catboost-common/1.2.7/catboost-common-1.2.7.jar"
  "https://repo1.maven.org/maven2/io/github/classgraph/classgraph/4.8.139/classgraph-4.8.139.jar"
  "https://repo1.maven.org/maven2/ai/catboost/catboost-spark-macros_2.12/1.2.7/catboost-spark-macros_2.12-1.2.7.jar"
)
