### ISSUE TITLE
m1 java CatBoost failed to load

### ISSUE THREAD

**Issue by gaoyuanzong** [catboost/catboost#2121]
Problem:
Caused by: java.io.FileNotFoundException: File /darwin-aarch64/lib/libcatboost4j-prediction.dylib was not found inside JAR.
	at ai.catboost.common.NativeLib.copyFileFromJar(NativeLib.java:70)
	at ai.catboost.common.NativeLib.createTemporaryFileFromJar(NativeLib.java:99)
	at ai.catboost.common.NativeLib.loadNativeLibraryFromJar(NativeLib.java:58)
	at ai.catboost.common.NativeLib.smartLoad(NativeLib.java:21)
	at ai.catboost.CatBoostModel.<clinit>(CatBoostModel.java:111)
catboost version: 1.0.6
Operating System: macbook m1 pro
CPU: 
GPU:

**Comment by rusty-2** [comment]
`catboost-prediction` package, even in newest version just released (**1.1**) depends on `catboost-common` in version **1.0.4** for some reason and in version 1.0.5 there was a change in how the path to the dylib is created ([link](https://github.com/catboost/catboost/commit/9a176cf3d3aecfcb47005872f61708c82f77f9de))

Forcing synced versions of prediction & common packages worked for me to run catboost on m1
