### ISSUE TITLE
Unable to load the library

### ISSUE THREAD

**Issue by guptaaditya13** [catboost/catboost#214]
Unable to load the library
> from catboost import CatBoostRegressor

throws error

>Traceback (most recent call last):
  File "/Users/aditya.g/Projects/python-env/PredictionModels/lib/python3.6/site-packages/catboost/core.py", line 27, in <module>
    from catboost.gpu._catboost import _PoolBase, _CatBoostBase, CatboostError, _cv, _set_logger, _reset_logger, _configure_malloc
ImportError: dlopen(/Users/aditya.g/Projects/python-env/PredictionModels/lib/python3.6/site-packages/catboost/gpu/_catboost.so, 2): Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /Users/aditya.g/Projects/python-env/PredictionModels/lib/python3.6/site-packages/catboost/gpu/_catboost.so
  Reason: image not found

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/Users/aditya.g/Projects/python-env/PredictionModels/lib/python3.6/site-packages/catboost/core.py", line 30, in <module>
    from _catboost import _PoolBase, _CatBoostBase, CatboostError, _cv, _set_logger, _reset_logger, _configure_malloc
ModuleNotFoundError: No module named '_catboost'

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aditya.g/Projects/python-env/PredictionModels/lib/python3.6/site-packages/catboost/__init__.py", line 1, in <module>
    from .core import Pool, CatBoost, CatBoostClassifier, CatBoostRegressor, CatboostError, cv  # noqa
  File "/Users/aditya.g/Projects/python-env/PredictionModels/lib/python3.6/site-packages/catboost/core.py", line 32, in <module>
    from ._catboost import _PoolBase, _CatBoostBase, CatboostError, _cv, _set_logger, _reset_logger, _configure_malloc
ImportError: dynamic module does not define module export function (PyInit__catboost)

**Comment by melaanya** [comment]
I have the same issue

**Comment by sab** [comment]
Fixed in 0.5.2.1. Please try it and let us know if any problem occure.
