### ISSUE TITLE
Error: can't start device more than once

### ISSUE THREAD

**Issue by abhigenie92** [catboost/catboost#2154]
Problem:
```
Traceback (most recent call last):
  File "main.py", line 40, in <module>
    label_col_name="complaint_y_n")
  File "main.py", line 29, in cat_boost
    eval_set=(X_test, y_test)
  File "/usr/local/lib/python3.6/dist-packages/catboost/core.py", line 5009, in fit
    silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model, callbacks, log_cout, log_cerr)
  File "/usr/local/lib/python3.6/dist-packages/catboost/core.py", line 2283, in _fit
    train_params["init_model"]
  File "/usr/local/lib/python3.6/dist-packages/catboost/core.py", line 1705, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4585, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4634, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/cuda/cuda_lib/single_device.h:231: Error: can't start device more than once
```
catboost version: Latest
Operating System: Linux
CPU: -
GPU: NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3

I'm trying to use two GPUs here like this:
$ CUDA_VISIBLE_DEVICES=4,5 /usr/bin/python3 main.py

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@abhigenie92 could you please share a reproducer?
the following code works fine
```python
import catboost
model = catboost.CatBoostClassifier(iterations=2000,
    depth = 15,
    task_type="GPU")
train_data = [[0, 3],
              [4, 1],
              [8, 1],
              [9, 1]]
train_labels = [0, 0, 1, 1]
model.fit(train_data,
          train_labels,
          verbose=True)
model.fit(train_data,
          train_labels,
          verbose=True)
```

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@abhigenie92 ping?

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
@abhigenie92 please feel free to reopen (and add an end-to-end repro), if the problem is still there
