### ISSUE TITLE
Unable to specify TrainingDriver listening port (listeningPort)

### ISSUE THREAD

**Issue by gkarg** [catboost/catboost#2181]
Problem: Unable to specify TrainingDriver listening port (listeningPort)
catboost version: 1.0.6
Operating System: Linux
CPU:
GPU:

Driver-side error:
```
Caused by: ai.catboost.CatBoostError: Initial worker wait timeout of 01min 00sec expired
	at ai.catboost.spark.UpdatableWorkersInfo.initWorkers(TrainingDriver.scala:126)
	at ai.catboost.spark.TrainingDriver.run(TrainingDriver.scala:264)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

Executor-side error: 
```
22/09/30 18:11:14 INFO spark.TrainingDriver: CatBoost worker started listening at port 37867
22/09/30 18:11:14 INFO spark.TrainingDriver: send WorkerInfo to CatBoost training driver at /192.168.234.83:34879
22/09/30 18:11:14 INFO CatBoostWorker[partitionId=0]: ai.catboost.spark.CatBoostTrainingDriverConnectException: java.net.ConnectException: Connection refused (Connection refused)
22/09/30 18:11:14 INFO CatBoostWorker[partitionId=0]: processPartition: end```
```

We're trying to run catbook-spark in spark-client mode on hadoop, and our driver environment has some networking restrictions, more specifically, it has no reachable ports by default. This problem is also generally relevant for spark itself (spark driver/block-manager/ui ports could not be assigned automatically), which we mitigate by setting 

- 'spark.driver.host', 
- 'spark.driver.bindAddress',
- 'spark.driver.port',
- 'spark.driver.blockManager.port',
- 'spark.ui.port',

programmatically.

However, I was not able to find similar settings for catboost TrainingDriver, and my cursory overview of the code suggested that it's not possible at all (e.g. https://github.com/catboost/catboost/blob/dfc3f04050ef9acc3f070f38fe363fec93a3bc8d/catboost/spark/catboost4j-spark/core/src/main/scala/ai/catboost/spark/CatBoostPredictor.scala#L227 - listeningPort `0` is hardcoded)

I'm not really familiar with catboost codebase, nor speak Scala, so please take my analysis with a grain (a mountain?) of salt.

It would be of great benefit to us to have an ability to set the listeningPort, and also to specify bind IP address manually.

**Comment by gkarg** [comment]
❤️  Thank you!
