### ISSUE TITLE
pip install catboost@master python package from github failed

### ISSUE THREAD

**Issue by WeichenXu123** [catboost/catboost#2242]
Problem:

The command failed: `pip install git+https://github.com/catboost/catboost.git#subdirectory=catboost/python-package`
Link: https://github.com/mlflow/mlflow/actions/runs/3629953000/jobs/6122754464#step:11:181

Error message:

<details>
  <summary>Click to show error log</summary>

```
# pip wheel --no-deps --wheel-dir /home/runner/.cache/wheels git+https://github.com/catboost/catboost.git#subdirectory=catboost/python-package
Collecting git+https://github.com/catboost/catboost.git#subdirectory=catboost/python-package
  Cloning https://github.com/catboost/catboost.git to /tmp/pip-req-build-4h4kqlkq
  Running command git clone --filter=blob:none --quiet https://github.com/catboost/catboost.git /tmp/pip-req-build-4h4kqlkq
  Resolved https://github.com/catboost/catboost.git to commit ae701de874a53c2c33dbaecda1bc37135fc0390d
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: catboost
  Building wheel for catboost (setup.py): started
  Building wheel for catboost (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [121 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
  Running setup.py clean for catboost
      creating build/lib.linux-x86_64-3.8
      creating build/lib.linux-x86_64-3.8/catboost
      copying catboost/datasets.py -> build/lib.linux-x86_64-3.8/catboost
      copying catboost/__init__.py -> build/lib.linux-x86_64-3.8/catboost
      copying catboost/metrics.py -> build/lib.linux-x86_64-3.8/catboost
      copying catboost/utils.py -> build/lib.linux-x86_64-3.8/catboost
      copying catboost/version.py -> build/lib.linux-x86_64-3.8/catboost
      copying catboost/monoforest.py -> build/lib.linux-x86_64-3.8/catboost
      copying catboost/text_processing.py -> build/lib.linux-x86_64-3.8/catboost
      copying catboost/core.py -> build/lib.linux-x86_64-3.8/catboost
      copying catboost/plot_helpers.py -> build/lib.linux-x86_64-3.8/catboost
      copying catboost/dev_utils.py -> build/lib.linux-x86_64-3.8/catboost
      creating build/lib.linux-x86_64-3.8/catboost/widget
      copying catboost/widget/callbacks.py -> build/lib.linux-x86_64-3.8/catboost/widget
      copying catboost/widget/__init__.py -> build/lib.linux-x86_64-3.8/catboost/widget
      copying catboost/widget/ipythonwidget.py -> build/lib.linux-x86_64-3.8/catboost/widget
      copying catboost/widget/metrics_plotter.py -> build/lib.linux-x86_64-3.8/catboost/widget
      creating build/lib.linux-x86_64-3.8/catboost/eval
      copying catboost/eval/factor_utils.py -> build/lib.linux-x86_64-3.8/catboost/eval
      copying catboost/eval/_fold_storage.py -> build/lib.linux-x86_64-3.8/catboost/eval
      copying catboost/eval/_fold_model.py -> build/lib.linux-x86_64-3.8/catboost/eval
      copying catboost/eval/execution_case.py -> build/lib.linux-x86_64-3.8/catboost/eval
      copying catboost/eval/_readers.py -> build/lib.linux-x86_64-3.8/catboost/eval
      copying catboost/eval/__init__.py -> build/lib.linux-x86_64-3.8/catboost/eval
      copying catboost/eval/_splitter.py -> build/lib.linux-x86_64-3.8/catboost/eval
      copying catboost/eval/utils.py -> build/lib.linux-x86_64-3.8/catboost/eval
      copying catboost/eval/log_config.py -> build/lib.linux-x86_64-3.8/catboost/eval
      copying catboost/eval/catboost_evaluation.py -> build/lib.linux-x86_64-3.8/catboost/eval
      copying catboost/eval/_fold_models_handler.py -> build/lib.linux-x86_64-3.8/catboost/eval
      copying catboost/eval/evaluation_result.py -> build/lib.linux-x86_64-3.8/catboost/eval
      creating build/lib.linux-x86_64-3.8/catboost/widget/ipython
      copying catboost/widget/ipython/catboost-ipython-debug.ipynb -> build/lib.linux-x86_64-3.8/catboost/widget/ipython
      creating build/lib.linux-x86_64-3.8/catboost/widget/ipython/new_cv_2
      copying catboost/widget/ipython/new_cv_2/catboost_training.json -> build/lib.linux-x86_64-3.8/catboost/widget/ipython/new_cv_2
      creating build/lib.linux-x86_64-3.8/catboost/widget/ipython/new_train
      copying catboost/widget/ipython/new_train/catboost_training.json -> build/lib.linux-x86_64-3.8/catboost/widget/ipython/new_train
      creating build/lib.linux-x86_64-3.8/catboost/widget/ipython/new_cv_3
      copying catboost/widget/ipython/new_cv_3/catboost_training.json -> build/lib.linux-x86_64-3.8/catboost/widget/ipython/new_cv_3
      creating build/lib.linux-x86_64-3.8/catboost/widget/ipython/new_eval
      copying catboost/widget/ipython/new_eval/catboost_training.json -> build/lib.linux-x86_64-3.8/catboost/widget/ipython/new_eval
      creating build/lib.linux-x86_64-3.8/catboost/widget/ipython/new_train_with_nan
      copying catboost/widget/ipython/new_train_with_nan/catboost_training.json -> build/lib.linux-x86_64-3.8/catboost/widget/ipython/new_train_with_nan
      creating build/lib.linux-x86_64-3.8/catboost/widget/ipython/accuracy
      copying catboost/widget/ipython/accuracy/catboost_training.json -> build/lib.linux-x86_64-3.8/catboost/widget/ipython/accuracy
      creating build/lib.linux-x86_64-3.8/catboost/widget/ipython/new_cv_1
      copying catboost/widget/ipython/new_cv_1/catboost_training.json -> build/lib.linux-x86_64-3.8/catboost/widget/ipython/new_cv_1
      creating build/lib.linux-x86_64-3.8/catboost/widget/ipython/new_train_best
      copying catboost/widget/ipython/new_train_best/catboost_training.json -> build/lib.linux-x86_64-3.8/catboost/widget/ipython/new_train_best
      creating build/lib.linux-x86_64-3.8/catboost/widget/ipython/new_cv_subdirs
      creating build/lib.linux-x86_64-3.8/catboost/widget/ipython/new_cv_subdirs/first
      copying catboost/widget/ipython/new_cv_subdirs/first/catboost_training.json -> build/lib.linux-x86_64-3.8/catboost/widget/ipython/new_cv_subdirs/first
      creating build/lib.linux-x86_64-3.8/catboost/widget/ipython/new_cv_subdirs/second
      copying catboost/widget/ipython/new_cv_subdirs/second/catboost_training.json -> build/lib.linux-x86_64-3.8/catboost/widget/ipython/new_cv_subdirs/second
      creating build/lib.linux-x86_64-3.8/catboost/widget/ipython/subdirs
      creating build/lib.linux-x86_64-3.8/catboost/widget/ipython/subdirs/new_train
      copying catboost/widget/ipython/subdirs/new_train/catboost_training.json -> build/lib.linux-x86_64-3.8/catboost/widget/ipython/subdirs/new_train
      creating build/lib.linux-x86_64-3.8/catboost/widget/ipython/subdirs/new_train_multi
      copying catboost/widget/ipython/subdirs/new_train_multi/catboost_training.json -> build/lib.linux-x86_64-3.8/catboost/widget/ipython/subdirs/new_train_multi
      running build_ext
      Buildling _catboost.so with ymake
      EXECUTE: /opt/hostedtoolcache/Python/3.8.12/x64/bin/python /tmp/pip-req-build-4h4kqlkq/ya make /tmp/pip-req-build-4h4kqlkq/catboost/python-package/../../catboost/python-package/catboost --no-src-links --output /tmp/pip-req-build-4h4kqlkq/catboost/python-package/build/temp.linux-x86_64-3.8 -DPYTHON_CONFIG=python3-config -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -r -DNO_DEBUGINFO -DHAVE_CUDA=no
      Downloading https://storage.mds.yandex.net/get-devtools-opensource/233854/fba20aeabae11002ead119f4c9117e0f [..] OK
      Downloading https://storage.mds.yandex.net/get-devtools-opensource/250854/e90cf5[30](https://github.com/mlflow/mlflow/actions/runs/3629953000/jobs/6122754464#step:11:31)d88c9[31](https://github.com/mlflow/mlflow/actions/runs/3629953000/jobs/6122754464#step:11:32)4b8bbd1845122484d [................................................] Output root is subdirectory of Arcadia root, this may cause non-idempotent build
      Error: Unable to fetch resource OS_SDK_ROOT-sbr:617908641
      Traceback (most recent call last):
        File "devtools/ya/yalibrary/runner/tasks/pattern.py", line 39, in __call__
          self._ctx.patterns[self._pattern] = self.fetch(self._resources_map[self._pattern])
        File "devtools/ya/yalibrary/runner/tasks/pattern.py", line 65, in fetch
          return os.path.abspath(self._fetch_resource_if_need(self._fetcher, self._res_dir, resource, progress_callback, self._ctx.state))
        File "devtools/ya/yalibrary/fetcher/resource_fetcher.py", line 61, in fetch_resource_if_need
          downloader = _get_downloader(fetcher, parsed_uri, progress_callback, state, keep_directory_packed)
        File "devtools/ya/yalibrary/fetcher/resource_fetcher.py", line 95, in _get_downloader
          return _HttpDownloaderWithConfigMapping(parsed_uri.resource_id, default_resource_info)
        File "devtools/ya/yalibrary/fetcher/resource_fetcher.py", line 144, in __init__
          resource_url=mapping["resources"][resource_id],
      KeyError: '617908641'
      ------- PREPARE $(OS_SDK_ROOT-sbr:617908641)
      ERROR: '617908641'
      Failed
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-4h4kqlkq/catboost/python-package/setup.py", line 259, in <module>
          setup(
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-req-build-4h4kqlkq/catboost/python-package/setup.py", line 151, in run
          _bdist_wheel.run(self)
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/wheel/bdist_wheel.py", line [32](https://github.com/mlflow/mlflow/actions/runs/3629953000/jobs/6122754464#step:11:33)5, in run
          self.run_command("build")
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-req-build-4h4kqlkq/catboost/python-package/setup.py", line 117, in run
          _build.run(self)
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-req-build-4h4kqlkq/catboost/python-package/setup.py", line 186, in run
          self.build_with_ymake(topsrc_dir, build_dir, catboost_ext, put_dir, verbose, dry_run)
        File "/tmp/pip-req-build-4h4kqlkq/catboost/python-package/setup.py", line 219, in build_with_ymake
          logging_execute(ymake_cmd + ['-DHAVE_CUDA=no'], verbose, dry_run)
        File "/tmp/pip-req-build-4h4kqlkq/catboost/python-package/setup.py", line 62, in logging_execute
          subprocess.check_call(cmd, universal_newlines=True)
        File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.8.12/x64/bin/python', '/tmp/pip-req-build-4h4kqlkq/ya', 'make', '/tmp/pip-req-build-4h4kqlkq/catboost/python-package/../../catboost/python-package/catboost', '--no-src-links', '--output', '/tmp/pip-req-build-4h4kqlkq/catboost/python-package/build/temp.linux-x86_64-3.8', '-DPYTHON_CONFIG=python3-config', '-DUSE_ARCADIA_PYTHON=no', '-DOS_SDK=local', '-r', '-DNO_DEBUGINFO', '-DHAVE_CUDA=no']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for catboost
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line [34](https://github.com/mlflow/mlflow/actions/runs/3629953000/jobs/6122754464#step:11:35), in <module>
        File "/tmp/pip-req-build-4h4kqlkq/catboost/python-package/setup.py", line 261, in <module>
          version=os.environ.get('CATBOOST_PACKAGE_VERSION') or guess_catboost_version(),
        File "/tmp/pip-req-build-4h4kqlkq/catboost/python-package/setup.py", line [54](https://github.com/mlflow/mlflow/actions/runs/3629953000/jobs/6122754464#step:11:55), in guess_catboost_version
          exec(compile(open(version_py).read(), version_py, 'exec'))
      FileNotFoundError: [Errno 2] No such file or directory: 'catboost/version.py'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for catboost

```
</details>

catboost version: master
Operating System: Ubuntu 22.0 LTS
CPU: Intel x86_64
GPU: None.

**Comment by WeichenXu123** [comment]
CC @georgthegreat @andrey-khropov Could you provide some help! Thank you!

**Comment by kizill** [comment]
Hello! Currently we didn't support this way of installation. I guess, we can make some steps in this way working on #2278 and #830

**Comment by WeichenXu123** [comment]
Hi @kizill 

Then how to build dev version ?
like: 

I tried `cmake ./ -DCMAKE_BUILD_TYPE=Release -DPython3_ROOT_DIR=/home/weichen.xu/miniconda3/envs/py38 ` but I cannot disable CUDA when building .

And I cannot find the `ya.make` tool.

**Comment by WeichenXu123** [comment]
@kizill 

Since this commit https://www.google.com/url?q=https://github.com/catboost/catboost/commit/c5c642ca0b8e093336d0229ac4b14c78db3915bb&sa=D&source=docs&ust=1676291879791884&usg=AOvVaw1HY3V-h8uolGsX6PbpBK4n 

`pip install git+https://github.com/catboost/catboost.git#subdirectory=catboost/python-package` command does not work.
Previously the command works.

**Comment by andrey-khropov** [comment]
> Hi @kizill
> 
> Then how to build dev version ? like:
> 
> I tried `cmake ./ -DCMAKE_BUILD_TYPE=Release -DPython3_ROOT_DIR=/home/weichen.xu/miniconda3/envs/py38 ` but I cannot disable CUDA when building . We want to run it on CI so we cannot build with CUDA

There's a problem with disabling CUDA now, I've created an issue #2298 about it.
 
> And I cannot find the `ya.make` tool.

Yes, since https://github.com/catboost/catboost/commit/c5c642ca0b8e093336d0229ac4b14c78db3915bb there will be CMake-based builds.

If you urgently need some custom builds from source without CUDA please use some revision before https://github.com/catboost/catboost/commit/c5c642ca0b8e093336d0229ac4b14c78db3915bb. We're sorry for the inconvenience.

**Comment by WeichenXu123** [comment]
@andrey-khropov 

Thank you!
and can we make command `pip install git+https://github.com/catboost/catboost.git#subdirectory=catboost/python-package` work ? Previously it works. It should be simple to support, just replace `ya make` command with cmake.

**Comment by harupy** [comment]
@WeichenXu123 

> It should be simple to support, just replace ya make command with cmake.

Is replacing `ya make` with `cmake` simple? I'm not sure.

**Comment by WeichenXu123** [comment]
> Is replacing `ya make` with `cmake` simple? I'm not sure.

Let's wait @andrey-khropov 's reply. If it is hard to support, we can still use cmake command in our MLflow CI script.

**Comment by andrey-khropov** [comment]
@WeichenXu123 It has not been so easy but it is now again possible to install catboost from master by running `pip install git+https://github.com/catboost/catboost.git#subdirectory=catboost/python-package`.

There're some caveats though:
- On macOS and Linux it is assumed that `clang` and `clang++` are available on the command line and clang version is 12 or greater. 
  If not it is recommended to set  `clang` and `clang++` as aliases to newer versions like that:
  ```
  alias clang=clang-12
  alias clang++=clang++12
  ```
  before running the installation.
- On Windows Visual Studio 2019 build tools with toolset 14.28.29333 is required.
- `conan` version 1.57-1.59 (2.x is not supported yet) should be installed
- `ninja` should be installed
- `setup.py` is now fixed and it also supports building catboost python package with Jupyter visualization widget support (previously it was only possible using `mk_wheel.py`). But this requires [Yarn](https://yarnpkg.com/) to be installed. Buiding widget can be disabled with passing `--no-widget` option to the installer.
- If `CUDA_PATH` or `CUDA_ROOT` environment variable is detected CUDA support in python package will be enabled by default. You can also manually specify path to CUDA root dir with `--with-cuda=<path_to_cuda_root>` option. CUDA 11.x is recommended, CUDA 12.x is not supported yet. CUDA support can be explicitly disabled with `--no-cuda` option.

**Comment by andrey-khropov** [comment]
JFYI: Documentation has been updated to reflect the latest changes: https://catboost.ai/en/docs/installation/python-installation-method-build-from-source

**Comment by newbie-lad** [comment]
I just wanted to install catboost (which is odd that simple pip install is not available to me), not solve a lot of errors. I am ought to use something else, alas.
