### ISSUE TITLE
Error when initializing  Spark Catboost Pool on Databricks 

### ISSUE THREAD

**Issue by winooze** [catboost/catboost#2291]
Problem:
When trying to run code from [documentation](https://catboost.ai/en/docs/concepts/spark-quickstart-python), Regression, row 
```trainPool = catboost_spark.Pool(trainDf)```, 
 the following error occurs: ```java.lang.NoSuchMethodError: scala.runtime.Statics.releaseFence()V```
```
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
File <command-894036326279610>:27
     19 trainData = [
     20     Row(Vectors.dense(0.1, 0.2, 0.11), 0.12),
     21     Row(Vectors.dense(0.97, 0.82, 0.33), 0.22),
     22     Row(Vectors.dense(0.13, 0.22, 0.23), 0.34),
     23     Row(Vectors.dense(0.8, 0.62, 0.0), 0.1)
     24 ]
     26 trainDf = spark.createDataFrame(spark.sparkContext.parallelize(trainData), StructType(srcDataSchema))
---> 27 trainPool = catboost_spark.Pool(trainDf)
     29 evalData = [
     30     Row(Vectors.dense(0.22, 0.33, 0.9), 0.1),
     31     Row(Vectors.dense(0.11, 0.1, 0.21), 0.9),
     32     Row(Vectors.dense(0.77, 0.0, 0.0), 0.72)
     33 ]

File /local_disk0/spark-c2433650-66ab-4c08-93ad-761c6523923e/userFiles-cf84b118-3901-456f-a4fb-4769789100d2/addedFile2491643048929638855ai_catboost_catboost_spark_3_2_2_13_1_1_1-81754.jar/catboost_spark/core.py:546, in Pool.__init__(self, data_frame_or_java_object, pairs_data_frame)
    544     java_obj = data_frame_or_java_object
    545 else:
--> 546     java_obj = JavaWrapper._new_java_obj("ai.catboost.spark.Pool", data_frame_or_java_object, pairs_data_frame)
    548 super(Pool, self).__init__(java_obj)
    549 self.baselineCol = Param(self, "baselineCol", "baseline column name")

File /databricks/spark/python/pyspark/ml/wrapper.py:86, in JavaWrapper._new_java_obj(java_class, *args)
     84     java_obj = getattr(java_obj, name)
     85 java_args = [_py2java(sc, arg) for arg in args]
---> 86 return java_obj(*java_args)

File /databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py:1585, in JavaClass.__call__(self, *args)
   1579 command = proto.CONSTRUCTOR_COMMAND_NAME +\
   1580     self._command_header +\
   1581     args_command +\
   1582     proto.END_COMMAND_PART
   1584 answer = self._gateway_client.send_command(command)
-> 1585 return_value = get_return_value(
   1586     answer, self._gateway_client, None, self._fqn)
   1588 for temp_arg in temp_args:
   1589     temp_arg._detach()

File /databricks/spark/python/pyspark/sql/utils.py:209, in capture_sql_exception.<locals>.deco(*a, **kw)
    207 def deco(*a: Any, **kw: Any) -> Any:
    208     try:
--> 209         return f(*a, **kw)
    210     except Py4JJavaError as e:
    211         converted = convert_exception(e.java_exception)

File /databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py:326, in get_return_value(answer, gateway_client, target_id, name)
    324 value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
    325 if answer[1] == REFERENCE_TYPE:
--> 326     raise Py4JJavaError(
    327         "An error occurred while calling {0}{1}{2}.\n".
    328         format(target_id, ".", name), value)
    329 else:
    330     raise Py4JError(
    331         "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332         format(target_id, ".", name, value))

Py4JJavaError: An error occurred while calling None.ai.catboost.spark.Pool.
: java.lang.NoSuchMethodError: scala.runtime.Statics.releaseFence()V
	at ai.catboost.spark.Pool.<init>(Pool.scala:320)
	at ai.catboost.spark.Pool.<init>(Pool.scala:342)
	at ai.catboost.spark.Pool.<init>(Pool.scala:430)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:257)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
	at java.lang.Thread.run(Thread.java:750)
```
catboost version: ai.catboost:catboost-spark_3.2_2.13: 1.1.1 
Operating System: Databricks Runtime Version 12.1 ML (includes Apache Spark 3.3.1, Scala 2.12)

CPU: autoscaling cluster, 1 to 8 workers 14 GB, 4 cores, driver 28 GB, 8 cores. 

Message from the cluster's "Libraries" fold: ```com/fasterxml/jackson/core/jackson-databind#2.12.2.jar has been evicted due to: [com/fasterxml/jackson/core/jackson-databind#2.13.1.jar].```
![изображение](https://user-images.githubusercontent.com/65462107/216920517-103cac97-0503-44e9-bc28-c0e08f7d6d1f.png)
<img width="1079" alt="изображение" src="https://user-images.githubusercontent.com/65462107/216920636-4b86d98c-796b-4038-a21b-10c5d07ebb0a.png">

**Comment by andrey-khropov** [comment]
You have both Spark and Scala versions mismatch. You use catboost-spark for Spark 3.2 and Scala 2.13 but your Spark on DataBricks setup uses Spark 3.3 and Scala 2.12.

%%
catboost version: ai.catboost:catboost-spark_3.2_2.13: 1.1.1
Operating System: Databricks Runtime Version 12.1 ML (includes Apache Spark 3.3.1, Scala 2.12)
%%

Just use the proper version of catboost-spark package: ai.catboost:catboost-spark_3.3_2.12: 1.1.1

**Comment by andrey-khropov** [comment]
``Argument list is too long`` is a different known error #1842. It will be fixed in the next release.
