### ISSUE TITLE
sklearn.base.clone failed with Catboostclassifier in a Pipeline

### ISSUE THREAD

**Issue by Crispy13** [catboost/catboost#2337]
Problem: 
```
from catboost import CatBoostClassifier
from sklearn.base import clone
from sklearn.pipeline import Pipeline

pp = Pipeline(
    [
        ('ML', CatBoostClassifier(learning_rate=None)),
    ]
)

pp.set_params(**{'ML__learning_rate':None})
pp.get_params()

pp_clone = clone(pp)
```

**raised:**
```
2023-03-23 12:11:51,199    
Traceback (most recent call last):
  File "/software/anaconda3/envs/TOSC_ML/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3460, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_3961619/2881284288.py", line 1, in <module>
    pp_clone = clone(pp)
  File "/software/anaconda3/envs/TOSC_ML/lib/python3.10/site-packages/sklearn/base.py", line 89, in clone
    new_object_params[name] = clone(param, safe=False)
  File "/software/anaconda3/envs/TOSC_ML/lib/python3.10/site-packages/sklearn/base.py", line 67, in clone
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/software/anaconda3/envs/TOSC_ML/lib/python3.10/site-packages/sklearn/base.py", line 67, in <listcomp>
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/software/anaconda3/envs/TOSC_ML/lib/python3.10/site-packages/sklearn/base.py", line 67, in clone
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/software/anaconda3/envs/TOSC_ML/lib/python3.10/site-packages/sklearn/base.py", line 67, in <listcomp>
    return estimator_type([clone(e, safe=safe) for e in estimator])
  File "/software/anaconda3/envs/TOSC_ML/lib/python3.10/site-packages/sklearn/base.py", line 96, in clone
    param2 = params_set[name]
KeyError: 'learning_rate'
```

**Probable cause I think:**
at line 5019, catboost/core.py
```
for key, value in iteritems(locals().copy()):
    if key not in not_params and value is not None:
        params[key] = value
```

Because `learning_rate` was `None`, 'learning_rate' was not a key of `params`.
I can not stop to set `learning_rate` explicitly, I need to use grid search of sklearn. (`learning_rate = [None, 0.03, ...]`)

Other algorithms (e.g. GradientBoosting, RandomForest etc.) work properly.

catboost version: 1.1.1
Operating System: CentOS
CPU: AMD
GPU: None

**Comment by GrigoriiTarasov** [comment]
CatBoost is not cloned as estimator as intended in documentation [https://scikit-learn.org/stable/modules/generated/sklearn.base.clone.html]
"It returns a new estimator with the same parameters that has **not been fitted on any data**."

but here is a quick workaround 
`new_pipeline = clone(fitted_pipeline[:-1])

catboost_hyperparams = fitted_pipeline[-1].get_params()

new_catboost_classifier = cb.CatBoostClassifier(**catboost_hyperparams)

new_pipeline.steps.append(
    ('catboost', new_catboost_classifier))`

**Comment by fingoldo** [comment]
> new_catboost_classifier = cb.CatBoostClassifier(**catboost_hyperparams)

nice. probably

```
from copy import copy

new_catboost_classifier=copy(fitted_pipeline[-1])
```

should also work.

**Comment by timvink** [comment]
Here's another alternative implementation that utilizes the `__sklearn_clone__` method ([docs](https://scikit-learn.org/stable/modules/generated/sklearn.base.clone.html)) that `sklearn.base.clone` will use asof `scikit-learn>=1.3.0`:

```python
from catboost import CatBoostClassifier
from sklearn.base import clone

class CustomCatBoostClassifier(CatBoostClassifier):
    def __sklearn_clone__(self):
        return CatBoostClassifier(**self.get_params())

def test_custom_cat():
    model = CustomCatBoostClassifier(custom_metric=['AUC'])
    clone(model)
```

**Comment by salosx** [comment]
why this implementation of __sklearn_clone__ still is not in CatBoost base class?)
