### ISSUE TITLE
'PythonTrait' object has no attribute 'tmp_build_dir' when using mk_wheel.py

### ISSUE THREAD

**Issue by Crispy13** [catboost/catboost#2350]
```
Trying to build GPU version
Trying to build _catboost native library
GPU version build failed: 'PythonTrait' object has no attribute 'tmp_build_dir'
Trying to build CPU version
Trying to build _catboost native library
CPU version build failed: 'PythonTrait' object has no attribute 'tmp_build_dir'
Traceback (most recent call last):
  File "Downloads/catboost/catboost/python-package/catboost/../mk_wheel.py", line 389, in <module>
    wheel_name = build(build_system, arc_root, out_root, tail_args, args.build_widget == 'yes', args.build_with_cuda == 'yes')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/imbdx/user/eck/Downloads/catboost/catboost/python-package/catboost/../mk_wheel.py", line 375, in build
    raise Exception('Nothing built')
Exception: Nothing built
```

The error message was shown when running `python ../mk_wheel.py` in `catboost/catboost/python-package/catboost` dir.

When I see the code `mk_wheel.py`, It seems that there is no code assigning a value to `self.tmp_build_dir`.

**Comment by andrey-khropov** [comment]
We've recently switched from `mk_wheel.py` to Python standard tools. I've updated the documentation about this: https://catboost.ai/en/docs/installation/python-installation-method-build-a-wheel-package#standard

**Comment by andrey-khropov** [comment]
mk_wheel.py for building with CMake is no longer supported, use setup.py.
