### ISSUE TITLE
Build fails on macOS - catboost 1.2

### ISSUE THREAD

**Issue by DrShushen** [catboost/catboost#2371]
### Problem:
Since the `1.2` update, installing `catboost` on `"macos-latest"` GitHub Actions runners fails. This affects a number of projects that I work on that have `catboost` as a dependency. 

The build failure can be found in [this GitHub workflow](https://github.com/DrShushen/GH-actions-debug/actions/runs/4860949351/jobs/8665397003).

As of version `1.1.1` this issue was not happening, so I'm guessing it's related to the latest build https://pypi.org/project/catboost/1.2/#files

<details>

<summary>Expand to see build logs</summary>

#### Build logs as taken directly from the github runner are shown here. See also [the GitHub workflow](https://github.com/DrShushen/GH-actions-debug/actions/runs/4860949351/jobs/8665397003).

```txt
Requirement already satisfied: pip in /Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages (23.1.1)
Collecting pip
  Using cached pip-23.1.2-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.1.1
    Uninstalling pip-23.1.1:
      Successfully uninstalled pip-23.1.1
Successfully installed pip-23.1.2
Collecting catboost>=1.2
  Downloading catboost-1.2.tar.gz (95.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.9/95.9 MB 20.8 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting graphviz (from catboost>=1.2)
  Downloading graphviz-0.20.1-py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.0/47.0 kB 7.2 MB/s eta 0:00:00
Collecting matplotlib (from catboost>=1.2)
  Using cached matplotlib-3.7.1-cp38-cp38-macosx_10_12_x86_64.whl (7.4 MB)
Collecting numpy>=1.16.0 (from catboost>=1.2)
  Using cached numpy-1.24.3-cp38-cp38-macosx_10_9_x86_64.whl (19.8 MB)
Collecting pandas>=0.24 (from catboost>=1.2)
  Using cached pandas-2.0.1-cp38-cp38-macosx_10_9_x86_64.whl (11.6 MB)
Collecting scipy (from catboost>=1.2)
  Using cached scipy-1.10.1-cp38-cp38-macosx_10_9_x86_64.whl (35.0 MB)
Collecting plotly (from catboost>=1.2)
  Downloading plotly-5.14.1-py2.py3-none-any.whl (15.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 41.6 MB/s eta 0:00:00
Collecting six (from catboost>=1.2)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting python-dateutil>=2.8.2 (from pandas>=0.24->catboost>=1.2)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pytz>=2020.1 (from pandas>=0.24->catboost>=1.2)
  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
Collecting tzdata>=2022.1 (from pandas>=0.24->catboost>=1.2)
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 29.1 MB/s eta 0:00:00
Collecting contourpy>=1.0.1 (from matplotlib->catboost>=1.2)
  Downloading contourpy-1.0.7-cp38-cp38-macosx_10_9_x86_64.whl (243 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 244.0/244.0 kB 21.8 MB/s eta 0:00:00
CollectBuilding cycler>=0.10 (from matplotlib->catboost>=1.2)
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting fonttools>=4.22.0 (from matplotlib->catboost>=1.2)
  Downloading fonttools-4.39.3-py3-none-any.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 37.3 MB/s eta 0:00:00
Collecting kiwisolver>=1.0.1 (from matplotlib->catboost>=1.2)
  Downloading kiwisolver-1.4.4-cp38-cp38-macosx_10_9_x86_64.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.4/65.4 kB 9.1 MB/s eta 0:00:00
Collecting packaging>=20.0 (from matplotlib->catboost>=1.2)
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting pillow>=6.2.0 (from matplotlib->catboost>=1.2)
  Downloading Pillow-9.5.0-cp38-cp38-macosx_10_10_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 25.8 MB/s eta 0:00:00
Collecting pyparsing>=2.3.1 (from matplotlib->catboost>=1.2)
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 14.3 MB/s eta 0:00:00
Collecting importlib-resources>=3.2.0 (from matplotlib->catboost>=1.2)
  Using cached importlib_resources-5.12.0-py3-none-any.whl (36 kB)
Collecting tenacity>=6.2.0 (from plotly->catboost>=1.2)
  Downloading tenacity-8.2.2-py3-none-any.whl (24 kB)
Collecting zipp>=3.1.0 (from importlib-resources>=3.2.0->matplotlib->catboost>=1.2)
  Using cached zipp-3.15.0-py3-none-any.whl (6.8 kB)
Building wheels for collected packages: catboost
  Building wheel for catboost (pyproject.toml): started
  Building wheel for catboost (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for catboost (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [96 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.15-x86_64-cpython-38
      creating build/lib.macosx-10.15-x86_64-cpython-38/catboost
      copying catboost/monoforest.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost
      copying catboost/plot_helpers.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost
      copying catboost/metrics.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost
      copying catboost/version.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost
      copying catboost/text_processing.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost
      copying catboost/datasets.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost
      copying catboost/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost
      copying catboost/core.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost
      copying catboost/utils.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost
      copying catboost/dev_utils.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost
      creating build/lib.macosx-10.15-x86_64-cpython-38/catboost/widget
      copying catboost/widget/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost/widget
      copying catboost/widget/metrics_plotter.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost/widget
      copying catboost/widget/ipythonwidget.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost/widget
      copying catboost/widget/callbacks.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost/widget
      creating build/lib.macosx-10.15-x86_64-cpython-38/catboost/eval
      copying catboost/eval/catboost_evaluation.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost/eval
      copying catboost/eval/_fold_model.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost/eval
      copying catboost/eval/_readers.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost/eval
      copying catboost/eval/log_config.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost/eval
      copying catboost/eval/_splitter.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost/eval
      copying catboost/eval/__init__.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost/eval
      copying catboost/eval/execution_case.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost/eval
      copying catboost/eval/_fold_storage.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost/eval
      copying catboost/eval/factor_utils.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost/eval
      copying catboost/eval/utils.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost/eval
      copying catboost/eval/evaluation_result.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost/eval
      copying catboost/eval/_fold_models_handler.py -> build/lib.macosx-10.15-x86_64-cpython-38/catboost/eval
      running build_ext
      Buildling _catboost with cmake and ninja
      target_platform=darwin-x86_64. Building targets _catboost with PIC
      Running "cmake /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-rik3hogp/catboost_edaea41cb61849f5a85631e37874fcd2/catboost_all_src -B /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-rik3hogp/catboost_edaea41cb61849f5a85631e37874fcd2/build/temp.macosx-10.15-x86_64-cpython-38 -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-rik3hogp/catboost_edaea41cb61849f5a85631e37874fcd2/catboost_all_src/build/toolchains/clang.toolchain --log-level=VERBOSE -DCMAKE_POSITION_INDEPENDENT_CODE=On -DCATBOOST_COMPONENTS=python-package -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 -DHAVE_CUDA=no -DPython3_ROOT_DIR=/Users/runner/hostedtoolcache/Python/3.8.16/x64"
      CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
      CMake Error: CMAKE_ASM_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-b27d888_/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-b27d888_/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-b27d888_/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-b27d888_/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 723, in <module>
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-b27d888_/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-b27d888_/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-b27d888_/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-b27d888_/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-b27d888_/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-b27d888_/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 389, in run
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-b27d888_/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-b27d888_/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-b27d888_/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-b27d888_/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 324, in run
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-b27d888_/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-b27d888_/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-b27d888_/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-build-env-b27d888_/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 436, in run
        File "<string>", line 454, in build_with_cmake_and_ninja
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-rik3hogp/catboost_edaea41cb61849f5a85631e37874fcd2/catboost_all_src/build/build_native.py", line 517, in build
          cmd_runner.run(cmake_cmd, env=build_environ)
        File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-rik3hogp/catboost_edaea41cb61849f5a85631e37874fcd2/catboost_all_src/build/build_native.py", line 164, in run
          subprocess.run(cmd, check=True, **subprocess_run_kwargs)
        File "/Users/runner/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-rik3hogp/catboost_edaea41cb61849f5a85631e37874fcd2/catboost_all_src', '-B', '/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-rik3hogp/catboost_edaea41cb61849f5a85631e37874fcd2/build/temp.macosx-10.15-x86_64-cpython-38', '-G', 'Ninja', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-install-rik3hogp/catboost_edaea41cb61849f5a85631e37874fcd2/catboost_all_src/build/toolchains/clang.toolchain', '--log-level=VERBOSE', '-DCMAKE_POSITION_INDEPENDENT_CODE=On', '-DCATBOOST_COMPONENTS=python-package', '-DCMAKE_OSX_DEPLOYMENT_TARGET=11.0', '-DHAVE_CUDA=no', '-DPython3_ROOT_DIR=/Users/runner/hostedtoolcache/Python/3.8.16/x64']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for catboost
ERROR: Could not build wheels for catboost, which is required to install pyproject.toml-based projects
Failed to build catboost
```

</details>

**`catboost` version:** `1.2`
**Operating System:** macOS 12 Monterey, at least according to [About GitHub-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners)
**CPU:** 3-core CPU (x86_64), according to [About GitHub-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners)
**GPU:** None

**Comment by DrShushen** [comment]
Understood, thanks

**Comment by xmatthias** [comment]
@DrShushen did you find a fix for this?

I'm seeing the same in our CI - but we're clearly not setting 10.15 as platform - if that's set, then it would be comming from the github runners (?)  config?

**Comment by DrShushen** [comment]
No, not looked at this issue on my end yet, for now I'm setting the dependency to `"catboost<1.2"`. Not sure why `macosx-10.15` is being detected on the GitHub runner. Do post here if you find a solution.

**Comment by xmatthias** [comment]
On a quick note, it seems to relate to this discussion: https://discuss.python.org/t/pep-425-platform-tag/5157/3.

`python -c "import sysconfig;print(sysconfig.get_platform())"` indeed shows `macosx-10.15-x86_64` on 3.8, but `macosx-11.7-x86_64` on 3.9.16 (same runner of `macos-latest`, just a different python version).

Since there's no wheels for that platform available - it's failing (for probably obvious reasons).

For now - i suspect that it's something to do with python 3.8 detecting the version wrongly, since github runners install X versions of the SDK
but it's a pretty wide guess - as i'm not too familiar with macOS in general.

**Comment by xmatthias** [comment]
Did some further tests - and it seems to be an issue with 3.8 - which detects the version differently (run: https://github.com/xmatthias/actionstest/actions/runs/4869050623/jobs/8683112338)

looking at the output of `pip gethost` - which is effectively this: `python -c 'from pip._vendor.distlib.util import get_host_platform; print(f"pip gethost: {get_host_platform()}")'`, it's quite inconsistent throughout the versions (ignoring 3.7, as there's no support for it in catboost anymore).

| Python version| platform| uses Wheel | 
|--------|--------|--------|
| 3.8 |  macosx-10.15-x86_64 | ❌  |
| 3.9 | macosx-11.7-x86_64 |✅  |
| 3.10 | macosx-11.7-x86_64 |✅  |
| 3.11 | macosx-10.9-universal2 | ✅  |

3 out of 4 versions correctly use the provided wheel (`*-macosx_11_0_universal2.whl` ) - while 3.8 does not.

**Comment by andrey-khropov** [comment]
> ignoring 3.7, as there's no support for it in catboost anymore
Where did you get this information? CatBoost still supports python 3.7, even on macOS and I can install version 1.2 (Although on macOS 12 Monterey):

```
$ uname -a
Darwin akhropov-2osx 21.6.0 Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64 x86_64
$ python3.7 -m pip install catboost==1.2
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting catboost==1.2
  Downloading catboost-1.2-cp37-cp37m-macosx_11_0_universal2.whl (25.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.6/25.6 MB 638.2 kB/s eta 0:00:00
...
Successfully installed catboost-1.2
$ python3.7
Python 3.7.16 (default, Dec  7 2022, 01:34:15) 
[Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import catboost
>>> catboost.version
<module 'catboost.version' from '/usr/local/lib/python3.7/site-packages/catboost/version.py'>
>>> catboost.version.VERSION
'1.2'
```

**Comment by andrey-khropov** [comment]
I'm able to successfully install catboost 1.2 using wheels for python3.8 (from pyenv) on macOS 11.x and macOS 12.x on the x86_64 architecture with the same versions of python3.8 (3.8.16) and pip (23.1.2) as the github runner:

macOS 11.x:

```
% uname -m
x86_64
% sw_vers
ProductName:	macOS
ProductVersion:	11.5.1
BuildVersion:	20G80
% pyenv shell 3.8.16
% python -m pip install catboost==1.2
Collecting catboost==1.2
  Using cached catboost-1.2-cp38-cp38-macosx_11_0_universal2.whl (25.6 MB)
...
Successfully installed catboost-1.2
% python
Python 3.8.16 (default, Apr  7 2023, 00:58:00) 
[Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import catboost
>>> catboost.version.VERSION
'1.2'
```

macOS 12.x:

```
$ uname -m
x86_64
$ sw_vers
ProductName:	macOS
ProductVersion:	12.6.5
BuildVersion:	21G531
$ pyenv shell 3.8.16
$ python -m pip install catboost==1.2
Collecting catboost==1.2
  Using cached catboost-1.2-cp38-cp38-macosx_11_0_universal2.whl (25.6 MB)
...
Successfully installed catboost-1.2
$ python
Python 3.8.16 (default, Jan 25 2023, 18:08:23) 
[Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import catboost
>>> catboost.version.VERSION
'1.2'
```

So the issue seems to be with **the particular** python 3.8.16 installation used by GitHub actions.

**Comment by PrimozGodec** [comment]
Currently, I see two possible solutions:
- Install ninja to enable `catboost` to be built: `brew install ninja`
- Use the older version: `catboost<1.2`

Did anyone find a better solution to fix the current Githu Action environment so that those fixes wouldn't be required? It seems GH Actions don't plan to make any changes https://github.com/actions/setup-python/issues/654.

**Comment by xmatthias** [comment]
> For now I'm going to close the issue.

source: https://github.com/actions/setup-python/issues/654#issuecomment-1522536262

To me, the above statement is not a final decision.
The original issue just mentioned that it's different - not necessarily that it's creating "whatever" issues (or any particular issue, anyway).

**Comment by ddelange** [comment]
would it be possible for catboost to build separate wheels for intel and arm macs?

the [cibuildwheel defaults](https://github.com/MagicStack/asyncpg/blob/v0.27.0/.github/workflows/release.yml#L85) will generate the following wheels:
```
asyncpg-0.27.0-cp311-cp311-macosx_10_9_x86_64.whl
asyncpg-0.27.0-cp311-cp311-macosx_11_0_arm64.whl
```

you will be able to reach mostly any mac user with these two without tradeoff.

in contrast, universal wheels are essentially duplicating binaries (x86 + arm64) to maximize portability (packaged in a mac app for instance), but I think it also sacrifices on device compatibility and increases local storage usage.

**Comment by andrey-khropov** [comment]
> would it be possible for catboost to build separate wheels for intel and arm macs?

**Comment by ddelange** [comment]
having a `macosx_10_9_x86_64` wheel on pypi does not mean catboost explicitly supports osx 10 per se, from a python packaging perspective this wheel (even if it's built on osx 11) is simply backward compatible by design

**Comment by ddelange** [comment]
So this is [definitively](https://github.com/actions/setup-python/issues/654#issuecomment-1576692309) a "won't fix" on GitHub side.

This means that `catboost>=1.3 & macos-latest & py<=3.8` would remain broken in all Github CI setups of all downstream projects.

@andrey-khropov could the catboost team once more consider backwards compatible wheels? I think it'll save many a dev the debug journey!

**Comment by xmatthias** [comment]
The good news is, with the release of the new python versions, this was auto-fixed (as expected).

if your pipeline didn't auto-update to the latest version yet, you can force this via "check-latest: true" in the action setup

``` yaml
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        check-latest: true
```
