### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'iteritems' on predict on a DataFrame

### ISSUE THREAD

**Issue by lucgiffon** [catboost/catboost#2411]
Problem: Catboost depends on pandas >=0.24 but it is not true
catboost version: 1.0.6

In pandas version 2.0.2, DataFrame.iteritems has been removed yet catboost depends on this method. I get the following error when calling predict on a DataFrame.

```
Traceback (most recent call last):
  File "/home/lgiffon/anaconda3/envs/price-index/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-2398a3949ea0>", line 1, in <module>
    model.predict(eval_set[model.feature_names_])
  File "/home/lgiffon/anaconda3/envs/price-index/lib/python3.10/site-packages/catboost/core.py", line 5635, in predict
    return self._predict(data, prediction_type, ntree_start, ntree_end, thread_count, verbose, 'predict', task_type)
  File "/home/lgiffon/anaconda3/envs/price-index/lib/python3.10/site-packages/catboost/core.py", line 2458, in _predict
    data, data_is_single_object = self._process_predict_input_data(data, parent_method_name, thread_count)
  File "/home/lgiffon/anaconda3/envs/price-index/lib/python3.10/site-packages/catboost/core.py", line 2438, in _process_predict_input_data
    data = Pool(
  File "/home/lgiffon/anaconda3/envs/price-index/lib/python3.10/site-packages/catboost/core.py", line 790, in __init__
    self._init(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
  File "/home/lgiffon/anaconda3/envs/price-index/lib/python3.10/site-packages/catboost/core.py", line 1411, in _init
    self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
  File "_catboost.pyx", line 3941, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 3991, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 3807, in _catboost._PoolBase._init_features_order_layout_pool
  File "_catboost.pyx", line 2717, in _catboost._set_features_order_data_pd_data_frame
  File "/home/lgiffon/anaconda3/envs/price-index/lib/python3.10/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'iteritems'
model.predict(eval_set[model.feature_names_].values)
Out[5]: 
array([ 2.12401385e+00, -1.22539282e+00,  3.42449121e-01, ...,
       -8.26475821e-01, -1.12224466e-03, -3.65242185e-01])
```

**Comment by nov-stacy** [comment]
Hello! You use old version of catboost. This pandas version is supported in catboost==1.2

**Comment by lucgiffon** [comment]
Sorry

**Comment by jpgard** [comment]
Hi, I still get this issue using catboost==1.2.5 (most recent version) and pandas==1.3.5 . Can you advise on how to configure the dependencies?
