### ISSUE TITLE
catboost-spark model feature importance methods not working

### ISSUE THREAD

**Issue by shay16144** [catboost/catboost#2468]
Problem: Cannot produce featureImportance
catboost version:  ai.catboost:catboost-spark_3.3_2.12:1.2

Hi, I am trying to access the feature important methods after training a model but keep getting the following error for eachtype of feature importance:   
py4j.Py4JException: Method getFeatureImportanceShapValues([class org.apache.spark.sql.Dataset, class ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl.EPreCalcShapValues, class ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl.ECalcTypeShapValues, class ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl.EExplainableModelOutput, null, null]) does not exist

Is there any solution to this?

**Comment by andrey-khropov** [comment]
Unfortunately, I cannot reproduce this. We have tests for feature importance for Spark [here](https://github.com/catboost/catboost/tree/master/catboost/spark/catboost4j-spark/core/src/test/python), [feature_importance_test.py](https://github.com/catboost/catboost/blob/master/catboost/spark/catboost4j-spark/core/src/test/python/feature_importance_test.py) specifically.

It works with PySpark 3.3 and CatBoost 1.2 for me. So, please provide a more detailed environment and code to reproduce the error you have encountered.

**Comment by shay16144** [comment]
Databricks cluster:   11.3 LTS ML (includes Apache Spark 3.3.0, Scala 2.12)
worker type:  Standard_E16d_V4


py4j.Py4JException: Method getFeatureImportanceShapValues([class org.apache.spark.sql.Dataset, class ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl.EPreCalcShapValues, class ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl.ECalcTypeShapValues, class ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl.EExplainableModelOutput, null, null]) does not exist
---------------------------------------------------------------------------
Py4JError                                 Traceback (most recent call last)
<command-34777500251157> in <cell line: 1>()
----> 1 shap = model.getFeatureImportanceShapValues(train_df)

/local_disk0/spark-a534b64a-0a60-497d-8334-e8b47f4d62da/userFiles-078d28ae-8f39-4e10-a370-10750891cdcd/addedFile1842108208698047231ai_catboost_catboost_spark_3_3_2_12_1_2-4db1b.jar/catboost_spark/core.py in getFeatureImportanceShapValues(self, data, preCalcMode, calcType, modelOutputType, referenceData, outputColumns)
   5696               contains outputColumns and "shapValues" column with Matrix of shape (n_classes x (n_features + 1)) with SHAP values
   5697         """
-> 5698         return self._call_java(
   5699             "getFeatureImportanceShapValues",
   5700             data,

/databricks/spark/python/pyspark/ml/wrapper.py in _call_java(self, name, *args)
     70 
     71         java_args = [_py2java(sc, arg) for arg in args]
---> 72         return _java2py(sc, m(*java_args))
     73 
     74     @staticmethod

/databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1319 
   1320         answer = self.gateway_client.send_command(command)
-> 1321         return_value = get_return_value(
   1322             answer, self.gateway_client, self.target_id, self.name)
   1323 

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
    194     def deco(*a: Any, **kw: Any) -> Any:
    195         try:
--> 196             return f(*a, **kw)
    197         except Py4JJavaError as e:
    198             converted = convert_exception(e.java_exception)

/databricks/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    328                     format(target_id, ".", name), value)
    329             else:
--> 330                 raise Py4JError(
    331                     "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332                     format(target_id, ".", name, value))

Py4JError: An error occurred while calling o4523.getFeatureImportanceShapValues. Trace:
py4j.Py4JException: Method getFeatureImportanceShapValues([class org.apache.spark.sql.Dataset, class ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl.EPreCalcShapValues, class ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl.ECalcTypeShapValues, class ru.yandex.catboost.spark.catboost4j_spark.core.src.native_impl.EExplainableModelOutput, null, null]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:341)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:349)
	at py4j.Gateway.invoke(Gateway.java:297)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:195)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:115)
	at java.lang.Thread.run(Thread.java:750)

**Comment by shay16144** [comment]
The model is fine, it is only when trying to acquire feature importance that I'm getting the error

import catboost_spark
from pyspark.sql.functions import *
from pyspark.ml.feature import StringIndexer, VectorAssembler
import pandas as pd
from pyspark.ml import Pipeline, PipelineModel
import logging
logging.basicConfig(level=logging.WARN)
logger = logging.getLogger(__name__)
logger = spark._jvm.org.apache.log4j
logging.getLogger("py4j.java_gateway").setLevel(logging.ERROR)
 
import warnings
warnings.filterwarnings(action='ignore')

spark.conf.set("spark.sql.execution.arrow.pyspark.enabled", "true")
spark.conf.set('logLevel', "ERROR") 
spark.conf.set("spark.sql.mapKeyDedupPolicy","LAST_WIN")
from pyspark.ml.evaluation import MulticlassClassificationEvaluator
from pyspark.ml.tuning import CrossValidator, ParamGridBuilder

classifier = catboost_spark.CatBoostClassifier(iterations=1400, learningRate = 0.1, depth = 7, evalMetric = 'Accuracy',  useBestModel = True, lossFunction = 'MultiClass')


trainPool = catboost_spark.Pool(train_df)
evalPool = catboost_spark.Pool(test_df)
model = classifier.fit(trainPool, evalDatasets = [evalPool])

**Comment by Jerome3590** [comment]
I was able to get this to work for a few of my models. Still investigating. Using PySpark on AWS EMR but I think it worked when I installed these directly:
JAR_URLS=(
  "https://repo1.maven.org/maven2/ai/catboost/catboost-spark_3.5_2.12/1.2.7/catboost-spark_3.5_2.12-1.2.7.jar"
  "https://repo1.maven.org/maven2/ai/catboost/catboost-prediction/1.2.7/catboost-prediction-1.2.7.jar"
  "https://repo1.maven.org/maven2/ai/catboost/catboost-common/1.2.7/catboost-common-1.2.7.jar"
  "https://repo1.maven.org/maven2/io/github/classgraph/classgraph/4.8.139/classgraph-4.8.139.jar"
  "https://repo1.maven.org/maven2/ai/catboost/catboost-spark-macros_2.12/1.2.7/catboost-spark-macros_2.12-1.2.7.jar"
)

**Comment by Jerome3590** [comment]
I have this working with the scala api but haven't went back and tried PySpark yet. May be awhile before I test the PySpark implementation
