### ISSUE TITLE
macOS 14.1.1 (23B81) install catboost error

### ISSUE THREAD

**Issue by Jampion-Zhang** [catboost/catboost#2541]
Problem: python3 -m pip install catboost error
catboost version:
Operating System: macOS 14.1.1 (23B81)
CPU: M2
GPU:

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting catboost
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d3/65/d55e51dab8f29b66827b4304eaf19f583506aaaf66413a8505a370181314/catboost-1.2.2.tar.gz (60.1 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [114 lines of output]
      Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
      Collecting setuptools>=64.0
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/bb/e1/ed2dd0850446b8697ad28d118df885ad04140c64ace06c4bd559f7c8a94f/setuptools-69.0.2-py3-none-any.whl (819 kB)
      Collecting wheel
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c7/c3/55076fc728723ef927521abaa1955213d094933dc36d4a2008d5101e1af5/wheel-0.42.0-py3-none-any.whl (65 kB)
      Collecting jupyterlab
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a7/f2/b3ed35a9d75c22c7a90dc51963e57373d000007ba3ccbfc6277ba6448aa8/jupyterlab-4.0.9-py3-none-any.whl (9.2 MB)
      Collecting conan<=1.59,>=1.57
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/41/b2/839b3bdd1a02e0d32c13a49ce6fe8239535997736cafab864a0eb351e5ac/conan-1.59.0.tar.gz (780 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting async-lru>=1.0.0 (from jupyterlab)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/fa/9f/3c3503693386c4b0f245eaf5ca6198e3b28879ca0a40bde6b0e319793453/async_lru-2.0.4-py3-none-any.whl (6.1 kB)
      Collecting ipykernel (from jupyterlab)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/73/14/ec9a1c42d2c952c848a1ac366718783ab725148faf910bc086601809cefd/ipykernel-6.27.1-py3-none-any.whl (114 kB)
      Collecting jinja2>=3.0.3 (from jupyterlab)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/bc/c3/f068337a370801f372f2f8f6bad74a5c140f6fda3d9de154052708dd3c65/Jinja2-3.1.2-py3-none-any.whl (133 kB)
      Collecting jupyter-core (from jupyterlab)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ab/ea/af6508f71d2bcbf4db538940120cc3d3f10287f62105e756bd315aa345b5/jupyter_core-5.5.0-py3-none-any.whl (28 kB)
      Collecting jupyter-lsp>=2.0.0 (from jupyterlab)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a6/b9/bb98cc91cda084a2756938682d02bdaf221a38f30b7126ba65ed7cde3ea6/jupyter_lsp-2.2.1-py3-none-any.whl (66 kB)
      Collecting jupyter-server<3,>=2.4.0 (from jupyterlab)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3b/c8/2f997f763abafbed76fdb2534aa150939f2882f0ea88cd084a8b8a8f0e4d/jupyter_server-2.11.1-py3-none-any.whl (380 kB)
      Collecting jupyterlab-server<3,>=2.19.0 (from jupyterlab)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a2/97/abbbe35fc67b6f9423309988f2e411f7cb117b08321866d3d8b720f4c0d4/jupyterlab_server-2.25.2-py3-none-any.whl (58 kB)
      Collecting notebook-shim>=0.2 (from jupyterlab)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f4/79/73250372e5bbab63018b41b02d5cc6b395655ec6c1254e477ef7c913aada/notebook_shim-0.2.3-py3-none-any.whl (13 kB)
      Collecting packaging (from jupyterlab)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ec/1a/610693ac4ee14fcdf2d9bf3c493370e4f2ef7ae2e19217d7a237ff42367d/packaging-23.2-py3-none-any.whl (53 kB)
      Collecting tornado>=6.2.0 (from jupyterlab)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e8/52/4775f3e6630bbc3808e678eb2294beeb654040cf45cc2b66cd6efdcf2571/tornado-6.3.3-cp38-abi3-macosx_10_9_universal2.whl (425 kB)
      Collecting traitlets (from jupyterlab)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a7/1d/7d07e1b152b419a8a9c7f812eeefd408a0610d869489ee2e86973486713f/traitlets-5.14.0-py3-none-any.whl (85 kB)
      Collecting requests<3.0.0,>=2.25 (from conan<=1.59,>=1.57)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl (62 kB)
      Collecting urllib3<1.27,>=1.26.6 (from conan<=1.59,>=1.57)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b0/53/aa91e163dcfd1e5b82d8a890ecf13314e3e149c05270cc644581f77f17fd/urllib3-1.26.18-py2.py3-none-any.whl (143 kB)
      Collecting colorama<0.5.0,>=0.3.3 (from conan<=1.59,>=1.57)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d1/d6/3965ed04c63042e047cb6a3e6ed1a63a35087b6a609aa3a15ed8ac56c221/colorama-0.4.6-py2.py3-none-any.whl (25 kB)
      Collecting PyYAML<=6.0,>=3.11 (from conan<=1.59,>=1.57)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/36/2b/61d51a2c4f25ef062ae3f74576b01638bebad5e045f747ff12643df63844/PyYAML-6.0.tar.gz (124 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'error'
        error: subprocess-exited-with-error

        × Getting requirements to build wheel did not run successfully.
        │ exit code: 1
        ╰─> [54 lines of output]
            running egg_info
            writing lib/PyYAML.egg-info/PKG-INFO
            writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
            writing top-level names to lib/PyYAML.egg-info/top_level.txt
            Traceback (most recent call last):
              File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                main()
              File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
                return hook(config_settings)
                       ^^^^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-2yelvxy6/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
                return self._get_build_requires(config_settings, requirements=['wheel'])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-2yelvxy6/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
                self.run_setup()
              File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-2yelvxy6/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
                exec(code, locals())
              File "<string>", line 288, in <module>
              File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-2yelvxy6/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
                return distutils.core.setup(**attrs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-2yelvxy6/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
                return run_commands(dist)
                       ^^^^^^^^^^^^^^^^^^
              File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-2yelvxy6/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
                dist.run_commands()
              File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-2yelvxy6/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
                self.run_command(cmd)
              File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-2yelvxy6/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
                super().run_command(command)
              File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-2yelvxy6/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-2yelvxy6/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 321, in run
                self.find_sources()
              File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-2yelvxy6/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
                mm.run()
              File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-2yelvxy6/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 551, in run
                self.add_defaults()
              File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-2yelvxy6/overlay/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
                sdist.add_defaults(self)
              File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-2yelvxy6/overlay/lib/python3.12/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
                super().add_defaults()
              File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-2yelvxy6/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
                self._add_defaults_ext()
              File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-2yelvxy6/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
                self.filelist.extend(build_ext.get_source_files())
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "<string>", line 204, in get_source_files
              File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-2yelvxy6/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
                raise AttributeError(attr)
            AttributeError: cython_sources
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error

      × Getting requirements to build wheel did not run successfully.
      │ exit code: 1
      ╰─> See above for output.

      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by Jampion-Zhang** [comment]
The problem was solved when I run `pip install "cython<3.0.0" && pip install --no-build-isolation pyyaml==6.0` from [this url](https://github.com/yaml/pyyaml/issues/724), but a new problem was find.

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting catboost
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d3/65/d55e51dab8f29b66827b4304eaf19f583506aaaf66413a8505a370181314/catboost-1.2.2.tar.gz (60.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting graphviz (from catboost)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/de/5e/fcbb22c68208d39edff467809d06c9d81d7d27426460ebc598e55130c1aa/graphviz-0.20.1-py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.0/47.0 kB 652.4 kB/s eta 0:00:00
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from catboost) (3.8.0)
Requirement already satisfied: numpy>=1.16.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from catboost) (1.26.1)
Requirement already satisfied: pandas>=0.24 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from catboost) (2.1.1)
Requirement already satisfied: scipy in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from catboost) (1.11.3)
Collecting plotly (from catboost)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/a8/07/72953cf70e3bd3a24cbc3e743e6f8539abe6e3e6d83c3c0c83426eaffd39/plotly-5.18.0-py3-none-any.whl (15.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.6/15.6 MB 55.4 MB/s eta 0:00:00
Requirement already satisfied: six in ./Library/Python/3.12/lib/python/site-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./Library/Python/3.12/lib/python/site-packages (from pandas>=0.24->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=0.24->catboost) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=0.24->catboost) (2023.3)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->catboost) (1.1.1)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->catboost) (4.43.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->catboost) (1.4.5)
Requirement already satisfied: packaging>=20.0 in ./Library/Python/3.12/lib/python/site-packages (from matplotlib->catboost) (23.2)
Requirement already satisfied: pillow>=6.2.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->catboost) (10.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib->catboost) (3.1.1)
Collecting tenacity>=6.2.0 (from plotly->catboost)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/f4/f1/990741d5bb2487d529d20a433210ffa136a367751e454214013b441c4575/tenacity-8.2.3-py3-none-any.whl (24 kB)
Building wheels for collected packages: catboost
  Building wheel for catboost (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for catboost (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [101 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-312
      creating build/lib.macosx-10.9-universal2-cpython-312/catboost
      copying catboost/monoforest.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost
      copying catboost/plot_helpers.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost
      copying catboost/metrics.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost
      copying catboost/version.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost
      copying catboost/text_processing.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost
      copying catboost/datasets.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost
      copying catboost/__init__.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost
      copying catboost/core.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost
      copying catboost/utils.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost
      copying catboost/dev_utils.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost
      creating build/lib.macosx-10.9-universal2-cpython-312/catboost/widget
      copying catboost/widget/__init__.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost/widget
      copying catboost/widget/metrics_plotter.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost/widget
      copying catboost/widget/ipythonwidget.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost/widget
      copying catboost/widget/callbacks.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost/widget
      creating build/lib.macosx-10.9-universal2-cpython-312/catboost/eval
      copying catboost/eval/catboost_evaluation.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost/eval
      copying catboost/eval/_fold_model.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost/eval
      copying catboost/eval/_readers.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost/eval
      copying catboost/eval/log_config.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost/eval
      copying catboost/eval/_splitter.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost/eval
      copying catboost/eval/__init__.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost/eval
      copying catboost/eval/execution_case.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost/eval
      copying catboost/eval/_fold_storage.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost/eval
      copying catboost/eval/factor_utils.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost/eval
      copying catboost/eval/utils.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost/eval
      copying catboost/eval/evaluation_result.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost/eval
      copying catboost/eval/_fold_models_handler.py -> build/lib.macosx-10.9-universal2-cpython-312/catboost/eval
      running build_ext
      Buildling _catboost with cmake and ninja
      target_platform=darwin-arm64. Building targets _catboost with PIC
      Running "cmake /private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-install-dkpwx_lj/catboost_daf4289c40eb454e9275d831f1a3b86d/catboost_all_src -B /private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-install-dkpwx_lj/catboost_daf4289c40eb454e9275d831f1a3b86d/build/temp.macosx-10.9-universal2-cpython-312 -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-install-dkpwx_lj/catboost_daf4289c40eb454e9275d831f1a3b86d/catboost_all_src/build/toolchains/clang.toolchain --log-level=VERBOSE -DCMAKE_POSITION_INDEPENDENT_CODE=On -DCATBOOST_COMPONENTS=python-package -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 -DHAVE_CUDA=no -DPython3_ROOT_DIR=/Library/Frameworks/Python.framework/Versions/3.12"
      CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
      CMake Error: CMAKE_ASM_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-opzsvjty/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 404, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-opzsvjty/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-opzsvjty/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-opzsvjty/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 731, in <module>
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-opzsvjty/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-opzsvjty/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-opzsvjty/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-opzsvjty/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-opzsvjty/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-opzsvjty/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 397, in run
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-opzsvjty/overlay/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-opzsvjty/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-opzsvjty/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-opzsvjty/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 332, in run
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-opzsvjty/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-opzsvjty/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-opzsvjty/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-build-env-opzsvjty/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 444, in run
        File "<string>", line 462, in build_with_cmake_and_ninja
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-install-dkpwx_lj/catboost_daf4289c40eb454e9275d831f1a3b86d/catboost_all_src/build/build_native.py", line 517, in build
          cmd_runner.run(cmake_cmd, env=build_environ)
        File "/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-install-dkpwx_lj/catboost_daf4289c40eb454e9275d831f1a3b86d/catboost_all_src/build/build_native.py", line 164, in run
          subprocess.run(cmd, check=True, **subprocess_run_kwargs)
        File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-install-dkpwx_lj/catboost_daf4289c40eb454e9275d831f1a3b86d/catboost_all_src', '-B', '/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-install-dkpwx_lj/catboost_daf4289c40eb454e9275d831f1a3b86d/build/temp.macosx-10.9-universal2-cpython-312', '-G', 'Ninja', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_TOOLCHAIN_FILE=/private/var/folders/fz/z1j7vyp50slgfstnpv6z6vl00000gn/T/pip-install-dkpwx_lj/catboost_daf4289c40eb454e9275d831f1a3b86d/catboost_all_src/build/toolchains/clang.toolchain', '--log-level=VERBOSE', '-DCMAKE_POSITION_INDEPENDENT_CODE=On', '-DCATBOOST_COMPONENTS=python-package', '-DCMAKE_OSX_DEPLOYMENT_TARGET=11.0', '-DHAVE_CUDA=no', '-DPython3_ROOT_DIR=/Library/Frameworks/Python.framework/Versions/3.12']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for catboost
Failed to build catboost
ERROR: Could not build wheels for catboost, which is required to install pyproject.toml-based projects

**Comment by andrey-khropov** [comment]
1) CatBoost tries to be built from the source distribution during installation because at the time of CatBoost release 1.2.2 Python 3.12 has not been officially released and there are no prebuilt wheels for CatBoost 1.2.2 for Python 3.12 because of that. 
Python 3.12 is supported in the master now and the next release 1.2.3 (which is expected to be released this week) will contain wheels for it.

2) Problem with Cython and PyYAML has been fixed in #2520.

3) Regarding the last problem with building from the source code. 

> CMake Error: CMake was unable to find a build program corresponding to "Ninja". 

You have to [set up a build environment](https://catboost.ai/en/docs/installation/python-installation-method-build-from-source-linux-macos#dependencies-and-requirements) in order to build from the source code.

So your choices are:

1) Use CatBoost with python <= 3.11 for now until CatBoost release 1.2.3
2) Build the python package from the source code from the recent master (after the fix for #2520) using [these instructions](https://catboost.ai/en/docs/installation/python-installation-method-build-from-source) (but it is generally less recommended for end users as releases are more stable)

**Comment by gsgxnet** [comment]
At this time there is not CatBoost 1.2.3 available at conda-forge. 
```
conda search catboost | grep '1.2.[23]'
catboost                       1.2.2 py310hbe9552e_0  conda-forge         
catboost                       1.2.2 py311h267d04e_0  conda-forge         
catboost                       1.2.2  py38h10201cd_0  conda-forge         
catboost                       1.2.2  py39h2804cbe_0  conda-forge   
```
Still only 1.2.2.
Any plans for a short term release of 1.2.3?

**Comment by einarwar** [comment]
Any updates on this @andrey-khropov ?

**Comment by PrimozGodec** [comment]
Is there any plan to make a new release soon? Would you like any help with it? We would benefit from having Python 3.12. wheels on PyPi.

**Comment by andrey-khropov** [comment]
> Is there any plan to make a new release soon? Would you like any help with it? We would benefit from having Python 3.12. wheels on PyPi.

https://github.com/catboost/catboost/discussions/2592
