### ISSUE TITLE
Error during installing in RStudio

### ISSUE THREAD

**Issue by treshomg** [catboost/catboost#26]
I have the next error:

Downloading GitHub repo catboost/catboost@master
from URL https://api.github.com/repos/catboost/catboost/zipball/master
Installing catboost
"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/yahooomg/AppData/Local/Temp/RtmpqyHggA/devtools24941ce5572/catboost-catboost-7e4ba38/catboost/R-package"  \
  --library="C:/Program Files/R/R-3.4.0/library" --install-tests 

* installing *source* package 'catboost' ...
** libs
  running 'src/Makefile.win' ...
/cygdrive/c/Users/yahooomg/AppData/Local/Temp/RtmpqyHggA/devtools24941ce5572/catboost-catboost-7e4ba38/catboost/R-package/src/../../../ya.bat make -r -o ../../..
2017-07-19T08:15:12.209000 [MainThread] Info: Attention! Using system user-defined compiler: cl.exe (check CC and CXX env vars).
2017-07-19T08:15:12.210000 [MainThread] Info: will fetch 'YMake' from sandbox

Traceback (most recent call last):
  File "devtools/ya/entry/entry.py", line 157, in exit_interceptor
    func()
  File "devtools/ya/entry/entry.py", line 56, in <lambda>
    return lambda: wrapper(f)
  File "devtools/ya/entry/entry.py", line 121, in f
    res = func()
  File "devtools/ya/entry/entry.py", line 250, in <lambda>
    run_main = lambda: do_main(args)
  File "devtools/ya/entry/entry.py", line 49, in do_main
    res = handler.handle(handler, args, prefix=['ya'])
  File "devtools/ya/core/handler.py", line 157, in handle
    return handler.handle(self, args[1:], prefix + [name])
  File "devtools/ya/core/dispatch.py", line 37, in handle
    return self.command().handle(root_handler, args, prefix)
  File "devtools/ya/core/handler.py", line 337, in handle
    return self._action(params)
  File "devtools/ya/app.py", line 64, in helper
    return action(ctx.params)
  File "devtools/ya/build/build_handler.py", line 11, in do_ya_make
    return YaMake(params, app_ctx).go()
  File "devtools/ya/build/ya_make.py", line 519, in __init__
    self.ctx = Context(self.opts, app_ctx=app_ctx, graph=graph, tests=tests, configure_errors=configure_errors, make_files=make_files)
  File "devtools/ya/build/ya_make.py", line 347, in __init__
    self.graph, self.tests, self.configure_errors, self.make_files = _build_graph_and_tests(self.opts, app_ctx)
  File "devtools/ya/build/ya_make.py", line 282, in _build_graph_and_tests
    graph, tests, gh, make_files = lg.build_graph_and_tests(opts, check=True, ev_listener=ev_listener)
  File "devtools/ya/build/graph.py", line 1372, in build_graph_and_tests
    real_ymake_bin = ct.tool('ymake')
  File "devtools/ya/core/tools.py", line 214, in tool
    return toolchain.find(name, with_params, for_platform)
  File "devtools/ya/core/tools.py", line 152, in find
    executable = cur_bottle[executable_name]  # if executable_name is None it's Ok
  File "devtools/ya/core/tools.py", line 60, in __getitem__
    path = self.resolve()
  File "devtools/ya/core/tools.py", line 42, in resolve
    return self.__fetcher.fetch_if_need(self.__match, tared, binname).where
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 286, in fetch_if_need
    self.__c[key] = self._fetch_if_need(*args, **kwargs)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 296, in _fetch_if_need
    if self._fetch(name, tared, lambda x: name.lower() in x.lower(), binname):
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 276, in _fetch
    _install(self.where, do_install)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 71, in _install
    func(install_guard)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 239, in do_install
    http_client.download_file(url=config.mapping()["resources"][by_platform[best]["id"]], path=download_to)
  File "devtools/ya/exts/retry.py", line 49, in wrapper
    return retry(proxy_func, **retry_kwargs)
  File "devtools/ya/exts/retry.py", line 22, in retry
    return func()
  File "devtools/ya/exts/retry.py", line 48, in <lambda>
    proxy_func = lambda: func(*args, **kwargs)
  File "devtools/ya/exts/http_client.py", line 56, in download_file
    res = urllib2.urlopen(request, timeout=timeout)
  File "contrib/tools/python/src/Lib/urllib2.py", line 154, in urlopen
  File "contrib/tools/python/src/Lib/urllib2.py", line 431, in open
  File "contrib/tools/python/src/Lib/urllib2.py", line 449, in _open
  File "contrib/tools/python/src/Lib/urllib2.py", line 409, in _call_chain
  File "contrib/tools/python/src/Lib/urllib2.py", line 1227, in http_open
  File "contrib/tools/python/src/Lib/urllib2.py", line 1194, in do_open
  File "contrib/tools/python/src/Lib/httplib.py", line 1057, in request
  File "contrib/tools/python/src/Lib/httplib.py", line 1097, in _send_request
  File "contrib/tools/python/src/Lib/httplib.py", line 1053, in endheaders
  File "contrib/tools/python/src/Lib/httplib.py", line 889, in _send_output
**UnicodeDecodeError:** 'ascii' codec can't decode byte 0xcf in position 25: ordinal not in range(128)
make: *** [libcatboostr.dll] Error 1
Предупреждение: работающая команда 'make --no-print-directory -f "Makefile.win"' имеет статус 2
ERROR: compilation failed for package 'catboost'
* removing 'C:/Program Files/R/R-3.4.0/library/catboost'
Installation failed: Command failed (1)

Can anybody help with this?

**Comment by treshomg** [comment]
So, nobody can help with this?

**Comment by ferrr** [comment]
Sorry for not answering earlier!

We suspect that you have hostname with non-ASCII symbols. Fix is on the way, but for now you can try to change your hostname :)

**Comment by treshomg** [comment]
Thank you for answer, it helped me. But now I have the next error:

> devtools::install_github('catboost/catboost', subdir = 'catboost/R-package')
Downloading GitHub repo catboost/catboost@master
from URL https://api.github.com/repos/catboost/catboost/zipball/master
Installing catboost
"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/yahooomg/AppData/Local/Temp/RtmpYvFoTG/devtools23a46b5e296/catboost-catboost-e8be249/catboost/R-package"  \
  --library="C:/Program Files/R/R-3.4.0/library" --install-tests 

* installing *source* package 'catboost' ...
** libs
  running 'src/Makefile.win' ...
/cygdrive/c/Users/yahooomg/AppData/Local/Temp/RtmpYvFoTG/devtools23a46b5e296/catboost-catboost-e8be249/catboost/R-package/src/../../../ya.bat make -r -o ../../..
2017-07-22T15:26:35.491000 [MainThread] Info: Attention! Using system user-defined compiler: cl.exe (check CC and CXX env vars).

Config was not generated due to errors in C:\Users\yahooomg\AppData\Local\Temp\RtmpYvFoTG\devtools23a46b5e296\catboost-catboost-e8be249\build\ymake_conf.py
**ERROR:root:Could not detect cxx compiler, error is [Error 2]** 

make: *** [all] Error 1
Предупреждение: работающая команда 'make --no-print-directory -f "Makefile.win"' имеет статус 2
ERROR: compilation failed for package 'catboost'
* removing 'C:/Program Files/R/R-3.4.0/library/catboost'
Installation failed: Command failed (1)

**Comment by Mrugankakarte** [comment]
I think it is compiler issue.

Check if you visual studio installed
* Visual Studio with C++ build [tools](http://landinghub.visualstudio.com/visual-cpp-build-tools) (check #30)

**Comment by treshomg** [comment]
Thanks a lot, finally done
