### ISSUE TITLE
Pool Creation Error - TypeError: must be real number, not NoneType

### ISSUE THREAD

**Issue by irmakyucel** [catboost/catboost#2613]
Problem: After using a loaded model using catboost load, in the model.predict_proba() function I am facing the error below: 
Initially I thought it was about automatic pool creation of catboost so I explicitly created the Pool() but faced the exact same error in that function.

Traceback (most recent call last):
  File "/argo/staging/script", line 14, in <module>
    model_predict(date)
  File "/opt/workflow/app/pipeline/skorlama.py", line 22, in model_predict
    **pool = Pool(data=df_skor.values, label=None, cat_features=model.get_cat_feature_indices())**
  File "/usr/local/lib64/python3.9/site-packages/catboost/core.py", line 645, in __init__
    self._init(data, label, cat_features, text_features, embedding_features, pairs, weight,
  File "/usr/local/lib64/python3.9/site-packages/catboost/core.py", line 1222, in _init
    self._init_pool(data, label, cat_features, text_features, embedding_features, pairs, weight,
  File "_catboost.pyx", line 3763, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 3827, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 3736, in _catboost._PoolBase._init_objects_order_layout_pool
  File "_catboost.pyx", line 3269, in _catboost._set_data
  File "_catboost.pyx", line 3222, in _catboost._set_data_from_generic_matrix
  File "_catboost.pyx", line 2238, in _catboost.get_cat_factor_bytes_representation
  File "_catboost.pyx", line 1857, in _catboost.get_id_object_bytes_string_representation
TypeError: must be real number, not NoneType

catboost version: tried 1.0.6, 1.2.0 and 1.2.3
Operating System: Linux
CPU: yes
GPU: no

**Comment by nicktgr15** [comment]
Hi - I have the same issue 

Adding a `None` in the cat feature column will through that error 

e.g. 

```
train_data = [[None, 3],
              [4, 1],
              [8, 1],
              [9, 1]]
train_labels = [0, 0, 1, 1]
``` 

A `None` for the numerical feature is handled correctly. 

Is that the intended behaviour ? Also if a `None` for a categorical feature is replaced by e.g. empty string - would that allow the model to generalise well when that particular feature is missing during inference?

**Comment by andrey-khropov** [comment]
> Is that the intended behaviour ?

You can't use `None` in categorical features because there's no universal representation for missing categorical values in all APIs.
For python where basically all values are nullable (can be `None`) it is possible, but in other APIs, for example, when you load data from a dsv file, you have no universal way to specify missing values for categorical features. 

> Also if a None for a categorical feature is replaced by e.g. empty string - would that allow the model to generalise well when that particular feature is missing during inference?

You should apply similar logic during training and inference. If you have missing values during training and you transform them to some fixed value then do the same during inference, then it will be consistent and will work as intended.

**Comment by andrey-khropov** [comment]
As no clarifying information has been provided and a lot of time has passed, I'm closing this issue.
