### ISSUE TITLE
Numpy 2.0 support status?

### ISSUE THREAD

**Issue by ethanglaser** [catboost/catboost#2671]
Problem:
- `ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject` when reaching `import catboost as cb` with numpy 2.0

catboost version:
- version not specified during installation, defaults to 1.2.5

Operating System:
- has occurred on every system that I have attempted (both windows and linux)

I am migrating code to numpy 2.0 and currently validating with numpy 2.0.0rc2. A script that uses catboost fails with the error message indicated above. Steps to reproduce:

`conda create -n numpy2 python=3.12`
`conda activate numpy2`
`pip install numpy==2.0.0rc2`
`pip install catboost`
`python -c "import catboost as cb"`

I have also faced this issue with python 3.11 and numpy 2.0.0rc1. I was under the impression that catboost is supporting numpy 2.0 already, but perhaps this is not the case? Otherwise, please let me know where I may be going wrong. Thanks.

**Comment by jameslamb** [comment]
@andrey-khropov just noting for your planning purposes... the target release date for `numpy` 2.x is June 16th: https://github.com/numpy/numpy/issues/24300#issuecomment-2125643448

**Comment by rgommers** [comment]
> We'll have to investigate whether it will be possible to use `numpy` 2.x during compilation and be able to retain binary compatibility when using built CatBoost package with `numpy` 1.x (because, obviously, `numpy` 1.x will have to be supported for quite some time).

This is supported by default by NumPy 2.0, you don't have to do anything for it beyond building against numpy 2.0 (or right now, a numpy release candidate). Please see https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-0-specific-advice for more details.

**Comment by rohitblpprajapat** [comment]
facing similar issue

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[4], [line 1](vscode-notebook-cell:?execution_count=4&line=1)
----> [1](vscode-notebook-cell:?execution_count=4&line=1) from catboost import CatBoostRegressor
      [3](vscode-notebook-cell:?execution_count=4&line=3) dataset = np.array([[1,4,5,6],[4,5,6,7],[30,40,50,60],[20,15,85,60]])
      [4](vscode-notebook-cell:?execution_count=4&line=4) train_labels = [1.2,3.4,9.5,24.5]

File d:\AMEX Data Science Competition\env\Lib\site-packages\catboost\__init__.py:1
----> [1](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/__init__.py:1) from .core import (
      [2](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/__init__.py:2)     FeaturesData, EFstrType, EShapCalcType, EFeaturesSelectionAlgorithm, EFeaturesSelectionGrouping,
      [3](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/__init__.py:3)     Pool, CatBoost, CatBoostClassifier, CatBoostRegressor, CatBoostRanker, CatBoostError, cv, sample_gaussian_process, train,
      [4](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/__init__.py:4)     sum_models, _have_equal_features, to_regressor, to_classifier, to_ranker, MultiRegressionCustomMetric,
      [5](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/__init__.py:5)     MultiRegressionCustomObjective, MultiTargetCustomMetric, MultiTargetCustomObjective
      [6](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/__init__.py:6) )  # noqa
      [7](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/__init__.py:7) from .version import VERSION as __version__  # noqa
      [8](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/__init__.py:8) __all__ = [
      [9](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/__init__.py:9)     'FeaturesData', 'EFstrType', 'EShapCalcType', 'EFeaturesSelectionAlgorithm', 'EFeaturesSelectionGrouping',
     [10](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/__init__.py:10)     'Pool', 'CatBoost', 'CatBoostClassifier', 'CatBoostRegressor', 'CatBoostRanker', 'CatboostError',
   (...)
     [13](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/__init__.py:13)     'MultiTargetCustomMetric', 'MultiTargetCustomObjective'
     [14](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/__init__.py:14) ]

File d:\AMEX Data Science Competition\env\Lib\site-packages\catboost\core.py:45
     [40](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/core.py:40)         pass
     [42](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/core.py:42) import scipy.sparse
---> [45](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/core.py:45) from .plot_helpers import save_plot_file, try_plot_offline, OfflineMetricVisualizer
     [46](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/core.py:46) from . import _catboost
     [47](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/core.py:47) from .metrics import BuiltinMetric

File d:\AMEX Data Science Competition\env\Lib\site-packages\catboost\plot_helpers.py:5
      [2](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/plot_helpers.py:2) import os
      [3](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/plot_helpers.py:3) import warnings
----> [5](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/plot_helpers.py:5) from . import _catboost
      [6](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/plot_helpers.py:6) fspath = _catboost.fspath
      [9](file:///D:/AMEX%20Data%20Science%20Competition/env/Lib/site-packages/catboost/plot_helpers.py:9) def try_plot_offline(figs):

File _catboost.pyx:1, in init _catboost()

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by adrinjalali** [comment]
Ping on this one since numpy2 is released now. Would be nice to have builds against numpy2 out there.

**Comment by andrey-khropov** [comment]
> Ping on this one since numpy2 is released now. Would be nice to have builds against numpy2 out there.



> Ping on this one since numpy2 is released now. Would be nice to have builds against numpy2 out there.

I'm working on it.

**Comment by xhc926** [comment]
> facing similar issue
> 
> ValueError Traceback (most recent call last) Cell In[4], line 1 ----> 1 from catboost import CatBoostRegressor 3 dataset = np.array([[1,4,5,6],[4,5,6,7],[30,40,50,60],[20,15,85,60]]) 4 train_labels = [1.2,3.4,9.5,24.5]
> 
> File d:\AMEX Data Science Competition\env\Lib\site-packages\catboost__init__.py:1 ----> 1 from .core import ( 2 FeaturesData, EFstrType, EShapCalcType, EFeaturesSelectionAlgorithm, EFeaturesSelectionGrouping, 3 Pool, CatBoost, CatBoostClassifier, CatBoostRegressor, CatBoostRanker, CatBoostError, cv, sample_gaussian_process, train, 4 sum_models, _have_equal_features, to_regressor, to_classifier, to_ranker, MultiRegressionCustomMetric, 5 MultiRegressionCustomObjective, MultiTargetCustomMetric, MultiTargetCustomObjective 6 ) # noqa 7 from .version import VERSION as **version** # noqa 8 **all** = [ 9 'FeaturesData', 'EFstrType', 'EShapCalcType', 'EFeaturesSelectionAlgorithm', 'EFeaturesSelectionGrouping', 10 'Pool', 'CatBoost', 'CatBoostClassifier', 'CatBoostRegressor', 'CatBoostRanker', 'CatboostError', (...) 13 'MultiTargetCustomMetric', 'MultiTargetCustomObjective' 14 ]
> 
> File d:\AMEX Data Science Competition\env\Lib\site-packages\catboost\core.py:45 40 pass 42 import scipy.sparse ---> 45 from .plot_helpers import save_plot_file, try_plot_offline, OfflineMetricVisualizer 46 from . import _catboost 47 from .metrics import BuiltinMetric
> 
> File d:\AMEX Data Science Competition\env\Lib\site-packages\catboost\plot_helpers.py:5 2 import os 3 import warnings ----> 5 from . import _catboost 6 fspath = _catboost.fspath 9 def try_plot_offline(figs):
> 
> File _catboost.pyx:1, in init _catboost()
> 
> ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Exactly this frustrating problem...and there's an opinion that we downgrade numpy to version before 1.15. Trying to verify it, still.

**Comment by xhc926** [comment]
Guys I've solved this problem partially. First I downgraded my numpy package to 1.xx, say, 1.25(ensure the version isn't outdated), and then import catboost(at least latest version is compatible, so this is easy), and finally compile your code is OK. From these results I suppose numpy 2.xx cannot work well with some other related packages, so downgrading numpy seems a must.

**Comment by RubTalha** [comment]
https://stackoverflow.com/questions/78650222/valueerror-numpy-dtype-size-changed-may-indicate-binary-incompatibility-expec

**Comment by andrey-khropov** [comment]
> > Ping on this one since numpy2 is released now. Would be nice to have builds against numpy2 out there.
> 
> I'm working on it.

Unfortunately it is taking longer than expected because we're using Cython 0.29.x and it produces code incompatible with NumPy 2.0 . I'm trying to upgrade to Cython 3.0.x but it introduces a bunch of different issues.

**Comment by Volume999** [comment]
Is it possible to specify the numpy dependency in this project?

**Comment by andrey-khropov** [comment]
> Is it possible to specify the numpy dependency in this project? So that builds don't break accidentally

I've committed the restriction of `numpy` versions to < 2.0 : https://github.com/catboost/catboost/commit/4b1b8ae023367fdbc69db18306252e6730163e34, it will be included in the next release that is expected very soon.

For now you can install `numpy` with a version < 2.0 explicitly before installing `catboost`.

**Comment by sunitab55** [comment]
> > Is it possible to specify the numpy dependency in this project? So that builds don't break accidentally
> 
> I've committed the restriction of `numpy` versions to < 2.0 : [4b1b8ae](https://github.com/catboost/catboost/commit/4b1b8ae023367fdbc69db18306252e6730163e34), it will be included in the next release that is expected very soon.
> 
> For now you can install `numpy` with a version < 2.0 explicitly before installing `catboost`.

This finally worked for me! I downgraded the numpy library but left the catboost untouched. After reading your comment, I uninstalled both, installed numpy <3 first and then catboost and it works now. Thank You

**Comment by NaymahAdnan** [comment]
> > > Is it possible to specify the numpy dependency in this project? So that builds don't break accidentally
> > 
> > 
> > I've committed the restriction of `numpy` versions to < 2.0 : [4b1b8ae](https://github.com/catboost/catboost/commit/4b1b8ae023367fdbc69db18306252e6730163e34), it will be included in the next release that is expected very soon.
> > For now you can install `numpy` with a version < 2.0 explicitly before installing `catboost`.
> 
> This finally worked for me! I downgraded the numpy library but left the catboost untouched. After reading your comment, I uninstalled both, installed numpy <3 first and then catboost and it works now. Thank You

Hi, Did you have you downgrade your python version to work with numpy < 2.0? I am on Python 3.12 and this give me errors when I uninstall numpy and try to install a version < 2.

**Comment by andrey-khropov** [comment]
> Hi, Did you have you downgrade your python version to work with numpy < 2.0? I am on Python 3.12 and this give me errors when I uninstall numpy and try to install a version < 2.

What kind of errors? I can successfully install and use catboost with numpy < 2 with python 3.12.x.

**Comment by NaymahAdnan** [comment]
> > Hi, Did you have you downgrade your python version to work with numpy < 2.0? I am on Python 3.12 and this give me errors when I uninstall numpy and try to install a version < 2.
> 
> What kind of errors? I can successfully install and use catboost with numpy < 2 with python 3.12.x.

Let me explain my problem in better terms: I am trying to use the .cbm file of my catboost model from a .net environment, using the catboostmodel.dll. But since my model is not loading using '[DllImport("catboostmodel.dll", EntryPoint = "LoadFullModelFromFile")]' I decided to just check from within python that my .cbm file is ok. 

This .cbm file was generated with the latest python, numpy and catboost packages. 

_When I run a python script to load the model I get the following: ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject_

**From what I read here, I will have to downgrade Python (to 3.9), downgrade numpy (Install 1.22.4), install catboost again, and then regenerate my model .cbm file? Is my understanding correct?**

If only ONNX was supported with categorical features I would not have had to go through this.....hoping I can become a contributor one day! Thanks in advance...

**Comment by andrey-khropov** [comment]
> > > Hi, Did you have you downgrade your python version to work with numpy < 2.0? I am on Python 3.12 and this give me errors when I uninstall numpy and try to install a version < 2.
> > 
> > 
> > What kind of errors? I can successfully install and use catboost with numpy < 2 with python 3.12.x.
> 
> Let me explain my problem in better terms: I am trying to use the .cbm file of my catboost model from a .net environment, using the catboostmodel.dll. But since my model is not loading using '[DllImport("catboostmodel.dll", EntryPoint = "LoadFullModelFromFile")]'

Can you create a separate issue with a detailed explanation for that?

> I decided to just check from within python that my .cbm file is ok.
> 
> This .cbm file was generated with the latest python, numpy and catboost packages.
> 
> _When I run a python script to load the model I get the following: ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject_

Do I understand correctly that you trained the model with (python X, numpy Y, catboost Z) versions and then get this error when loading the trained model with the same (python X, numpy Y, catboost Z) combination?

Can you provide a reproducible example how you set up the environment?

> 
> **From what I read here, I will have to downgrade Python (to 3.9), downgrade numpy (Install 1.22.4), install catboost again, and then regenerate my model .cbm file? Is my understanding correct?**

I don't see python 3.9 mentioned anywhere before in this issue. You don't need a different python version. Any supported python version (3.7.x - 3.12.x) will do. The only thing necessary is to ensure that numpy version is 'numpy (>=1.16.0, <2.0)' .

**Comment by NaymahAdnan** [comment]
> > > > Hi, Did you have you downgrade your python version to work with numpy < 2.0? I am on Python 3.12 and this give me errors when I uninstall numpy and try to install a version < 2.
> > > 
> > > 
> > > What kind of errors? I can successfully install and use catboost with numpy < 2 with python 3.12.x.
> > 
> > 
> > Let me explain my problem in better terms: I am trying to use the .cbm file of my catboost model from a .net environment, using the catboostmodel.dll. But since my model is not loading using '[DllImport("catboostmodel.dll", EntryPoint = "LoadFullModelFromFile")]'
> 
> Can you create a separate issue with a detailed explanation for that?
> 
> > I decided to just check from within python that my .cbm file is ok.
> > This .cbm file was generated with the latest python, numpy and catboost packages.
> > _When I run a python script to load the model I get the following: ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject_
> 
> Do I understand correctly that you trained the model with (python X, numpy Y, catboost Z) versions and then get this error when loading the trained model with the same (python X, numpy Y, catboost Z) combination?
> 
> Can you provide a reproducible example how you set up the environment?
> 
> > **From what I read here, I will have to downgrade Python (to 3.9), downgrade numpy (Install 1.22.4), install catboost again, and then regenerate my model .cbm file? Is my understanding correct?**
> 
> I don't see python 3.9 mentioned anywhere before in this issue. You don't need a different python version. Any supported python version (3.7.x - 3.12.x) will do. The only thing necessary is to ensure that numpy version is 'numpy (>=1.16.0, <2.0)' .

When I try to downgrade numpy to 1.9 with python 3.12, i get this error: **ModuleNotFoundError: No module named 'imp'**

**Comment by NaymahAdnan** [comment]
I am really not winning: Just some more backinfo - I need to use catboost .cbm file but i keep getting the error 'Expected 96 from C header, got 88 from PyObject' on model import. To solve this I have attempted the ffg:

**python --version**
Python 3.12.5

**>pip list**
Package                   Version
------------------------- --------------
anyio                     4.4.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
astroid                   1.6.6
asttokens                 2.4.1
async-lru                 2.0.4
attrs                     24.2.0
babel                     2.16.0
beautifulsoup4            4.12.3
bleach                    6.1.0
blinker                   1.8.2
bottle                    0.12.25
catboost                  1.2.5
certifi                   2024.7.4
cffi                      1.17.0
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
coloredlogs               15.0.1
comm                      0.2.2
conan                     2.6.0
contourpy                 1.2.1
cycler                    0.12.1
debugpy                   1.8.5
decorator                 5.1.1
defusedxml                0.7.1
deprecation               2.0.7
distro                    1.1.0
et-xmlfile                1.1.0
executing                 2.0.1
fasteners                 0.19
fastjsonschema            2.20.0
Flask                     3.0.3
flatbuffers               24.3.25
fonttools                 4.53.1
fqdn                      1.5.1
future                    0.16.0
graphviz                  0.20.3
h11                       0.14.0
httpcore                  1.0.5
httpx                     0.27.2
humanfriendly             10.0
idna                      3.8
ipykernel                 6.29.5
ipython                   8.26.0
ipywidgets                8.1.5
isoduration               20.11.0
isort                     5.13.2
itsdangerous              2.2.0
jedi                      0.19.1
Jinja2                    3.1.4
joblib                    1.4.2
json5                     0.9.25
jsonpointer               3.0.0
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
jupyter                   1.1.0
jupyter_client            8.6.2
jupyter-console           6.6.3
jupyter_core              5.7.2
jupyter-events            0.10.0
jupyter-lsp               2.2.5
jupyter_server            2.14.2
jupyter_server_terminals  0.5.3
jupyterlab                4.2.5
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.3
jupyterlab_widgets        3.0.13
kiwisolver                1.4.5
lazy-object-proxy         1.10.0
lightgbm                  4.5.0
MarkupSafe                2.1.5
matplotlib                3.9.2
matplotlib-inline         0.1.7
mccabe                    0.7.0
mistune                   3.0.2
mpmath                    1.3.0
nbclient                  0.10.0
nbconvert                 7.16.4
nbformat                  5.10.4
nest-asyncio              1.6.0
node-semver               0.6.1
notebook                  7.2.2
notebook_shim             0.2.4
numpy                     2.1.0
onnx                      1.16.2
onnxconverter-common      1.14.0
onnxruntime               1.19.0
openpyxl                  3.1.5
overrides                 7.7.0
packaging                 24.1
pandas                    2.2.2
pandocfilters             1.5.1
parso                     0.8.4
patch                     1.16
patch-ng                  1.17.4
pillow                    10.4.0
pip                       24.2
platformdirs              4.2.2
plotly                    5.23.0
pluginbase                0.7
prometheus_client         0.20.0
prompt_toolkit            3.0.47
protobuf                  3.20.2
psutil                    6.0.0
pure_eval                 0.2.3
pycparser                 2.22
Pygments                  2.18.0
PyJWT                     1.7.1
pylint                    1.8.4
pyparsing                 3.1.2
pyreadline3               3.4.1
python-dateutil           2.9.0.post0
python-json-logger        2.0.7
pytz                      2024.1
pywin32                   306
pywinpty                  2.0.13
PyYAML                    6.0.2
pyzmq                     26.2.0
referencing               0.35.1
requests                  2.32.3
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.20.0
scikit-learn              1.5.1
scipy                     1.14.1
seaborn                   0.13.2
Send2Trash                1.8.3
setuptools                74.0.0
six                       1.16.0
skl2onnx                  1.17.0
sniffio                   1.3.1
soupsieve                 2.6
stack-data                0.6.3
sympy                     1.13.2
tenacity                  9.0.0
terminado                 0.18.1
threadpoolctl             3.5.0
tinycss2                  1.3.0
tornado                   6.4.1
tqdm                      4.66.5
traitlets                 5.14.3
types-python-dateutil     2.9.0.20240821
tzdata                    2024.1
uri-template              1.3.0
urllib3                   1.26.19
wcwidth                   0.2.13
webcolors                 24.8.0
webencodings              0.5.1
websocket-client          1.8.0
Werkzeug                  3.0.4
widgetsnbextension        4.0.13
wrapt                     1.16.0
xgboost                   2.1.1

**>pip install numpy==1.22.4**
Collecting numpy==1.22.4
  Using cached numpy-1.22.4.zip (11.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Nadnan\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Nadnan\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Nadnan\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\Users\Nadnan\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Nadnan\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\Nadnan\AppData\Local\Temp\pip-build-env-eq0pags1\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\Nadnan\AppData\Local\Temp\pip-build-env-eq0pags1\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\Nadnan\AppData\Local\Temp\pip-build-env-eq0pags1\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.



_Can any kind person see what I have done wrong? I did too try downgrading python to 3.9, installing numpy <2, importing catboost but still got the same error._

**Comment by andrey-khropov** [comment]
> > Is it possible to specify the numpy dependency in this project? So that builds don't break accidentally
> 
> I've committed the restriction of `numpy` versions to < 2.0 : [4b1b8ae](https://github.com/catboost/catboost/commit/4b1b8ae023367fdbc69db18306252e6730163e34), it will be included in the next release that is expected very soon.
> 
> For now you can install `numpy` with a version < 2.0 explicitly before installing `catboost`.

CatBoost 1.2.6 with this specification for numpy dependency has been released so it is no longer necessary to change numpy version by hand.

Version 2.0.x support is still work in progress.

**Comment by filbranden** [comment]
Any updates on support for numpy 2? Last comment indicates it's work in progress but there doesn't seem to be any other tracker than this one. Thanks!

**Comment by andrey-khropov** [comment]
> Any updates on support for numpy 2?

It is still in progress, I expect to finish this week. 

> there doesn't seem to be any other tracker than this one.

This issue is the right one, as you can see it is still open.

**Comment by jakirkham** [comment]
Apologies if this is already known, didn't see it in the thread

IIUC CatBoost uses pybind11. For NumPy 2 support, [pybind11 version `2.12.0+`]( https://github.com/pybind/pybind11/releases/tag/v2.12.0 ) is needed. More details in this PR: https://github.com/pybind/pybind11/pull/5050

**Comment by filbranden** [comment]
Hi 👋 

Any updates on numpy 2 support? Last update indicate it was close, but it's been a few weeks

Thanks!

**Comment by filbranden** [comment]
Kindly asking whether there are any updates on progress for numpy 2 support

Thanks!

**Comment by andrey-khropov** [comment]
> Kindly asking whether there are any updates on progress for numpy 2 support
> 
> Thanks!

It's almost ready but unfortunately I have been busy with other things. I expect to return to it and finish next week.

**Comment by g0bel1n** [comment]
Hi guys, any updates/ETA for numpy 2.0 support ? Also, maybe someone has a hotfix to use models trained under numpy <2.0 in a numpy > 2.0 env ?

Thanks for the hard work :)

**Comment by andrey-khropov** [comment]
> Hi guys, any updates/ETA for numpy 2.0 support ? 

I'll try to finish this in two weeks.

**Comment by xmatthias** [comment]
Any progress? 
Catboost is unfortunately the last dependency preventing us from updating numpy - and with that included also supporting 3.13.

**Comment by gianfa** [comment]
@andrey-khropov I'm cheering for you on this! 🚀

**Comment by antonstor** [comment]
Any progress on this? 🙏

**Comment by antonstor** [comment]
@georgthegreat would you have any awareness of progress on supporting numpy 2.0?
We're anxiously waiting, would appreciate any communication on progress and if we should hold our breath.

**Comment by georgthegreat** [comment]
No, unfortunately I do not have any details regarding the update.

**Comment by btschroer** [comment]
Thanks for pushing `numpy-2.0` support. Really important feature.

**Comment by andrey-khropov** [comment]
> Any progress on this? 🙏

Stiil working on it with the highest priority.

**Comment by antonstor** [comment]
Hi @andrey-khropov from your work so far do you have a sense of how much work is still left? 2 weeks? 1 month? 2 months?

I am trying to decide if I need to pursue a workaround on my end.
Guidance on the timeline would be highly appreciated.

Thank you so much for your work on this!

**Comment by andrey-khropov** [comment]
> Hi [@andrey-khropov](https://github.com/andrey-khropov) from your work so far do you have a sense of how much work is still left? 2 weeks? 1 month? 2 months?
> 
> I am trying to decide if I need to pursue a workaround on my end. Guidance on the timeline would be highly appreciated.
> 
> Thank you so much for your work on this!

Sorry for the delay. I've finally been able to build CatBoost with Numpy 2 successfully. I will make the necessary commits within a couple of days.

**Comment by btschroer** [comment]
@andrey-khropov this is great news. Thanks a lot for pushing this 👍 .

**Comment by filbranden** [comment]
Looks like all the changes needed for numpy 2 have been merged to trunk, correct?

Are there plans to release a new package version soon, so that we could get a numpy 2 compatible catboost from PyPI directly?

Thank you!

**Comment by jimbow973** [comment]
i built a wheel from master branch under windows, i modified setup.py to change numpy requirement (still < 2.0). But when testing this wheel it doesn't work properly... Can't wait to have a clean numpy 2.x compatible release.

**Comment by andrey-khropov** [comment]
> i built a wheel from master branch under windows, i modified setup.py to change numpy requirement (still < 2.0). But when testing this wheel it doesn't work properly... 

Since https://github.com/catboost/catboost/commit/b6fd136e3fc173bc335ae65fb976f27b550f24ad Numpy 2.x is fully supported, including with Python 3.13.

> Can't wait to have a clean numpy 2.x compatible release.

The release will be very soon.

**Comment by celestinoxp** [comment]
@andrey-khropov Testing latest commit from catboost to work with numy 2... It works It works!!!!!

**Comment by chaudharyachint08** [comment]
Thanks @celestinoxp @andrey-khropov I am installing from latest commit. Hope Numpy 2.x compatibility would be released soon on PyPI

**Comment by romaup** [comment]
@andrey-khropov kindly ask you to release Numpy 2.x support in pypi ASAP
Currently, all the projects with a catboost as a 3rd party dependency require a full kernel restart in Colab, which is a kind of a blocker to use catboost in a DS tools like AutoML, AutoFE libraries etc
We do have this issue in [Upgini](https://github.com/upgini/upgini)

> > i built a wheel from master branch under windows, i modified setup.py to change numpy requirement (still < 2.0). But when testing this wheel it doesn't work properly...
> 
> Since [b6fd136](https://github.com/catboost/catboost/commit/b6fd136e3fc173bc335ae65fb976f27b550f24ad) Numpy 2.x is fully supported, including with Python 3.13.
> 
> > Can't wait to have a clean numpy 2.x compatible release.
> 
> The release will be very soon.

**Comment by andrey-khropov** [comment]
CatBoost 1.2.8 has been released on PyPI. Conda release will be ready in several hours.
