### ISSUE TITLE
Signal 11 (SEGV) crash due to invalid memory access

### ISSUE THREAD

**Issue by hunts** [catboost/catboost#2687]
Problem: signal 11 (SEGV) crash due to invalid memory access
catboost version: 1.2
Operating System: Debian Bookworm (Linux 6.6.30)
CPU: AMD EPYC 7713 64-Core Processor
GPU: N/A
CatBoost Rust Package: 0.1.0

The line of code where issue occurs: https://github.com/catboost/catboost/blob/5b392a300becba1543d58c676020db64101f9fbf/contrib/libs/cxxsupp/libcxx/include/__algorithm/equal.h#L28

Backtrace from coredump:

```
#0  std::__y1::__equal_to<char, char>::operator() (__x=<error reading variable: Cannot access memory at address 0x74656e0386>, __y=@0x7f5fd54aaa08: 94 '^', this=<optimized out>)
    at /cargo/home/git/checkouts/catboost-25dbec0b4ea9f31f/233c95b/base/contrib/libs/cxxsupp/libcxx/include/__algorithm/comp.h:36
No locals.
#1  std::__y1::equal<char const*, char const*, std::__y1::__equal_to<char, char> > (__first1=0x74656e0386 <error: Cannot access memory at address 0x74656e0386>, __last1=0x74656e0396 <error: Cannot access memory at address 0x74656e0396>, 
    __first2=0x7f5fd54aaa08 "^x\315\2510i\374_.\254\222h\367\312\227\a\b\252J\325_\177", __pred=...) at /cargo/home/git/checkouts/catboost-25dbec0b4ea9f31f/233c95b/base/contrib/libs/cxxsupp/libcxx/include/__algorithm/equal.h:28
No locals.
#2  std::__y1::equal<char const*, char const*> (__first1=0x74656e0386 <error: Cannot access memory at address 0x74656e0386>, __last1=0x74656e0396 <error: Cannot access memory at address 0x74656e0396>, 
    __first2=0x7f5fd54aaa08 "^x\315\2510i\374_.\254\222h\367\312\227\a\b\252J\325_\177") at /cargo/home/git/checkouts/catboost-25dbec0b4ea9f31f/233c95b/base/contrib/libs/cxxsupp/libcxx/include/__algorithm/equal.h:38
No locals.
#3  std::__y1::operator==<char, 16ul> (__x=..., __y=...) at /cargo/home/git/checkouts/catboost-25dbec0b4ea9f31f/233c95b/base/contrib/libs/cxxsupp/libcxx/include/array:375
No locals.
#4  NCB::TGuid::operator== (this=0x74656e0376, rhs=...) at /cargo/home/git/checkouts/catboost-25dbec0b4ea9f31f/233c95b/base/catboost/libs/helpers/guid.cpp:12
No locals.
#5  0x000055fd22257001 in std::__y1::equal_to<NCB::TGuid>::operator() (__x=..., __y=..., this=<optimized out>) at /cargo/home/git/checkouts/catboost-25dbec0b4ea9f31f/233c95b/base/contrib/libs/cxxsupp/libcxx/include/__functional/operations.h:413
No locals.
#6  THashTable<std::__y1::pair<NCB::TGuid const, unsigned int>, NCB::TGuid, THash<NCB::TGuid>, TSelect1st, TEqualTo<NCB::TGuid>, std::__y1::allocator<NCB::TGuid> >::equals<NCB::TGuid, NCB::TGuid> (this=0x7f5f9c1df348, l=..., r=...)
    at /cargo/home/git/checkouts/catboost-25dbec0b4ea9f31f/233c95b/base/util/generic/hash_table.h:493
No locals.
#7  THashTable<std::__y1::pair<NCB::TGuid const, unsigned int>, NCB::TGuid, THash<NCB::TGuid>, TSelect1st, TEqualTo<NCB::TGuid>, std::__y1::allocator<NCB::TGuid> >::find<NCB::TGuid> (this=0x7f5f9c1df348, key=...)
    at /cargo/home/git/checkouts/catboost-25dbec0b4ea9f31f/233c95b/base/util/generic/hash_table.h:782
        n = <optimized out>
        first = 0x74656e036e
#8  THashMap<NCB::TGuid, unsigned int, THash<NCB::TGuid>, TEqualTo<NCB::TGuid>, std::__y1::allocator<NCB::TGuid> >::find<NCB::TGuid> (this=0x7f5f9c1df348, key=...) at /cargo/home/git/checkouts/catboost-25dbec0b4ea9f31f/233c95b/base/util/generic/hash.h:218
No locals.
#9  NCB::TTextProcessingCollection::GetAbsoluteCalcerOffset (this=0x7f5f9c1df2c0, calcerGuid=...) at /cargo/home/git/checkouts/catboost-25dbec0b4ea9f31f/233c95b/base/catboost/private/libs/text_features/text_processing_collection.cpp:534
        it = {cur = 0x74656e036e}
#10 0x000055fd221171b3 in NCB::NModelEvaluation::BinarizeFeatures<NCB::NModelEvaluation::NDetail::TCpuEvaluator::Calc(TArrayRef<TArrayRef<float const> const>, TArrayRef<TArrayRef<int const> const>, TArrayRef<TArrayRef<TBasicStringBuf<char, std::__y1::char_traits<char> > const> const>, TArrayRef<TArrayRef<TArrayRef<float const> const> const>, unsigned long, unsigned long, TArrayRef<double>, NCB::NModelEvaluation::TFeatureLayout const*) const::{lambda(TFeaturePosition, unsigned long)#1}, NCB::NModelEvaluation::NDetail::TCpuEvaluator::Calc(TArrayRef<TArrayRef<float const> const>, TArrayRef<TArrayRef<int const> const>, TArrayRef<TArrayRef<TBasicStringBuf<char, std::__y1::char_traits<char> > const> const>, TArrayRef<TArrayRef<TArrayRef<float const> const> const>, unsigned long, unsigned long, TArrayRef<double>, NCB::NModelEvaluation::TFeatureLayout const*) const::{lambda(TFeaturePosition, unsigned long)#2}, NCB::NModelEvaluation::NDetail::TCpuEvaluator::Calc(TArrayRef<TArrayRef<float const> const>, TArrayRef<TArrayRef<int const> const>, TArrayRef<TArrayRef<TBasicStringBuf<char, std::__y1::char_traits<char> > const> const>, TArrayRef<TArrayRef<TArrayRef<float const> const> const>, unsigned long, unsigned long, TArrayRef<double>, NCB::NModelEvaluation::TFeatureLayout const*) const::{lambda(TFeaturePosition, unsigned long)#3}, NCB::NModelEvaluation::NDetail::TCpuEvaluator::Calc(TArrayRef<TArrayRef<float const> const>, TArrayRef<TArrayRef<int const> const>, TArrayRef<TArrayRef<TBasicStringBuf<char, std::__y1::char_traits<char> > const> const>, TArrayRef<TArrayRef<TArrayRef<float const> const> const>, unsigned long, unsigned long, TArrayRef<double>, NCB::NModelEvaluation::TFeatureLayout const*) const::{lambda(TFeaturePosition, unsigned long)#4}>(TModelTrees const&, TModelTrees::TForApplyData const&, TIntrusivePtr<ICtrProvider, TDefaultIntrusivePtrOps<ICtrProvider> > const&, TIntrusivePtr<NCB::TTextProcessingCollection, TDefaultIntrusivePtrOps<NCB::TTextProcessingCollection> > const&, TIntrusivePtr<NCB::TEmbeddingProcessingCollection, TDefaultIntrusivePtrOps<NCB::TEmbeddingProcessingCollection> > const&, NCB::NModelEvaluation::NDetail::TCpuEvaluator::Calc(TArrayRef<TArrayRef<float const> const>, TArrayRef<TArrayRef<int const> const>, TArrayRef<TArrayRef<TBasicStringBuf<char, std::__y1::char_traits<char> > const> const>, TArrayRef<TArrayRef<TArrayRef<float const> const> const>, unsigned long, unsigned long, TArrayRef<double>, NCB::NModelEvaluation::TFeatureLayout const*) const::{lambda(TFeaturePosition, unsigned long)#1}, NCB::NModelEvaluation::NDetail::TCpuEvaluator::Calc(TArrayRef<TArrayRef<float const> const>, TArrayRef<TArrayRef<int const> const>, TArrayRef<TArrayRef<TBasicStringBuf<char, std::__y1::char_traits<char> > const> const>, TArrayRef<TArrayRef<TArrayRef<float const> const> const>, unsigned long, unsigned long, TArrayRef<double>, NCB::NModelEvaluation::TFeatureLayout const*) const::{lambda(TFeaturePosition, unsigned long)#2}, NCB::NModelEvaluation::NDetail::TCpuEvaluator::Calc(TArrayRef<TArrayRef<float const> const>, TArrayRef<TArrayRef<int const> const>, TArrayRef<TArrayRef<TBasicStringBuf<char, std::__y1::char_traits<char> > const> const>, TArrayRef<TArrayRef<TArrayRef<float const> const> const>, unsigned long, unsigned long, TArrayRef<double>, NCB::NModelEvaluation::TFeatureLayout const*) const::{lambda(TFeaturePosition, unsigned long)#3}, NCB::NModelEvaluation::NDetail::TCpuEvaluator::Calc(TArrayRef<TArrayRef<float const> const>, TArrayRef<TArrayRef<int const> const>, TArrayRef<TArrayRef<TBasicStringBuf<char, std::__y1::char_traits<char> > const> const>, TArrayRef<TArrayRef<TArrayRef<float const> const> const>, unsigned long, unsigned long, TArrayRef<double>, NCB::NModelEvaluation::TFeatureLayout const*) const::{lambda(TFeaturePosition, unsigned long)#4}, unsigned long, unsigned long, NCB::NModelEvaluation::TCPUEvaluatorQuantizedData*, TArrayRef<unsigned int>, TArrayRef<float>, TArrayRef<float>, NCB::NModelEvaluation::TFeatureLayout const*) (trees=..., applyData=..., ctrProvider=..., textProcessingCollection=..., embeddingProcessingCollection=..., floatAccessor=..., floatAccessor@entry=..., catFeatureAccessor=..., textFeatureAccessor=..., 
    embeddingFeatureAccessor=..., start=0, end=1, cpuEvaluatorQuantizedData=0x7f5fd54ab530, transposedHash=..., ctrs=..., estimatedFeatures=..., featureInfo=0x0) at /cargo/home/git/checkouts/catboost-25dbec0b4ea9f31f/233c95b/base/catboost/libs/model/cpu/quantization.h:497
        reorderedOffset = <optimized out>
        estimatedFeaturePtr = <optimized out>
        estimatedFeature = {ModelEstimatedFeature = {SourceFeatureId = 0, CalcerId = {static GUID_SIZE = 16, DefaultValue = {__elems_ = "___ILLEGAL_GUID"}, Value = {__elems_ = "^x\315\2510i\374_.\254\222h\367\312\227\a"}, dw = {T_ = 0x7f5fd54aaa08, S_ = 4}}, LocalId = 25, 
            SourceFeatureType = EEstimatedSourceFeatureType::Text}, Borders = {<std::__y1::vector<float, std::__y1::allocator<float> >> = {__begin_ = 0x7f5f88559b90, __end_ = 0x7f5f88559b94, __end_cap_ = {<std::__y1::__compressed_pair_elem<float*, 0, false>> = {
                  __value_ = 0x7f5f88559b94}, <std::__y1::__compressed_pair_elem<std::__y1::allocator<float>, 1, true>> = {<std::__y1::allocator<float>> = {<std::__y1::__non_trivial_if<true, std::__y1::allocator<float> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}}, <No data fields>}}
        __end4 = 0x7f5f9c1de1b0
        __begin4 = 0x7f5f9c1dbf50
        __range4 = <optimized out>
        textFeaturesTotalNum = 132
        docCount = 1
        resultPtrForBlockStart = 0x7f5fd54ab420 ""
        fullDocCount = <optimized out>
        expectedQuantizedFeaturesLen = <optimized out>
        resultPtr = <optimized out>
        result = <optimized out>

```

**Comment by hunts** [comment]
For what it worth, we saw only one server (out of few thousands) had the issue and no more events since that, so likely very rare condition triggered.
