### ISSUE TITLE
Can't apply visitor to GPU quantized data in CatBoostClassifier.predict call

### ISSUE THREAD

**Issue by wizardsd** [catboost/catboost#2707]
Problem: Can't apply visitor to GPU quantized data
catboost version: 1.2.5
Operating System: Windows 11 Enterprise N
CPU: Intel Core i7-6700K
GPU: Nvidia RTX 4060 Ti

I quantize pools and use them during training and evaluation later on the same GPU. It's more efficient to run HPO this way than without quantization.

```python
import numpy as np
from catboost import Pool, CatBoostClassifier

dataset = np.array([[0, 0, 0], [1, 1, 1]])
labels = np.array([0, 1])
pool_file_path = "pool.bin"
task_type = "GPU"   # CPU works as expected

pool = Pool(dataset, labels)
pool.quantize(border_count=1, task_type=task_type)
pool.save(pool_file_path)
del pool

# Somewhere later in the code ...
model_pool = Pool(f"quantized://{pool_file_path}")

model = CatBoostClassifier(iterations=5, task_type=task_type)
model.fit(model_pool)
model.predict(model_pool, task_type=task_type)
```

On the CPU it works as expected, but gives the following error on the GPU:
```
Traceback (most recent call last):
  File ".\scripts\demo.py", line 20, in <module>
    model.predict(model_pool, task_type=task_type)
  File ".\.venv\Lib\site-packages\catboost\core.py", line 5276, in predict
    return self._predict(data, prediction_type, ntree_start, ntree_end, thread_count, verbose, 'predict', task_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\.venv\Lib\site-packages\catboost\core.py", line 2608, in _predict
    predictions = self._base_predict(data, prediction_type, ntree_start, ntree_end, thread_count, verbose, task_type)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".\.venv\Lib\site-packages\catboost\core.py", line 1832, in _base_predict
    return self._object._base_predict(pool, prediction_type, ntree_start, ntree_end, thread_count, verbose, task_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_catboost.pyx", line 4969, in _catboost._CatBoost._base_predict
  File "_catboost.pyx", line 4976, in _catboost._CatBoost._base_predict
_catboost.CatBoostError: C:/Go_Agent/pipelines/BuildMaster/catboost.git/catboost/private/libs/algo/model_quantization_adapter.cpp:119: Can't apply visitor to GPU quantized data, please contact catboost developers via GitHub issue or in support chat
```

**Comment by ek-ak** [comment]
Hello! 
Sorry, model evaluation on GPU is not supported for quantized pools now. We will improve the error message.

**Comment by andrey-khropov** [comment]
> Why not improve model evaluation?

This will be done eventually but it requires more work.
