### ISSUE TITLE
Building CatBoost from source on top of OpenSSL 3.x

### ISSUE THREAD

**Issue by boegel** [catboost/catboost#2725]
Problem:

I'm trying to install CatBoost from source on a Red Hat Enterprise Linux (RHEL) 9.4 system, where OpenSSL 3.0.x is the system OpenSSL.

While the installation of CatBoost actually works (basically using "`--prefix=/software/CatBoost/1.2.5  --verbose  --no-deps  --ignore-installed  --no-index  --no-build-isolation  .`"), the resulting installation doesn't work because `python -c "import catboost"` fails with:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/CatBoost/1.2.5/lib/python3.11/site-packages/catboost/__init__.py", line 1, in <module>
    from .core import (
  File "/software/CatBoost/1.2.5/lib/python3.11/site-packages/catboost/core.py", line 45, in <module>
    from .plot_helpers import save_plot_file, try_plot_offline, OfflineMetricVisualizer
  File "/software/CatBoost/1.2.5/lib/python3.11/site-packages/catboost/plot_helpers.py", line 5, in <module>
    from . import _catboost
ImportError: /software/CatBoost/1.2.5/lib/python3.11/site-packages/catboost/_catboost.so: undefined symbol: SSL_get1_peer_certificate,  (at easybuild/framework/easyblock.py:3670 in _sanity_check_step)
```

catboost version: 1.2.5
Operating System: RHEL 9.4
CPU: Intel Skylake (but that's irrelevant here)
GPU: none

Does this indicate that CatBoost is simply not compatible yet with OpenSSL 3?
If so, are there any plans towards making it compatible?

I'm happy to try and come up with a patch for this myself, but I first want to check if this is already in the works (and how hard it would be for someone who's totally unfamiliar with the CatBoost codebase)

**Comment by boegel** [comment]
> How exactly do you build CatBoost?
> 
> > ""--prefix=/software/CatBoost/1.2.5  --verbose  --no-deps  --ignore-installed  --no-index  --no-build-isolation  .""
> 
> From what command are these flags?

Sorry, these are arguments to `python3 -m pip install`, that somehow got dropped from my copy-paste...

We basically download the source tarball for `CatBoost`, unpack it, and then run `python3 -m pip install` with the above options to build & install CatBoost.



> CatBoost uses fixed version of OpenSSL (1.1.1t for now) [that is taken from Conan packages](https://github.com/catboost/catboost/blob/48285dba2f22699e4e396bded8947cbc9b067f8d/conanfile.py#L13) and statically linked into the binaries, not OpenSSL installed in the system.
> 
> You can check it by running `ldd` command on CatBoost binaries, it should not have any OpenSSL dependencies.

Indeed:

```
$ ldd /tmp/vsc40003/software/CatBoost/1.2.5/lib/python3.11/site-packages/catboost/_catboost.so
        linux-vdso.so.1 (0x00007fffba150000)
        libc.so.6 => /lib64/libc.so.6 (0x000014b40a200000)
        /lib64/ld-linux-x86-64.so.2 (0x000014b40c1dc000)
        libm.so.6 => /lib64/libm.so.6 (0x000014b40c0f3000)
```

I'm guessing the "`undefined symbol: SSL_get1_peer_certificate`" error happens because I'm trying to import `catboost` using a `python` that is built on top of OpenSSL 3.x?

**Comment by andrey-khropov** [comment]
> I'm guessing the "`undefined symbol: SSL_get1_peer_certificate`" error happens because I'm trying to import `catboost` using a `python` that is built on top of OpenSSL 3.x?

That should not happen because, as I've said, OpenSSL is linked into CatBoost statically, so no OpenSSL functions should be resolved while loading CatBoost shared library `so`.

I've successfully used CatBoost on many systems with different python installations including those that have been built with OpenSSL 3.0.x.
