### ISSUE TITLE
Training continuation for GPU is not yet supported

### ISSUE THREAD

**Issue by Ethan1X** [catboost/catboost#2736]
Problem:
catboost version:
Operating System:
CPU:
GPU:

Traceback (most recent call last):
    model.fit(trainx_df, trainy_df, eval_set=valid_pool, use_best_model=True, verbose=False, init_model=model)
  File "/data/liangxuefeng/.conda/envs/py3.10/lib/python3.10/site-packages/catboost/core.py", line 5827, in fit
    return self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline,
  File "/data/liangxuefeng/.conda/envs/py3.10/lib/python3.10/site-packages/catboost/core.py", line 2400, in _fit
    self._train(
  File "/data/liangxuefeng/.conda/envs/py3.10/lib/python3.10/site-packages/catboost/core.py", line 1780, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4833, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4882, in _catboost._CatBoost._train
_catboost.CatBoostError: /src/catboost/catboost/cuda/train_lib/train.cpp:321: Training continuation for GPU is not yet supported

Thank you very much？

**Comment by HamdiBarkous** [comment]
is solving this issue planned in the next releases?

**Comment by andrey-khropov** [comment]
> is solving this issue planned in the next releases?

Not in the next release but it should be eventually supported. But CatBoost is open source so anybody can implement it and send a pull request.
