### ISSUE TITLE
Error when call fit(plot=True), jupyter python3.5, Ubuntu

### ISSUE THREAD

**Issue by musindmitriy** [catboost/catboost#28]
```
import ipywidgets; print(ipywidgets.__version__)
import IPython; print(IPython.__version__)
X = [[1, 2], [3, 4]]
y = [1, 2]
ckf = cgb.CatBoostRegressor()
ckf.fit(X, y, plot=True)
```

Outputs:
```
6.0.0
6.1.0

/usr/local/lib/python3.5/dist-packages/catboost/core.py:385: UserWarning: For drow plots in fit() method you should install ipywidgets and ipython
  warnings.warn("For drow plots in fit() method you should install ipywidgets and ipython")

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/catboost/core.py in _fit(self, X, y, cat_features, sample_weight, baseline, use_best_model, eval_set, verbose, plot)
    380             try:
--> 381                 from widget import CatboostIpythonWidget
    382                 widget = CatboostIpythonWidget(train_dir)

ImportError: No module named 'widget'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-32-cc8632cdb220> in <module>()
      4 y = [1, 2]
      5 ckf = cgb.CatBoostRegressor()
----> 6 ckf.fit(X, y, plot=True)

/usr/local/lib/python3.5/dist-packages/catboost/core.py in fit(self, X, y, cat_features, sample_weight, baseline, use_best_model, eval_set, verbose, plot)
    432         model : CatBoost
    433         """
--> 434         return self._fit(X, y, cat_features, sample_weight, baseline, use_best_model, eval_set, verbose, plot)
    435 
    436     def _predict(self, data, weight, prediction_type, ntree_limit, verbose):

/usr/local/lib/python3.5/dist-packages/catboost/core.py in _fit(self, X, y, cat_features, sample_weight, baseline, use_best_model, eval_set, verbose, plot)
    384             except ImportError as e:
    385                 warnings.warn("For drow plots in fit() method you should install ipywidgets and ipython")
--> 386                 raise ImportError(e.message)
    387         with log_fixup():
    388             self._train(X, eval_set, params)

AttributeError: 'ImportError' object has no attribute 'message'
```

**Comment by musindmitriy** [comment]
With catboost-0.1.1.5:
```
6.0.0
6.1.0

<catboost.core.CatBoostRegressor at 0x7f78b1242d30>

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/catboost/widget/ipythonwidget.py", line 28, in update_widget
    self.update_data(subdirs=subdirs)
  File "/usr/local/lib/python3.5/dist-packages/catboost/widget/ipythonwidget.py", line 54, in update_data
    content = self.update_data_from_dir(path)
  File "/usr/local/lib/python3.5/dist-packages/catboost/widget/ipythonwidget.py", line 83, in update_data_from_dir
    for row in list(csv.reader(meta_in, delimiter='\t')):
_csv.Error: iterator should return strings, not bytes (did you open the file in text mode?)
```

**Comment by Donskov7** [comment]
We fixed it in new version, please reinstall CatBoost.

**Comment by annaveronika** [comment]
It is fixed now, try updating to the last version.
