### ISSUE TITLE
"TypeError: expected bytes, str found" on Python 3.5

### ISSUE THREAD

**Issue by tezer** [catboost/catboost#31]
Hi
I am trying to run my own script which is based (with minor modifications) on catboost/catboost/tutorials/quora_catboost_w2v.ipynb
I get the following error message:
`Traceback (most recent call last):
  File "/home/myhome/PycharmProjects/123/CatBoost/test.py", line 219, in <module>
    clf.fit(train, y_train)
  File "/home/myhome/virtualenv/tensorflow/lib/python3.5/site-packages/catboost/core.py", line 929, in fit
    self._fit(X, y, cat_features, sample_weight, baseline, use_best_model, eval_set, verbose, plot)
  File "/home/myhome/virtualenv/tensorflow/lib/python3.5/site-packages/catboost/core.py", line 365, in _fit
    X = Pool(X, y, cat_features=cat_features, weight=sample_weight, baseline=baseline)
  File "/home/myhome/virtualenv/tensorflow/lib/python3.5/site-packages/catboost/core.py", line 94, in __init__
    self._init(data, label, cat_features, weight, baseline, feature_names)
  File "/home/myhome/virtualenv/tensorflow/lib/python3.5/site-packages/catboost/core.py", line 305, in _init
    self._init_pool(data_matrix, label, weight, baseline, feature_names)
  File "_catboost.pyx", line 361, in _catboost._PoolBase._init_pool (/home/donskov/.ya/build/build_root/78633066626b733765616e696f713972/catboost/python-package/catboost/_catboost.pyx.cpp:5141)
  File "_catboost.pyx", line 373, in _catboost._PoolBase._init_pool (/home/donskov/.ya/build/build_root/78633066626b733765616e696f713972/catboost/python-package/catboost/_catboost.pyx.cpp:5006)
  File "_catboost.pyx", line 418, in _catboost._PoolBase._set_feature_names (/home/donskov/.ya/build/build_root/78633066626b733765616e696f713972/catboost/python-package/catboost/_catboost.pyx.cpp:6629)
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_TString (/home/donskov/.ya/build/build_root/78633066626b733765616e696f713972/catboost/python-package/catboost/_catboost.pyx.cpp:17167)
TypeError: expected bytes, str found`

Is there any way to fix it?

**Comment by sgaynetdinov** [comment]
Hi, show issue https://github.com/catboost/catboost/issues/17
