### ISSUE TITLE
Building Catboost GPU throws an error

### ISSUE THREAD

**Issue by ManrajGrover** [catboost/catboost#311]
Problem: Building Catboost GPU throws an error

Following instructions [here](), I ran the following command:

```py
python mk_wheel.py -DPYTHON_INCLUDE="-I/usr/include/python3.6m" -DPYTHON_LIBRARIES="-lpython3.6m -lpthread -ldl  -lutil -lm" -DCUDA_ROOT="/usr/local/cuda"
```

which failed to build the GPU version with following logs:

```sh
------- [CC] {pic, FAILED} $(S)/catboost/python-package/catboost/helpers.cpp
command /root/.ya/tools/v3/531642148/bin/clang++ --sysroot=/ -B/usr/bin -c -o /root/.ya/build/build_root/s4k2/000810/catboost/python-package/catboost/helpers.cpp.pic.o /root/projects/catboost/catboost/python-package/catboost/helpers.cpp -I/root/.ya/build/build_root/s4k2/000810 -I/root/projects/catboost -I/root/projects/catboost/contrib/tools/cython/Cython/Includes -I/root/projects/catboost/contrib/libs/cxxsupp/libcxxrt -I/root/projects/catboost/contrib/libs/cxxsupp/libcxx/include -I/root/projects/catboost/contrib/libs/protobuf -I/root/projects/catboost/contrib/libs/protobuf/google/protobuf -I/root/projects/catboost/contrib/libs/openssl/include -I/root/projects/catboost/contrib/libs/brotli/include -Woverloaded-virtual -Wno-invalid-offsetof -Wno-attributes -Wno-undefined-var-template -std=c++14 -pipe -m64 -msse -msse3 -msse2 -O2 -Wno-inconsistent-missing-override -Wno-c++17-extensions -Wno-exceptions -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DGNU -D_GNU_SOURCE -DSSE_ENABLED=1 -DSSE3_ENABLED=1 -DSSE2_ENABLED=1 -DNDEBUG -D_THREAD_SAFE -D_PTHREADS -D_REENTRANT -D__LONG_LONG_SUPPORTED -Wall -W -Wno-parentheses -Wno-deprecated -fPIC -DCATBOOST_OPENSOURCE=yes -D_OS_SDK=local -nostdinc++ -I/usr/local/cuda/include -DFAKEID=cython0_28_1_try5 -DARCADIA_ROOT=/root/projects/catboost -DARCADIA_BUILD_ROOT=/root/.ya/build/build_root/s4k2/000810 -Werror -Wno-error=deprecated-declarations PYTHON-NOT-FOUND -nostdinc++ failed with exit code 1
clang-5.0: error: no such file or directory: 'PYTHON-NOT-FOUND'
Failed
GPU version build failed
Building CPU version
/usr/bin/python /root/projects/catboost/ya make /root/projects/catboost/catboost/python-package/catboost --no-src-links -r --output /tmp/tmpl5lz7bd4 -DPYTHON_CONFIG=python3-config -DNO_DEBUGINFO -DOS_SDK=local -DUSE_ARCADIA_PYTHON=no -DPYTHON_INCLUDE=-I/usr/include/python3.6m -DPYTHON_LIBRARIES=-lpython3.6m -lpthread -ldl  -lutil -lm -DCUDA_ROOT=/usr/local/cuda -DHAVE_CUDA=no
------- [CC] {pic, FAILED} $(S)/catboost/python-package/catboost/helpers.cpp
command /root/.ya/tools/v3/531642148/bin/clang++ --sysroot=/ -B/usr/bin -c -o /root/.ya/build/build_root/4jg8/0000c4/catboost/python-package/catboost/helpers.cpp.pic.o /root/projects/catboost/catboost/python-package/catboost/helpers.cpp -I/root/.ya/build/build_root/4jg8/0000c4 -I/root/projects/catboost -I/root/projects/catboost/contrib/tools/cython/Cython/Includes -I/root/projects/catboost/contrib/libs/cxxsupp/libcxxrt -I/root/projects/catboost/contrib/libs/cxxsupp/libcxx/include -I/root/projects/catboost/contrib/libs/protobuf -I/root/projects/catboost/contrib/libs/protobuf/google/protobuf -I/root/projects/catboost/contrib/libs/openssl/include -I/root/projects/catboost/contrib/libs/brotli/include -Woverloaded-virtual -Wno-invalid-offsetof -Wno-attributes -Wno-undefined-var-template -std=c++14 -pipe -m64 -msse -msse3 -msse2 -O2 -Wno-inconsistent-missing-override -Wno-c++17-extensions -Wno-exceptions -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DGNU -D_GNU_SOURCE -DSSE_ENABLED=1 -DSSE3_ENABLED=1 -DSSE2_ENABLED=1 -DNDEBUG -D_THREAD_SAFE -D_PTHREADS -D_REENTRANT -D__LONG_LONG_SUPPORTED -Wall -W -Wno-parentheses -Wno-deprecated -fPIC -DCATBOOST_OPENSOURCE=yes -D_OS_SDK=local -nostdinc++ -DFAKEID=cython0_28_1_try5 -DARCADIA_ROOT=/root/projects/catboost -DARCADIA_BUILD_ROOT=/root/.ya/build/build_root/4jg8/0000c4 -Werror -Wno-error=deprecated-declarations PYTHON-NOT-FOUND -nostdinc++ failed with exit code 1
clang-5.0: error: no such file or directory: 'PYTHON-NOT-FOUND'
Failed
Traceback (most recent call last):
  File "mk_wheel.py", line 215, in <module>
    wheel_name = build(arc_root, out_root, sys.argv[1:])
  File "mk_wheel.py", line 179, in build
    subprocess.check_call(cpu_cmd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '/root/projects/catboost/ya', 'make', '/root/projects/catboost/catboost/python-package/catboost', '--no-src-links', '-r', '--output', '/tmp/tmpl5lz7bd4', '-DPYTHON_CONFIG=python3-config', '-DNO_DEBUGINFO', '-DOS_SDK=local', '-DUSE_ARCADIA_PYTHON=no', '-DPYTHON_INCLUDE=-I/usr/include/python3.6m', '-DPYTHON_LIBRARIES=-lpython3.6m -lpthread -ldl  -lutil -lm', '-DCUDA_ROOT=/usr/local/cuda', '-DHAVE_CUDA=no']' returned non-zero exit status 1
```
catboost version: Latest HEAD
Operating System: Ubuntu 16.04
GPU: GeForce GTX 980 Ti

**Comment by ManrajGrover** [comment]
Any update on this?

**Comment by ManrajGrover** [comment]
@annaveronika @kizill Please help.

**Comment by kizill** [comment]
Do you have python-dev package installed?
Can you try `-DPYTHON_CONFIG={path to your python-config}` and `-DOS_SDK=local` options?
