### ISSUE TITLE
No module named '_catboost' 

### ISSUE THREAD

**Issue by bnavras** [catboost/catboost#319]
1) pip install catboost --no-cache-dir

Requirement already satisfied: six in ./lib/python3.6/site-packages (from catboost) (1.11.0)
Requirement already satisfied: pandas in ./lib/python3.6/site-packages (from catboost) (0.22.0)
Requirement already satisfied: numpy in ./lib/python3.6/site-packages (from catboost) (1.14.0)
Requirement already satisfied: python-dateutil>=2 in ./lib/python3.6/site-packages (from pandas->catboost) (2.6.1)
Requirement already satisfied: pytz>=2011k in ./lib/python3.6/site-packages/pytz-2017.3-py3.6.egg (from pandas->catboost) (2017.3)
Installing collected packages: catboost
Successfully installed catboost-0.8

2) from catboost import CatBoostClassifier

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-27-a552d8edcebd> in <module>()
----> 1 from catboost import CatBoostClassifier

~/PycharmProjects/jupyter/lib/python3.6/site-packages/catboost/__init__.py in <module>()
----> 1 from .core import Pool, CatBoost, CatBoostClassifier, CatBoostRegressor, CatboostError, cv, train  # noqa
      2 try:
      3     from .widget import MetricVisualizer  # noqa
      4 except:
      5     pass

~/PycharmProjects/jupyter/lib/python3.6/site-packages/catboost/core.py in <module>()
     48 
     49 
---> 50 _catboost = get_catboost_bin_module()
     51 _PoolBase = _catboost._PoolBase
     52 _CatBoostBase = _catboost._CatBoostBase

~/PycharmProjects/jupyter/lib/python3.6/site-packages/catboost/core.py in get_catboost_bin_module()
     44         except ImportError:
     45             pass
---> 46     import _catboost
     47     return _catboost
     48 

ModuleNotFoundError: No module named '_catboost'

Версия python3.6.2
ОС: Linux(Debian)

**Comment by crazymidnight** [comment]
I have same issue. OS: Ubuntu 16.04

**Comment by crazymidnight** [comment]
No, from ppa:jonathonf/python-3.6

**Comment by kizill** [comment]
@crazymidnight, sorry for delay. I tried to reprocude your problem on clean ubuntu xenial with python3.6 from `ppa:jonathonf/python-3.6` and everything was working just fine. Could you please try to manually edit your `~/PycharmProjects/jupyter/lib/python3.6/site-packages/catboost/core.py` like this:
```python
def get_catboost_bin_module():
    if '_catboost' in sys.modules:
        return sys.modules['_catboost']
    so_paths = get_so_paths('./gpu') + get_so_paths('./')
    for so_path in so_paths:
        try:
            loaded_catboost = imp.load_dynamic('_catboost', so_path)
            sys.modules['catboost._catboost'] = loaded_catboost
            return loaded_catboost
        except ImportError as e:
            print(e)
    import _catboost
    return _catboost
```
and share output?

**Comment by dlihhats** [comment]
I get the same error: `ModuleNotFoundError: No module named '_catboost'` when trying to import Catboost in my Python 3.6 code running in Docker on Google App Engine flex environment.

Google App Engine uses Debian Jessie. My Dockerfile looks like this:

```
FROM gcr.io/google-appengine/python

# Create a virtualenv for dependencies. This isolates these packages from
# system-level packages.
RUN virtualenv /env -p python3

# Setting these environment variables are the same as running
# source /env/bin/activate.
ENV VIRTUAL_ENV /env
ENV PATH /env/bin:$PATH

RUN apt-get update; \
        apt-get install -y \
        build-essential \
        python-dev \
        python-setuptools \
        python-matplotlib \
        libatlas-dev \
        curl \
        ssh \
        libatlas3gf-base && \
        apt-get clean

# Copy the application's requirements.txt and run pip to install all
# dependencies into the virtualenv.
ADD requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt
```

I've also posted a question on StackOverflow, no luck so far: https://stackoverflow.com/questions/50007204/catboost-on-google-appengine-python-flexible-environment/

If instead I use Python 2.7 by specifying `RUN virtualenv /env`, Catboost works fine.

**Comment by dlihhats** [comment]
After switching from virtualenv to conda in my Dockerfile above, I've been able to import Catboost from Python 3.6 just fine.

**Comment by annaveronika** [comment]
@bnavras Did you manage to install catboost?

**Comment by annaveronika** [comment]
Closing because of inactivity. Feel free to reopen if something doesn't work for you.

**Comment by sfog17** [comment]
same issue for me 

working in a conda environment
python 3.6
catboost installed with conda commands

Works in the command line, but doesn't work with Jupyer notebook

> ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-4c4156b93204> in <module>()
----> 1 import catboost
ModuleNotFoundError: No module named 'catboost'

**Comment by lbogomolov** [comment]
I have the same problem, cannot import CatBoostClassifier
```
(base) lbogomolov@m:~$ pip install catboost --no-cache-dir
Collecting catboost
  Downloading https://files.pythonhosted.org/packages/19/ea/d6cbdf03fb1e8ea8c7c7a0b37b89c8f8b3825ec625d428d49b6230656c00/catboost-0.11.1-cp36-none-manylinux1_x86_64.whl (55.3MB)
    100% |████████████████████████████████| 55.3MB 11.5MB/s
Requirement already satisfied: enum34 in ./anaconda3/lib/python3.6/site-packages (from catboost) (1.1.6)
Requirement already satisfied: numpy>=1.11.1 in ./anaconda3/lib/python3.6/site-packages (from catboost) (1.14.3)
Requirement already satisfied: six in ./anaconda3/lib/python3.6/site-packages (from catboost) (1.11.0)
Requirement already satisfied: pandas>=0.19.1 in ./anaconda3/lib/python3.6/site-packages (from catboost) (0.23.0)
Requirement already satisfied: python-dateutil>=2.5.0 in ./anaconda3/lib/python3.6/site-packages (from pandas>=0.19.1->catboost) (2.7.3)
Requirement already satisfied: pytz>=2011k in ./anaconda3/lib/python3.6/site-packages (from pandas>=0.19.1->catboost) (2018.4)
Installing collected packages: catboost
Successfully installed catboost-0.11.1

(base) lbogomolov@m:~$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from catboost import CatBoostClassifier
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lbogomolov/anaconda3/lib/python3.6/site-packages/catboost/__init__.py", line 1, in <module>
    from .core import FeaturesData, EFstrType, Pool, CatBoost, CatBoostClassifier, CatBoostRegressor, CatboostError, cv, train, sum_models  # noqa
  File "/home/lbogomolov/anaconda3/lib/python3.6/site-packages/catboost/core.py", line 52, in <module>
    _catboost = get_catboost_bin_module()
  File "/home/lbogomolov/anaconda3/lib/python3.6/site-packages/catboost/core.py", line 48, in get_catboost_bin_module
    import _catboost
ModuleNotFoundError: No module named '_catboost'
>>>
```

**Comment by lbogomolov** [comment]
I've modified a bit `get_catboost_bin_module()`

```python
def get_catboost_bin_module():
    if '_catboost' in sys.modules:
        return sys.modules['_catboost']
    so_paths = get_so_paths('./')
    ###=====>>>
    print(so_paths)
    loaded_catboost = imp.load_dynamic('_catboost', so_paths[0])
    sys.modules['catboost._catboost'] = loaded_catboost
    return loaded_catboost
    ###=====<<<
    ###for so_path in so_paths:
    ###    try:
    ###        loaded_catboost = imp.load_dynamic('_catboost', so_path)
    ###        sys.modules['catboost._catboost'] = loaded_catboost
    ###        return loaded_catboost
    ###    except ImportError:
    ###        pass
    import _catboost
    return _catboost

```

the path to `_catboost.so` is fine but it gives `cannot enable executable stack as shared object requires: Invalid argument` error

```
(base) lbogomolov@wl020690:~$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from catboost import CatBoostClassifier
['/home/lbogomolov/anaconda3/lib/python3.6/site-packages/catboost/./_catboost.so']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lbogomolov/anaconda3/lib/python3.6/site-packages/catboost/__init__.py", line 1, in <module>
    from .core import FeaturesData, EFstrType, Pool, CatBoost, CatBoostClassifier, CatBoostRegressor, CatboostError, cv, train, sum_models  # noqa
  File "/home/lbogomolov/anaconda3/lib/python3.6/site-packages/catboost/core.py", line 58, in <module>
    _catboost = get_catboost_bin_module()
  File "/home/lbogomolov/anaconda3/lib/python3.6/site-packages/catboost/core.py", line 43, in get_catboost_bin_module
    loaded_catboost = imp.load_dynamic('_catboost', so_paths[0])
  File "/home/lbogomolov/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/lbogomolov/anaconda3/lib/python3.6/site-packages/catboost/./_catboost.so: cannot enable executable stack as shared object requires: Invalid argument
>>>
```

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Now noexecstack is on by default.
https://github.com/catboost/catboost/commit/4883e73504aadf44e2689c7059770c55536eeeab
