### ISSUE TITLE
build failed windows10 ,i7,gtx1060

### ISSUE THREAD

**Issue by janelu9** [catboost/catboost#393]
Problem: 
Info: Attention! Using system user-defined compiler: cl.exe (check CC and CXX env vars).
Config was not generated due to errors in E:\catboost\build\ymake_conf.py
Traceback (most recent call last):
  File "E:\catboost\build\ymake_conf.py", line 2491, in <module>
    main()
  File "E:\catboost\build\ymake_conf.py", line 2484, in main
    build = Build(arcadia, options.build_type, options.toolchain_params, force_ignore_local_files=not options.local_distbuild)
  File "E:\catboost\build\ymake_conf.py", line 518, in __init__
    self.tc = self._get_toolchain_options()
  File "E:\catboost\build\ymake_conf.py", line 633, in _get_toolchain_options
    return MSVCToolchainOptions(self, detector)
  File "E:\catboost\build\ymake_conf.py", line 1080, in __init__
    raise ConfigureError('No %WindowsSdkDir%, %WindowsSDKVersion% or %VCINSTALLDIR% present. Please, run vcvars64.bat to setup preferred environment.')
ConfigureError: No %WindowsSdkDir%, %WindowsSDKVersion% or %VCINSTALLDIR% present. Please, run vcvars64.bat to setup preferred environment.
catboost version: {version}
Operating System: {OS}
CPU: {CPU}
# GPU: {GPU}

**Comment by dbakshee** [comment]
Hi @janelu9 ,

I believe the file `VC\bin\amd64\vcvars64.bat` is not supposed to be run on its own. The correct way of setting MSVS environment is to run `VC\varsall64.bat x64`.

**Comment by janelu9** [comment]
sorry @dbakshee  .
I still con't build it .
there is only one varsall64.bat  in ### "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build"

**Comment by dbakshee** [comment]
Hi @janelu,
I am sorry for not updating you. The environment setter script that you use is the correct one. An issue was in the .vcxproj files that we generated. I hope we have fixed one (it is works with Community and Professional versions of MSVS), so I ask you to check if the issue has gone at your side. 
However, we are still struggling with other issues preventing compilation of Catboost in MSVS. 
Please do not hesitate to let us know about the build problems you encounter.
Dima

**Comment by CoderCoderCoder** [comment]
Same error - any solution for it?... Thanks.

**Comment by dbakshee** [comment]
Hi @janelu9 

We should have solved the problem by a recent commit. Please pull the latest version and try `ya make --rebuild ...`

Also, please be informed that MSVC compiler 19.14 shall not be used to compile catboost, use 19.13. 
If you intend to build with CUDA 9.1 you should use compiler 19.11, not newer, and for CUDA 9.2 you should use compiler 19.13.  (compiler version is defined by value of _MSC_VER macro, refer to https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering)

Environment variables used by  `%WindowsSdkDir%, %WindowsSDKVersion% or %VCINSTALLDIR%` shall be set by MSVS IDE internally, or by a call of the environment setter .bat file from a command line or batch file. For example:

`call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" -vcvars_ver=14.13` 


Thanks
Dima
