### ISSUE TITLE
SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by ctlaltdefeat** [catboost/catboost#403]
Whenever trying to train using GPU, I get the error:

```
...(process name) terminated by signal SIGSEGV (Address boundary error)
```

I'm using CUDA 9.1: running ```nvcc --version``` gives
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
```
I initially tried using the python version with the latest pypi package (0.9.1) and using the "Test catboost" example from the documentation. Training with CPU worked.

I then tried to directly use the commandline version, with the same result. 
Note that I set ```--logging-level Debug``` with the commandline binary but no extra info was given.

Note also that other python packages that utilize CUDA 9.1 (such as pytorch) work as expected.

catboost version: 0.9.1
Operating System: Linux
GPU: nvidia GTX 1080

**Comment by Noxoomo** [comment]
Hi!

Could you provide command line args you've used?
This is very strange, because cmd-line version has almost no dependencies on external world (like python/etc) and needs just proper NVIDIA driver (at least 379)

And could you run nvidia-smi and show output?

**Comment by Noxoomo** [comment]
And did CatBoost printed anything at all with --logging-level Debug?

**Comment by ctlaltdefeat** [comment]
nvidia-smi:
```
Fri Jul  6 17:40:39 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.24                 Driver Version: 396.24                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   43C    P0    36W / 180W |      0MiB /  8118MiB |      3%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

and  ```./catboost-cuda-linux-0.9 fit --learn-set train.tsv --task-type GPU --logging-level Info --allow-writing-files false``` gives:

```
Random seed 25225766074096
Mem usage: After data read: 19369984
Float Feature #2 is empty
fish: “./catboost-cuda-linux-0.9 fit -…” terminated by signal SIGSEGV (Address boundary error)
```

where train.tsv contains:

```
5.1     3.5     1.4     0.2
4.9     3.0     1.4     0.2
4.7     3.2     1.3     0.2
4.6     3.1     1.5     0.2
5.0     3.6     1.4     0.2
```

**Comment by Noxoomo** [comment]
Oh, we found bug with python-package that  was not triggered in our internal builds, GPU fails without eval-set, we will fix this soon

but cmd-line seems to fail for a different reason. did CPU runs well?  Maybe you could  share train.tsv or run with gdb and send us backtrace?

**Comment by ctlaltdefeat** [comment]
I already specified train.tsv above, unless I'm misunderstanding. 
CPU runs well with cmdline.
I ran GPU with gdb, here's what occurs (not much unfortunately):

```
Starting program: /home/ctlaltdefeat/catboost-cuda-linux-0.9 fit --learn-set t.tsv --logging-level Debug --task-type GPU
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Random seed 68206117662754
[New Thread 0x7ffff705c700 (LWP 15752)]
[New Thread 0x7ffff685b700 (LWP 15753)]
[New Thread 0x7ffff605a700 (LWP 15754)]
[New Thread 0x7ffff5859700 (LWP 15755)]
[New Thread 0x7ffff5058700 (LWP 15756)]
[New Thread 0x7ffff4857700 (LWP 15757)]
[New Thread 0x7ffff4056700 (LWP 15758)]
[New Thread 0x7ffff3855700 (LWP 15759)]
Loading features...
Mem usage: After data read: 54067200
[New Thread 0x7ffff3054700 (LWP 15760)]
[New Thread 0x7ffff2853700 (LWP 15761)]
[New Thread 0x7ffff2052700 (LWP 15762)]
[New Thread 0x7ffff1851700 (LWP 15763)]
[New Thread 0x7ffff1050700 (LWP 15764)]
[New Thread 0x7ffff084f700 (LWP 15765)]
[New Thread 0x7ffff004e700 (LWP 15766)]
Float Feature #2 is empty

Thread 14 "ParLocalExecuto" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff1050700 (LWP 15764)]
0x000000000062ec04 in ?? ()
```

**Comment by Noxoomo** [comment]
Oh, sorry, missed that you wrote train.csv

I checked this pool with binary on GTX1080Ti and K40, worked fine
Could you please  add call  thread apply all bt after crash?

**Comment by ctlaltdefeat** [comment]
```
(gdb) thread apply all bt

Thread 16 (Thread 0x7ffff004e700 (LWP 15766)):
#0  0x00007ffff77baffc in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000068a020 in TCondVar::TImpl::WaitD(TMutex&, TInstant) ()
#2  0x0000000000681abf in Event::WaitD(TInstant) ()
#3  0x000000000065e31b in NPar::TLocalExecutor::TImpl::HostWorkerThread(void*) ()
#4  0x0000000000676b12 in ?? ()
#5  0x00007ffff77b5075 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007ffff74ea53f in clone () from /usr/lib/libc.so.6

Thread 15 (Thread 0x7ffff084f700 (LWP 15765)):
#0  0x00007ffff77baffc in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000068a020 in TCondVar::TImpl::WaitD(TMutex&, TInstant) ()
#2  0x0000000000681abf in Event::WaitD(TInstant) ()
#3  0x000000000065e31b in NPar::TLocalExecutor::TImpl::HostWorkerThread(void*) ()
#4  0x0000000000676b12 in ?? ()
#5  0x00007ffff77b5075 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007ffff74ea53f in clone () from /usr/lib/libc.so.6

Thread 14 (Thread 0x7ffff1050700 (LWP 15764)):
#0  0x000000000062ec04 in ?? ()
#1  0x000000000062e102 in ?? ()
#2  0x00000000009725c3 in ?? ()
#3  0x00000000009724bb in ?? ()
#4  0x0000000000971c84 in NCatboostCuda::TBordersBuilder::operator()(NCatboostOptions::TBinarizationOptions const&) ()
#5  0x00000000009710e5 in NCatboostCuda::BuildBorders(TVector<float, std::__y1::allocator<float> > const&, unsigned int, NCatboostOptions::TBinarizationOptions const&) ()
#6  0x00000000009820f1 in ?? ()
#7  0x00000000006600e9 in ?? ()
#8  0x00000000006605de in ?? ()
#9  0x000000000065e247 in NPar::TLocalExecutor::TImpl::HostWorkerThread(void*) ()
#10 0x0000000000676b12 in ?? ()
#11 0x00007ffff77b5075 in start_thread () from /usr/lib/libpthread.so.0
#12 0x00007ffff74ea53f in clone () from /usr/lib/libc.so.6

Thread 13 (Thread 0x7ffff1851700 (LWP 15763)):
#0  0x00007ffff77baffc in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000068a020 in TCondVar::TImpl::WaitD(TMutex&, TInstant) ()
#2  0x0000000000681abf in Event::WaitD(TInstant) ()
#3  0x000000000065e31b in NPar::TLocalExecutor::TImpl::HostWorkerThread(void*) ()
#4  0x0000000000676b12 in ?? ()
#5  0x00007ffff77b5075 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007ffff74ea53f in clone () from /usr/lib/libc.so.6

Thread 12 (Thread 0x7ffff2052700 (LWP 15762)):
#0  0x00007ffff77baffc in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000068a020 in TCondVar::TImpl::WaitD(TMutex&, TInstant) ()
#2  0x0000000000681abf in Event::WaitD(TInstant) ()
#3  0x000000000065e31b in NPar::TLocalExecutor::TImpl::HostWorkerThread(void*) ()
#4  0x0000000000676b12 in ?? ()
#5  0x00007ffff77b5075 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007ffff74ea53f in clone () from /usr/lib/libc.so.6

Thread 11 (Thread 0x7ffff2853700 (LWP 15761)):
#0  0x00007ffff77baffc in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000068a020 in TCondVar::TImpl::WaitD(TMutex&, TInstant) ()
#2  0x0000000000681abf in Event::WaitD(TInstant) ()
#3  0x000000000065e31b in NPar::TLocalExecutor::TImpl::HostWorkerThread(void*) ()
#4  0x0000000000676b12 in ?? ()
#5  0x00007ffff77b5075 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007ffff74ea53f in clone () from /usr/lib/libc.so.6

Thread 10 (Thread 0x7ffff3054700 (LWP 15760)):
---Type <return> to continue, or q <return> to quit---
#0  0x00007ffff77baffc in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000068a020 in TCondVar::TImpl::WaitD(TMutex&, TInstant) ()
#2  0x0000000000681abf in Event::WaitD(TInstant) ()
#3  0x000000000065e31b in NPar::TLocalExecutor::TImpl::HostWorkerThread(void*) ()
#4  0x0000000000676b12 in ?? ()
#5  0x00007ffff77b5075 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007ffff74ea53f in clone () from /usr/lib/libc.so.6

Thread 9 (Thread 0x7ffff3855700 (LWP 15759)):
#0  0x00007ffff77baffc in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000068a020 in TCondVar::TImpl::WaitD(TMutex&, TInstant) ()
#2  0x0000000000681abf in Event::WaitD(TInstant) ()
#3  0x000000000065e31b in NPar::TLocalExecutor::TImpl::HostWorkerThread(void*) ()
#4  0x0000000000676b12 in ?? ()
#5  0x00007ffff77b5075 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007ffff74ea53f in clone () from /usr/lib/libc.so.6

Thread 8 (Thread 0x7ffff4056700 (LWP 15758)):
#0  0x00007ffff77baffc in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000068a020 in TCondVar::TImpl::WaitD(TMutex&, TInstant) ()
#2  0x0000000000681abf in Event::WaitD(TInstant) ()
#3  0x000000000065e31b in NPar::TLocalExecutor::TImpl::HostWorkerThread(void*) ()
#4  0x0000000000676b12 in ?? ()
#5  0x00007ffff77b5075 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007ffff74ea53f in clone () from /usr/lib/libc.so.6

Thread 7 (Thread 0x7ffff4857700 (LWP 15757)):
#0  0x00007ffff77baffc in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000068a020 in TCondVar::TImpl::WaitD(TMutex&, TInstant) ()
#2  0x0000000000681abf in Event::WaitD(TInstant) ()
#3  0x000000000065e31b in NPar::TLocalExecutor::TImpl::HostWorkerThread(void*) ()
#4  0x0000000000676b12 in ?? ()
#5  0x00007ffff77b5075 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007ffff74ea53f in clone () from /usr/lib/libc.so.6

Thread 6 (Thread 0x7ffff5058700 (LWP 15756)):
#0  0x00007ffff77baffc in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000068a020 in TCondVar::TImpl::WaitD(TMutex&, TInstant) ()
#2  0x0000000000681abf in Event::WaitD(TInstant) ()
#3  0x000000000065e31b in NPar::TLocalExecutor::TImpl::HostWorkerThread(void*) ()
#4  0x0000000000676b12 in ?? ()
#5  0x00007ffff77b5075 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007ffff74ea53f in clone () from /usr/lib/libc.so.6

Thread 5 (Thread 0x7ffff5859700 (LWP 15755)):
#0  0x00007ffff77baffc in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000068a020 in TCondVar::TImpl::WaitD(TMutex&, TInstant) ()
#2  0x0000000000681abf in Event::WaitD(TInstant) ()
#3  0x000000000065e31b in NPar::TLocalExecutor::TImpl::HostWorkerThread(void*) ()
#4  0x0000000000676b12 in ?? ()
#5  0x00007ffff77b5075 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007ffff74ea53f in clone () from /usr/lib/libc.so.6

Thread 4 (Thread 0x7ffff605a700 (LWP 15754)):
#0  0x00007ffff77baffc in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000068a020 in TCondVar::TImpl::WaitD(TMutex&, TInstant) ()
#2  0x0000000000681abf in Event::WaitD(TInstant) ()
#3  0x000000000065e31b in NPar::TLocalExecutor::TImpl::HostWorkerThread(void*) ()
#4  0x0000000000676b12 in ?? ()
#5  0x00007ffff77b5075 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007ffff74ea53f in clone () from /usr/lib/libc.so.6

---Type <return> to continue, or q <return> to quit---
Thread 3 (Thread 0x7ffff685b700 (LWP 15753)):
#0  0x00007ffff77baffc in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000068a020 in TCondVar::TImpl::WaitD(TMutex&, TInstant) ()
#2  0x0000000000681abf in Event::WaitD(TInstant) ()
#3  0x000000000065e31b in NPar::TLocalExecutor::TImpl::HostWorkerThread(void*) ()
#4  0x0000000000676b12 in ?? ()
#5  0x00007ffff77b5075 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007ffff74ea53f in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7ffff705c700 (LWP 15752)):
#0  0x00007ffff77baffc in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000000000068a020 in TCondVar::TImpl::WaitD(TMutex&, TInstant) ()
#2  0x0000000000681abf in Event::WaitD(TInstant) ()
#3  0x000000000065e31b in NPar::TLocalExecutor::TImpl::HostWorkerThread(void*) ()
#4  0x0000000000676b12 in ?? ()
#5  0x00007ffff77b5075 in start_thread () from /usr/lib/libpthread.so.0
#6  0x00007ffff74ea53f in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff7fdc2c0 (LWP 15750)):
#0  0x00007ffff74d1e47 in sched_yield () from /usr/lib/libc.so.6
#1  0x000000000065ed95 in NPar::TLocalExecutor::ExecRange(TIntrusivePtr<NPar::ILocallyExecutable, TDefaultIntrusivePtrOps<NPar::ILocallyExecutable> >, int, int, int) ()
#2  0x000000000065f0b7 in NPar::TLocalExecutor::ExecRange(std::__y1::function<void (int)>, int, int, int) ()
#3  0x000000000097e017 in NCatboostCuda::TDataProviderBuilder::Finish() ()
#4  0x00000000002a1bd9 in NCB::TAsyncProcDataProviderBase<TString>::FinalizeBuilder(bool, NCB::IPoolBuilder*) ()
#5  0x00000000005176d9 in NCB::ReadPool(NCB::TPathWithScheme const&, NCB::TPathWithScheme const&, NCatboostOptions::TDsvPoolFormatParams const&, TVector<int, std::__y1::allocator<int> > const&, bool, TVector<TString, std::__y1::allocator<TString> > const&, NPar::TLocalExecutor*, NCB::IPoolBuilder*) ()
#6  0x00000000003539f0 in NCatboostCuda::TrainModel(NCatboostOptions::TPoolLoadParams const&, NCatboostOptions::TOutputFilesOptions const&, NJson::TJsonValue const&) ()
#7  0x000000000025192f in mode_fit(int, char const**) ()
#8  0x00000000006222fe in PtrWrapper::operator()(TVector<TString, std::__y1::allocator<TString> > const&) ()
#9  0x0000000000620f65 in TModChooser::Run(TVector<TString, std::__y1::allocator<TString> > const&) const ()
#10 0x00000000006209ee in TModChooser::Run(int, char const**) const ()
#11 0x00000000002688b7 in main ()
(gdb)
```

**Comment by ctlaltdefeat** [comment]
OK!
So it turns out that this toy train.tsv was incorrectly generated and had an empty column in the end (tabs on all lines), which caused the problem with cmdline - after fixing it, it works.
With the python I'm definitely using a proper dataset, but if you say the issue there is different I can certainly wait.
Thanks for the patience!
