### ISSUE TITLE
NCudaLib::TOutOfMemoryError

### ISSUE THREAD

**Issue by kitianFresh** [catboost/catboost#407]
Problem: {_catboost.CatboostError: Invalid param `pinned_memory_size`.}
catboost version: {0.8.1}
Operating System: {Ubuntu 16.04}
CPU: {CPU}
GPU: {nvidia k80}
 
when i use `pinned_memory_size` param described in document, it raise error: 
```
Traceback (most recent call last):
  File "catbst.py", line 147, in <module>
    model.clf = CatBoostClassifier(task_type='GPU' if gpu_mode else 'CPU', gpu_cat_features_storage='CpuPinnedMemory', pinned_memory_size=2147483648)
  File "/usr/local/lib/python2.7/dist-packages/catboost/core.py", line 1623, in __init__
    super(CatBoostClassifier, self).__init__(params)
  File "/usr/local/lib/python2.7/dist-packages/catboost/core.py", line 702, in __init__
    self._check_params(params)
  File "/usr/local/lib/python2.7/dist-packages/catboost/core.py", line 734, in _check_params
    raise CatboostError("Invalid param `{}`.".format(param))
_catboost.CatboostError: Invalid param `pinned_memory_size`.
```

following is  my  code snnipet where error took place.
```
model.clf = CatBoostClassifier(task_type='GPU' if gpu_mode else 'CPU', gpu_cat_features_storage='CpuPinnedMemory', pinned_memory_size=1073741824*4)
```

**Comment by Noxoomo** [comment]
Hi!

We fixed in 0.9.1.1, or you could use CatBoost object with additional parameter "loss-function": "Logloss" instead of CatBoostClassifier, this should also work

**Comment by kitianFresh** [comment]
@Noxoomo Thanks for your reply! I upgrade my catboost from 0.8.1.1 to 0.9.1.1, but it raised another error about out of memory, my vm's memory is 104G, swap 80G,  and GPU is nvidia P100 which's memory is 16G.  My data size is (52134536, 51).

following is my error:
```
Learning rate set to 0.24409
Application terminated with error: (NCudaLib::TOutOfMemoryError) catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:305: Error: Out of memory. Requested 198.8776855; Free 82.55537033
uncaught exception:
    address -> 0x10790f908
    what() -> "catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:305: Error: Out of memory. Requested 198.8776855; Free 82.55537033"
    type -> NCudaLib::TOutOfMemoryError
Aborted (core dumped)
```

**Comment by Noxoomo** [comment]
52134536, 51 — 51 features, right?
And how many categorical features are there? Could you please provide output with "logging_level": "Debug"

**Comment by kitianFresh** [comment]
Yeah, 51 features, and there are five categorical features. following is the error after debug:

```
Requested devices:
  0. Tesla P100-PCIE-16GB (compute capability 6.0)
Free memory on device #0 15098.40937MB
Build catFeatures compressed dataset for 3 features and 52134536 documents
Memory usage at #0: 99.43945313MB
Build catFeatures compressed dataset for 3 features and 52134536 documents
Memory usage at #0: 99.43945313MB
Ctr computation for permutation #0 is finished
Ctr computation for permutation #1 is finished
Ctr computation for permutation #2 is finished
Ctr computation for permutation #3 is finished
Compressed index written in 63.600601 seconds
Compressed DataSet Learn permutation-independent features with features #48 features
Grid policy BinaryFeatures
Memory usage for 2 features, 52134536 documents at #0: 198.8774719 MB
Grid policy HalfByteFeatures
Memory usage for 3 features, 52134536 documents at #0: 198.8774719 MB
Grid policy OneByteFeatures
Memory usage for 43 features, 52134536 documents at #0: 2187.652191 MB
Compressed DataSet Learn permutation dependent features #0 with features #9 features
Grid policy HalfByteFeatures
Memory usage for 9 features, 52134536 documents at #0: 397.7549438 MB
Compressed DataSet Learn permutation dependent features #1 with features #9 features
Grid policy HalfByteFeatures
Memory usage for 9 features, 52134536 documents at #0: 397.7549438 MB
Compressed DataSet Learn permutation dependent features #2 with features #9 features
Grid policy HalfByteFeatures
Memory usage for 9 features, 52134536 documents at #0: 397.7549438 MB
Compressed DataSet Learn permutation dependent features #3 with features #9 features
Grid policy HalfByteFeatures
Memory usage for 9 features, 52134536 documents at #0: 397.7549438 MB
Compressed DataSet Test dataset with features #57 features
Grid policy BinaryFeatures
Memory usage for 2 features, 52134536 documents at #0: 198.8774719 MB
Grid policy HalfByteFeatures
Memory usage for 12 features, 52134536 documents at #0: 397.7549438 MB
Grid policy OneByteFeatures
Memory usage for 43 features, 52134536 documents at #0: 2187.652191 MB
Application terminated with error: (NCudaLib::TOutOfMemoryError) catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:305: Error: Out of memory. Requested 198.8776855; Free 82.55537033
uncaught exception:
    address -> 0x10790e288
    what() -> "catboost/cuda/cuda_lib/memory_pool/stack_like_memory_pool.h:305: Error: Out of memory. Requested 198.8776855; Free 82.55537033"
    type -> NCudaLib::TOutOfMemoryError
Aborted (core dumped)
```

**Comment by kitianFresh** [comment]
@Noxoomo I use 
`gpu_cat_features_storage='CpuPinnedMemory', pinned_memory_size=1073741824*4`. I think it will use ram when gpu memory is not enough, but cuda it still report some memory error.

**Comment by kitianFresh** [comment]
@Noxoomo I use 
`gpu_cat_features_storage='CpuPinnedMemory', pinned_memory_size=1073741824*4`. I think it will use ram when gpu memory is not enough, but cuda it still report some memory error.

**Comment by annaveronika** [comment]
You can set max_ctr_complexity to 1 or to 2 and set border_count=16, this should help.
We will provide a tutorial how to deal with out of memory errors on GPU. Please, follow issue #428

**Comment by FAFUuser** [comment]
Hi @kitianFresh  how dou you deal with out of memory?
