### ISSUE TITLE
catboost/cuda/methods/tree_ctr_memory_usage_estimator.h:133: Error: not enough memory for tree-ctrs?

### ISSUE THREAD

**Issue by kitianFresh** [catboost/catboost#415]
Problem: {_catboost.CatboostError: catboost/cuda/methods/tree_ctr_memory_usage_estimator.h:133: Error: not enough memory for tree-ctrs: 2666.668652 available, need at least 4902.937321}
catboost version: {0.9.1.1}
Operating System: {ubuntu 16.04}
CPU: {CPU}
GPU: {Tesla P100-PCIE-16GB}

I use catboost model like this `CatBoostClassifier(iterations=3000, task_type='GPU' if gpu_mode else 'CPU', used_ram_limit='200gb', gpu_cat_features_storage='CpuPinnedMemory', pinned_memory_size=2147483648, logging_level='Debug')` to deal with (52134536,52) data, but it raise following error, I observe that my memory 200G is enough, my data size is 10G.

```
Learning rate set to 0.152525
Requested devices:
  0. Tesla P100-PCIE-16GB (compute capability 6.0)
  1. Tesla P100-PCIE-16GB (compute capability 6.0)
Free memory on device #0 15098.40937MB
Free memory on device #1 15173.28125MB
Build catFeatures compressed dataset for 4 features and 52134536 documents
Memory usage at #0: 66.29296875MB
Memory usage at #1: 66.29296875MB
Build catFeatures compressed dataset for 4 features and 52134536 documents
Memory usage at #0: 66.29296875MB
Memory usage at #1: 66.29296875MB


Ctr computation for permutation #0 is finished
Ctr computation for permutation #1 is finished
Ctr computation for permutation #2 is finished
Ctr computation for permutation #3 is finished
Compressed index written in 46.390163 seconds
Compressed DataSet Learn permutation-independent features with features #50 features
Grid policy BinaryFeatures
Memory usage for 1 features, 52134536 documents at #0: 198.8774719 MB
Grid policy BinaryFeatures
Memory usage for 2 features, 52134536 documents at #1: 198.8774719 MB
Grid policy HalfByteFeatures
Memory usage for 2 features, 52134536 documents at #0: 198.8774719 MB
Grid policy HalfByteFeatures
Memory usage for 2 features, 52134536 documents at #1: 198.8774719 MB
Grid policy OneByteFeatures
Memory usage for 21 features, 52134536 documents at #0: 1193.264832 MB
Grid policy OneByteFeatures
Memory usage for 22 features, 52134536 documents at #1: 1193.264832 MB
Compressed DataSet Learn permutation dependent features #0 with features #12 features
Grid policy HalfByteFeatures
Memory usage for 6 features, 52134536 documents at #0: 198.8774719 MB
Grid policy HalfByteFeatures
Memory usage for 6 features, 52134536 documents at #1: 198.8774719 MB
Compressed DataSet Learn permutation dependent features #1 with features #12 features
Grid policy HalfByteFeatures
Memory usage for 6 features, 52134536 documents at #0: 198.8774719 MB
Grid policy HalfByteFeatures
Memory usage for 6 features, 52134536 documents at #1: 198.8774719 MB
Compressed DataSet Learn permutation dependent features #2 with features #12 features
Grid policy HalfByteFeatures
Memory usage for 6 features, 52134536 documents at #0: 198.8774719 MB
Grid policy HalfByteFeatures
Memory usage for 6 features, 52134536 documents at #1: 198.8774719 MB
Compressed DataSet Learn permutation dependent features #3 with features #12 features
Grid policy HalfByteFeatures
Memory usage for 6 features, 52134536 documents at #0: 198.8774719 MB
Grid policy HalfByteFeatures
Memory usage for 6 features, 52134536 documents at #1: 198.8774719 MB
Compressed DataSet Test dataset with features #62 features
Grid policy BinaryFeatures
Memory usage for 1 features, 52134536 documents at #0: 198.8774719 MB
Grid policy BinaryFeatures
Memory usage for 2 features, 52134536 documents at #1: 198.8774719 MB
Grid policy HalfByteFeatures
Memory usage for 8 features, 52134536 documents at #0: 198.8774719 MB
Grid policy HalfByteFeatures
Memory usage for 8 features, 52134536 documents at #1: 198.8774719 MB
Grid policy OneByteFeatures
Memory usage for 21 features, 52134536 documents at #0: 1193.264832 MB
Grid policy OneByteFeatures
Memory usage for 22 features, 52134536 documents at #1: 1193.264832 MB
0:      total: 354ms    remaining: 17m 42s



Traceback (most recent call last):
  File "catbst.py", line 117, in <module>
    model.clf.fit(X_train, y_train.ravel(), cat_features=cat_feature_inds, eval_set=(X_train, y_train.ravel()))
  File "/usr/local/lib/python2.7/dist-packages/catboost/core.py", line 2058, in fit
    silent, early_stopping_rounds)
  File "/usr/local/lib/python2.7/dist-packages/catboost/core.py", line 1072, in _fit
    self._train(train_pool, eval_sets, params, allow_clear_pool)
  File "/usr/local/lib/python2.7/dist-packages/catboost/core.py", line 818, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool)
  File "_catboost.pyx", line 1300, in _catboost._CatBoost._train
  File "_catboost.pyx", line 1319, in _catboost._CatBoost._train
_catboost.CatboostError: catboost/cuda/methods/tree_ctr_memory_usage_estimator.h:133: Error: not enough memory for tree-ctrs: 2666.668652 available, need at least 4902.937321

```

**Comment by annaveronika** [comment]
You can try setting max_ctr_complexity=1 or 2 to reduce amount of memory that is used for feature combinations. We will provide a tutorial for that, please follow #428
