### ISSUE TITLE
Error saving the model

### ISSUE THREAD

**Issue by tezer** [catboost/catboost#47]
I am trying to save a trained model:
`clf.save_model(fname='cb.model')`

But I get an error message:

`Traceback (most recent call last):
  File "/home/myhome/PycharmProjects/123/CatBoost/catboost_train.py", line 120, in <module>
    clf.save_model(fname='cb.model')
  File "/home/myhome/virtualenv/tensorflow/lib/python3.5/site-packages/catboost/core.py", line 638, in save_model
    self._save_model(fname, format, export_parameters)
  File "_catboost.pyx", line 768, in _catboost._CatBoostBase._save_model (/home/donskov/.ya/build/build_root/6d786f6630393533326272727668366a/catboost/python-package/catboost/_catboost.pyx.cpp:14763)
  File "_catboost.pyx", line 667, in _catboost._CatBoost._save_model (/home/donskov/.ya/build/build_root/6d786f6630393533326272727668366a/catboost/python-package/catboost/_catboost.pyx.cpp:11571)
  File "_catboost.pyx", line 669, in _catboost._CatBoost._save_model (/home/donskov/.ya/build/build_root/6d786f6630393533326272727668366a/catboost/python-package/catboost/_catboost.pyx.cpp:11458)
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_TString (/home/donskov/.ya/build/build_root/6d786f6630393533326272727668366a/catboost/python-package/catboost/_catboost.pyx.cpp:17179)
TypeError: expected bytes, str found`

Python 3.5, CatBoost 0.1.1.5

**Comment by sriramchit** [comment]
Windows 10, Python 3.6.2 

Im facing a similar problem with the kaggle titanic notebook 
model.save_model('catboost_model.dump')

Error
************
devtools\python362\lib\site-packages\catboost\core.py in save_model(self, fname, format, export_parameters)
    636         if not isinstance(fname, STRING_TYPES):
    637             raise CatboostError("Invalid fname type={}: must be str().".format(type(fname)))
--> 638         self._save_model(fname, format, export_parameters)
    639 
    640     def load_model(self, fname):

devtools\python362\lib\site-packages\catboost\_catboost.pyd in string.from_py.__pyx_convert_string_from_py_TString (c:\users\donskov\.ya\build\build_root\6830666230336978356274386c383661\catboost\python-package\catboost\_catboost.pyx.cpp:17179)()

TypeError: expected bytes, str found

**Comment by annaveronika** [comment]
this is fixed now, try updating to the last version.
