### ISSUE TITLE
CatboostError: Invalid cat_features

### ISSUE THREAD

**Issue by artemidius** [catboost/catboost#528]
Hi! I'm just scratching the surface with this code
```python
train_df = pd.read_csv('snapshots.csv')
y = train_df.RESULT
X = train_df.drop('RESULT', axis=1)
cat_features = range(0, X.shape[1])
X_train, X_validation, y_train, y_validation = train_test_split(X, y, train_size=0.8, random_state=1234)
model = CatBoostClassifier(
    thread_count=2,
    iterations=5,
    random_seed=1136926949945377,
)
model.fit(
    X_train, y_train,
    cat_features=cat_features,
    eval_set=(X_validation, y_validation),
    logging_level='Silent'
)
```
The last line runs into error
```
Traceback (most recent call last):
  File "/PycharmProjects/untitled2/main.py", line 27, in <module>
    logging_level='Silent'
  File "/PycharmProjects/untitled2/venv/lib/python3.6/site-packages/catboost/core.py", line 2163, in fit
    silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval)
  File "/PycharmProjects/untitled2/venv/lib/python3.6/site-packages/catboost/core.py", line 1100, in _fit
    train_pool = _build_train_pool(X, y, cat_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, column_description)
  File "/PycharmProjects/untitled2/venv/lib/python3.6/site-packages/catboost/core.py", line 666, in _build_train_pool
    group_weight=group_weight, subgroup_id=subgroup_id, pairs_weight=pairs_weight, baseline=baseline)
  File "/PycharmProjects/untitled2/venv/lib/python3.6/site-packages/catboost/core.py", line 296, in __init__
    self._init(data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names)
  File "/PycharmProjects/untitled2/venv/lib/python3.6/site-packages/catboost/core.py", line 612, in _init
    self._check_cf_type(cat_features)
  File "/PycharmProjects/untitled2/venv/lib/python3.6/site-packages/catboost/core.py", line 328, in _check_cf_type
    raise CatboostError("Invalid cat_features type={}: must be list() or np.ndarray().".format(type(cat_features)))
_catboost.CatboostError: Invalid cat_features type=<class 'range'>: must be list() or np.ndarray().
```

`print(train_df.head())` prints
```
   RESULT    SYMBOL      ...         Feature_7999   Feature_8000
0       0    QKCBTC      ...                 -999           -999
1       0    BNBBTC      ...                false           true
2       0   EOSUSDT      ...                 -999           -999
3       0    WTCBTC      ...                 -999           -999
4       0    XRPETH      ...                 true           true
```

I would be grateful for any advice.

catboost version: 0.10.4.1
Operating System: MacOS
CPU: 2,8 GHz Intel Core i7

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Hi artemidius
Most likely, list(...) is missing in cat_features = range(0, X.shape[1]) around range(...).
E.

**Comment by annaveronika** [comment]
This should solve the issue
