### ISSUE TITLE
Problem with save_model

### ISSUE THREAD

**Issue by nirvana1122** [catboost/catboost#57]
I am having problem with save_model. I was able to pickle and unpickle it.

>>classifier.save_model(fileName, format="cbm")
Traceback (most recent call last):

  File "<ipython-input-34-577684e0c859>", line 1, in <module>
    classifier.save_model(fileName, format="cbm")

  File "C:\Anaconda3\lib\site-packages\catboost\core.py", line 638, in save_model
    self._save_model(fname, format, export_parameters)

  File "_catboost.pyx", line 768, in _catboost._CatBoostBase._save_model (c:\users\donskov\.ya\build\build_root\37396b7a77396336667370646e6e6a34\catboost\python-package\catboost\_catboost.pyx.cpp:14763)

  File "_catboost.pyx", line 667, in _catboost._CatBoost._save_model (c:\users\donskov\.ya\build\build_root\37396b7a77396336667370646e6e6a34\catboost\python-package\catboost\_catboost.pyx.cpp:11571)

  File "_catboost.pyx", line 669, in _catboost._CatBoost._save_model (c:\users\donskov\.ya\build\build_root\37396b7a77396336667370646e6e6a34\catboost\python-package\catboost\_catboost.pyx.cpp:11458)

  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_TString (c:\users\donskov\.ya\build\build_root\37396b7a77396336667370646e6e6a34\catboost\python-package\catboost\_catboost.pyx.cpp:17179)

TypeError: expected bytes, str found

**Comment by nosyrev** [comment]
Same problem, but only with python3.6
OS: macOS Sierra 10.12.6
With python2 (2.7.10) all works

How to reproduce:
```(python)
>>> import catboost
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module '_catboost' does not match runtime version 3.6
  return f(*args, **kwds)
>>> catboost.__version__
'0.1.1.5'
>>> clf.fit([[1, 1, 1, 1], [0, 0, 0, 0]], [1, 0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'clf' is not defined
>>> clf = catboost.CatBoostRegressor()
>>> clf.fit([[1, 1, 1, 1], [0, 0, 0, 0]], [1, 0])
<catboost.core.CatBoostRegressor object at 0x1012bee80>
>>> clf.save_model("test.model")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/catboost/core.py", line 638, in save_model
    self._save_model(fname, format, export_parameters)
  File "_catboost.pyx", line 768, in _catboost._CatBoostBase._save_model (/Users/donskov/.ya/build/build_root/676262796c7473396e3470616173676a/catboost/python-package/catboost/_catboost.pyx.cpp:14763)
  File "_catboost.pyx", line 667, in _catboost._CatBoost._save_model (/Users/donskov/.ya/build/build_root/676262796c7473396e3470616173676a/catboost/python-package/catboost/_catboost.pyx.cpp:11571)
  File "_catboost.pyx", line 669, in _catboost._CatBoost._save_model (/Users/donskov/.ya/build/build_root/676262796c7473396e3470616173676a/catboost/python-package/catboost/_catboost.pyx.cpp:11458)
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_TString (/Users/donskov/.ya/build/build_root/676262796c7473396e3470616173676a/catboost/python-package/catboost/_catboost.pyx.cpp:17179)
TypeError: expected bytes, str found
```

**Comment by annaveronika** [comment]
This is fixed now, try updating to the last version.
