### ISSUE TITLE
ModuleNotFoundError: No module named '_catboost'

### ISSUE THREAD

**Issue by lbogomolov** [catboost/catboost#576]
I'd like to reopen https://github.com/catboost/catboost/issues/319 but cannot do so.

The problem is the same: I  cannot import CatBoostClassifier with ModuleNotFoundError: No module named '_catboost'.

```
(base) lbogomolov@m:~$ pip install catboost --no-cache-dir
Collecting catboost
  Downloading https://files.pythonhosted.org/packages/19/ea/d6cbdf03fb1e8ea8c7c7a0b37b89c8f8b3825ec625d428d49b6230656c00/catboost-0.11.1-cp36-none-manylinux1_x86_64.whl (55.3MB)
    100% |████████████████████████████████| 55.3MB 11.5MB/s
Requirement already satisfied: enum34 in ./anaconda3/lib/python3.6/site-packages (from catboost) (1.1.6)
Requirement already satisfied: numpy>=1.11.1 in ./anaconda3/lib/python3.6/site-packages (from catboost) (1.14.3)
Requirement already satisfied: six in ./anaconda3/lib/python3.6/site-packages (from catboost) (1.11.0)
Requirement already satisfied: pandas>=0.19.1 in ./anaconda3/lib/python3.6/site-packages (from catboost) (0.23.0)
Requirement already satisfied: python-dateutil>=2.5.0 in ./anaconda3/lib/python3.6/site-packages (from pandas>=0.19.1->catboost) (2.7.3)
Requirement already satisfied: pytz>=2011k in ./anaconda3/lib/python3.6/site-packages (from pandas>=0.19.1->catboost) (2018.4)
Installing collected packages: catboost
Successfully installed catboost-0.11.1

(base) lbogomolov@m:~$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from catboost import CatBoostClassifier
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lbogomolov/anaconda3/lib/python3.6/site-packages/catboost/__init__.py", line 1, in <module>
    from .core import FeaturesData, EFstrType, Pool, CatBoost, CatBoostClassifier, CatBoostRegressor, CatboostError, cv, train, sum_models  # noqa
  File "/home/lbogomolov/anaconda3/lib/python3.6/site-packages/catboost/core.py", line 52, in <module>
    _catboost = get_catboost_bin_module()
  File "/home/lbogomolov/anaconda3/lib/python3.6/site-packages/catboost/core.py", line 48, in get_catboost_bin_module
    import _catboost
ModuleNotFoundError: No module named '_catboost'
>>>
```

OS: Bash on Ubuntu on Windows 10
```
lbogomolov@m:~$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

_Originally posted by @lbogomolov in https://github.com/catboost/catboost/issue_comments#issuecomment-444944560_

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Now noexecstack is on by default.
https://github.com/catboost/catboost/commit/4883e73504aadf44e2689c7059770c55536eeeab
