### ISSUE TITLE
Processor for scheme [C] not found

### ISSUE THREAD

**Issue by gabrielpeixoto** [catboost/catboost#579]
Problem:
I called `train_pool = Pool(train_file, column_description=description_file)` and I got this error:

```
Traceback (most recent call last):
  File "C:/Users/escav/PycharmProjects/crmaccess/creditscore/main.py", line 26, in <module>
    treinamento.treinar(train_file=TRAIN_FILE, descricao_file=CD_FILE)
  File "C:\Users\escav\PycharmProjects\crmaccess\creditscore\classification.py", line 13, in treinar
    train_pool = Pool(train_file, column_description=descricao_file)
  File "C:\Python37\lib\site-packages\catboost\core.py", line 271, in __init__
    self._read(data, column_description, pairs, delimiter, has_header, thread_count)
  File "C:\Python37\lib\site-packages\catboost\core.py", line 577, in _read
    self._read_pool(pool_file, column_description, pairs, delimiter[0], has_header, thread_count)
  File "_catboost.pyx", line 997, in _catboost._PoolBase._read_pool
  File "_catboost.pyx", line 1018, in _catboost._PoolBase._read_pool
_catboost.CatboostError: c:/goagent/pipelines/buildmaster/catboost.git/catboost/libs/data_util/path_with_scheme.h:49: Processor for scheme [C] not found
```

train_file:
```
0	1	5	2	0	0	0	0	0	1	6	0	0	0	0	1	3
0	1	6	5	0	0	0	0		1	3	1	3	1	0	6	1
0	1	6	5	0	0	0	0		1	3	1	3	1	0	6	1
0	1	4	2	4	4	0	0	0	2	4	0	0	0	5	4	1
0	1	4	2	0	0	0	0		1	4	0	0	0	5	4	1
```
description_file
```
0	Target
1	Num	Sexo
2	Num	Idade
3	Num	Estado Civil
4	Num	Experiencia Trabalho
5	Num	Tempo Mesmo Lugar
6	Num	Tem Avalista
7	Num	Qtd. Referências
8	Num	Tem outras receitas
9	Num	Qtd. Dependentes
10	Num	Qtd. Desembolsos
11	Num	SPC Valor
12	Num	SPC Última ocorrência
13	Num	SPC quantidade
14	Num	SPC Valor Score risco
15	Num	SPC Score Risco
16	Num	Bacen Status
```

catboost version:  0.11.2
Operating System: Windows 10

**Comment by annaveronika** [comment]
what are your train_file and description_file values?

**Comment by annaveronika** [comment]
You probably have problems with slashes

**Comment by gabrielpeixoto** [comment]
My mistake, here the right values:

'C://xampp//htdocs//crmaccess//storage//app//creditscore///train'
'C://xampp//htdocs//crmaccess//storage//app//creditscore///train.cd'

**Comment by bratao** [comment]
This happens to me too om Windows!

I guess it somehow try to extract the path drive on Windows as a scheme ( C: part)

**Comment by Evgueni-Petrov-aka-espetrov** [comment]
Hi all,
Could you please backslash backslashes on Windows, as follows?
`C:\\xampp\\htdocs\\crmaccess\\storage\\app\\creditscore\\train`
