### ISSUE TITLE
Two issues with CatBoostClasifier

### ISSUE THREAD

**Issue by yt87** [catboost/catboost#615]
Problem: My training dataset consists of real numbers, with possible missing values. Here is a sample:

 t2ms1 | t2ms0 | t2ms | r2ms | cbot | cdep | evl0 | cwd | swd | th50 | twba
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
265.500000 | 263.8 | 266.2 | 92.19358 | 1895.772827 | 4677.980246 | NaN | -0.995077 | -0.099103 | 5192.0420 | 269.03622
266.200012 | 263.8 | 266.9 | 92.80827 | 1886.454905 | 3626.603031 | NaN | -0.994314 | -0.106486 | 5198.1104 | 269.38583
274.100006 | 273.1 | 274.1 | 94.89946 | 1552.607742 | 8072.396604 | 27.561523 | -0.997113 | 0.075933 | 5360.1330 | NaN
274.100006 | 273.1 | 273.1 | 95.67526 | 1457.566381 | 8566.423931 | 9.009004 | -0.997300 | 0.073434 | 5360.0566 | 272.77380
273.100006 | 273.2 | 272.4 | 95.18951 | 1221.076688 | 7706.523774 | -5.823495 | -0.939197 | 0.343379 | 5358.9150 | NaN

Target is binary. Model parameters as follows:
```
params = {'logging_level': 'Verbose',
          'loss_function': 'Logloss:border=0.01',
          'use_best_model': True,
          'nan_mode': 'Forbidden',
          'od_type': 'Iter',
          'od_wait': 40,
          'learning_rate': 0.02,
          'iterations': 200,
          }
```
I expected that `nan_mode='Forbidden` would raise an exception. However python crashes with traceback (in Jupyter):
```
libunwind: decodeEHHdr /var/lib/go-agent/pipelines/BuildMaster/catboost.git/contrib/libs/libunwind_master/src/EHHeaderParser.hpp:62 - Unsupported .eh_frame_hdr version
[I 03:46:54.191 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
```
Filling missing values beforehand fixes this issue. Is this a bug?

The second issue is that the `border` parameter value for `loss_function` does not seem to have any effect, neither in log output, predicted probabilities or classes. Bug or obsolete documentation?

catboost version: {0.12.1}
Operating System: {Fedora 29}
CPU: {CPU}
# GPU: {GPU}

**Comment by yt87** [comment]
I did some debugging on the attached file.
[x.csv.gz](https://github.com/catboost/catboost/files/2754028/x.csv.gz)
The code is:

```
import numpy as np
import pandas as pd
import catboost as cb

ptyp = 24
df = pd.read_csv('x.csv', index_col='vtim', parse_dates=['vtim'])
df = df.loc['2010-06-20 00:00:00':'2010-07-11 23:00:00']
df = df[df['PT']>0]
y = (df['PT']&ptyp != 0).astype(np.int64)
X = df.drop('PT', axis=1)
cbc = cb.CatBoostClassifier(nan_mode='Forbidden')
pool = cb.Pool(X, y)
#print('=====PPP', pool.get_features())
cbc.fit(pool)
```
I did get crashes by modifying the date selection line, though I was not able to see a pattern. Sometimes an exception is raised:
```
Traceback (most recent call last):
  File "x.py", line 14, in <module>
    cbc.fit(pool)
  File "/mnt/sdc1/home/gtrojan/miniconda3/envs/devel1/lib/python3.7/site-packages/catboost/core.py", line 2180, in fit
    silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval)
  File "/mnt/sdc1/home/gtrojan/miniconda3/envs/devel1/lib/python3.7/site-packages/catboost/core.py", line 1126, in _fit
    self._train(train_pool, eval_sets, params, allow_clear_pool)
  File "/mnt/sdc1/home/gtrojan/miniconda3/envs/devel1/lib/python3.7/site-packages/catboost/core.py", line 828, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool)
  File "_catboost.pyx", line 2294, in _catboost._CatBoost._train
  File "_catboost.pyx", line 2314, in _catboost._CatBoost._train
_catboost.CatboostError: catboost/libs/data_new/quantization.cpp:165: Feature #4: There are nan factors and nan values for  float features are not allowed. Set nan_mode != Forbidden.
```
When the crash occurs, the full traceback is:
```
libunwind: decodeEHHdr /var/lib/go-agent/pipelines/BuildMaster/catboost.git/contrib/libs/libunwind_master/src/EHHeaderParser.hpp:62 - Unsupported .eh_frame_hdr version

Thread 11 "ParLocalExecuto" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffd82d1700 (LWP 15652)]
0x00007ffff7c5453f in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff7c5453f in raise () from /lib64/libc.so.6
#1  0x00007ffff7c3e895 in abort () from /lib64/libc.so.6
#2  0x00007fffbe43a0ea in assert_rtn(char const*, char const*, int, char const*) ()
   from /mnt/sdc1/home/gtrojan/miniconda3/envs/devel1/lib/python3.7/site-packages/catboost/./_catboost.so
#3  0x00007fffbe43d2b6 in libunwind::LocalAddressSpace::findUnwindSections(unsigned long, libunwind::UnwindInfoSections&)::{lambda(dl_phdr_info*, unsigned long, void*)#1}::operator()(dl_phdr_info*, unsigned long, void*) const ()
   from /mnt/sdc1/home/gtrojan/miniconda3/envs/devel1/lib/python3.7/site-packages/catboost/./_catboost.so
#4  0x00007ffff7d5515f in dl_iterate_phdr () from /lib64/libc.so.6
#5  0x00007fffbe43a72f in libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::setInfoBasedOnIPRegister(bool) ()
   from /mnt/sdc1/home/gtrojan/miniconda3/envs/devel1/lib/python3.7/site-packages/catboost/./_catboost.so
#6  0x00007fffbe43a5aa in libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step() ()
   from /mnt/sdc1/home/gtrojan/miniconda3/envs/devel1/lib/python3.7/site-packages/catboost/./_catboost.so
#7  0x00007fffbe440bb8 in _Unwind_Backtrace ()
   from /mnt/sdc1/home/gtrojan/miniconda3/envs/devel1/lib/python3.7/site-package--Type <RET> for more, q to quit, c to continue without paging--c
s/catboost/./_catboost.so
#8  0x00007fffbe52de43 in TBackTrace::Capture() () from /mnt/sdc1/home/gtrojan/miniconda3/envs/devel1/lib/python3.7/site-packages/catboost/./_catboost.so
#9  0x00007fffbef79d15 in NCB::TQuantizationImpl::Do(NCB::TQuantizationOptions const&, TIntrusivePtr<NCB::TDataProviderTemplate<NCB::TRawObjectsDataProvider>, TDefaultIntrusivePtrOps<NCB::TDataProviderTemplate<NCB::TRawObjectsDataProvider> > >, TIntrusivePtr<NCB::TQuantizedFeaturesInfo, TDefaultIntrusivePtrOps<NCB::TQuantizedFeaturesInfo> >, bool, TRestorableFastRng64*, NPar::TLocalExecutor*)::{lambda(NCB::TFeatureIdx<(EFeatureType)0>)#1}::operator()(NCB::TFeatureIdx<(EFeatureType)0>) const::{lambda()#1}::operator()() const () from /mnt/sdc1/home/gtrojan/miniconda3/envs/devel1/lib/python3.7/site-packages/catboost/./_catboost.so
#10 0x00007fffbe58104c in std::__y1::__function::__func<NCB::ExecuteTasksInParallel(TVector<std::__y1::function<void ()>, std::__y1::allocator<std::__y1::function<void ()> > >*, NPar::TLocalExecutor*)::$_0, std::__y1::allocator<NCB::ExecuteTasksInParallel(TVector<std::__y1::function<void ()>, std::__y1::allocator<std::__y1::function<void ()> > >*, NPar::TLocalExecutor*)::$_0>, void (int)>::operator()(int&&) () from /mnt/sdc1/home/gtrojan/miniconda3/envs/devel1/lib/python3.7/site-packages/catboost/./_catboost.so
#11 0x00007fffbe56f654 in (anonymous namespace)::TFunctionWrapperWithPromise::LocalExec(int) () from /mnt/sdc1/home/gtrojan/miniconda3/envs/devel1/lib/python3.7/site-packages/catboost/./_catboost.so
#12 0x00007fffbe56faee in (anonymous namespace)::TLocalRangeExecutor::LocalExec(int) () from /mnt/sdc1/home/gtrojan/miniconda3/envs/devel1/lib/python3.7/site-packages/catboost/./_catboost.so
#13 0x00007fffbe56d363 in NPar::TLocalExecutor::TImpl::HostWorkerThread(void*) () from /mnt/sdc1/home/gtrojan/miniconda3/envs/devel1/lib/python3.7/site-packages/catboost/./_catboost.so
#14 0x00007fffbe54ddd2 in (anonymous namespace)::TPosixThread::ThreadProxy(void*) () from /mnt/sdc1/home/gtrojan/miniconda3/envs/devel1/lib/python3.7/site-packages/catboost/./_catboost.so
#15 0x00007ffff7f8358e in start_thread () from /lib64/libpthread.so.0
#16 0x00007ffff7d196a3 in clone () from /lib64/libc.so.6
(gdb) 
```

**Comment by kizill** [comment]
fixed libunwind issues in https://github.com/catboost/catboost/commit/c9a3e0cfae2da0e441e91c07883df472e3dc9fbc
with https://github.com/llvm-mirror/libunwind/commit/216d7214f8b99a575883e5b8bec871ab1a6ea42e
