### ISSUE TITLE
Can't save model. Seems that some path hardcoded inside

### ISSUE THREAD

**Issue by glebreutov** [catboost/catboost#68]
When trying to save a model, following exception occurs. Look's like developer path has hardcoded inside lib: `/Users/donskov/.ya/build/build_root/`
I use Python 3.6 on macOS Sierra

```Traceback (most recent call last):
  File "/Users/glebreutov/Py/draw3d/train_free_catboost.py", line 42, in <module>
    model.save_model(fname="/Users/glebreutov/Py/draw3d/catboobs/xmodel")
  File "/Users/glebreutov/Py/draw3d/3denv/lib/python3.6/site-packages/catboost/core.py", line 638, in save_model
    self._save_model(fname, format, export_parameters)
  File "_catboost.pyx", line 768, in _catboost._CatBoostBase._save_model (/Users/donskov/.ya/build/build_root/676262796c7473396e3470616173676a/catboost/python-package/catboost/_catboost.pyx.cpp:14763)
  File "_catboost.pyx", line 667, in _catboost._CatBoost._save_model (/Users/donskov/.ya/build/build_root/676262796c7473396e3470616173676a/catboost/python-package/catboost/_catboost.pyx.cpp:11571)
  File "_catboost.pyx", line 669, in _catboost._CatBoost._save_model (/Users/donskov/.ya/build/build_root/676262796c7473396e3470616173676a/catboost/python-package/catboost/_catboost.pyx.cpp:11458)
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_TString (/Users/donskov/.ya/build/build_root/676262796c7473396e3470616173676a/catboost/python-package/catboost/_catboost.pyx.cpp:17179)
TypeError: expected bytes, str found```

**Comment by raidhon** [comment]
Similarly.
Debian 9 - Python 3.6.2
```
Traceback (most recent call last):
[ 1874.99992978  1855.          1855.          1855.        ]
  File "/home/raidhon/Project/python/neyral_training/train_boost.py", line 30, in <module>
    model.save_model(dir + "/model/rmod")
  File "/home/raidhon/Progs/python/lib/python3.6/site-packages/catboost/core.py", line 638, in save_model
    self._save_model(fname, format, export_parameters)
  File "_catboost.pyx", line 768, in _catboost._CatBoostBase._save_model (/home/donskov/.ya/build/build_root/686b74643362767a7270306a66633031/catboost/python-package/catboost/_catboost.pyx.cpp:14763)
  File "_catboost.pyx", line 667, in _catboost._CatBoost._save_model (/home/donskov/.ya/build/build_root/686b74643362767a7270306a66633031/catboost/python-package/catboost/_catboost.pyx.cpp:11571)
  File "_catboost.pyx", line 669, in _catboost._CatBoost._save_model (/home/donskov/.ya/build/build_root/686b74643362767a7270306a66633031/catboost/python-package/catboost/_catboost.pyx.cpp:11458)
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_TString (/home/donskov/.ya/build/build_root/686b74643362767a7270306a66633031/catboost/python-package/catboost/_catboost.pyx.cpp:17179)
TypeError: expected bytes, str found
```

**Comment by Donskov7** [comment]
@glebreutov @raidhon thanks for feedback. This problem will be solved in next version, which now on review.

**Comment by annaveronika** [comment]
This is fixed now, try updating catboost to last version.

**Comment by raidhon** [comment]
@annaveronika Thank you everything works!
