### ISSUE TITLE
Problem to use save_model() method in CatBoostClassifer

### ISSUE THREAD

**Issue by ryukinix** [catboost/catboost#744]
# Description
Problem: I cannot use save_model() more.
catboost version: `0.13` `0.13.1` `0.12.1`
Operating System: `Linux celeste 4.19.30-1-lts #1 SMP Tue Mar 19 23:22:15 UTC 2019 x86_64 GNU/Linux`
CPU: 
```
CPU:
  Topology: Dual Core model: Intel Core i5-3320M bits: 64 type: MT MCP 
  L2 cache: 3072 KiB 
  Speed: 1197 MHz min/max: 1200/3300 MHz Core speeds (MHz): 1: 1197 2: 1197 
  3: 1197 4: 1197 
```

# Traceback

```
:: Saving model to: /app/workspace/models/model.bin
Traceback (most recent call last):
  File "/usr/local/bin/company_shutdown", line 11, in <module>
    load_entry_point('company-shutdown', 'console_scripts', 'company_shutdown')()
  File "/app/company_shutdown/main.py", line 131, in cli
    return fire.Fire()
  File "/usr/local/lib/python3.6/site-packages/fire/core.py", line 163, in Fire
    _PrintResult(component_trace, verbose=component_trace.verbose)
  File "/usr/local/lib/python3.6/site-packages/fire/core.py", line 221, in _PrintResult                                                                                
    print(helputils.HelpString(result, component_trace, verbose))
  File "/usr/local/lib/python3.6/site-packages/fire/helputils.py", line 92, in HelpString                                                                              
    info['usage'] = UsageString(component, trace, verbose)
  File "/usr/local/lib/python3.6/site-packages/fire/helputils.py", line 197, in UsageString                                                                            
    completions = completion.Completions(component, verbose)
  File "/usr/local/lib/python3.6/site-packages/fire/completion.py", line 172, in Completions                                                                           
    for member_name, unused_member in _Members(component, verbose)
  File "/usr/local/lib/python3.6/site-packages/fire/completion.py", line 123, in _Members                                                                              
    members = inspect.getmembers(component)
  File "/usr/local/lib/python3.6/inspect.py", line 342, in getmembers
    value = getattr(object, key)
  File "/usr/local/lib/python3.6/site-packages/catboost/core.py", line 988, in is_fitted_                                                                              
    raise CatBoostError("is_fitted_ property is not supported anymore, use is_fitted() method instead.")                                                               
_catboost.CatBoostError: is_fitted_ property is not supported anymore, use is_fitted() method instead.                                                                 
make: *** [Makefile:57: train] Error 1
```

**Comment by ryukinix** [comment]
Seems something related to `fire` library inspection that I return the `model` object in the function that I train :thinking:

**Comment by annaveronika** [comment]
Thanks for reporting this, we'll look into this.

**Comment by ek-ak** [comment]
Could you please provide a minimal reproducing example and fire version?

**Comment by nikitxskv** [comment]
@ryukinix Hi!
We removed deprecated fields.
Try to update, rebuild CatBoost and try again.

**Comment by ryukinix** [comment]
Nice! There is some nice guide to build catboost locally? I see the build system is not common like make, cmake etc...

**Comment by nikitxskv** [comment]
Yes, [here](https://catboost.ai/docs/installation/python-installation-method-build-from-source-linux-macos.html#python-installation-method-build-from-source-linux-macos) it is.

**Comment by annaveronika** [comment]
Fix is on github - closing the issue. Will be on pypi in the next release, which we plan for tomorrow.
