### ISSUE TITLE
catboost4j-prediction.dll was not found

### ISSUE THREAD

**Issue by bugfoot** [catboost/catboost#851]
### Problem: 
Despite adding [Maven dependency of Catboost Model Applier 0.2.5](https://mvnrepository.com/artifact/ai.catboost/catboost-prediction/0.2.5) to the build.sbt of my Scala project:

```
// https://mvnrepository.com/artifact/ai.catboost/catboost-prediction
libraryDependencies += "ai.catboost" % "catboost-prediction" % "0.2.5"
```

I get the below error when trying to import an existing model using `CatBoostModel.loadModel` as described in the tutorial:

```
12:26:21.377 [main] DEBUG ai.catboost.NativeLib - no catboost4j-prediction in java.library.path
12:26:21.520 [main] ERROR ai.catboost.NativeLib - failed to load native library from both default location and JAR
12:26:21.522 [main] ERROR ai.catboost.NativeLib - Failed to load native library
java.io.FileNotFoundException: File /win32-x86_64/lib/catboost4j-prediction.dll was not found inside JAR.
	at ai.catboost.NativeLib.copyFileFromJar(NativeLib.java:104)
	at ai.catboost.NativeLib.createTemporaryFileFromJar(NativeLib.java:133)
	at ai.catboost.NativeLib.loadNativeLibraryFromJar(NativeLib.java:92)
	at ai.catboost.NativeLib.smartLoad(NativeLib.java:54)
	at ai.catboost.NativeLib.<clinit>(NativeLib.java:22)
	at ai.catboost.CatBoostModel.loadModel(CatBoostModel.java:39)
	at my.package.ClassName.<init>(Do.scala:51)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scalatest.junit.JUnitRunner.<init>(JUnitRunner.scala:64)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
java.lang.ExceptionInInitializerError
	at ai.catboost.CatBoostModel.loadModel(CatBoostModel.java:39)
	at my.package.ClassName.<init>(Do.scala:51)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.scalatest.junit.JUnitRunner.<init>(JUnitRunner.scala:64)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: File /win32-x86_64/lib/catboost4j-prediction.dll was not found inside JAR.
	at ai.catboost.NativeLib.<clinit>(NativeLib.java:25)
	... 22 more
Caused by: java.io.FileNotFoundException: File /win32-x86_64/lib/catboost4j-prediction.dll was not found inside JAR.
	at ai.catboost.NativeLib.copyFileFromJar(NativeLib.java:104)
	at ai.catboost.NativeLib.createTemporaryFileFromJar(NativeLib.java:133)
	at ai.catboost.NativeLib.loadNativeLibraryFromJar(NativeLib.java:92)
	at ai.catboost.NativeLib.smartLoad(NativeLib.java:54)
	at ai.catboost.NativeLib.<clinit>(NativeLib.java:22)
	... 22 more

Process finished with exit code -1
```

### catboost version: 
Catboost Model Applier 0.2.5 (model created with CatBoost 0.15 via Python API)
### Operating System: 
64-bit Windows 10, Version 1809 (OS Build 17763.503)
### CPU: 
Intel Core i7-7700HQ @ 2.80GHz
GPU not used.

**Comment by annaveronika** [comment]
Sorry for inconvenience, we'll look into this soon.

**Comment by andrey-khropov** [comment]
Maven version 0.2.6 released today supports Windows.
