### ISSUE TITLE
Error with incremental training

### ISSUE THREAD

**Issue by pplonski** [catboost/catboost#861]
catboost version: 0.15.1
Operating System: Ubuntu 16.04
CPU: Yes
GPU: No

## Problem: 
I have a problem with incremental training. I'm using the code and error is attached.

What I'm trying to do is to learn CatBoost model for several iterations and after each chunk of iterations, I would like to check different metrics. Maybe I'm doing something wrong when setting the iterations?

```
from sklearn import datasets
from catboost import CatBoostClassifier

X, y = datasets.make_classification(
            n_samples=200,
            n_features=5,
            n_informative=5,
            n_redundant=0,
            n_classes=2,
            n_clusters_per_class=1,
            n_repeated=0,
            shuffle=False,
            random_state=0,
        )

model = CatBoostClassifier(iterations=0, loss_function="Logloss")

for i in range(5):
    model._init_params["iterations"] += 50
    model.fit(X, y, save_snapshot=True, snapshot_file="./mysnapshot-1")
    print("Iteration", model._init_params["iterations"])

```

The error message:
```
Traceback (most recent call last):
  File "reproduce_bug.py", line 20, in <module>
    model.fit(X, y, save_snapshot=True, snapshot_file="./mysnapshot-1")
  File "/home/piotr/sandbox/catboost_bug/venv/lib/python3.6/site-packages/catboost/core.py", line 2803, in fit
    silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
  File "/home/piotr/sandbox/catboost_bug/venv/lib/python3.6/site-packages/catboost/core.py", line 1279, in _fit
    self._train(train_pool, eval_sets, params, allow_clear_pool, init_model)
  File "/home/piotr/sandbox/catboost_bug/venv/lib/python3.6/site-packages/catboost/core.py", line 895, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 2481, in _catboost._CatBoost._train
  File "_catboost.pyx", line 2537, in _catboost._CatBoost._train
_catboost.CatBoostError: catboost/libs/algo/learn_context.cpp:406: Saved model's params are different from current model's params

```

**Comment by annaveronika** [comment]
We'll look into this

**Comment by andrey-khropov** [comment]
> catboost version: 0.15.1
> Operating System: Ubuntu 16.04
> CPU: Yes
> GPU: No
> ## Problem:
> 
> I have a problem with incremental training. I'm using the code and error is attached.
> 
> What I'm trying to do is to learn CatBoost model for several iterations and after each chunk of iterations, I would like to check different metrics. Maybe I'm doing something wrong when setting the iterations?

If you enable snapshots, training parameters are saved in the snapshot (because a certain snapshot will be only valid for the particular set of training parameters), when you change 'iterations' parameter your snapshot saved from the previous training became invalid, that's why you see this error (we'll change the error message so it will be explicit about snapshots).

The proper way is to pass 'init_model' parameter to 'fit' like that:

```py
from sklearn import datasets
from catboost import CatBoostClassifier

print ('python version=', sys.version)
print ('catboost version=', catboost.version.VERSION)


X, y = datasets.make_classification(
            n_samples=200,
            n_features=5,
            n_informative=5,
            n_redundant=0,
            n_classes=2,
            n_clusters_per_class=1,
            n_repeated=0,
            shuffle=False,
            random_state=0,
        )

model = CatBoostClassifier(iterations=50, loss_function="Logloss")

for i in range(5):
    model.fit(X, y, init_model = model if i else None)
    print("Iteration", model._init_params["iterations"] * (i + 1))
```
