### ISSUE TITLE
«pandas==0.24.2 + catboost==0.15.1 = KeyError: 0.»  With Pandas 0.23 all OK

### ISSUE THREAD

**Issue by belonesox** [catboost/catboost#864]
Problem:
On pandas 0.23.2 all OK. Then I upgraded to pandas 0.24.2
got 
```
Traceback (most recent call last):
  File "bug.py", line 85, in <module>
    trainmodel()
  File "bug.py", line 56, in trainmodel
    verbose=True)
  File "/home/stas/projects/-smopt/catboost-bugs/bug-catboost-pandas-24/lib64/python3.5/site-packages/catboost/core.py", line 3236, in fit
    save_snapshot, snapshot_file, snapshot_interval, init_model)
  File "/home/stas/projects/-smopt/catboost-bugs/bug-catboost-pandas-24/lib64/python3.5/site-packages/catboost/core.py", line 1233, in _fit
    train_pool = _build_train_pool(X, y, cat_features, pairs, sample_weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, column_description)
  File "/home/stas/projects/-smopt/catboost-bugs/bug-catboost-pandas-24/lib64/python3.5/site-packages/catboost/core.py", line 691, in _build_train_pool
    group_weight=group_weight, subgroup_id=subgroup_id, pairs_weight=pairs_weight, baseline=baseline)
  File "/home/stas/projects/-smopt/catboost-bugs/bug-catboost-pandas-24/lib64/python3.5/site-packages/catboost/core.py", line 320, in __init__
    self._init(data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names)
  File "/home/stas/projects/-smopt/catboost-bugs/bug-catboost-pandas-24/lib64/python3.5/site-packages/catboost/core.py", line 672, in _init
    self._init_pool(data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names)
  File "_catboost.pyx", line 2113, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 2144, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 2013, in _catboost._PoolBase._init_features_order_layout_pool
  File "_catboost.pyx", line 1660, in _catboost._set_features_order_data_pd_data_frame
  File "/home/stas/projects/-smopt/catboost-bugs/bug-catboost-pandas-24/lib64/python3.5/site-packages/pandas/core/series.py", line 868, in __getitem__
    result = self.index.get_value(self, key)
  File "/home/stas/projects/-smopt/catboost-bugs/bug-catboost-pandas-24/lib64/python3.5/site-packages/pandas/core/indexes/base.py", line 4360, in get_value
    iloc = self.get_loc(key)
  File "/home/stas/projects/-smopt/catboost-bugs/bug-catboost-pandas-24/lib64/python3.5/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 987, in pandas._libs.hashtable.Int64HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 993, in pandas._libs.hashtable.Int64HashTable.get_item
KeyError: 0
```
Demo script, demo data, virtual env to reproduct — all uploaded 
https://cloud.mail.ru/public/3dEp/5iNQtsUpm

catboost version: 0.15.1
Operating System: Linux

**Comment by khrisanfov** [comment]
This is similar to #757

**Comment by kizill** [comment]
We've fixed categorical columns support a year ago, so closing this issue. If you still has problems with it - feel free to reopen this issue.
Thanks! 👍
