### ISSUE TITLE
Custom loss function

### ISSUE THREAD

**Issue by wboleksii** [catboost/catboost#887]
I'm trying to define a custom loss function. Everything works fine with `MultiClass` loss, but with my custom loss I'm getting the error blow:

```
Traceback (most recent call last):

  File "\venv\lib\site-packages\catboost\core.py", line 2928, in fit
    silent, early_stopping_rounds, save_snapshot, snapshot_file, snapshot_interval, init_model)
  File "\venv\lib\site-packages\catboost\core.py", line 1283, in _fit
    self._train(train_pool, eval_sets, params, allow_clear_pool, init_model)
  File "\venv\lib\site-packages\catboost\core.py", line 899, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 2490, in _catboost._CatBoost._train
  File "_catboost.pyx", line 2546, in _catboost._CatBoost._train
_catboost.CatBoostError: c:/goagent/pipelines/buildmaster/catboost.git/catboost/libs/target/target_converter.cpp:53: Target value "S" cannot be parsed as float
```

Here is the function (I've copied the example).

```
class CustomObjective(object):
    def calc_ders_multi(self, approxes, targets, weights):
        assert len(approxes) == len(targets)
        if weights is not None:
            assert len(weights) == len(approxes)

        exponents = []
        for index in range(len(approxes)):
            exponents.append(math.exp(approxes[index]))

        result = []
        for index in range(len(targets)):
            p = exponents[index] / (1 + exponents[index])
            der1 = (1 - p) if targets[index] > 0.0 else -p
            der2 = -p * (1 - p)

            if weights is not None:
                der1 *= weights[index]
                der2 *= weights[index]

            result.append((der1, der2))

        return result


classifier = CatBoostClassifier(
       use_best_model=False,
       task_type='GPU',
       loss_function=CustomObjective(),
       eval_metric='TotalF1',
       cat_features=cat_cols,
       random_state=42,
       verbose=1
)


classifier.fit(X_train, y_train)
```

catboost version: 0.15.2
Operating System: Windows

**Comment by annaveronika** [comment]
Sorry for late response! Custom loss functions are not supported for GPU training. We'll make sure there's a good exception for this case.

**Comment by annaveronika** [comment]
This is fixed.
