### ISSUE TITLE
Enconding error while compiling the static library on windows using python

### ISSUE THREAD

**Issue by estamosperdidos** [catboost/catboost#918]
Problem: Instruction 
`C:\Python36\python.exe ya make -r catboost/libs/model_interface/static`
outputs an encoding error 

I have checked:

`
import sys
sys.getdefaultencoding()
$ 'utf-8'
`

File "devtools/ya/app.py", line 350, in configure_exit_interceptor
    yield
File "devtools/ya/app.py", line 56, in helper
    return action(args)
  File "devtools/ya/entry/entry.py", line 45, in do_main
    res = handler.handle(handler, args, prefix=['ya'])
  File "devtools/ya/core/handler.py", line 159, in handle
    return handler.handle(self, args[1:], prefix + [name])
  File "devtools/ya/core/dispatch.py", line 37, in handle
    return self.command().handle(root_handler, args, prefix)
  File "devtools/ya/core/handler.py", line 341, in handle
    return self._action(params)
  File "devtools/ya/app.py", line 78, in helper
    return action(ctx.params)
  File "devtools/ya/build/build_handler.py", line 71, in do_ya_make
    builder = ya_make.YaMake(params, app_ctx)
  File "devtools/ya/build/ya_make.py", line 630, in __init__ self.ctx = Context(self.opts, app_ctx=app_ctx, graph=graph, tests=tests, configure_errors=configure_errors, make_files=make_files, lite_graph=lite
_graph)
  File "devtools/ya/build/ya_make.py", line 428, in __init__
    self.graph, self.tests, self.stripped_tests, self.configure_errors, self.make_files = _build_graph_and_tests(self.opts, app_ctx)
  File "devtools/ya/build/ya_make.py", line 242, in _build_graph_and_tests
    graph, tests, stripped_tests, gh, make_files = lg.build_graph_and_tests(opts, check=True, ev_listener=ev_listener)
  File "devtools/ya/build/graph.py", line 2510, in build_graph_and_tests
    graph['conf']['resources'].append(vcs_info())
  File "devtools/ya/exts/async.py", line 69, in <lambda>
    return lambda: unwrap(e())
  File "devtools/ya/exts/async.py", line 11, in wrap
    return f(), None
  File "devtools/ya/build/graph.py", line 1410, in <lambda>
    vcs_info = core_async.future(lambda: get_version_info(src_dir, bld_dir, opts.vcs_file, opts.flags), daemon=False)
  File "devtools/ya/build/graph.py", line 2590, in get_version_info
    json_str = vcsversion.get_version_info(arc_root, bld_root, fake_data)
  File "devtools/ya/yalibrary/vcs/vcsversion/__init__.py", line 638, in get_version_info
    build_date=_SystemInfo.get_date())
  File "devtools/ya/yalibrary/vcs/vcsversion/__init__.py", line 74, in _dump_json
    j['PROGRAM_VERSION'] = info['scm_text'] + "\n" + other_data
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa2 in position 220: ordinal not in range(128)

catboost version: 0.16
Operating System: Windows 7 Professional
CPU: Intel Xeon CPU ES-2630 v3 @ 2.40 GHz

**Comment by annaveronika** [comment]
This is fixed now

**Comment by rafpyprog** [comment]
Same here:

ya.bat make -r -DUSE_ARCADIA_PYTHON=no -DUSE_SYSTEM_PYTHON='3.6' -DCUDA_ROOT='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1'

Traceback (most recent call last):
  File "devtools/ya/app.py", line 391, in configure_exit_interceptor
    yield
  File "devtools/ya/app.py", line 62, in helper
    return action(args)
  File "devtools/ya/entry/entry.py", line 54, in do_main
    res = handler.handle(handler, args, prefix=['ya'])
  File "devtools/ya/core/handler.py", line 159, in handle
    return handler.handle(self, args[1:], prefix + [name])
  File "devtools/ya/core/dispatch.py", line 37, in handle
    return self.command().handle(root_handler, args, prefix)
  File "devtools/ya/core/handler.py", line 341, in handle
    return self._action(params)
  File "devtools/ya/app.py", line 88, in helper
    return action(ctx.params)
  File "devtools/ya/build/build_handler.py", line 85, in do_ya_make
    builder = ya_make.YaMake(params, app_ctx)
  File "devtools/ya/build/ya_make.py", line 832, in __init__
    self.ctx = Context(self.opts, app_ctx=app_ctx, graph=graph, tests=tests, configure_errors=configure_errors, make_files=make_files, lite_graph=lite_graph)
  File "devtools/ya/build/ya_make.py", line 494, in __init__
    self.graph, self.tests, self.stripped_tests, self.configure_errors, self.make_files = _build_graph_and_tests(self.opts, app_ctx)
  File "devtools/ya/build/ya_make.py", line 247, in _build_graph_and_tests
    graph, tests, stripped_tests, gh, make_files = lg.build_graph_and_tests(opts, check=True, ev_listener=ev_listener)
  File "devtools/ya/build/graph.py", line 2177, in build_graph_and_tests
    heater=heater, cache_dir=cache_dir, change_list=change_list)
  File "devtools/ya/build/graph.py", line 2369, in get_tools
    tools_targets |= find_tools_targets(no_pic()[0])
  File "devtools/ya/exts/asyncthread.py", line 71, in <lambda>
    return lambda: unwrap(e())
  File "devtools/ya/exts/asyncthread.py", line 29, in unwrap
    reraise(e[0], e[1], e[2])
  File "devtools/ya/exts/asyncthread.py", line 13, in wrap
    return f(), None
  File "devtools/ya/build/graph.py", line 2298, in <lambda>
    change_list=opts.build_graph_cache_cl), daemon=False)
  File "devtools/ya/build/graph.py", line 2184, in build_no_pic
    heater=heater, cache_dir=cache_dir, change_list=change_list)
  File "devtools/ya/build/graph.py", line 2171, in prepare_graph
    heater=heater, cache_dir=cache_subdir, change_list=change_list)
  File "devtools/ya/build/graph.py", line 1892, in gen_graph
    heater=heater, cache_dir=cache_dir, change_list=change_list)
  File "devtools/ya/build/graph.py", line 1785, in gen_opts
    conf_debug=opts.conf_debug_options, debug_id=debug_id
  File "devtools/ya/yalibrary/guards/__init__.py", line 59, in boo
    return func(*args, **kwargs)
  File "devtools/ya/build/genconf.py", line 270, in gen_conf
    p = sp.Popen(cmd, env=env, stdout=sp.PIPE, stderr=sp.PIPE)
  File "contrib/tools/python/src/Lib/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "contrib/tools/python/src/Lib/subprocess.py", line 599, in _execute_child
    args = list2cmdline(args)
  File "contrib/tools/python/src/Lib/subprocess.py", line 294, in list2cmdline
    return ''.join(result)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 0: ordinal not in range(128)
