### ISSUE TITLE
 model.get_all_params() default output is 'eval_metric': 'RMSE'

### ISSUE THREAD

**Issue by AndreyGurevich** [catboost/catboost#940]
Problem:  model.get_all_params() gives wrong output for 'eval_metric'. prints `RMSE` for multiclass classification
catboost version: 0.16.2
Operating System: Ubuntu 16
Code to reproduce:
### 1. no metrics at all
I do not specify `eval_metric` and `loss_function` in params. They are commented. But I use custom metric:
```
P_full = Pool(X, y.reshape(-1))
parameters = {
    #'eval_metric': 'MultiClass',
    'iterations': 15,
    'metric_period': 100,
    #'loss_function': 'MultiClass',
    'l2_leaf_reg': 30,
    'random_seed': 0,
    'depth': 6,
    'custom_metric': ['F1', 'Recall'] 
}
scores = cv(P_full,
            params=parameters,
            stratified=True,
            fold_count=3
            )

scores.to_csv('catboost_score.csv')

model = CatBoostClassifier(**parameters)
model.fit(P_full)
print(model.get_all_params())
```
Output is 
```
Traceback (most recent call last):
  File "/home/ag/PycharmProjects/tracker/trainer_boosting.py", line 26, in <module>
    fold_count=3
  File "/home/ag/anaconda3/envs/tracker/lib/python3.7/site-packages/catboost/core.py", line 4331, in cv
    as_pandas, folds)
  File "_catboost.pyx", line 3381, in _catboost._cv
  File "_catboost.pyx", line 3403, in _catboost._cv
_catboost.CatBoostError: catboost/libs/metrics/metric.cpp:5108: loss [RMSE] is incompatible with metric [F1] (no classification support)

Process finished with exit code 1
```
loss [RMSE] in Classifier is unexpected for me :(
Next try:
### Specify loss_function
```
parameters = {
    #'eval_metric': 'MultiClass',
    'iterations': 15,
    'metric_period': 100,
    'loss_function': 'MultiClass',
    'l2_leaf_reg': 30,
    'random_seed': 0,
    'depth': 6,
    'custom_metric': ['F1', 'Recall'] # , 'F1', 'Precision', 'Recall'
}
```
Output:
```
0:	learn: 1.6973536	test: 1.6975012	best: 1.6975012 (0)	total: 542ms	remaining: 7.59s
14:	learn: 1.0226863	test: 1.0236245	best: 1.0236245 (14)	total: 6.42s	remaining: 0us
0:	learn: 1.6938054	total: 30.2ms	remaining: 423ms
14:	learn: 1.0122435	total: 316ms	remaining: 0us
{'nan_mode': 'Min', 'eval_metric': 'RMSE', 'iterations': 15, 'sampling_frequency': 'PerTree', 'fold_permutation_block': 0, 'leaf_estimation_method': 'Newton', 'boosting_type': 'Plain', 'feature_border_type': 'GreedyLogSum', 'bayesian_matrix_reg': 0.1000000015, 'l2_leaf_reg': 30, 'random_strength': 1, 'rsm': 1, 'model_size_reg': 0.5, 'approx_on_full_history': False, 'use_best_model': False, 'class_names': ['0.0', '1.0', '2.0', '3.0', '4.0', '5.0'], 'random_seed': 0, 'depth': 6, 'has_time': False, 'fold_len_multiplier': 2, 'border_count': 254, 'bagging_temperature': 1, 'classes_count': 0, 'sparse_features_conflict_fraction': 0, 'custom_metric': ['F1', 'Recall'], 'leaf_estimation_backtracking': 'AnyImprovement', 'best_model_min_trees': 1, 'loss_function': 'MultiClass', 'learning_rate': 0.02999999933, 'task_type': 'CPU', 'leaf_estimation_iterations': 1, 'bootstrap_type': 'Bayesian', 'permutation_count': 4}
```
Pay attention to `'eval_metric': 'RMSE', 'loss_function': 'MultiClass'`

Next try:
### specify eval_metric:
```
parameters = {
    'eval_metric': 'MultiClass',
    'iterations': 15,
    'metric_period': 100,
    'loss_function': 'MultiClass',
    'l2_leaf_reg': 30,
    'random_seed': 0,
    'depth': 6,
    'custom_metric': ['F1', 'Recall'] # , 'F1', 'Precision', 'Recall'
}
```
Output:
```
0:	learn: 1.6973536	test: 1.6975012	best: 1.6975012 (0)	total: 611ms	remaining: 8.55s
14:	learn: 1.0226863	test: 1.0236245	best: 1.0236245 (14)	total: 6.43s	remaining: 0us
0:	learn: 1.6938054	total: 26.5ms	remaining: 371ms
14:	learn: 1.0122435	total: 337ms	remaining: 0us
{'nan_mode': 'Min', 'eval_metric': 'MultiClass', 'iterations': 15, 'sampling_frequency': 'PerTree', 'fold_permutation_block': 0, 'leaf_estimation_method': 'Newton', 'boosting_type': 'Plain', 'feature_border_type': 'GreedyLogSum', 'bayesian_matrix_reg': 0.1000000015, 'l2_leaf_reg': 30, 'random_strength': 1, 'rsm': 1, 'model_size_reg': 0.5, 'approx_on_full_history': False, 'use_best_model': False, 'class_names': ['0.0', '1.0', '2.0', '3.0', '4.0', '5.0'], 'random_seed': 0, 'depth': 6, 'has_time': False, 'fold_len_multiplier': 2, 'border_count': 254, 'bagging_temperature': 1, 'classes_count': 0, 'sparse_features_conflict_fraction': 0, 'custom_metric': ['F1', 'Recall'], 'leaf_estimation_backtracking': 'AnyImprovement', 'best_model_min_trees': 1, 'loss_function': 'MultiClass', 'learning_rate': 0.02999999933, 'task_type': 'CPU', 'leaf_estimation_iterations': 1, 'bootstrap_type': 'Bayesian', 'permutation_count': 4}
```

Now eval_metric printed as MultiClass.

Why RMSE is used here by default?

**Comment by annaveronika** [comment]
This is fixed now in code and will be on pypi in the next release.

**Comment by AndreyGurevich** [comment]
Good news! Thank you.
