### ISSUE TITLE
catFeaturesHashToString has to be specified if the model contains one hot features

### ISSUE THREAD

**Issue by hdarabi** [catboost/catboost#967]
Problem: 
Hi guys, I faced this problem when I tried to export my model to PMML. I was able to properly train my model, use it for making predictions. I read from the documentation that I need to set             **one_hot_max_size=one_hot_max_size** in exporting the models to PMML (I was getting an error for that). However, I get a new error after adding the following code:

    one_hot_max_size = data[self.features].nunique().max()
    catboost_model = CatBoostClassifier(custom_loss=['Logloss'], random_seed=SEED,
            learning_rate=0.005, one_hot_max_size=one_hot_max_size)

Please note all of my features are categorical. Here is the error:

    Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
     exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-16-2f8bcebe43d1>", line 1, in <module>
    model_exporter.export(file_name='catboost_model')
    File "/Users/hdarabi/00git/catboost-model/src/Exporter.py", line 41, in export
    'pmml_model_version': self.exec_date.strftime("%Y-%m-%d %H:%M")
    File "/Users/hdarabi/Library/Python/3.7/lib/python/site-packages/catboost/core.py", line 2213, in save_model
    self._save_model(fname, format, export_parameters, pool)
    File "/Users/hdarabi/Library/Python/3.7/lib/python/site-packages/catboost/core.py", line 1043, in _save_model
    self._object._save_model(output_file, format, params_string, pool)
    File "_catboost.pyx", line 2983, in _catboost._CatBoost._save_model
    File "_catboost.pyx", line 2994, in _catboost._CatBoost._save_model
    _catboost.CatBoostError: catboost/libs/model/model_export/pmml_helpers.cpp:482: Internal         
    CatBoost Error (contact developers for assistance): catFeaturesHashToString has to be specified if the model contains one hot features

catboost version: 0.16.5
Operating System: MacOS Mojave
CPU: 2.2 GHz Intel Core I7
GPU: Radeon Pro 555X 4 GB

**Comment by andrey-khropov** [comment]
You also need to pass learn dataset to 'pool' parameter value of 'catboost_model.save_model' method when saving model with categorical features in PMML format.

Like this:

```py
catboost_model.save_model(
    model_name,
    format='pmml',
    export_parameters={
        'pmml_copyright': 'Tremor Video Inc. (c)',
        'pmml_description': 'Catboost model for predicting {}.'.format(target),
        'pmml_model_version': '1.0.0'
    },
    pool=train
)
```
Unfortunately, it is not mentioned in documentation, we'll fix it soon.
