### ISSUE TITLE
Can't import catboost

### ISSUE THREAD

**Issue by Denisevi4** [catboost/catboost#969]
Problem: Can't import catboost
catboost version: 0.16-py37_0
Operating System: CentOs7
CPU: Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
Number of GPU: 4

After installing catboost with conda:
conda install -c conda-forge catboost

I get an error when trying to import catboost:

```
Python 3.7.1 | packaged by conda-forge | (default, Mar 13 2019, 12:57:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import catboost
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/denper/anaconda2/envs/d1_py3_env/lib/python3.7/site-packages/catboost/__init__.py", line 1, in <module>
    from .core import FeaturesData, EFstrType, Pool, CatBoost, CatBoostClassifier, CatBoostRegressor, CatBoostError, cv, train, sum_models  # noqa
  File "/home/denper/anaconda2/envs/d1_py3_env/lib/python3.7/site-packages/catboost/core.py", line 60, in <module>
    _catboost = get_catboost_bin_module()
  File "/home/denper/anaconda2/envs/d1_py3_env/lib/python3.7/site-packages/catboost/core.py", line 51, in get_catboost_bin_module
    loaded_catboost = imp.load_dynamic('_catboost', so_path)
  File "/home/denper/anaconda2/envs/d1_py3_env/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "numpy.pxd", line 918, in init _catboost
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

my numpy version is 1.15.4

**Comment by buhrmann** [comment]
I've had the same problem. Seems like the minimum version for numpy has increased to 1.16 in [catboost's conda-forge feedstock](https://github.com/conda-forge/catboost-feedstock/commit/e2ab854f4d7ac229ea3d00a0011dffcfcd97b50a). But for some reason conda happily installs it alongside numpy 1.15.4 without complaining, which then fails at runtime. Not sure exactly if that's a feedstock problem or a conda problem, but updating numpy manually solved it for me.

**Comment by Denisevi4** [comment]
Thanks @buhrmann 

my numpy was 1.15.4. Once I updated numpy, it imports now.
