### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Denisevi4** [catboost/catboost#973]
Problem:
catboost version:
Operating System: CentOs7
CPU:
4 GPUs:

Tried installing from source, but getting a SSL error.

Following https://github.com/catboost/catboost/issues/182
I added those recommended lines to ya, but now getting this SSL error:

```
(d1_py3_env) [denper@opuschdvux0221 catboost]$ ../../../ya make -r -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -DPYTHON_CONFIG=/home/denper/anaconda2/envs/d1_py3_env/bin/python3-config -DCUDA_ROOT=/usr/local/cuda
Downloading https://storage.mds.yandex.net/get-devtools-opensource/479623/ae3be4ad8edfd1a9b3c8e42697bd3d71 [..] OK
Downloading https://storage.mds.yandex.net/get-devtools-opensource/479623/1091697648 [..............................................................] OK
Info: will fetch 'ymake'
Traceback (most recent call last):
  File "devtools/ya/app.py", line 350, in configure_exit_interceptor
    yield
  File "devtools/ya/app.py", line 56, in helper
    return action(args)
  File "devtools/ya/entry/entry.py", line 46, in do_main
    res = handler.handle(handler, args, prefix=['ya'])
  File "devtools/ya/core/handler.py", line 159, in handle
    return handler.handle(self, args[1:], prefix + [name])
  File "devtools/ya/core/dispatch.py", line 37, in handle
    return self.command().handle(root_handler, args, prefix)
  File "devtools/ya/core/handler.py", line 341, in handle
    return self._action(params)
  File "devtools/ya/app.py", line 78, in helper
    return action(ctx.params)
  File "devtools/ya/build/build_handler.py", line 71, in do_ya_make
    builder = ya_make.YaMake(params, app_ctx)
  File "devtools/ya/build/ya_make.py", line 646, in __init__
    self.ctx = Context(self.opts, app_ctx=app_ctx, graph=graph, tests=tests, configure_errors=configure_errors, make_files=make_files, lite_graph=lite_graph)
  File "devtools/ya/build/ya_make.py", line 434, in __init__
    self.graph, self.tests, self.stripped_tests, self.configure_errors, self.make_files = _build_graph_and_tests(self.opts, app_ctx)
  File "devtools/ya/build/ya_make.py", line 242, in _build_graph_and_tests
    graph, tests, stripped_tests, gh, make_files = lg.build_graph_and_tests(opts, check=True, ev_listener=ev_listener)
  File "devtools/ya/build/graph.py", line 1653, in build_graph_and_tests
    real_ymake_bin = tools.tool('ymake')
  File "devtools/ya/yalibrary/tools/__init__.py", line 213, in tool
    return toolchain.find(name, with_params, for_platform)
  File "devtools/ya/yalibrary/tools/__init__.py", line 151, in find
    executable = cur_bottle[executable_name]  # if executable_name is None it's Ok
  File "devtools/ya/yalibrary/tools/__init__.py", line 59, in __getitem__
    path = self.resolve()
  File "devtools/ya/yalibrary/tools/__init__.py", line 41, in resolve
    return self.__fetcher.fetch_if_need(self.__formula["match"], tared, binname).where
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 283, in fetch_if_need
    self.__c[key] = self._fetch_if_need(*args, **kwargs)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 344, in _fetch_if_need
    if self._fetch(name, tared, lambda x: name.lower() in x.lower(), binname):
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 269, in _fetch
    _install(res_path, do_install)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 73, in _install
    func(install_guard)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 248, in do_install
    self._download(name, res, download_to)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 418, in _download
    http_client.download_file(url=config.mapping()["resources"][resource["id"]], path=download_to)
  File "devtools/ya/exts/retry.py", line 20, in wrapper
    return retry(proxy_func, **retry_kwargs)
  File "devtools/ya/exts/retry.py", line 12, in retry
    return lpr.retry_call(func, conf=_conf(func, *args, **kwargs))
  File "library/python/retry/__init__.py", line 183, in retry_call
    return _retry(conf, functools.partial(f, *f_args, **f_kwargs))
  File "library/python/retry/__init__.py", line 221, in _retry
    return f()
  File "devtools/ya/exts/retry.py", line 19, in <lambda>
    proxy_func = lambda: func(*args, **kwargs)
  File "devtools/ya/exts/http_client.py", line 63, in download_file
    raise e
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>
```

I can't even find those python files.

**Comment by annaveronika** [comment]
Sorry for a long response, we'll look into this!

**Comment by orivej** [comment]
@Denisevi4, are you behind a proxy (such as a corporate web proxy, or a network-wide antivirus, or using a local proxy) that intercepts HTTPS connections? If so, do you want `ya` to disable SSL validation, or to trust the certificate of the proxy? If not, could you show the output of `ya -v make …` (`../../../ya -v make -r -DUSE_ARCADIA_PYTHON=no -DOS_SDK=local -DPYTHON_CONFIG=/home/denper/anaconda2/envs/d1_py3_env/bin/python3-config -DCUDA_ROOT=/usr/local/cuda`)?

**Comment by Denisevi4** [comment]
I can give it to you once I come back to work from vacation. But I'd like first understand the reason behind the hidden installation builds that are not part of this github repo.

Given that you're a Russian company that raises some questions. Nothing against yandex, but there is a prior bias towards the intentions.

**Comment by orivej** [comment]
We won't be able to add your certificate to the [default trust store](https://github.com/catboost/catboost/blob/master/certs/cacert.pem). We could:
- let `ya` ignore SSL validation errors with a new command line option (`ya --no-check-certificate`)
- let you use a custom certificate bundle (`ya --ca-certificate=file`)
- let `ya` prefer system certificate bundle (if it contains your certificate)
- let `ya` prefer `certs/cacert.pem` from the repo to the builtin copy of this file (so that you could add your certificate there)

`ya` is the program that orchestrates the build process based on `ya.make` files and the `build/` directory in this repo. It is used here in the same way it is used in Yandex, as a binary download. We want to make it open source too, but that would be in a different repo, and you will still need a binary `ya` in order to build `ya` from source (unless we implement a way to bootstrap `ya` without `ya`).

**Comment by annaveronika** [comment]
> I can give it to you once I come back to work from vacation. But I'd like first understand the reason behind the hidden installation builds that are not part of this github repo.
> 
> Given that you're a Russian company that raises some questions. Nothing against yandex, but there is a prior bias towards the intentions.

It is also possible to use auto generated make files for building the project, if you don't want to use ya binary.

**Comment by annaveronika** [comment]
Also @Denisevi4 you were planning to provide output of ya -v make …
Could you do it?

**Comment by MotoRZR** [comment]
I have the exact same issue.  Also behind a proxy.  Here's the output of my ya -v make

> Also @Denisevi4 you were planning to provide output of ya -v make …
> Could you do it?

C:\Users\user\.ya\tools\88fbde4cbc_d\ya-bin
Debug: Module "display_log" initialized in 0.000000
Debug: Custom fetcher: None, fetcher parameters: [{'name': 'skynet'}, {'name': 'custom'}, {'name': 'sandbox'}, {'name': 'mds'}, {'name': 'proxy'}], sb_token none
Debug: Module "fetcher_params" initialized in 0.001000
Debug: Module "fetcher" initialized in 0.040000
Debug: Revision: 6009455
Debug: Module "revision" initialized in 0.000000
Debug: Event log file is 15-17-16.hbmtxfp9bqoflf7f.evlog
Debug: Module "evlog" initialized in 0.002000
Debug: Module "showstack" initialized in 0.000000
Debug: Using dummy fs layer (absent C:\Folder\CProg\catboost\__DIGEST__.2.json)
Debug: Module "fs_layer" initialized in 0.000000
Debug: Module "profile" initialized in 0.000000
Debug:
Debug: Module "mlockall" initialized in 0.001000
Debug: Profile step ya_make_handler_started - 1574954237.13
Debug: Set stage ya_make_handler_started=1574954237.13
Debug: Profile step context_generating_started - 1574954237.13
Debug: Set stage context_generating_started=1574954237.13
Debug: Profile step build_graph_cache_configuration_started - 1574954237.13
Debug: Set stage build_graph_cache_configuration_started=1574954237.13
Debug: _BuildGraphCacheQuery None None
Debug: Build graph cache processing started
Debug: Build graph cache processing disabled
Debug: Set stage build_graph_cache_configuration_finished=1574954237.14
Debug: Profile step build_graph_cache_configuration_finished - 1574954237.14
Debug: Profile step context_creation_started - 1574954237.14
Debug: Set stage context_creation_started=1574954237.14
Debug: Acquiring filelock (blocking=True): C:\Users\user\.ya\build\.lock
Debug: Profile step build_graph_and_tests_started - 1574954237.15
Debug: Set stage build_graph_and_tests_started=1574954237.15
Debug: Collect vcs info
Debug: flags: {
    "CATBOOST_OPENSOURCE": "yes",
    "CFLAGS": "-DCATBOOST_OPENSOURCE=yes",
    "CONSISTENT_DEBUG_LIGHT": "yes",
    "CXXFLAGS": "-DCATBOOST_OPENSOURCE=yes",
    "HAVE_MKL": "no",
    "USE_ARCADIA_CUDA": "no",
    "USE_ASMLIB": "no",
    "USE_GCCFILTER": "no",
    "USE_GCCFILTER_COLOR": "no",
    "USE_MKL": "no"
}
Debug: detecting vcs from C:\Folder\CProg\catboost for paths: ['C:\\Folder\\CProg\\catboost']
Debug: host toolchain: {
    "build_type": "release",
    "flags": {
        "CATBOOST_OPENSOURCE": "yes",
        "CFLAGS": "-DCATBOOST_OPENSOURCE=yes",
        "CLANG_COVERAGE": "no",
        "CXXFLAGS": "-DCATBOOST_OPENSOURCE=yes",
        "HAVE_MKL": "no",
        "NO_DEBUGINFO": "yes",
        "NO_SVN_DEPENDS": "yes",
        "TOOL_BUILD_MODE": "yes",
        "TRAVERSE_RECURSES": "no",
        "USE_ASMLIB": "no",
        "USE_GCCFILTER": "no",
        "USE_GCCFILTER_COLOR": "no",
        "USE_MKL": "no"
    },
    "name": "system_cxx",
    "params": {
        "cxx_compiler": "cl.exe",
        "type": "system_cxx"
    },
    "platform": {
        "host": {
            "arch": "x86_64",
            "os": "WIN",
            "toolchain": "default"
        },
        "target": {
            "arch": "x86_64",
            "os": "WIN",
            "toolchain": "default"
        }
    }
}
Debug: common root: C:\Folder\CProg\catboost
Debug: target toolchain: {
    "name": "system_cxx",
    "params": {
        "cxx_compiler": "cl.exe",
        "type": "system_cxx"
    },
    "platform": {
        "host": {
            "arch": "x86_64",
            "os": "WIN",
            "toolchain": "default"
        },
        "target": {
            "arch": "x86_64",
            "os": "WIN",
            "toolchain": "default"
        }
    },
    "platform_name": "DEFAULT-WIN-X86_64"
}
Debug: vcs root: C:\Folder\CProg\catboost (git)
Debug: is_cross: True
Debug: Using old-style toolchain for: ymake
Debug: check ymake by [552977342] task-id in C:\Users\user\.ya\tools\v3 dir
Debug: not installed C:\Users\user\.ya\tools\v3\552977342
Debug: will fetch 'ymake' by [552977342] task-id
Info: will fetch 'ymake'
Debug: Use conf from C:\Folder\CProg\catboost\build\mapping.conf.json
Debug: found ['win32', 'darwin', 'linux_musl'] platforms
Debug: will use 'win32' platform
Debug: Acquiring filelock (blocking=True): C:\Users\user\.ya\tools\v3\1222268138.lock
Debug: not installed C:\Users\user\.ya\tools\v3\1222268138
Debug: Downloading https://storage.mds.yandex.net/get-devtools-opensource/233854/1222268138 to C:\Users\user\.ya\tools\v3\1222268138\.resource.jqwj42g7, expect md5=None
Debug: exception after 0:00:00.203000 on 1 try <lambda>: URLError(URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),)) (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>)
Debug: fatal: no tag exactly matches 'abbc7486de95c63cb769f4dcc224e44aae2c6d5b'

Running git describe --exact-match --tags HEAD failed with exit code 128
Debug: Git info commit:abbc7486de95c63cb769f4dcc224e44aae2c6d5b, author:halin-george <halin-george@yandex-team.ru>, summary:Make tsan compatible with coroutines' switch context by explicitly marking switches., svn_id:date: 2019-11-27T10:27:30+07:00
revision: 6013228

[GLY] Update ymake

Revision: r6009773
Author: dvshkurko
Sandbox task ID: 555589507
Glycine run ID: 77d09d77-c820-4613-86c0-5928dbaf5ff4

Note: mandatory check (NEED_CHECK) was skipped
ref:88daf9b6c13064dcb09f5e3cd3ef63d3b354d6cb
Debug: Got version json  "{\n    \"ARCADIA_PATCH_NUMBER\": 8471,\n    \"ARCADIA_SOURCE_HG_HASH\": \"abbc7486de95c63cb769f4dcc224e44aae2c6d5b\",\n    \"ARCADIA_SOURCE_LAST_AUTHOR\": \"halin-george <halin-george@yandex-team.ru>\",\n    \"ARCADIA_SOURCE_LAST_CHANGE\": 6009773,\n    \"ARCADIA_SOURCE_PATH\": \"C:\\\\Folder\\\\CProg\\\\catboost\",\n    \"ARCADIA_SOURCE_REVISION\": -1,\n    \"ARCADIA_SOURCE_URL\": \"\",\n    \"ARCADIA_TAG\": \"\",\n    \"BRANCH\": \"heads/master\",\n    \"BUILD_DATE\": \"2019-11-28T15:17:17.000000Z\",\n    \"BUILD_HOST\": \"WARBLE123\",\n    \"BUILD_TIMESTAMP\": 1574954237,\n    \"BUILD_USER\": \"user\",\n    \"PROGRAM_VERSION\": \"Git info:\\n    Commit: abbc7486de95c63cb769f4dcc224e44aae2c6d5b\\n    Branch: heads/master\\n    Author: halin-george <halin-george@yandex-team.ru>\\n    Summary: Make tsan compatible with coroutines' switch context by explicitly marking switches.\\n    git-svn info:\\n    Last Changed Rev: 6009773\\n\\nOther info:\\n    Build by: user\\n    Top src dir: C:\\\\Folder\\\\CProg\\\\catboost\\n    Top build dir: C:\\\\Users\\\\user\\\\.ya\\\\build\\n    Hostname: WARBLE123\\n    Host information: \\n        Microsoft Windows [Version 10.0.17763.805]\\n\\n    \",\n    \"SCM_DATA\": \"Git info:\\n    Commit: abbc7486de95c63cb769f4dcc224e44aae2c6d5b\\n    Branch: heads/master\\n    Author: halin-george <halin-george@yandex-team.ru>\\n    Summary: Make tsan compatible with coroutines' switch context by explicitly marking switches.\\n    git-svn info:\\n    Last Changed Rev: 6009773\\n\",\n    \"VCS\": \"git\"\n}"
Debug: Timer get_version_info, stage vcs info: 0.773000001907
Debug: Downloading https://storage.mds.yandex.net/get-devtools-opensource/233854/1222268138 to C:\Users\user\.ya\tools\v3\1222268138\.resource.jqwj42g7, expect md5=None
Debug: exception after 0:00:05.401000 on 2 try <lambda>: URLError(URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),)) (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>)
Debug: Downloading https://storage.mds.yandex.net/get-devtools-opensource/233854/1222268138 to C:\Users\user\.ya\tools\v3\1222268138\.resource.jqwj42g7, expect md5=None
Debug: exception after 0:00:15.574000 on 3 try <lambda>: URLError(URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),)) (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>)
Debug: Downloading https://storage.mds.yandex.net/get-devtools-opensource/233854/1222268138 to C:\Users\user\.ya\tools\v3\1222268138\.resource.jqwj42g7, expect md5=None
Debug: exception after 0:01:13.943000 on 4 try <lambda>: URLError(URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),)) (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>)
Debug: Downloading https://storage.mds.yandex.net/get-devtools-opensource/233854/1222268138 to C:\Users\user\.ya\tools\v3\1222268138\.resource.jqwj42g7, expect md5=None
Debug: exception after 0:01:34.133000 on 5 try <lambda>: URLError(URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),)) (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>)
Debug: Downloading https://storage.mds.yandex.net/get-devtools-opensource/233854/1222268138 to C:\Users\user\.ya\tools\v3\1222268138\.resource.jqwj42g7, expect md5=None
Debug: exception after 0:01:59.266000 on 6 try <lambda>: URLError(URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),)) (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>)
Debug: Downloading https://storage.mds.yandex.net/get-devtools-opensource/233854/1222268138 to C:\Users\user\.ya\tools\v3\1222268138\.resource.jqwj42g7, expect md5=None
Debug: exception after 0:02:29.423000 on 7 try <lambda>: URLError(URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),)) (<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>)
Debug: Ensuring filelock released: C:\Users\user\.ya\tools\v3\1222268138.lock
Debug: Module "mlockall" stopped in 0.000000
Debug: Module "profile" stopped in 0.000000
Debug: Module "fs_layer" stopped in 0.000000
Debug: Module "showstack" stopped in 0.000000
Debug: Module "evlog" stopped in 0.005000
Debug: Module "revision" stopped in 0.000000
Debug: Module "fetcher" stopped in 0.000000
Debug: Module "fetcher_params" stopped in 0.000000
Debug: Module "display_log" stopped in 0.000000
Debug: Module "custom_file_log" stopped in 0.000000
Traceback (most recent call last):
  File "devtools/ya/app.py", line 379, in configure_exit_interceptor
    yield
  File "devtools/ya/app.py", line 59, in helper
    return action(args)
  File "devtools/ya/entry/entry.py", line 54, in do_main
    res = handler.handle(handler, args, prefix=['ya'])
  File "devtools/ya/core/handler.py", line 159, in handle
    return handler.handle(self, args[1:], prefix + [name])
  File "devtools/ya/core/dispatch.py", line 37, in handle
    return self.command().handle(root_handler, args, prefix)
  File "devtools/ya/core/handler.py", line 341, in handle
    return self._action(params)
  File "devtools/ya/app.py", line 83, in helper
    return action(ctx.params)
  File "devtools/ya/build/build_handler.py", line 85, in do_ya_make
    builder = ya_make.YaMake(params, app_ctx)
  File "devtools/ya/build/ya_make.py", line 703, in __init__
    self.ctx = Context(self.opts, app_ctx=app_ctx, graph=graph, tests=tests, configure_errors=configure_errors, make_files=make_files, lite_graph=lite_graph)
  File "devtools/ya/build/ya_make.py", line 473, in __init__
    self.graph, self.tests, self.stripped_tests, self.configure_errors, self.make_files = _build_graph_and_tests(self.opts, app_ctx)
  File "devtools/ya/build/ya_make.py", line 243, in _build_graph_and_tests
    graph, tests, stripped_tests, gh, make_files = lg.build_graph_and_tests(opts, check=True, ev_listener=ev_listener)
  File "devtools/ya/build/graph.py", line 1788, in build_graph_and_tests
    real_ymake_bin = tools.tool('ymake')
  File "devtools/ya/yalibrary/tools/__init__.py", line 213, in tool
    return toolchain.find(name, with_params, for_platform)
  File "devtools/ya/yalibrary/tools/__init__.py", line 151, in find
    executable = cur_bottle[executable_name]  # if executable_name is None it's Ok
  File "devtools/ya/yalibrary/tools/__init__.py", line 59, in __getitem__
    path = self.resolve()
  File "devtools/ya/yalibrary/tools/__init__.py", line 41, in resolve
    return self.__fetcher.fetch_if_need(self.__formula["match"], tared, binname).where
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 330, in fetch_if_need
    self.__c[key] = self._fetch_if_need(*args, **kwargs)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 394, in _fetch_if_need
    if self._fetch(name, tared, lambda x: name.lower() in x.lower(), binname):
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 316, in _fetch
    _install(res_path, do_install)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 80, in _install
    fs_handler(install_guard)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 72, in fs_handler
    func(install_guard)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 293, in do_install
    self._download(name, res, download_to)
  File "devtools/ya/yalibrary/fetcher/__init__.py", line 468, in _download
    http_client.download_file(url=config.mapping()["resources"][resource["id"]], path=download_to)
  File "devtools/ya/exts/retry.py", line 20, in wrapper
    return retry(proxy_func, **retry_kwargs)
  File "devtools/ya/exts/retry.py", line 12, in retry
    return lpr.retry_call(func, conf=_conf(func, *args, **kwargs))
  File "library/python/retry/__init__.py", line 183, in retry_call
    return _retry(conf, functools.partial(f, *f_args, **f_kwargs))
  File "library/python/retry/__init__.py", line 221, in _retry
    return f()
  File "devtools/ya/exts/retry.py", line 19, in <lambda>
    proxy_func = lambda: func(*args, **kwargs)
  File "devtools/ya/exts/http_client.py", line 64, in download_file
    raise e
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>

**Comment by MotoRZR** [comment]
> > I can give it to you once I come back to work from vacation. But I'd like first understand the reason behind the hidden installation builds that are not part of this github repo.
> > Given that you're a Russian company that raises some questions. Nothing against yandex, but there is a prior bias towards the intentions.
> 
> It is also possible to use auto generated make files for building the project, if you don't want to use ya binary.

Anna, could you please give some further clarification as to how one does would do this?

**Comment by dmitko** [comment]
@MotoRZR https://github.com/catboost/catboost/issues/973#issuecomment-535225020 – here @orivej suggests several approaches: which one is the most preferable for you?

**Comment by annaveronika** [comment]
Hope the problem is solved. Closing because of inactivity.
