### ISSUE TITLE
"Labels variable is empty" error in Windows 10 x64 but not Ubuntu 16.04 LTS x64

### ISSUE THREAD

**Issue by TouringPlans** [catboost/catboost#991]
Problem: _catboost.CatBoostError: Labels variable is empty.** occurs in Windows 10 x64 but not in Ubuntu 16.04 LTS
catboost version: 0.17
Operating System: Windows 10 x64
CPU:
# GPU:

I and another member of my team are running the same code, with the same data, on two separate machines with the same libraries installed. Catboost is giving the error below on Windows, but not Ubuntu.

The complete error message is:

**Traceback (most recent call last):
  File "find_best_model_v1.py", line 1425, in <module>
    model.fit(X[base_features], y,eval_set=(X_test[base_features],y_test), verbose = 0, plot = False)
  File "C:\Users\scblo\AppData\Local\Programs\Python\Python37\lib\site-packages\catboost\core.py", line 4050, in fit
    save_snapshot, snapshot_file, snapshot_interval, init_model)
  File "C:\Users\scblo\AppData\Local\Programs\Python\Python37\lib\site-packages\catboost\core.py", line 1527, in _fit
    save_snapshot, snapshot_file, snapshot_interval, init_model
  File "C:\Users\scblo\AppData\Local\Programs\Python\Python37\lib\site-packages\catboost\core.py", line 1483, in _prepare_train_params
    eval_sets.append(Pool(eval_set[0], eval_set[1], cat_features=train_pool.get_cat_feature_indices()))
  File "C:\Users\scblo\AppData\Local\Programs\Python\Python37\lib\site-packages\catboost\core.py", line 331, in __init__
    self._init(data, label, cat_features, pairs, weight, group_id, group_weight, subgroup_id, pairs_weight, baseline, feature_names)
  File "C:\Users\scblo\AppData\Local\Programs\Python\Python37\lib\site-packages\catboost\core.py", line 779, in _init
    self._check_label_empty(label)
  File "C:\Users\scblo\AppData\Local\Programs\Python\Python37\lib\site-packages\catboost\core.py", line 436, in _check_label_empty
    raise CatBoostError("Labels variable is empty.")
_catboost.CatBoostError: Labels variable is empty.**

**Comment by annaveronika** [comment]
This error occurs only in python when labels is not None, but is empty. The code that is generating this error doesn't depend on GPU vs CPU, it's a high level check. This means that you had a problem in your code.
